### ISSUE TITLE
New properties for HMIP-PSM after upgrade to FW 2.6.2 (aka send this info to the devoloper)

### ISSUE THREAD

**Issue by grimneko** [ioBroker/ioBroker.hm-rpc#101]
While I setup a HMIP-PSM plug with firmware 2.6.2, this message turned up in my log:
`

hm-rpc.1 | 2018-10-12 13:31:02.135 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"WEEK_PROGRAM_TARGET_CHANNEL_LOCK":{"MIN":"MANU_MODE","OPERATIONS":2,"MAX":"A
-- | -- | -- | --
hm-rpc.1 | 2018-10-12 13:31:02.135 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.SWITCH_WEEK_PROFILE.4"
hm-rpc.1 | 2018-10-12 13:31:02.124 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:8","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.104 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:7","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.099 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"VOLTAGE":{"MIN":0,"UNIT":"V","OPERATIONS":5,"MAX":409.5,"FLAGS":1,"ID":"VOLT
hm-rpc.1 | 2018-10-12 13:31:02.099 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.ENERGIE_METER_TRANSMITTER.4"
hm-rpc.1 | 2018-10-12 13:31:02.086 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:6","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.075 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"SECTION_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"UNKNOWN","FLAGS":1,"ID
hm-rpc.1 | 2018-10-12 13:31:02.075 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.SWITCH_VIRTUAL_RECEIVER.4"
hm-rpc.1 | 2018-10-12 13:31:02.064 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:3","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.061 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"SECTION_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"UNKNOWN","FLAGS":1,"ID
hm-rpc.1 | 2018-10-12 13:31:02.061 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.SWITCH_TRANSMITTER.4"
hm-rpc.1 | 2018-10-12 13:31:02.047 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:2","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.045 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"PRESS_SHORT":{"MIN":false,"OPERATIONS":4,"MAX":true,"FLAGS":1,"ID":"PRESS_SH
hm-rpc.1 | 2018-10-12 13:31:02.044 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.KEY_TRANSCEIVER.4"
hm-rpc.1 | 2018-10-12 13:31:02.032 | info | xmlrpc -> getParamsetDescription ["0001D3C99C5846:1","VALUES"]
hm-rpc.1 | 2018-10-12 13:31:02.025 | warn | Send  this info to developer:  {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"CONFI
hm-rpc.1 | 2018-10-12 13:31:02.025 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-PSM.MAINTENANCE.4"
`

Changelog for that update: https://www.eq-3.de/Downloads/Software/Firmware/Homematic%20IP/changelog_HmIP-PSM_update_V2_6_2.txt
Firmwarefile: https://www.eq-3.de/Downloads/Software/Firmware/Homematic%20IP/HmIP-PSM_update_V2_6_2_170504.tgz

**Comment by BuZZy1337** [comment]
Die Angaben sind leider nicht vollständig.
Hast du noch eine Chance die Einträge direkt aus dem Logfile zu holen?

**Comment by grimneko** [comment]
Leider nicht mehr, und seit dem Update auf die Github Repo Version kamen die Meldungen auch nicht mehr.
