### ISSUE TITLE
keine aktive verbindung nach ccu neustart.

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.hm-rpc#103]
Adapter meldet zwar verbunden, ist es jedoch nicht auf der CuxD Index Seite wird auch NICHT 

`als RPC-Server(INIT) von 192.168.8.33:8701 (hm-rpc.1) angefordert!` angezeigt erst nach manuellen 
rpc instsnce Neustart wieder verbunden!

**Comment by Apollon77** [comment]
Logs? Im Zweifel bitte Debug-Log einschalten und versuchen nachzustellen

**Comment by Matten-Matten** [comment]
> hm-rega.1 | 2018-10-20 08:17:01.637 | info | got state values
> -- | -- | -- | --
> hm-rega.1 | 2018-10-20 08:17:01.278 | info | request state values
> hm-rega.1 | 2018-10-20 08:17:01.278 | info | deleted 0 variables
> hm-rega.1 | 2018-10-20 08:17:01.278 | info | added/updated 4 variables
> hm-rega.1 | 2018-10-20 08:17:01.262 | info | got 4 variables
> hm-rega.1 | 2018-10-20 08:17:01.106 | info | time difference local-ccu 0s
> hm-rega.1 | 2018-10-20 08:17:01.091 | info | ReGaHSS 192.168.27.75 up
> hm-rega.1 | 2018-10-20 08:16:31.034 | error | CCU 192.168.27.75 unreachable
> hm-rega.1 | 2018-10-20 08:16:31.034 | error | post request error: connect ETIMEDOUT 192.168.27.75:8181
> hm-rpc.2 | 2018-10-20 08:15:56.290 | debug | system.adapter.admin.0: logging true
> hm-rpc.2 | 2018-10-20 08:15:36.396 | debug | clear connecting interval
> hm-rpc.2 | 2018-10-20 08:15:36.396 | info | Connected
> hm-rpc.2 | 2018-10-20 08:15:36.396 | info | new CUxD devices/channels after filter: 0
> hm-rpc.2 | 2018-10-20 08:15:36.381 | info | binrpc -> listDevices 0
> hm-rpc.2 | 2018-10-20 08:15:36.365 | debug | start connecting interval
> hm-rpc.2 | 2018-10-20 08:15:36.349 | debug | binrpc -> 192.168.27.75:8701 init ["xmlrpc_bin://192.168.27.76:8701","hm-rpc.2"]
> hm-rpc.2 | 2018-10-20 08:15:36.349 | debug | Connect...
> hm-rpc.2 | 2018-10-20 08:15:36.349 | info | binrpc client is trying to connect to 192.168.27.75:8701 with ["xmlrpc_bin://192.168.27.76:8701","hm-rpc.2"]
> hm-rpc.2 | 2018-10-20 08:15:36.349 | info | binrpc server is trying to listen on 192.168.27.76:8701
> hm-rpc.2 | 2018-10-20 08:15:35.704 | info | starting. Version 1.7.2 in C:/ioBroker/node_modules/iobroker.hm-rpc, node: v6.11.4
> hm-rpc.2 | 2018-10-20 08:15:35.548 | debug | statesDB connected
> hm-rpc.2 | 2018-10-20 08:15:35.501 | debug | objectDB connected
> host.ioBroker | 2018-10-20 08:15:34.394 | info | instance system.adapter.hm-rpc.2 started with pid 8560
>

**Comment by Matten-Matten** [comment]
ok Problem hat sich gelöst in dem ich die neuste Version des Adapters installiert habe. 

Die Version 1.7.6 muss unbedingt ins ioBroker Repository. 

Trotzdem vielen Dank.

Gruß
Matten Matten

**Comment by Apollon77** [comment]
will do
