### ISSUE TITLE
Compatibility to XML-API 2.0

### ISSUE THREAD

**Issue by Saharel001** [ioBroker/ioBroker.hm-rpc#1040]
**Is your feature request related to a problem? Please describe.**
no, not yet

**Describe the solution you'd like**
Compatibility to https://github.com/homematic-community/XML-API/releases/tag/2.0

**Describe alternatives you've considered**
A Homematic XML-API update warning in iobroker. Because the 2.0 API have braking changes.

**Comment by Saharel001** [comment]
iobroker not use XML-API, my mistake.

**Comment by Apollon77** [comment]
Really? I think it could be chosen ... do we then need to remove that @foxriver76

**Comment by foxriver76** [comment]
No, we are not using it, it is an addon which has a different url

`http://[CCU_IP]/addons/xmlapi/[ScriptName]?sid=[TOKEN_ID]`

**Comment by agross** [comment]
> No, we are not using it

There is the option to choose the XML-RPC protocol. Is that also not using the XML Plugin's API?
