### ISSUE TITLE
Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-SWDO.MAINTENANCE.1"

### ISSUE THREAD

**Issue by puravida69at** [ioBroker/ioBroker.hm-rpc#107]
Ich hoffe, das passt so?

`
 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"SABOTAGE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"SABOTAGE","TYPE":"BOOL","DEFAULT":false},"CONFIG_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"CONFIG_PENDING","TYPE":"BOOL","DEFAULT":false},"DUTY_CYCLE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"DUTY_CYCLE","TYPE":"BOOL","DEFAULT":false},"LOW_BAT":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"LOW_BAT","TYPE":"BOOL","DEFAULT":false},"INSTALL_TEST":{"MIN":false,"OPERATIONS":3,"MAX":true,"FLAGS":2,"ID":"INSTALL_TEST","TYPE":"BOOL","DEFAULT":false},"UNREACH":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":25,"ID":"UNREACH","TYPE":"BOOL","DEFAULT":false},"OPERATING_VOLTAGE_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"OVERFLOW","FLAGS":1,"ID":"OPERATING_VOLTAGE_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW"]},"RSSI_DEVICE":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_DEVICE","TYPE":"INTEGER","DEFAULT":0},"OPERATING_VOLTAGE":{"MIN":0,"OPERATIONS":5,"MAX":25.2,"FLAGS":1,"ID":"OPERATING_VOLTAGE","TYPE":"FLOAT","DEFAULT":0},"RSSI_PEER":{"MIN":-128,"OPERATIONS":5,"MAX":127,"FLAGS":1,"ID":"RSSI_PEER","TYPE":"INTEGER","DEFAULT":0},"ERROR_CODE":{"MIN":0,"OPERATIONS":5,"MAX":255,"FLAGS":9,"ID":"ERROR_CODE","TYPE":"INTEGER","DEFAULT":0},"UPDATE_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"UPDATE_PENDING","TYPE":"BOOL","DEFAULT":false}}}

`

**Comment by BuZZy1337** [comment]
> Ich hoffe, das passt so?

Ja.. Passt so! Danke. ☺️ 

Done.
