### ISSUE TITLE
Send this info to developer: _id: "hm-rpc.meta.VALUES.HMIP-SWDO.SHUTTER_CONTACT.1"

### ISSUE THREAD

**Issue by puravida69at** [ioBroker/ioBroker.hm-rpc#108]
`
Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"STATE":{"MIN":"CLOSED","UNIT":"\"\"","OPERATIONS":5,"MAX":"OPEN","FLAGS":1,"ID":"STATE","TAB_ORDER":0,"TYPE":"ENUM","DEFAULT":"CLOSED","VALUE_LIST":["CLOSED","OPEN"],"CONTROL":"DOOR_SENSOR.STATE"}}}

`

**Comment by BuZZy1337** [comment]
Done.
