### ISSUE TITLE
Connection to CCU3 not possible with authentication

### ISSUE THREAD

**Issue by ravenhal** [ioBroker/ioBroker.hm-rpc#1170]
If authentication in CCU3 is activated, the instances of hm-rpc won't connect:

Init not possible, going to stop: Unknown XML-RPC tag 'TITLE'
Cannot call init: [http://0.0.0.0:42001, ""] Unknown XML-RPC tag 'TITLE'

The instances 0 and 1 (I first tried rfd and Homematic IP) first turn yellow/orange but don't get a connection to device or service. Then they become red and try to restart with the same results.

The hm-rega-instance is green the whole time.

If I deactivate the authentication the instances can connect and become green after some seconds.
HTTPS is active and all relevant ports (42001, 42010, 48181) are open.

**Versions:**
 - hm-rpc version: v1.16.0
 - hm-rega version: v4.0.0
 -  iobroker version: 5.0.19
 - JS-Controller version: v18.19.0 (node.js)
 - Node version: v18.19.0
 - Operating system: RaspiOS Bookworm 
 Linux cg-home-pi 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux
 - CCU model: CCU3 with raspberrymatic 3.73.9.20240130
 
**Additional context**
CCU3 and iobroker (on RaspberryPi) are in the same subnet.

**Comment by sh-hedge** [comment]
Same problem here. If yuthentication is enabled in CCU3 no connection is possible.
If authentication is disabled in the CCU it workes.

Username and Password are filled and https was tested... no success..

**Comment by klein0r** [comment]
The problem is the encryption (which is not used by jsonConfig / io-package). `encryptedNative` is not set. This leads to the problems

1. Upgraded installation will still work (but display a strange value in the configuration -> the encrypted value)
2. New installations will not work, since the values are not stored encrypted, but will be decryped

<img width="620" alt="Screenshot 2024-03-13 at 09 45 35" src="https://github.com/ioBroker/ioBroker.hm-rpc/assets/1959049/54609e8e-0731-43b2-8879-9c410c6c1399">

I'm going to fix this

**Comment by sh-hedge** [comment]
Just tested your commit. But still have an error and get no connection.
In my Homematic Log it says:
![image](https://github.com/ioBroker/ioBroker.hm-rpc/assets/3350458/480f992e-b611-4ee5-bfb4-be59833e64b0)

**Comment by klein0r** [comment]
> Just tested your commit.

Looks like you haven't re-entered your credentials after the upgrade.

**Comment by sh-hedge** [comment]
Yes I did. Just reinstalled the adapter from you git repo and recreated the instance. 
then needed to re enter all the informations (IPs, Username, PW, https) etc... And still got the same error.

**Comment by klein0r** [comment]
> Just reinstalled the adapter from you git repo

Ah sorry, I haven't commited the build files and the release process will do that. So it's not possible to test my version via GitHub installs.

**Comment by foxriver76** [comment]
> > Just reinstalled the adapter from you git repo
> 
> Ah sorry, I haven't commited the build files and the release process will do that. So it's not possible to test my version via GitHub installs.

The adapter needs to be built before release, the `build`directory is part of GitHub and not only the npm package to enable GitHub installs.

**Comment by klein0r** [comment]
@foxriver76 Yes I know, but I never include it in PRs to avoid merge conflicts

**Comment by sh-hedge** [comment]
@foxriver76 @klein0r 

Hm, for me its still not working....
In ioBroker still version 1.16.0 is shown up. Even after fresh installation of the adapter and instances.
And sideloading via github repo ist working and showing v. 1.17.0, but with the same problem (no connection and username/pw error on homematic side)

**Comment by sh-hedge** [comment]
> @foxriver76 @klein0r
> 
> Hm, for me its still not working.... In ioBroker still version 1.16.0 is shown up. Even after fresh installation of the adapter and instances. Sideloading via github repo is working and showing v. 1.17.0, but with the same problem (no connection and username/pw error on homematic side)


Forget about it... After sideloading again, now it workes....

**Comment by klein0r** [comment]
> Sideloading via github repo

Don't install adapters via Github... always via npm

**Comment by sh-hedge** [comment]
> > Sideloading via github repo
> 
> Don't install adapters via Github... always via npm


Thx, now I installed it via npm. Also works in general.
But, the homematic devices are not syncing properly... Could be another problem. It was okay with the 1.16.0 version... :-/
