### ISSUE TITLE
Connection Error with Auth Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.hm-rpc#120]
`hm-rpc.0	2018-12-07 12:25:53.584	error	init error: Error: Unknown XML-RPC tag 'TITLE'
hm-rpc.0	2018-12-07 12:25:53.581	debug	xmlrpc -> 192.168.2.25:2001/ init ["http://192.168.2.24:2001","hm-rpc.0"]
hm-rpc.0	2018-12-07 12:25:23.591	error	init error: Error: Unknown XML-RPC tag 'TITLE'
hm-rpc.0	2018-12-07 12:25:23.582	debug	start connecting interval
hm-rpc.0	2018-12-07 12:25:23.582	debug	xmlrpc -> 192.168.2.25:2001/ init ["http://192.168.2.24:2001","hm-rpc.0"]
hm-rpc.0	2018-12-07 12:25:23.582	debug	Connect...
hm-rpc.0	2018-12-07 12:25:23.582	info	xmlrpc client is trying to connect to 192.168.2.25:2001/ with ["http://192.168.2.24:2001","hm-rpc.0"]
hm-rpc.0	2018-12-07 12:25:23.581	info	xmlrpc server is trying to listen on 192.168.2.24:2001`

https://forum.iobroker.net/viewtopic.php?f=20&t=18429&p=200960#p200960

**Comment by foxriver76** [comment]
Maybe this helps:
https://www.youtube.com/watch?v=LaQtyf7dl9w&lc=z23jutrzkt2kcpiag04t1aokgmn3vuqyr2bgsglsq3fgrk0h00410

and this:

https://forum.iobroker.net/viewtopic.php?f=36&t=18979

**Comment by foxriver76** [comment]
And when I take a short look at the log I recognize that the port is wrong.

**Comment by vr6syncro** [comment]
why ports wrong? are the ports are changing with and without auth?

**Comment by foxriver76** [comment]
According to the tilte of your raspmatic issue you are German. So please use the ressources given iny my first comment. You need at least RPC 1.8 and REGA 2.0 adapter versions. Both are available from GitHub only for testing purposes. With the current latest versions you can not manage authentication.

**Comment by vr6syncro** [comment]
Wie du es in deinem Video gezeigt hast switcht bei mir der Port nicht wenn ich die Auth aktiviere.
Daher hatte ich anscheinend den falschen Port. Leider kenne ich keine möglichkeit die benutzten Ports der HM anzeigen zu lassen.

Daher eine dringende Bitte von mir die Readme vom Adapter anzupassen mit den verwendeten Ports mit Auth eingeschaltet.

**Comment by foxriver76** [comment]
Dann stellt sich die Frage, ob du einen Upload des Adapters durchgeführt hast. Ports haben eine zusätzliche vier vorne dran.

**Comment by vr6syncro** [comment]
Es geht nun alles nachdem ich die Ports manuell geändert habe.
Und ja auch den Upload habe ich durchgeführt. Hatte nach dem Fehler extra nochmal geupdatet (incl. Upload) und ja die Felder sind auch da. Bin gerade nochmals in die stelle am Video gesprungen aber den Port wechsel macht er bei mir nicht.  In der Webconsole bekomme ich folgendes:
`Uncaught ReferenceError: $port is not defined
    at HTMLInputElement.<anonymous> (index_m.html?0:188)
    at HTMLInputElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLInputElement.q.handle (jquery-3.2.1.min.js:3)
    at Object.trigger (jquery-3.2.1.min.js:4)
    at HTMLInputElement.<anonymous> (jquery-3.2.1.min.js:4)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at r.fn.init.trigger (jquery-3.2.1.min.js:4)
    at HTMLSpanElement.<anonymous> (adapter-settings.js:529)
    at HTMLSpanElement.dispatch (jquery-3.2.1.min.js:3)
(anonymous) @ index_m.html?0:188
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3
trigger @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
each @ jquery-3.2.1.min.js:2
each @ jquery-3.2.1.min.js:2
trigger @ jquery-3.2.1.min.js:4
(anonymous) @ adapter-settings.js:529
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3`

**Comment by foxriver76** [comment]
Das sollte ich eigentlich vor 2 Tagen gefixt haben. Wann hast du denn von Git installiert?

**Comment by vr6syncro** [comment]
vor 2 stunden ungefähr. Ich werde nun mal einen clean install machen und den cache löschen.

**Comment by foxriver76** [comment]
Okay also aktuell steht in der index_html Zeile 188 wo der port nicht definiert war ein else. Und davor wurde in der Zeile die port Variable genutzt die ich aus Versehen auf die nicht existente Id port gesetzt hatte statt homeaticPort. s. https://github.com/ioBroker/ioBroker.hm-rpc/commit/55d359345be4dd9bf9c4e71518a4f6eba32091b8

**Comment by foxriver76** [comment]
Wäre nett, wenn du dann nochmal Feedback gibst, ob die Portauswahl läuft. Falls ja, kann das ganze dann mal nach npm.

**Comment by vr6syncro** [comment]
Ich habe es mir gerade angesehen. nach einem npm cache clean und einer neu Installation funktioniert die Funktion nun wie sie soll. Trotzdem war es für mich als User sehr schwer Infos zu finden das bei Authentifizierung nun zwingend andere Ports verwendet werden sollen. Eine Übersicht wäre dazu echt klassen. Ich bedanke mich aber hier erstmal für deine Unterstützung und mühen!

**Comment by foxriver76** [comment]
Deshalb sollen sie automatisch gewählt werden, um dem User dies abzunehmen. Jedoch schadet ein kleiner Vermerk in der README sicher nicht. Da stimme ich dir zu. 

Freut mich, dass ich dir helfen konnte.

**Comment by smartboart** [comment]
habe die Problem auch.
Obwohl der richtig Port eingestellt ist, 
erhalte ich port 0 wenn ich  mit iobroker l i die Ports chekce...siehe Foto
![unbenannt](https://user-images.githubusercontent.com/38385805/49747301-6d64ee00-fca3-11e8-91e1-744d7dfaf3d5.PNG)
