### ISSUE TITLE
Cannot call init: [http://192.168.2.25:42001, ""] Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by DieWaldfee** [ioBroker/ioBroker.hm-rpc#1209]
**Describe the bug**
zwei RPC-Instanzen liefen einwandfrei Homematic und HomematicIP), bis ich in node-red die CCU3 ansprechen wollte. Ich habe einen Testflow erstellt, die Daten der CCU3 eingetragen und die Misere begann.
Was funktioniert: REGA macht einen connect und überträgt auch Räume und Funktionen (Status grün)
Was nicht mehr funktioniert: RPC macht keinen Connect mehr und wirft die Fehlermeldung "Cannot call init: [http://192.168.2.25:42001, ""] Unknown XML-RPC tag 'TITLE'"

Verbindung über HTTPS - user name & Passwort gesetzt (zum Test auch ohne Sonderzeichen
REGA connectet mit in der Konfiguration.

hier die CCU-Einstellungen.
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/12a85107-e3dc-4fbb-a866-ab1f4ddf2401)

Einstellungen REGA:
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/31c9b852-9bfd-4163-ad4d-b73ce28c0113)
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/f2af1f0b-eb90-45bc-9fab-c625fbfea1d3)

Einstellungen RPC (analoge EInstellungen auch bei der 2. Instanz für HMIP):
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/132a95ff-389c-4ed9-a6e6-4a40bb19c4d2)
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/b0d33fa7-990e-4e46-88f0-0ce13784acd4)

Auszug aus dem Log-File:
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/afe1229e-726c-4d61-82cb-4446e564bc2e)

**Versions:**
 - hm-rpc version: 1.16.0
 - hm-rega version: 4.0.0
 - JS-Controller version: 5.0.19
 - Node version: v18.20.2
 - Operating system: Raspian
 - CCU model: CCU3
 - CCU firmware: 3.75.6

**Was habe ich bislang alles ausprobiert:**
- Node-Red instanz abgeschaltet - auch aktueller Zustand - kein Effekt.
- Raspbian Upgrade/full-update - vielleicht irgendetwas veraltet - kein Effekt
- Alle Adapter sind aktuell
- Firewall der CCU geprüft und zum Test auch mal auf HTTP umgestellt (auch in den Instanzen): gleicher Fehler
- REGA und RPC-Adapter deinstalliert und neu installiert & neu konfigurtiert -> gleicher Fehler...
- LOG-File der CCU geprüft - keine Fehlereinträge ersichtlich

Im Netzt habe ich sehr unterschiedliche Blog-Einträge gefunden, die mich allesamt nicht weitergebracht haben.
Hauptaugenmerk liegt auf der Konfiguration der CCU in der Firewall und der entsprechenden Eintragung im Adapter. 
Das passt aus meiner SIcht aber - und war vorher auch funktionstüchtig so eingerichtet. Ich gege davon aus, das der 
Test-Flow mit Abschaltung der node-Red-Instanz auch abgeschalten ist. (Flow hatte ich deaktiviert und dann node-Red
ganz disabled).

...was kann ich als nächstes testen? 
Danke für eure Hilfe

**Comment by DieWaldfee** [comment]
1.17.0 installed - no change in error
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/f4664871-ccbf-4785-b0f8-49609a7cd624)

![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/a5d88b3f-aa37-4d27-a4aa-9a5ac3fd874e)

**Comment by foxriver76** [comment]
Ich vermute du musst die Zugangsdaten neu eingeben mit der neuen Version

**Comment by DieWaldfee** [comment]
ich habe die Zugangsdaten aktualisiert mit gleichem Fehlerbild.
Danach habe ich die Instanzen und danach die Adapter (hm-rega und hm-rpc) gelöscht + reboot.
Nach der erneuten Installation und Konfiguration beider Adapter hat es funktioniert :-)
Mit der V1.17.0 wird jetzt wieder alles eingelesen - HMIP und HM funktionieren wieder
Danke für euren Support!

**Comment by DieWaldfee** [comment]
vielleicht ein Hinweis/Verbesserungsvorschlag zum Protokoll:
ich habe explizit ein falsches Passort eingegeben.

bei falschem Passwort im HM-REGA folgt im Protokoll:
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/f7c600d1-fcca-4634-92bb-70f44ed6c136)
(...damit kann man was anfangen)

bei falschem Passwort im HM-RPC folgt im Protokoll:
![grafik](https://github.com/ioBroker/ioBroker.hm-rpc/assets/66571311/610419ed-a8cd-4303-93e7-e5d978dc07aa)
Hieraus lässt sich schwer etwas ableiten. Vielleicht kann hier die Protokollausgabe verfeinert werden, um ein Autorisierungsproblem besser einzufangen und von anderen Fehler unterscheidbar zu machen. Bei falschem Passwort müsste ja auch für den RPC ein 401 von der CCU geschickt werden (zumindest meine Vermutung).
@klein0r und @foxriver76: wenn der Hinweis/Verbesserungsvorschlag für euch ok kann das Ticket gerne geschlossen werden.

**Comment by mcm1957** [comment]
Ev. wäre es eine Option das ganze XML Paket zu loggen, ggF mit einer Längenbegrenzung. Alterntiv könnte man xml natürlich auch auswerten - ich gehe davon aus, dass da irgendein lesbarer Text drinnen steht. Den könnte man ausgeben - oder nur auf den speziellen Text bei Passwortfehler checken.

Minimal könnte man zu "unknown XML-RPC Tag TITLE" noch "please check your password" oder ähnliches ausgeben damit der User zumindest beim wahrscheinlich häufigsten Fall eine Idee hat was er noc tun kann.

**Comment by DieWaldfee** [comment]
@klein0r, @mcm1957: mit der V1.16.0 lässt sich vormutlich ein allgemeiner Konfigurationsfehler nachstellen - mit der 1.17.0 kann dann wiederum das falsche Passwort eingegeben werden. Vielleicht könnt ihr response loggen und euch die Antwort anzeigen - ggf. steht ja doch noch was verwertbares drin. Ich selbst habe es probiert, komme aner nicht weit :-)...

Ich schließe das Ticket an dieser Stelle, weil der eigentliche Fehler ja behoben wurde - Danke nochmal
