### ISSUE TITLE
Ping error: Error: Unexpected end Line: 0 Column: 0 Char:

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.hm-rpc#125]
I always get the error "Ping error: Error: Unexpected end Line: 0 Column: 0 Char:" .. I am using hm-rpc.1 configured to pull the virtual devices from the ccu2 (CCU2 Firmware 2.27.8)..

Instance | Time | Mode | MSG
-- | -- | -- | --
hm-rpc.1 | 2018-12-19 15:00:56.440 | debug | start ping interval
hm-rpc.1 | 2018-12-19 15:00:56.440 | debug | clear connecting interval
hm-rpc.1 | 2018-12-19 15:00:56.440 | info | Connected
hm-rpc.1 | 2018-12-19 15:00:43.014 | debug | start connecting interval
hm-rpc.1 | 2018-12-19 15:00:43.014 | debug | clear ping interval
hm-rpc.1 | 2018-12-19 15:00:43.014 | debug | Connect...
hm-rpc.1 | 2018-12-19 15:00:43.014 | info | Disconnected
hm-rpc.1 | 2018-12-19 15:00:43.014 | error | Ping error: Error: Unexpected end Line: 0 Column: 0 Char:
hm-rpc.1 | 2018-12-19 15:00:43.006 | debug | Send PING...
hm-rpc.1 | 2018-12-19 15:00:43.006 | debug | [KEEPALIVE] Check if connection is alive

Screenshot of the instance settings:
![image](https://user-images.githubusercontent.com/6979405/50225159-054b9180-03a0-11e9-972a-764d02a40ca2.png)

![image](https://user-images.githubusercontent.com/6979405/50225182-1399ad80-03a0-11e9-817e-feb9db7f3744.png)

**Comment by foxriver76** [comment]
Maybe @Holuba can have a look at it, I think he implemented the functionality. He has implemented the functionality in https://github.com/ioBroker/ioBroker.hm-rpc/pull/99

**Comment by BuZZy1337** [comment]
I just tried the "virtual groups" thing for the first time right now.. Until now I only had the virtual groups on the ccu.. But not in iobroker.

**Comment by Holuba** [comment]
The undocumented VirtualDevice API has a reduced set of methods.
It also does not seem to support PING. Therefore, the error message comes in the log.

With my CCU2 the connection works, and also this error does not appear in the log ...

Here My Connection Settings:
![anmerkung 2018-12-19 211635](https://user-images.githubusercontent.com/35482742/50245750-a0119380-03d3-11e9-9940-d7af5ad74b1e.jpg)
![anmerkung 2018-12-19 211718](https://user-images.githubusercontent.com/35482742/50245751-a0aa2a00-03d3-11e9-93e8-f98ef8f8d89d.jpg)

CCU2 Firmware Version: 2.41.5
hm-rpc Version: 1.8.0

**Comment by Holuba** [comment]
Have you opened the CCU Firewall?

Here are my settings (IP 192.168.2.16 ist my iobroker server):
![anmerkung 2018-12-19 213427](https://user-images.githubusercontent.com/35482742/50246594-1dd69e80-03d6-11e9-9d36-67f4725f472f.jpg)

**Comment by foxriver76** [comment]
Wouldnt be a problem to disable ping for the virtual devices api but somwhere must be a difference between your setups. I don't think its a firewall issue, because firewall block normally just runs in a timeout.

**Comment by 150d** [comment]
I'm seeing both issues as well:

1. The path for "Virtual Devices" must be "/groups", not "/groups/" (trailing slash.) The devault, however, is "/groups/".

2. My adapter connects and successfully retrieves devices (the heating groups), but terminates a few seconds later with "Ping error: Error: Unexpected end". This is in hmserver.log:

`Jan 6 18:22:16 de.eq3.ccu.server.internal.RpcMessageHandler ERROR [vert.x-eventloop-thread-1] rpc.api.group Can not handle request 
de.eq3.cbcs.legacy.communication.rpc.RpcException: No handler with given name: ping
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.getMethod(AnnotationAwareRpcHandler.java:68)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodCall(XmlRpcParser.java:118)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseRequest(XmlRequestResponseProcessor.java:231)
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:68)
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:25)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:722)
`

Both of us (the OP of this issue and me) are running CCU2 with firmware v2.27.8, not the most recent one. Perhaps this issue has already been fixed on the CCU2-side in later versions (as in v2.41.5)? Can anybody verify that?

**Comment by 150d** [comment]
I'm happy to confirm that this indeed was the case: I've just installed the most recent firmware on the CCU2 (v2.41.5) and so far I'm not seeing the previous "ping errors" any more.

**Comment by foxriver76** [comment]
Is /groups/ now also working?

**Comment by 150d** [comment]
My adapter is still set to "/groups" (NO trailing slash) from before. I apologize for not trying, but since Holuba already has the configuration WITH trailing slash working I'd rather not try that out myself. (You know, when it's finally working, better not to poke the bear. ;-) )

**Comment by Holuba** [comment]
I added an Pull Request #140 witch excludes the Virtual Devices Deamon Type from Ping (because the Virtual Devices API not supports the Ping). I think this should solve this issue.

**Comment by foxriver76** [comment]
Thanks, but it seems like ping is supported when the CCU2 firmware is up to date.

**Comment by Holuba** [comment]
i have the latest Firmware Version 2.41.5 and the system.listMethods call to the Virtual Devices XML-RPC API responses these Methods:
- init
- getParamsetDescription
- getLinks
- getDeviceDescription
- getParamsetId
- getParamset
- putParamset
- system.listMethods
- listDevices
- getValue
- setValue
- listReplaceableDevices
- deleteDevice

I think newer Versions of CCU2 Firmware only doesn't throw an Exception?
(i use this Google Chrome Extension to check the API: https://chrome.google.com/webstore/detail/xml-rpc-client/mbelaappiaalhoceejaopcghdlnhhain )

**Comment by 150d** [comment]
I agree: I now have the new CCU2 firmware (v2.41.6) running for just over two hours and have not seen a single (ping-)error yet.

With the old CCU2 firmware (v2.27.8), it took less than a minute for the adapter to loose connection to the CCU2.

But hey, if it's not needed (or documented) anyway - sure, the less load on the CCU2 the better.

**Comment by foxriver76** [comment]
@Holuba I do not use the API, but if the method is not listed then you are right and we are more backward compatible. 

Can you confirm that it also works with /groups on the current firmware because it don’t seem to work with the implemented default path /groups/ in the older versions, then we could also change the default value in front end.

**Comment by 150d** [comment]
@foxriver76 yes, I currently have it running with the path "/groups" (NO trailing slash) with the new CCU2 formware.
