### ISSUE TITLE
Crash bei Zugriff auf EPaper Display

### ISSUE THREAD

**Issue by dwm66** [ioBroker/ioBroker.hm-rpc#126]
Servus,

seit geraumer Zeit liegt auf meinem Schreibtisch ein Homematic E-Paper Display.
Heut hab ich mal wieder damit rumgespielt, und prompt seltsames festgestellt:

Wenn ich versuche, auf die Zeilen zuzugreifen (hier: hm-rpc.0.NEQ12345678.0.EPAPER_LINE2) , sprich da neue Texte reinzuschreiben, crasht der hm-rpc Adapter. Im Grunde bei allen Zugriffen auf Lines, Icons, Sound etc.

Im Log erscheint:

```
2018-12-20 13:33:43.035  - [31merror[39m: hm-rpc.0 already running
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]: TypeError: line.substring is not a function
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at combineEPaperCommand (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:154:23)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at controlEPaper (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:249:17)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:353:23)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Manager.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Decoder.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
2018-12-20 13:33:43.061  - [31merror[39m: Caught by controller[0]:     at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
2018-12-20 13:33:43.061  - [31merror[39m: host.dragon instance system.adapter.hm-rpc.0 terminated with code 7 (Adapter already running)
2018-12-20 13:33:43.061  - [32minfo[39m: host.dragon Restart adapter system.adapter.hm-rpc.0 because enabled
2018-12-20 13:34:13.082  - [32minfo[39m: host.dragon instance system.adapter.hm-rpc.0 started with pid 8940
2018-12-20 13:34:13.448  - [32minfo[39m: hm-rpc.0 starting. Version 1.7.8 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v8.11.4
2018-12-20 13:34:13.751  - [32minfo[39m: hm-rpc.0 binrpc server is trying to listen on 0.0.0.0:2001
2018-12-20 13:34:13.752  - [32minfo[39m: hm-rpc.0 binrpc client is trying to connect to 10.22.1.15:2001/ with ["xmlrpc_bin://10.22.1.40:2001","hm-rpc.0"]
2018-12-20 13:34:13.759  - [32minfo[39m: hm-rpc.0 binrpc <- system.listMethods ["hm-rpc.0"]
2018-12-20 13:34:13.766  - [32minfo[39m: hm-rpc.0 binrpc <- listDevices ["hm-rpc.0"]
2018-12-20 13:34:13.796  - [32minfo[39m: hm-rpc.0 binrpc -> 544 devices
2018-12-20 13:34:14.590  - [32minfo[39m: hm-rpc.0 Connected
```

Das ging schon mal ... ich kann grad nicht genau nachvollziehen, mit welcher Version von hm-rpc Adapter und CCU Firmware sich das verabschiedet hat ... Hm.
Die Tasten-Events werden "normal" verarbeitet, das klappt.

Grad liegt das Ding wie gesagt nur rum, aber schick wär's schon wenns geht :)
Kann jemand mal reinschaun?

**Comment by foxriver76** [comment]
Existiert das Problem mit der aktuellen Version des Adapters? Ich sehe, dass bei dir 1.7.8 läuft. Und irgendwie läuft deine Instanz dem Log zufolge nicht korrekt: 

```
2018-12-20 13:33:43.061  - [31merror[39m: host.dragon instance system.adapter.hm-rpc.0 terminated with code 7 (Adapter already running)
```

Sollte das aktuell noch auftreten am Besten mal den Host neustarten oder den Prozess übers Terminal abschießen. Falls das Problem dann noch auftritt mit dem E-Paper, bitte mal das Loglevel des Adapters auf Debug ändern und hier reinstellen. Ich habe leider kein Display zum testen und glaube der betroffene Code wurde lange nicht angefasst.

**Comment by dwm66** [comment]
So ... 
- Adapter auf 1.8.0 upgrade
- System neu gestartet (läuft in docker, also "docker restart iob"), alle Adapter wieder grün
- Prozessliste gecheckt:
`root@dragon:~# ps aux | grep hm
root        33  1.2  0.6 1201196 50432 ?       Sl   18:21   0:02 io.hm-rpc.0
root        43  1.6  0.7 1031536 63928 ?       Sl   18:22   0:03 io.hm-rega.0
root       275  0.6  0.5 1000928 46128 ?       Sl   18:24   0:00 io.hm-rpc.1
`
Keine Änderung:

javascript.0 | 2018-12-21 18:28:24.064 | info | script.js.Steuerung.ereignisliste: Subscribe triggered
-- | -- | -- | --
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at Receiver._receiver.onmessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/WebSocket.js:141:47)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WebSocket.emit (events.js:211:7)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at emitOne (events.js:116:13)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WebSocket.onMessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib/EventTarget.js:99:16)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WebSocket.ws.onmessage (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WS.Transport.onData (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:137:8)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WS.Transport.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:145:8)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WS.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at WS.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:273:10)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | at Socket.onPacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:450:19)
hm-rpc.0 | 2018-12-21 18:28:23.564 | error | Error: server error
javascript.0 | 2018-12-21 18:28:23.563 | info | script.js.Steuerung.homematic: setForeignState(id=javascript.0.Ereignisse.Text, state="WARNUNG - Service hm-rpc.0 Connection hat Probleme. Bitte überprüfen!!!")
javascript.0 | 2018-12-21 18:28:23.563 | info | script.js.Steuerung.homematic: getState(id=hm-rpc.0.info.connection, timerId=0) => {"val":false,"ack":true,"ts":1545413303562,"q":0,"from":"system.adapter.hm-rpc.0","lc":1545413303562}
hm-rpc.0 | 2018-12-21 18:28:23.562 | error | server error
hm-rpc.0 | 2018-12-21 18:28:23.556 | info | Disconnected
hm-rpc.0 | 2018-12-21 18:28:23.552 | info | binrpc -> 10.22.1.15:2001/ init ["xmlrpc_bin://10.22.1.40:2001",""]
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:354:23)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at controlEPaper (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:250:17)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | at combineEPaperCommand (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:155:23)
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | TypeError: line.substring is not a function
hm-rpc.0 | 2018-12-21 18:28:23.551 | error | uncaught exception: line.substring is not a function
hm-rpc.0 | 2018-12-21 18:28:23.240 | debug | binrpc -> setValue 0 EPAPER_LINE3: Ohoh
...

hm-rpc.0 | 2018-12-21 18:28:55.284 | info | binrpc client is trying to connect to 10.22.1.15:2001/ with ["xmlrpc_bin://10.22.1.40:2001","hm-rpc.0"]
-- | -- | -- | --
hm-rpc.0 | 2018-12-21 18:28:55.284 | info | binrpc server is trying to listen on 0.0.0.0:2001
hm-rpc.0 | 2018-12-21 18:28:54.982 | info | starting. Version 1.8.0 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v8.11.4
host.dragon | 2018-12-21 18:28:54.590 | info | instance system.adapter.hm-rpc.0 started with pid 481
host.dragon | 2018-12-21 18:28:24.574 | info | Restart adapter system.adapter.hm-rpc.0 because enabled
host.dragon | 2018-12-21 18:28:24.574 | error | instance system.adapter.hm-rpc.0 terminated with code 6 (uncaught exception)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at Socket.adapter.getForeignState (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:354:23)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at controlEPaper (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:250:17)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: at combineEPaperCommand (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:155:23)
Caught | 2018-12-21 18:28:24.574 | error | by controller[0]: TypeError: line.substring is not a function

**Comment by Apollon77** [comment]
Debug-Log aktivieren per Instanzen -> Expertenmodus -> Spalte "Logstufe" dort auch "debug" stellen

**Comment by dwm66** [comment]
Der Auszug oben ist mit aktiviertem Debug auf der hm-rpc.0 Instanz

**Comment by dwm66** [comment]
Sorrry, kein close ... falschen Knopf erwischt :/

**Comment by foxriver76** [comment]
Kannst du mal ein Beispiel zeigen wie du den state beschreibst?

**Comment by foxriver76** [comment]
Man konnte vermuten, dass in https://github.com/ioBroker/ioBroker.hm-rpc/blob/03d0b77424b3abf538ad72d606886c4599196541/hm-rpc.js#L152 line kein String ist oder gar null und er wegen Icon die if Bedienung bestätigt und dann wäre line kein String und somit die Funktion substring nicht existent

**Comment by foxriver76** [comment]
Ich werde da die Tage mal was einbauen und etwas Logging hinzufügen, dass man zumindest mal die angekommenen Daten sieht.

**Comment by dwm66** [comment]
Ich hab einfach bei "Objects" was in den String getippt :)

Aber vom Javascript aus läßt sich's ebenfalls reproduzieren:
`
setState("hm-rpc.0.NEQ0711642.0.EPAPER_LINE2"/*EPDisplay:0.EPAPER_LINE2*/,"Huhu");
`

**Comment by foxriver76** [comment]
Kannst du es mal mit rpc 1.8.2 probieren?

**Comment by dwm66** [comment]
Grade die 1.8.2 probiert, das Problem ist weg. Hab die Lines, Icons, den "Sound" und das Signal probiert, passt.
Herzlichen Dank!
