### ISSUE TITLE
New HMIP Icons

### ISSUE THREAD

**Issue by Flauschi83** [ioBroker/ioBroker.hm-rpc#127]
With new devices, the icon list of a CCU got extended. I am not sure, which ones are already in (173 HMIP-BSL is not) I uploaded here some icons and thumbs. 
Could you please implement them?

**Comment by foxriver76** [comment]
Where can I find the related device names? Unfortunately they are not in the image name.

**Comment by Flauschi83** [comment]
oh sorry, the github upload renamed all the images. I put in here a zip, with all the raw images.


[icons.zip](https://github.com/ioBroker/ioBroker.hm-rpc/files/2706310/icons.zip)

**Comment by foxriver76** [comment]
Thank you and merry christmas :-)
