### ISSUE TITLE
JS doesn't get status of wall switch

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.hm-rpc#128]
Hi, I am trying to fetch the status "PRESS_SHORT" from a Bidcos Wall-Switch that controls a socket. The buttons in ioBroker work but I cannot collect the "true" via Blockly. All that happens is that the true in "INSTALL_TEST" turns green. What's wrong?

There is a direct pairing between the devices in the CCU but that shouldn't effect the states.

Using "latest"

**Comment by daniel-lo** [comment]
Added the button to dummy program on CCU and now it works. Probably nothing to look into .. not sure.

**Comment by Apollon77** [comment]
This is the topic with wall switches. They only send status to ccu if ccu „needs“ it ...

**Comment by daniel-lo** [comment]
What exactly is the effect of the dummy program? Other than fixing my current problem ;-) Is this known?

**Comment by foxriver76** [comment]
When there's no program, the status will not be sent to the CCU, because it is not needed for anything. As soon as there is a program which takes the switch into account, the CCU needs to know the status and then the status will be sent to the CCU.

**Comment by daniel-lo** [comment]
Thanks .. is this constant traffic or only on event? Is it mild on battery consumption?

**Comment by foxriver76** [comment]
I would assume that it is event based like the other devices and that it has no significant effect on the battery consumption, but I don't own a Homematic switch, so just assumptions. ;-)

**Comment by Apollon77** [comment]
In fact it is event based ... but question is of it is only send to "directly paired devices" or also to the ccu
