### ISSUE TITLE
Urlaubsmodus nicht einstellbar HMIP-eTRV

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.hm-rpc#131]
Die Urlaubsmodus-Werte, die in der Homematic-Oberfläche eingestellt wurden, werden erstmal korrekt angezeigt.

hm-rpc.1.xxxx.1:
PARTY_MODE: true
PARTY_SET_POINT_TEMPERATURE: 17
PARTY_TIME_END: "2019_01_20 12:00"
PARTY_TIME_START: "2019_01_15 12:00"

Wenn ich nun aber einen der beiden Zeitpunkte (Start oder End) im iobroker ändere, wird der jeweils andere mit dem Wert "1999_11_30 00:00" überschrieben.

**Comment by foxriver76** [comment]
Please test as soon as #129 is fixed

**Comment by justr1** [comment]
Unfortunately for me not solved with 1.8.2. After editing END date/time in iobroker, START date/time will change to "1999_11_30 00:00". And since 1.8.2 editing of START date/time has no effect anymore (Bestätigung: false).

**Comment by justr1** [comment]
In the meanwhile the START date/time was transmitted (acknowledgement: true, 40 min. after change), but now the END date/time has changed to "1999..." as well.

**Comment by foxriver76** [comment]
Kann es nachstellen, scheint bei allen HmIP Geräten aufzutreten, die Party Time unterstützen. Allerdings wird der Wert so von der CCU geliefert. Scheint also ein Fehler in der CCU/XML-RPC API zu sein. 
https://github.com/eq-3/occu/issues/89

**Comment by foxriver76** [comment]
.
