### ISSUE TITLE
hm-rpc NEQ000000 FAULT_REPORTING

### ISSUE THREAD

**Issue by Schweizer75** [ioBroker/ioBroker.hm-rpc#143]
For the Homematic NEQ000000 Door / Window Sensor the Datapoint FAULT_REPORTING is missing so you cant view Sabotage and other messages in IOBroker. The Faultreporting is still available in piVCCU. 

Please Fix!

**Comment by foxriver76** [comment]
What exactly is a NEQ000000 Door/Window Sensor? HM-Sec-SCo?

**Comment by foxriver76** [comment]
If so please use the ERROR State: 

{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 7,
    "states": {
      "0": "NO_ERROR",
      "1": "",
      "2": "",
      "3": "",
      "4": "",
      "5": "",
      "6": "",
      "7": "SABOTAGE"
    },
    "role": "indicator.error",
    "name": "Fenster Wohnzimmer:1.ERROR"
  },
  "native": {
    "CONTROL": "NONE",
    "DEFAULT": 0,
    "FLAGS": 9,
    "ID": "ERROR",
    "MAX": 7,
    "MIN": 0,
    "OPERATIONS": 5,
    "TAB_ORDER": 1,
    "TYPE": "ENUM",
    "UNIT": "",
    "VALUE_LIST": [
      "NO_ERROR",
      "",
      "",
      "",
      "",
      "",
      "",
      "SABOTAGE"
    ]
  },
  "from": "system.adapter.hm-rpc.0",
  "ts": 1545251445672,
  "_id": "hm-rpc.0.OEQ1197840.1.ERROR",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Schweizer75** [comment]
Thx... i was looking for fault_reporting as it has been set up 

Kindest regards John 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.01.19, 17:14, Max Hauser <notifications@github.com> schrieb:
If so please use the ERROR State:
{
"type": "state",
"common": {
"def": 0,
"type": "number",
"read": true,
"write": false,
"min": 0,
"max": 7,
"states": {
"0": "NO_ERROR",
"1": "",
"2": "",
"3": "",
"4": "",
"5": "",
"6": "",
"7": "SABOTAGE"
},
"role": "indicator.error",
"name": "Fenster Wohnzimmer:1.ERROR"
},
"native": {
"CONTROL": "NONE",
"DEFAULT": 0,
"FLAGS": 9,
"ID": "ERROR",
"MAX": 7,
"MIN": 0,
"OPERATIONS": 5,
"TAB_ORDER": 1,
"TYPE": "ENUM",
"UNIT": "",
"VALUE_LIST": [
"NO_ERROR",
"",
"",
"",
"",
"",
"",
"SABOTAGE"
]
},
"from": "system.adapter.hm-rpc.0",
"ts": 1545251445672,
"_id": "hm-rpc.0.OEQ1197840.1.ERROR",
"acl": {
"object": 1636,
"state": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator"
}
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ioBroker/ioBroker.hm-rpc","title":"ioBroker/ioBroker.hm-rpc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ioBroker/ioBroker.hm-rpc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@foxriver76 in #143: If so please use the ERROR State: \r\n\r\n{\r\n  \"type\": \"state\",\r\n  \"common\": {\r\n    \"def\": 0,\r\n    \"type\": \"number\",\r\n    \"read\": true,\r\n    \"write\": false,\r\n    \"min\": 0,\r\n    \"max\": 7,\r\n    \"states\": {\r\n      \"0\": \"NO_ERROR\",\r\n      \"1\": \"\",\r\n      \"2\": \"\",\r\n      \"3\": \"\",\r\n      \"4\": \"\",\r\n      \"5\": \"\",\r\n      \"6\": \"\",\r\n      \"7\": \"SABOTAGE\"\r\n    },\r\n    \"role\": \"indicator.error\",\r\n    \"name\": \"Fenster Wohnzimmer:1.ERROR\"\r\n  },\r\n  \"native\": {\r\n    \"CONTROL\": \"NONE\",\r\n    \"DEFAULT\": 0,\r\n    \"FLAGS\": 9,\r\n    \"ID\": \"ERROR\",\r\n    \"MAX\": 7,\r\n    \"MIN\": 0,\r\n    \"OPERATIONS\": 5,\r\n    \"TAB_ORDER\": 1,\r\n    \"TYPE\": \"ENUM\",\r\n    \"UNIT\": \"\",\r\n    \"VALUE_LIST\": [\r\n      \"NO_ERROR\",\r\n      \"\",\r\n      \"\",\r\n      \"\",\r\n      \"\",\r\n      \"\",\r\n      \"\",\r\n      \"SABOTAGE\"\r\n    ]\r\n  },\r\n  \"from\": \"system.adapter.hm-rpc.0\",\r\n  \"ts\": 1545251445672,\r\n  \"_id\": \"hm-rpc.0.OEQ1197840.1.ERROR\",\r\n  \"acl\": {\r\n    \"object\": 1636,\r\n    \"state\": 1636,\r\n    \"owner\": \"system.user.admin\",\r\n    \"ownerGroup\": \"system.group.administrator\"\r\n  }\r\n}"}],"action":{"name":"View Issue","url":"https://github.com/ioBroker/ioBroker.hm-rpc/issues/143#issuecomment-455879472"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ioBroker/ioBroker.hm-rpc/issues/143#issuecomment-455879472",
"url": "https://github.com/ioBroker/ioBroker.hm-rpc/issues/143#issuecomment-455879472",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Apollon77** [comment]
Who has setup what? Did you talk about an official device or a custom one with an own definition?
