### ISSUE TITLE
Image missing for HmIP-HEATING

### ISSUE THREAD

**Issue by do1osc** [ioBroker/ioBroker.hm-rpc#146]
On startup of the RPC, i get the message:
"no image for "HmIP-HEATING" found."

Can you please implement the Image....

**Comment by foxriver76** [comment]
It maybe I got it already. Can you confirm, that this is the correct one? https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/admin/icons/175_hmip-group-heating_thumb.png
