### ISSUE TITLE
[Feature Request] Connect 3rd party temperature sensors (like Xiaomi) with HomeMatic thermostats

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.hm-rpc#149]
Frequently asked question in the forum, e.g.:
https://forum.iobroker.net/viewtopic.php?t=17039
https://forum.iobroker.net/viewtopic.php?f=8&t=21460#p225489

Request is to override the measured, actual temperature of HomeMatic thermostats with the values from external 3rd party probes, like Xiaomi. 
HomeMatic wall mount temperature controls are pricey in comparison to 3rd party devices and are typically placed onto the wall at the room entrance, while the actual temperature – especially in large rooms – typically differs a couple or more degrees, so using 3rd party probes, like the ones from Xiaomi, would provide a much better actual temperature and save costs tremendously.

Users refer to FHEM and state FHEM would provide this option:
https://forum.iobroker.net/viewtopic.php?t=17039#p181350

Question is how this could be implemented in ioBroker?
Thanks :-)

**Comment by foxriver76** [comment]
From my point of view this is definitely not something which should be implemented here. We are providing a way to communicate with the xml and bin rpc, and this is not possible with them. As far as I know it‘s also not possible to manipulate these states with the ccu.

**Comment by Mic-M** [comment]
Thanks for your swift response, makes sense.
So should this be probably addressed through the Homematic CUx Daemon (CUxD) system? Sounds like this would be the only option if xml and bin rpc don't provide this option.

**Comment by Mic-M** [comment]
> The way to go for this scenario would be a helper script which configures the offset by the difference of you measurement sensor and your thermostat. I haven’t tested it but with the recent introduced sendTo commands you can control the MASTER area of your devices and should be able to configure the offset via ioBroker.
This sounds very promising, so using a script to calculate the offset, and use sendTo command to set the preset temperature accordingly.
I'll look into it. Thanks.

**Comment by DanielWeeber** [comment]
Afaik the direct linkage is only possible when both devices use the same protocol, hence it is not possible via cuxd and only via FHEM with certain hardware.

**Comment by Mic-M** [comment]
I have just coded a script using sendTo command to update the Homematic Offset value by calculating it with a 3rd party sensor (Xiaomi). Pre alpha, but first test worked for me.
https://github.com/Mic-M/iobroker.homematic-3rd-party-temp-sensors/blob/master/script_homematic-3rd-party-temp-sensors.js

Further details: https://forum.iobroker.net/viewtopic.php?f=21&t=10096&p=226590#p226590

**Comment by foxriver76** [comment]
Great work, by myself I use HM wall thermostats for measurement, but I guess many users will appreciate your script :-)
