### ISSUE TITLE
Heating Groups

### ISSUE THREAD

**Issue by sissiwup** [ioBroker/ioBroker.hm-rpc#150]
Hello,

Heating groups work much betten after the last update. At the moment there is an Problem with virtual Groups without an thermostat. The tempreature is fine but the humidity is set to 2000%.
It schoud be empty or NaN.

**Comment by foxriver76** [comment]
I will try to reproduce it.

**Comment by foxriver76** [comment]
Problem is that CCU Rega sends the values as string and we are checking for numbers, thus it is multiplicated by 100. I already have a fix for this, will push later or tommorow

**Comment by foxriver76** [comment]
fixed in rega 2.2.2

**Comment by foxriver76** [comment]
So now correctly fixed with hm-rpc 1.9.6
