### ISSUE TITLE
Log wird geflutet

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.hm-rpc#155]
**Describe the bug**
Mein Log wird geflutet. Ich habe heute meine ersten IP Geräte bekommen und folglich eine neue Instanz hm-rpc installiert. Unter Rega entsprechend die IP Instanz gewählt

**Screenshots & Logfiles**
hm-rpc.2	2019-02-15 17:04:06.497	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 17:04:06.278	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 17:04:06.259	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:56:06.359	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:56:06.348	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:56:06.190	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:56:06.153	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:52:36.394	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:52:36.382	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:52:36.046	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:52:36.021	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:49:06.137	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:49:06.125	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:49:05.972	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:49:05.955	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:45:36.178	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:45:36.165	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:45:35.881	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:45:35.865	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:37:12.148	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:37:12.135	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:37:11.792	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:37:11.775	info	xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2019-02-15 16:24:10.198	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:24:10.180	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:24:10.050	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:24:10.033	info	xmlrpc <- listDevices ["hm-rpc.2"]
javascript.0	2019-02-15 16:23:37.709	info	script.js.Garage.Garage: Garage wurde geschlossen
hm-rpc.2	2019-02-15 16:19:10.115	info	new HmIP devices/channels after filter: 0
hm-rpc.2	2019-02-15 16:19:10.103	info	xmlrpc <- newDevices 13
hm-rpc.2	2019-02-15 16:19:09.973	info	xmlrpc -> 0 devices
hm-rpc.2	2019-02-15 16:19:09.953	info	xmlrpc <- listDevices ["hm-rpc.2"]

**Versions:**
 - hm-rpc version: 1.9.6
 - hm-rega version: 3.2.0
 - JS-Controller version: 4.0.12
 - Node version: keine Ahnung (nicht aktuell) irgendwas mit 6
 - Operating system: Synology NAS im Docker
 - CCU model: CCU2
 - CCU firmware: 2.35.16

**Comment by foxriver76** [comment]
Firmware aktuell?

Von meinem iPhone gesendet

**Comment by Baenker** [comment]
Von der ccu nein.

**Comment by foxriver76** [comment]
Okay nur ist das mit ziemlicher Sicherheit das Problem ;-)

**Comment by Baenker** [comment]
Mist. Dann muss ich wohl dadurch. Ich werde das Update machen.

**Comment by foxriver76** [comment]
Gibt im Forum einige Threads zu FW Einstellungen. Letztendlich musst du nichts groß ändern solange Auth aus ist. Maximal den CuxD Port freigeben 8701

**Comment by Baenker** [comment]
Ich habe cixd installiert aber nicht in ioBroker eingebunden muss ich trotzdem einen Port freigeben? Und was meinst Du mit Auth? Ist das eine Einstellung in der ccu?

Rest suche ich mal.

**Comment by foxriver76** [comment]
Ja Sicherheit -> Authentifizierung ist die Einstellung.

Ne, so lange du keine CuxD Instanz hast nein.

**Comment by Baenker** [comment]
Nur zur Info: mit der aktuellen Version ist der Fehler tatsächlich weg. Vielen Dank

**Comment by foxriver76** [comment]
Gerne, danke für deine Rückmeldung.
