### ISSUE TITLE
HM-Dis-EP-WM55 epaper EPAPER_ICON2, EPAPER_ICON3 and EPAPER_ICON4 cannot properly be changed

### ISSUE THREAD

**Issue by stony2k** [ioBroker/ioBroker.hm-rpc#156]
**Describe the bug**
HM-Dis-EP-WM55 epaper display line 2,3 and 4 icons cannot properly be changed in blockly scripts. I tried to change the object type from "boolean" (why is it set to boolean by default?) to string. Shouldn't the error disappear since I've changed the object type to string? The warning appears with javascript controller version 3.6.5 and 4.0.11. I've not tested other versions so far.

**Screenshots & Logfiles**
Log:
_Wrong type of hm-rpc.1.NEQ1463345.0.EPAPER_LINE2: "string". Please fix, while deprecated and will not work in next versions._

Screenshot of blockly test script:
![unbenannt](https://user-images.githubusercontent.com/16526471/52873852-4bc72d80-3150-11e9-852c-9e7ca44ab7e8.JPG)

**Versions:**
 - hm-rpc version: 1.9.7
 - hm-rega version: 2.3.0
 - JS-Controller version: both 3.6.5 and 4.0.11
 - Node version: 8.15.0
 - Operating system: Debian strech
 - CCU model: CCU2
 - CCU firmware: 2.41.5

**Comment by stony2k** [comment]
**Update**
My fault: I've two epaper displays and only changed the type of EPAPER_ICON2, EPAPER_ICON3 and EPAPER_ICON4 to string at one of them. No I've changed the types at both devices and it works.

But I thinks it's still worth changing the standard type from boolean to string, or?

**Comment by foxriver76** [comment]
So are we talking about EPAPER_ICON or EPAPER_LINE or both? Could you show me the RAW of the datapoint?

**Comment by foxriver76** [comment]
Please show the raw of both an icon state and an line state. As far as I know the line can be set to any string value in Homematic and Icon can only be set to predefined icons? Is this correct?

**Comment by stony2k** [comment]
Sorry for the confusion. EPAPER_LINE2 to 4 are fine, I changed the title properly. Here is the raw of EPAPER_ICON2 the serve as a example (please note that I changed "type": "boolean" to "type": "string" in the common part):

`{
  "from": "system.adapter.hm-rega.0",
  "ts": 1550166640260,
  "common": {
    "name": "Lichtschalter Flur Badezimmer (Gerät):0.EPAPER_ICON2",
    "type": "string",
    "read": false,
    "write": true,
    "states": {
      "": "Empty",
      "0x80": "OFF",
      "0x81": "ON",
      "0x82": "Opened",
      "0x83": "Closed",
      "0x84": "error",
      "0x85": "All OK",
      "0x86": "Information",
      "0x87": "New message",
      "0x88": "Service message"
    }
  },
  "native": {
    "TYPE": "EPAPER_ICON",
    "ID": "ICON2",
    "OPERATIONS": 2,
    "STATES": {
      "": "Empty",
      "0x80": "OFF",
      "0x81": "ON",
      "0x82": "Opened",
      "0x83": "Closed",
      "0x84": "error",
      "0x85": "All OK",
      "0x86": "Information",
      "0x87": "New message",
      "0x88": "Service message"
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.1.NEQ1463345.0.EPAPER_ICON2",
  "type": "state"
}`

**Comment by foxriver76** [comment]
I've tried to fix it, but I do not own an epaper display to test. Could you test by installing from GitHub --> Upload --> restart instance --> delete Meta (in hm-rpc.meta) --> delete epaper device in your hm instance --> restart instance

**Comment by stony2k** [comment]
I worked! To confirm: I changed the type to boolean for testing purposes, deleted the 2 devices and restarted the homematic.rpc. The 2 devices were synced again and both EPAPER_LINE2 to 4 and EPAPER_ICON2 to 4 are now string. Thank you! 👍

**Comment by foxriver76** [comment]
Thanks for testing 👍🏼
