### ISSUE TITLE
[bug] HM-PBI-4-FM (Funk-Tasterschnittstelle 4fach)

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.hm-rpc#159]
Ich nutze eine Funk-Tasterschnittstelle 4fach (HM-PBI-4-FM)

Das Problem: egal ob ich über die Taster-SST (also direkt über das an die CCU angelernte Device) short press oder long press mache, im iobroker wird immer nur der state INSTALL_TEST auf true gesetzt. Im log sieht das dann so aus:
![grafik](https://user-images.githubusercontent.com/17086944/53735668-e1202c80-3e87-11e9-89a0-9e0e8a715768.png)
Gleiches gilt auch für xmlrpc.
Wenn ich hingegen via CCU den Tastendruck emuliere:
![grafik](https://user-images.githubusercontent.com/17086944/53735771-280e2200-3e88-11e9-9791-57605d31c3fc.png)
dann sieht es im log so aus:
![grafik](https://user-images.githubusercontent.com/17086944/53735835-50961c00-3e88-11e9-999a-dc3ce636a9d8.png)
also genau wie es sein soll und der state PRESS_SHORT wird im Objektbaum richtig gesetzt. Das klappt für alle vier Kanäle so und jeweils auch für short press und long press.

**Versions:**
 - hm-rpc version: <1.9.8>
 - hm-rega version: <2.3.0>
 - JS-Controller version: <1.5.7>
 - Node version: <8.15.0>
 - Operating system: <Debian 9 im Docker Container>
 - CCU model: <ds1517+>
 - CCU firmware: <2.41.5>

**Comment by Apollon77** [comment]
Du hast ein Dummy Programm anlegegt was diese Buttons nutzt um "Nichts "zu tun?
Per Default werden Button Press nicht überall hin gemeldet (Vermutung um Kommunikation zu sparen). Es landet daher nur dsann bei der Zentrale wenn die daran interessiert ist ... das Dummy-Programm stellt das sicher

**Comment by Steiger04** [comment]
@Apollon77 Mit dem Dummy Programm hatte ich auch gelesen und probiert. Hilft bei dem HM-PBI-4-FM mit firmware v1.5 aber definitiv nicht. Die Lösung des Problems ist die Umstellung des Übertragungsmodus auf Standard für jeden Kanal in der CCU, warum auch immer:

![grafik](https://user-images.githubusercontent.com/17086944/53742054-0cab1300-3e98-11e9-8b6d-b0a85ca5983d.png)

Komisch bleibt es aber trotzdem. Hat aber definitiv nichts mit dem Adapter zu tun.

**Comment by foxriver76** [comment]
Interessant. Was ist die Alternative zu Standard? MMn sollte das nicht so sein, da der Übertragungsmodus nichts mit der API zu tun hat. Evtl ein Issue bei https://github.com/eq-3/occu wert

**Comment by Steiger04** [comment]
@foxriver76 Muss mich bezgl. des Dummy Programmes korrigieren: Dies ist auch weiterhin erforderlich! Aber: der Übertragungsmodus muss beim HM-PBI-4-FM definitiv auf Standard gesetzt werden. Habe jetzt gerade beides noch einmal durchgetestet und nur für den Standardmodus wird auch der PRESS_LONG und PRESS_SHORT state übertragen.
