### ISSUE TITLE
Ping error mit CuxD

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.hm-rpc#160]
folgendes taucht immer wieder im LOG auf:
```
2019-03-06 10:58:36.353 - error: hm-rpc.1 Ping error: Error: response timeout
--
2019-03-06 10:58:36.358 - info: hm-rpc.1 Disconnected
```

**Comment by Matten-Matten** [comment]
cuxd Version 2.2.0
raspberrymatic CCU-Firmware: 3.43.15.20190223
HomeMatic RPC V 1.9.7

**Comment by foxriver76** [comment]
Gab früher mal das Problem, dass CuxD kein Ping unterstüzt hat, taucht die Meldung im gleichen Intervall auf wie das Wiederverbindungsintervall konfiguriert ist? Wenn es unregelmäßig auftritt, evtl. wirklich Verbindungsprobleme?

**Comment by Matten-Matten** [comment]
es tritt sporadisch auf, aber mehrfach am Tag

**Comment by Matten-Matten** [comment]
ich setze den Ping mal auf 120s hoch und dann mal schauen
