### ISSUE TITLE
States lassen sich nicht per MQTT ändern

### ISSUE THREAD

**Issue by Homezecke** [ioBroker/ioBroker.hm-rpc#162]
Hallo,

States von Hm Geräten lassen sich per MQTT zwar ändern, werden sogar bestätigt. Das Gerät zb. SchaltAktor ändert seinen Zustand jedoch nicht. (Schaltet nicht aus bzw ein)

**Comment by foxriver76** [comment]
Wenn du einen State schaltest, spielt es keine Rolle ob du das per Admin, MQTT, simple-api oder oder tust.. Der Adapter wird ein state change mit ack=false abarbeiten. Gibt es hierzu bereits ein Forum Thread, falls nein sollte das die erste Anlaufstelle sein. Grundlegend kann ich dir mit der knapp gehaltenen Beschreibung leider nicht weiterhelfen.

**Comment by Homezecke** [comment]
Ich hatte im Forum schon vor einiger Zeit nachgefragt. Konnte jedoch niemand helfen bzw bestätigen.

[]https://forum.iobroker.net/topic/14919/mit-mqtt-homematic-schalten


Ich verbinde z.B mit einem MQTT client zb. MQTT.fx und Publishe auf den Topic eines HM-Actors ändert sich dessen State wie gewünscht. Aber nur scheinbar, denn das Gerät selbst also die Hardware reagiert nicht. Dies betrifft allein Homematic Geräte. Alle andren States zb auch HM-Rega Systemvariablen, andere MQTT Geräte, javascript usw. lassen sich erfolgreich ändern. und die Änderung wirkt sich auch aus. Nur eben HM Geräte reagieren erst, wenn der zuvor per Mqtt geänderte State noch einmal zb. Händisch gesetzt wird.

**Comment by Apollon77** [comment]
wird auch das ack flag korrekt auf false gesetzt beim steuern?

**Comment by foxriver76** [comment]
Du setzt sicher ohne acknowledge? Kannst du mal bitte ein Debug Log Ausschnitt hiervon zeigen.

**Comment by Homezecke** [comment]
IM Debug Log erscheinen KEINE Meldungen zum Aktor wenn ich diesen per MQTT ändere. Ändere ich den State manuell dann schon. Wie setze ich ein State per MQTT mit ack ?

**Comment by foxriver76** [comment]
http://www.iobroker.net/docu/wp-content/uploads//5.png 3. von unten, falls das aktuell ist. Ich nutze den Adapter nicht.

**Comment by Homezecke** [comment]
ack ist eingeschaltet, noch einmal ohne probiert, das selbe verhalten.

**Comment by foxriver76** [comment]
Hm.. weiß nicht ob das richtig war, glaube da gehts um was anderes. Evtl. hat @Apollon77 Ahnung vom MQTT Adapter. Was ich noch gefunden habe: 

> Use different topic names for set and get - if active, so every state will have two topics: adapter/instance/stateName and adapter/instance/stateName/set. In this case topic with "/set" will be used to send non acknowledged commands (ack: false) and topic without "/set" to receive state updates (with ack: true). The client will receive sent messages back in this mode.

**Comment by foxriver76** [comment]
Von hm-rpc Seite her, kann ich nur sagen, dass der stateChange mindestens geloggt werden muss, so lange er mit ack=false stattfindet: https://github.com/ioBroker/ioBroker.hm-rpc/blob/a30715ae8c8f6d525eb8c325b1f9fb0271efdaa1/hm-rpc.js#L427

**Comment by Homezecke** [comment]
habe jetzt den log auf silly gestellt. Einzige Ausgabe nach Absetzen des MQTT-Publish:

hm-rpc.0 | 2019-03-14 16:53:40.177 | silly | inMem message hm-rpc.0.* hm-rpc.0.NEQ1828511.1.STATE
-- | -- | -- | --
hm-rpc.0 | 2019-03-14 16:53:40.170 | silly | inMem message hm-rpc.0.* hm-rpc.0.NEQ1828511.1.STATE

**Comment by Homezecke** [comment]
mqtt.0 | 2019-03-14 17:14:26.369 | debug | stateChange hm-rpc.0.NEQ1828511.1.STATE: {"val":true,"ack":true,"ts":1552580066360,"q":0,"from":"system.adapter.mqtt-client.7","lc":1552578820165}
-- | -- | -- | --


Die Ausgabe des MQTT Adapters

**Comment by foxriver76** [comment]
Genau da, muss `ack: false` stehen, statt `ack: true`. Also entweder ist es das oder was tiefgreifendes, was ich mir nicht vorstellen kann. Hast du das oben mit dem Topic mal probiert, um ein ack: false zu senden?

**Comment by Homezecke** [comment]
Ja das mit /set habe ich probiert. da kommt dann gar nix mehr an. was mich jetzt etwas verwundert: In den Adaptereinstellungen ist: ack auf false eingestellt. 
![image](https://user-images.githubusercontent.com/45821614/54373678-fcf0b300-467d-11e9-9482-b1ade46804f9.png)

**Comment by Homezecke** [comment]
Ja das mit /set habe ich probiert. da kommt dann gar nix mehr an. was mich jetzt etwas verwundert: In den Adaptereinstellungen ist: ack auf false eingestellt. 
![image](https://user-images.githubusercontent.com/45821614/54373869-480ac600-467e-11e9-8b80-8fc851380856.png)

**Comment by foxriver76** [comment]
So, hatte eben mal Zeit und habe mal den Adapter testwesie aufgesetzt, funktioniert bei mir 1A und es wird auch an mein Heizkörperthermostat übertragen. Wenn du mit mqtt setzt, steht dann der grüne (bestätigte) Wert mit Quelle (hm-rpc oder mqtt)?
![Bildschirmfoto von 2019-03-14 20-57-45](https://user-images.githubusercontent.com/25484431/54387526-ee18f900-469b-11e9-9591-083168bc046a.png)

Zum abgleichen, mein Setup: 
![Bildschirmfoto von 2019-03-14 21-01-52](https://user-images.githubusercontent.com/25484431/54387739-6f708b80-469c-11e9-8ad6-e7aefb0a2ed9.png)
![Bildschirmfoto von 2019-03-14 21-02-00](https://user-images.githubusercontent.com/25484431/54387743-70a1b880-469c-11e9-9327-c8b19c5e9b00.png)

Gesendet habe ich mit meinem Laptop mittels https://www.npmjs.com/package/mqtt-cli
ein Befehl sah so aus:
```bash
moritz@moritz-ThinkPad-E470:~/Schreibtisch/test-mqtt/node_modules/mqtt-cli$ ./mqtt-cli.js 192.168.178.65 hm-rpc/1/000393C99B9EDF.1.SET_POINT_TEMPERATURE/set 14
```

**Comment by Homezecke** [comment]
Hallo,

danke für Deine Hilfe! Habe es auch hinbekommen. Der Haken bei "Unterschiedliche Namen für Setzen und Lesen" muss drin sein und über den Zusatz zum Topic /set . Dann klappt es auch mit den HM-Geräten. Bei allen anderen ist das komischerweise nicht nötig.

Danke nochmals!

**Comment by foxriver76** [comment]
Gerne.
