### ISSUE TITLE
Optimierung der Vorbelegung des Merkmals Rolle für HM-Gerätetyp HM-Sec-RHS 

### ISSUE THREAD

**Issue by NicotheBob** [ioBroker/ioBroker.hm-rpc#163]
**Describe the bug**
Im Zuge der Installation des material ui adapters bin ich über folgenden Punkt gestolpert:

Beim Import der HM-Gerätedaten könnte die Vorbelegung der Rolle für Gerätetyp HM-Sec-RHS verbessert werden, damit beim Aufsetzen des material UI adapters weniger angepasst werden muss.

Bisher wird die Rolle "state" vorgegeben:
![grafik](https://user-images.githubusercontent.com/33368132/54490351-6ad2ef80-48b5-11e9-9db5-973e0e0f9e95.png)

Wünschenswert wäre die Vorbelegung mit "value.window"
![grafik](https://user-images.githubusercontent.com/33368132/54490446-23009800-48b6-11e9-8a9a-c1f41019c27c.png)

Damit funktioniert die Anzeige des Status in der material ui besser. Ist die Anpassung machbar oder gibt es bedenken?

Beste Grüße
Nico

**To Reproduce**

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - hm-rpc version: <rpc-version>
 - hm-rega version: <rega-version>
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - CCU model: <raspberrymatic/CCU/...>
 - CCU firmware: <ccu-version>

**Additional context**

**Comment by foxriver76** [comment]
WINDOW_STATE kann man auf jeden Fall problemlos auf value.window gemappt werden, das werde ich mal einbauen. Bei den STATE Datenpunkten, scheint dieser leider in unterschiedlichen Kontexten von Homematic verwendet zu werden, so nicht nur bei Fenster/Türkontakten sondern auch bei anderen. 

Möglichkeit wäre , wenn ```
obj.native.CONTROL === 'DOOR_SENSOR.STATE'
```
dann obj.common.role = value.window

Ich probiere heute Abend mal, das einzubauen.

**Comment by foxriver76** [comment]
Ist nun implementiert, allerdings wird dies nur bei einem neu anlegen des Gerätes berücksichtigt.

**Comment by NicotheBob** [comment]
Klasse. danke schön :)
