### ISSUE TITLE
Accessin

### ISSUE THREAD

**Issue by do1osc** [ioBroker/ioBroker.hm-rpc#165]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - hm-rpc version: <rpc-version>
 - hm-rega version: <rega-version>
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - CCU model: <raspberrymatic/CCU/...>
 - CCU firmware: <ccu-version>

**Additional context**

**Comment by foxriver76** [comment]
Yeah, makes sense
