### ISSUE TITLE
Problems with Data-Transmission

### ISSUE THREAD

**Issue by do1osc** [ioBroker/ioBroker.hm-rpc#166]
I am using a CCU3 with Firmware 3.45.5.
Since update thw FW to 3.45.5, ii get the following behavior:
I use the JavaScript-Engine for control the Heating-Actors.
If i set more than eg. 5 states, i get an problem. The next ones in the object-browser, the attached state ("keine Bestätigung") will be shown and no data seems to be transmitted to actor.
I do not know what is the problem, the data was not send to the actor.
I have this problem verry verry often since new FW.
 
Before the FW-update i get the problem, too. But this only every eg. 100 setState...

**To Reproduce**
Setup a Script, an write 20 setStates to different Actors.

**Expected behavior**
All data should be transmitted to the actors.

**Screenshots & Logfiles**
![grafik](https://user-images.githubusercontent.com/45193453/55279148-81496400-5315-11e9-951f-2dae935fee23.png)

Example Script:
`on({id: 'MyDataPoints.0.Allgemein.Guten_Morgen', val: true}, function (obj) {
    console.log('Guten Morgen Skript');
    if ((new Date().getDay() === 0 ? 7 : new Date().getDay()) == 6 || (new Date().getDay() === 0 ? 7 : new Date().getDay()) == 7) {
        console.log('Guten Morgen Wochenende');

        setState('hm-rpc.1.INT0000001.1.DURATION_UNIT'/*WHG GR WZ EZ Heizung:1 DURATION UNIT*/, 1);
        setState('hm-rpc.1.INT0000001.1.DURATION_VALUE'/*WHG GR WZ EZ Heizung:1 DURATION VALUE*/, 120);
        setStateDelayed('hm-rpc.1.INT0000001.1.SET_POINT_TEMPERATURE'/*WHG GR WZ EZ Heizung:1 SET POINT TEMPERATURE*/, 22, 1000);
        setTimeout( function() {
            console.log("WZ_EZ_ActTemp=" + getState('hm-rpc.1.INT0000001.1.ACTUAL_TEMPERATURE'/*WHG GR WZ EZ Heizung:1 ACTUAL TEMPERATURE*/).val, "debug");
            console.log("WZ_EZ_BoostTemp=" + (getState('hm-rpc.1.INT0000001.1.SET_POINT_TEMPERATURE'/*WHG GR WZ EZ Heizung:1 SET POINT TEMPERATURE*/).val - 0.5), "debug");
            console.log("BZ_ActTemp=" + getState('hm-rpc.1.INT0000009.1.ACTUAL_TEMPERATURE'/*WHG GR BZ Heizung:1 ACTUAL TEMPERATURE*/).val, "debug");
            console.log("BZ_BoostTemp=" + (getState('hm-rpc.1.INT0000009.1.SET_POINT_TEMPERATURE'/*WHG GR BZ Heizung:1 SET POINT TEMPERATURE*/).val - 0.5), "debug");

            if (getState('hm-rpc.1.INT0000001.1.ACTUAL_TEMPERATURE'/*WHG GR WZ EZ Heizung:1 ACTUAL TEMPERATURE*/).val <= getState('hm-rpc.1.INT0000001.1.SET_POINT_TEMPERATURE'/*WHG GR WZ EZ Heizung:1 SET POINT TEMPERATURE*/).val - 0.5 ) {
                setState('hm-rpc.1.INT0000001.1.BOOST_MODE'/*WHG GR WZ EZ Heizung:1 BOOST MODE*/, true);
                console.log("WZ_Boost ist eingeschaltet", "debug");
            }
            setState('hm-rpc.1.INT0000001.1.DURATION_UNIT'/*WHG GR WZ EZ Heizung:1 DURATION UNIT*/, 1);
            setState('hm-rpc.1.INT0000001.1.DURATION_VALUE'/*WHG GR WZ EZ Heizung:1 DURATION VALUE*/, 120);
            setStateDelayed('hm-rpc.1.INT0000009.1.SET_POINT_TEMPERATURE'/*WHG GR BZ Heizung:1 SET POINT TEMPERATURE*/, 22, 5000);

            if (getState('hm-rpc.1.INT0000009.1.ACTUAL_TEMPERATURE'/*WHG GR BZ Heizung:1 ACTUAL TEMPERATURE*/).val <= getState('hm-rpc.1.INT0000009.1.SET_POINT_TEMPERATURE'/*WHG GR BZ Heizung:1 SET POINT TEMPERATURE*/).val - 0.5 ) {
                setState('hm-rpc.1.INT0000009.1.BOOST_MODE'/*WHG GR BZ Heizung:1 BOOST MODE*/, true);
                console.log("BZ_Boost ist eingeschaltet", "debug");
            }
            setState('hm-rpc.1.INT0000009.1.DURATION_UNIT'/*WHG GR BZ Heizung:1 DURATION UNIT*/, 1);
            setState('hm-rpc.1.INT0000009.1.DURATION_VALUE'/*WHG GR BZ Heizung:1 DURATION VALUE*/, 120);
            setStateDelayed('hm-rpc.1.INT0000009.1.SET_POINT_TEMPERATURE'/*WHG BZ Heizung:1 SET POINT TEMPERATURE*/, 21, 5000);

            setState('hm-rpc.0.0001D8A991108A.4.STATE'/*Hmip-psm 0001d8a991108a:4 state*/, true);
            setState('hm-rpc.0.0001D8A9933E8B.4.STATE'/*Hmip-psm 0001d8a9933e8b:4 state*/, true);

            // Todo: Licht einschalten bei Nacht
        }, 5000);

        setStateDelayed("MyDataPoints.0.Allgemein.Guten_Morgen_Wochenende", false, 5000, false);
    } else {
        console.log('Guten Morgen');
//        setState('hm-rega.0.12233'/*Guten Morgen*/, true);

        setStateDelayed("MyDataPoints.0.Allgemein.Guten_Morgen", false, 5000);
    }
});
`

**Versions:**
 - hm-rpc version: 1.9.9
 - hm-rega version: 2.3.2
 - JS-Controller version: 4.1.12
 - Node version: 8.15.1
 - Operating system: raspian
 - CCU model: CCU3
 - CCU firmware: 3.45.5

**Comment by foxriver76** [comment]
Ich kann es mal probieren nachzustellen, allerdings würde ich empfehlen zwischen den setStates ein kurzes timeout zu fahren von zb 0,5 bis einer Sekunde, da das 868 Mhz Funkpeotokoll sich selbst stören kann. Tauchen im gleichen Fall auch Servicemeldungen auf?

**Comment by do1osc** [comment]
Mit Firmware meine ich die Firmware der CCU3.
Service-Meldungen tauchen keine auf.
Daher bin ich mir nicht sicher ob die setState's überhaupt bei der CCU3 ankommen.

Die Timeouts werde ich noch mal bei jedem setState einfügen.

**Comment by foxriver76** [comment]
Also liegt es eher speziell an den Datenpunkten, ist ja eine Heizgruppe, da muss ich erst mal rein schauen, kann da spontan wenig zu sagen.

**Comment by foxriver76** [comment]
Okay, also es scheint grundsätzlich bei den HMIP Geräten (bei den nicht HMIP-Geräten gibts das gar nicht) nicht übernommen zu werden. Die Frage ist allerdings, was möchtest du damit überhaupt steuern? Ich finde in der CCU keine Option die nach diesem Parameter aussieht, evtl. ist es mal wieder ein gelieferter Parameter mit dem man (aktuell) nichts anfangen kann.

**Comment by do1osc** [comment]
Hallo,

in der CCU ist es :
![image](https://user-images.githubusercontent.com/45193453/55287894-9541a400-53af-11e9-86fa-feb2e73a6f08.png)

Damit sagt man, das das Thermostat für "Duration_Value" (Zeit) , mit der Einheit "Duration_Unit" (Zeiteinheit) eingeschaltet werden soll. Nach dieser Zeit wird dann automatisch das eingestellte Heizprofil wieder aktiviert.

Nach dem setzen der Werte muss man noch den State mit der Temperatur setzen.

**Comment by foxriver76** [comment]
Also die XML-RPC wirft zwar kein Fehler, scheint den Wert jedoch auch nicht zu verarbeiten. Ebenfalls bekomme ich zwar die Existenz des Parameters bestätigt, mittels einer `getParamsetDescription`-Abfrage auf den Channel 1 eines `HmIP-eTRV`:

```javascript
{"VALVE_ADAPTION":{"MIN":false,"OPERATIONS":7,"MAX":true,"FLAGS":1,"ID":"VALVE_ADAPTION","TYPE":"BOOL","DEFAULT":false},"BOOST_TIME":{"MIN":0,"OPERATIONS":5,"MAX":2048,"FLAGS":1,"ID":"BOOST_TIME","TYPE":"INTEGER","DEFAULT":0},"PARTY_MODE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"PARTY_MODE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.PARTY_MODE"},"SET_POINT_TEMPERATURE":{"MIN":4.5,"UNIT":"�C","OPERATIONS":7,"MAX":30.5,"FLAGS":1,"ID":"SET_POINT_TEMPERATURE","TYPE":"FLOAT","DEFAULT":4.5,"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT"},"LEVEL_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"ERROR","FLAGS":1,"ID":"LEVEL_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW","UNDERFLOW","ERROR"]},"PARTY_TIME_START":{"MIN":"2000_01_01 00:00","OPERATIONS":7,"MAX":"2255_12_31 23:55","FLAGS":1,"ID":"PARTY_TIME_START","TYPE":"STRING","DEFAULT":"2000_01_01 00:00","CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_START"},"CONTROL_MODE":{"MIN":0,"OPERATIONS":2,"MAX":3,"FLAGS":1,"ID":"CONTROL_MODE","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.CONTROL_MODE"},"FROST_PROTECTION":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"FROST_PROTECTION","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.FROST_PROTECTION"},"PARTY_SET_POINT_TEMPERATURE":{"MIN":4.5,"OPERATIONS":5,"MAX":30.5,"FLAGS":1,"ID":"PARTY_SET_POINT_TEMPERATURE","TYPE":"FLOAT","DEFAULT":4.5,"CONTROL":"HEATING_CONTROL_HMIP.PARTY_SETPOINT_TEMP"},"SET_POINT_MODE":{"MIN":0,"OPERATIONS":7,"MAX":3,"FLAGS":1,"ID":"SET_POINT_MODE","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT_MODE"},"LEVEL":{"MIN":0,"OPERATIONS":7,"MAX":1.005,"FLAGS":1,"ID":"LEVEL","TYPE":"FLOAT","DEFAULT":0},"ACTUAL_TEMPERATURE_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"UNDERFLOW","FLAGS":1,"ID":"ACTUAL_TEMPERATURE_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW","UNDERFLOW"]},"DURATION_UNIT":{"MIN":"S","OPERATIONS":2,"MAX":"H","FLAGS":1,"ID":"DURATION_UNIT","TYPE":"ENUM","DEFAULT":"S","VALUE_LIST":["S","M","H"]},"SWITCH_POINT_OCCURED":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"SWITCH_POINT_OCCURED","TYPE":"BOOL","DEFAULT":false},"CONTROL_DIFFERENTIAL_TEMPERATURE":{"MIN":-10,"OPERATIONS":2,"MAX":10,"FLAGS":1,"ID":"CONTROL_DIFFERENTIAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0},"VALVE_STATE":{"MIN":"STATE_NOT_AVAILABLE","OPERATIONS":5,"MAX":"ERROR_POSITION","FLAGS":9,"ID":"VALVE_STATE","TYPE":"ENUM","DEFAULT":"STATE_NOT_AVAILABLE","VALUE_LIST":["STATE_NOT_AVAILABLE","RUN_TO_START","WAIT_FOR_ADAPTION","ADAPTION_IN_PROGRESS","ADAPTION_DONE","TOO_TIGHT","ADJUSTMENT_TOO_BIG","ADJUSTMENT_TOO_SMALL","ERROR_POSITION"]},"ACTIVE_PROFILE":{"MIN":1,"OPERATIONS":7,"MAX":3,"FLAGS":1,"ID":"ACTIVE_PROFILE","TYPE":"INTEGER","DEFAULT":1,"CONTROL":"HEATING_CONTROL_HMIP.ACTIVE_PROFILE"},"WINDOW_STATE":{"MIN":"CLOSED","OPERATIONS":7,"MAX":"OPEN","FLAGS":1,"ID":"WINDOW_STATE","TYPE":"ENUM","DEFAULT":"CLOSED","VALUE_LIST":["CLOSED","OPEN"],"CONTROL":"HEATING_CONTROL_HMIP.WINDOW_STATE"},"PARTY_TIME_END":{"MIN":"2000_01_01 00:00","OPERATIONS":7,"MAX":"2255_12_31 23:55","FLAGS":1,"ID":"PARTY_TIME_END","TYPE":"STRING","DEFAULT":"2000_01_01 00:00","CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_END"},"ACTUAL_TEMPERATURE":{"MIN":-3276.8,"OPERATIONS":5,"MAX":3276.7,"FLAGS":1,"ID":"ACTUAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.TEMPERATURE"},"BOOST_MODE":{"MIN":false,"OPERATIONS":6,"MAX":true,"FLAGS":1,"ID":"BOOST_MODE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.BOOST_MODE"},"DURATION_VALUE":{"MIN":0,"OPERATIONS":2,"MAX":16343,"FLAGS":1,"ID":"DURATION_VALUE","TYPE":"INTEGER","DEFAULT":0}}
```
Entsprechend legen wir das Objekt auch im ioBroker an, der Wert lässt sich jedoch nicht per XML-RPC auslesen und somit wird der zugehörige State nur zu Beginn durch REGA gefüllt. 
Laut der Operations Angabe von DURATION_VALUE sollte sich dieser jedoch per XML RPC steuern lassen.

Ein `getParamset` auf den Channel eines `HmIP-eTRV` liefert lediglich (jedoch sollte das nicht unbedingt aussagekräftig sein):

```javascript
{"BOOST_TIME":0,"PARTY_MODE":false,"SET_POINT_TEMPERATURE":14,"LEVEL_STATUS":0,"FROST_PROTECTION":false,"SET_POINT_MODE":0,"LEVEL":0,"ACTUAL_TEMPERATURE_STATUS":0,"SWITCH_POINT_OCCURED":false,"VALVE_STATE":4,"ACTIVE_PROFILE":1,"WINDOW_STATE":0,"ACTUAL_TEMPERATURE":17.5,"BOOST_MODE":false}
```

mMn sollte die XML-RPC das gewünschte Verhalten also hergeben. Wäre also ein Bug bei https://github.com/eq-3/occu wert.

**Comment by do1osc** [comment]
Okay, danke für den schnellen Support. Möchtest du dazu bei der occu ein Ticket anlegen? Du steckst da deutlich mehr drin als ich....

**Comment by foxriver76** [comment]
Schon erledigt. ;-)

**Comment by foxriver76** [comment]
.
