### ISSUE TITLE
Not possible to react on button press of epaper display

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.hm-rpc#167]
The ePaper display HM-Dis-EP-WM55 offers multiple datapoints for e.g. PRESS_SHORT and PRESS_LONG.
But it is not possible to react on those button clicks in Javascript.
E.g.
```
on(/^hm-rpc\.0\.NEQxxxxxx\.(0-9)\.PRESS_SHORT$/, function (obj) {
   log("pressed:" + obj._id);
});
```
is never triggered. 
You can see that the value gets updated (short green update in the object tree), but the JS is never triggered. Perhaps because it updates the value from true to true and therefor is not a real change and therefor not triggers the JS "on" function?

**Comment by foxriver76** [comment]
You are listening on a state change and not on an update. See https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state
