### ISSUE TITLE
IP Wired not working properly (HmIPW-DRS8)

### ISSUE THREAD

**Issue by KristianHeider** [ioBroker/ioBroker.hm-rpc#169]
There is only :0 with sub items all other channels meaningless.
![image](https://user-images.githubusercontent.com/17590490/56039849-86ef7280-5d35-11e9-95a8-70a297d87a93.png)

hm-rpc version 1.99

**Comment by foxriver76** [comment]
Bitte Log von den Metadaten, beim erstmaligen einlesen des Gerätes sollten die auf warn geloggt werden, sonst kann ich nicht beurteilen was da sein sollte. Falls es zu lange her ist, mal die Meta Daten hm-rpc.meta für das device unter Objekte löschen und das device selbst löschen unter Objekte und hm-rpc neustarten

**Comment by KristianHeider** [comment]
Für hmipw-drs8 (IP Wired 8fach https://www.elv.de/homematic-ip-wired-8-fach-schaltaktor.html <https://www.elv.de/homematic-ip-wired-8-fach-schaltaktor.html>) gibt es keine Metadaten (hm-rpc.meta). Wahrscheinlich wird es einfach noch nicht unterstützt. Sag, wenn ich weitere Infos geben kann.

**Comment by foxriver76** [comment]
Bist du sicher, dass es kein Objekt hm-rpc.VALUES.HmIPW-DRS8 gibt? Beim anlegen muss etwas geloggt werden, wenn das Gerät nicht bekannt ist. Welche Objekte sind im Channel 0, nur ALARM Objekte? Sonst kannst du mal noch folgendes Programm auf der CCU ausführen, um zu schauen, was lt Logikschicht für das Gerät da ist:

```
!# datapoints.fn 1.8
!#
!# Dieses Homematic-Script gibt eine Liste aller Datenpunkte (ausser WORKING/DIRECTION) als JSON String aus
!#
!# 3'2013-9'2014 hobbyquaker https://github.com/hobbyquaker
!#

string sDevId;
string sChnId;
string sDPId;
string sValue;
string sChnId;
string sDPId;
boolean dpFirst = true;
Write('{');
foreach (sDevId, root.Devices().EnumUsedIDs()) {
    object oDevice   = dom.GetObject(sDevId);
    boolean bDevReady = oDevice.ReadyConfig();
    if (bDevReady) {
        foreach (sChnId, oDevice.Channels()) {
            object oChannel = dom.GetObject(sChnId);
            foreach(sDPId, oChannel.DPs().EnumUsedIDs()) {
                object oDP = dom.GetObject(sDPId);
                if (oDP) {
                    if (oDP.TypeName() != "VARDP") {
                        if (dpFirst) {
                          dpFirst = false;
                        } else {
                          WriteLine(',');
                        }
                        string sValueType = oDP.ValueType();
                        Write('"');
                        WriteURL(oDP.Name());
                        Write('":');
                        if (sValueType == 20) {
                            Write('"');
                            WriteURL(oDP.Value());
                            Write('"');
                        } else {
                            sValue = oDP.Value();
                            if (sValueType == 2) {
                                if (sValue) {
                                    Write("true");
                                } else {
                                    Write("false");
                                }
                            } else {
                               if (sValue == "") {
                                    Write("0");
                               } else {
                                    Write(sValue);
                               }
                            }
                        }
                    }
                }
            }
        }
    }
}
Write('}');
```

**Comment by KristianHeider** [comment]
Du meinst hm-rpc.meta.VALUES.HmIPW…? Nichts. Auch nach DRS8 gesucht. Überhaupt keine HmIPW Values, nur HMW.
SN geändert:
0	
HmIPW-DRS8 00:0
edit
delete
CONFIG_PENDING_ALARM	

HmIPW-DRS8 00:0.CONFIG_PENDING_ALARM
state	indicator.alarm			ACKNOWLEDGED(2)	edit
delete
build
ERROR_OVERHEAT_ALARM	

HmIPW-DRS8 00:0.ERROR_OVERHEAT_ALARM
state	indicator.alarm			NO ALARM(0)	edit
delete
build
ERROR_UNDERVOLTAGE_ALARM	

HmIPW-DRS8 00:0.ERROR_UNDERVOLTAGE_ALARM
state	indicator.alarm			NO ALARM(0)	edit
delete
build
UNREACH_ALARM	

HmIPW-DRS8 00:0.UNREACH_ALARM
state	indicator.alarm			ACKNOWLEDGED(2)	edit
delete
build
UPDATE_PENDING_ALARM	

HmIPW-DRS8 00:0.UPDATE_PENDING_ALARM
state	indicator.alarm			NO ALARM(0)content_copyedit
Also nur Alarm Objekte.

Komisch in der Logikschicht gibt es gar kein HMIPW oder DRS8. Soll ich die ganze List wirklich veröffentlichen?

**Comment by KristianHeider** [comment]
Homematic RaspberryMatic 
3.45.5.20190330

**Comment by foxriver76** [comment]
> Du meinst hm-rpc.meta.VALUES.HmIPW…?
Ja meinte ich.

> Komisch in der Logikschicht gibt es gar kein HMIPW oder DRS8. Soll ich die ganze List wirklich veröffentlichen?
Such mal bitte nach der Seriennummer in der Ausgabe von dem Skript, also die 000..., die du im ersten Post (Screenshot) anonymisiert hast.

Soweit ich das richtig im Kopf hatte, hat jens maus mal in den Release Notes geschrieben, dass alle HMIPW Geräte nun von der CCU komplett unterstützt sind (darunter würde ich auch die API's fassen) und du bist ja auf der neusten CCU-FW.

**Comment by KristianHeider** [comment]
Wobei ich die Anfänglichen 00XXX der Seriennummer ersetzt habe.

"HmIP-RF.00XXX%3A0.ACTUAL_TEMPERATURE":21.000000,
"HmIP-RF.00XXX%3A0.CONFIG_PENDING":false,
"HmIP-RF.00XXX%3A0.ERROR_CODE":0,
"HmIP-RF.00XXX%3A0.ERROR_OVERHEAT":false,
"HmIP-RF.00XXX%3A0.ERROR_UNDERVOLTAGE":false,
"HmIP-RF.00XXX%3A0.IDENTIFICATION_MODE_KEY_VISUAL":false,
"HmIP-RF.00XXX%3A0.IDENTIFICATION_MODE_LCD_BACKLIGHT":false,
"HmIP-RF.00XXX%3A0.IDENTIFY_DURATION":0,
"HmIP-RF.00XXX%3A0.IDENTIFY_TARGET_LEVEL":0,
"HmIP-RF.00XXX%3A0.OPERATING_VOLTAGE":24.100000,
"HmIP-RF.00XXX%3A0.OPERATING_VOLTAGE_STATUS":0,
"HmIP-RF.00XXX%3A0.UNREACH":false,
"HmIP-RF.00XXX%3A0.UPDATE_PENDING":false,
"HmIP-RF.00XXX%3A1.PROCESS":0,
"HmIP-RF.00XXX%3A1.SECTION":0,
"HmIP-RF.00XXX%3A1.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A1.STATE":false,
"HmIP-RF.00XXX%3A2.ON_TIME":0,
"HmIP-RF.00XXX%3A2.PROCESS":0,
"HmIP-RF.00XXX%3A2.SECTION":0,
"HmIP-RF.00XXX%3A2.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A2.STATE":false,
"HmIP-RF.00XXX%3A3.ON_TIME":0,
"HmIP-RF.00XXX%3A3.PROCESS":0,
"HmIP-RF.00XXX%3A3.SECTION":0,
"HmIP-RF.00XXX%3A3.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A3.STATE":false,
"HmIP-RF.00XXX%3A4.ON_TIME":0,
"HmIP-RF.00XXX%3A4.PROCESS":0,
"HmIP-RF.00XXX%3A4.SECTION":0,
"HmIP-RF.00XXX%3A4.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A4.STATE":false,
"HmIP-RF.00XXX%3A5.PROCESS":0,
"HmIP-RF.00XXX%3A5.SECTION":0,
"HmIP-RF.00XXX%3A5.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A5.STATE":false,
"HmIP-RF.00XXX%3A6.ON_TIME":0,
"HmIP-RF.00XXX%3A6.PROCESS":0,
"HmIP-RF.00XXX%3A6.SECTION":0,
"HmIP-RF.00XXX%3A6.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A6.STATE":false,
"HmIP-RF.00XXX%3A7.ON_TIME":0,
"HmIP-RF.00XXX%3A7.PROCESS":0,
"HmIP-RF.00XXX%3A7.SECTION":0,
"HmIP-RF.00XXX%3A7.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A7.STATE":false,
"HmIP-RF.00XXX%3A8.ON_TIME":0,
"HmIP-RF.00XXX%3A8.PROCESS":0,
"HmIP-RF.00XXX%3A8.SECTION":0,
"HmIP-RF.00XXX%3A8.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A8.STATE":false,
"HmIP-RF.00XXX%3A9.PROCESS":0,
"HmIP-RF.00XXX%3A9.SECTION":0,
"HmIP-RF.00XXX%3A9.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A9.STATE":false,
"HmIP-RF.00XXX%3A10.ON_TIME":0,
"HmIP-RF.00XXX%3A10.PROCESS":0,
"HmIP-RF.00XXX%3A10.SECTION":0,
"HmIP-RF.00XXX%3A10.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A10.STATE":false,
"HmIP-RF.00XXX%3A11.ON_TIME":0,
"HmIP-RF.00XXX%3A11.PROCESS":0,
"HmIP-RF.00XXX%3A11.SECTION":0,
"HmIP-RF.00XXX%3A11.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A11.STATE":false,
"HmIP-RF.00XXX%3A12.ON_TIME":0,
"HmIP-RF.00XXX%3A12.PROCESS":0,
"HmIP-RF.00XXX%3A12.SECTION":0,
"HmIP-RF.00XXX%3A12.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A12.STATE":false,
"HmIP-RF.00XXX%3A13.PROCESS":0,
"HmIP-RF.00XXX%3A13.SECTION":0,
"HmIP-RF.00XXX%3A13.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A13.STATE":false,
"HmIP-RF.00XXX%3A14.ON_TIME":0,
"HmIP-RF.00XXX%3A14.PROCESS":0,
"HmIP-RF.00XXX%3A14.SECTION":0,
"HmIP-RF.00XXX%3A14.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A14.STATE":false,
"HmIP-RF.00XXX%3A15.ON_TIME":0,
"HmIP-RF.00XXX%3A15.PROCESS":0,
"HmIP-RF.00XXX%3A15.SECTION":0,
"HmIP-RF.00XXX%3A15.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A15.STATE":false,
"HmIP-RF.00XXX%3A16.ON_TIME":0,
"HmIP-RF.00XXX%3A16.PROCESS":0,
"HmIP-RF.00XXX%3A16.SECTION":0,
"HmIP-RF.00XXX%3A16.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A16.STATE":false,
"HmIP-RF.00XXX%3A17.PROCESS":0,
"HmIP-RF.00XXX%3A17.SECTION":0,
"HmIP-RF.00XXX%3A17.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A17.STATE":false,
"HmIP-RF.00XXX%3A18.ON_TIME":0,
"HmIP-RF.00XXX%3A18.PROCESS":0,
"HmIP-RF.00XXX%3A18.SECTION":0,
"HmIP-RF.00XXX%3A18.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A18.STATE":false,
"HmIP-RF.00XXX%3A19.ON_TIME":0,
"HmIP-RF.00XXX%3A19.PROCESS":0,
"HmIP-RF.00XXX%3A19.SECTION":0,
"HmIP-RF.00XXX%3A19.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A19.STATE":false,
"HmIP-RF.00XXX%3A20.ON_TIME":0,
"HmIP-RF.00XXX%3A20.PROCESS":0,
"HmIP-RF.00XXX%3A20.SECTION":0,
"HmIP-RF.00XXX%3A20.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A20.STATE":false,
"HmIP-RF.00XXX%3A21.PROCESS":0,
"HmIP-RF.00XXX%3A21.SECTION":0,
"HmIP-RF.00XXX%3A21.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A21.STATE":false,
"HmIP-RF.00XXX%3A22.ON_TIME":0,
"HmIP-RF.00XXX%3A22.PROCESS":0,
"HmIP-RF.00XXX%3A22.SECTION":0,
"HmIP-RF.00XXX%3A22.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A22.STATE":false,
"HmIP-RF.00XXX%3A23.ON_TIME":0,
"HmIP-RF.00XXX%3A23.PROCESS":0,
"HmIP-RF.00XXX%3A23.SECTION":0,
"HmIP-RF.00XXX%3A23.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A23.STATE":false,
"HmIP-RF.00XXX%3A24.ON_TIME":0,
"HmIP-RF.00XXX%3A24.PROCESS":0,
"HmIP-RF.00XXX%3A24.SECTION":0,
"HmIP-RF.00XXX%3A24.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A24.STATE":false,
"HmIP-RF.00XXX%3A25.PROCESS":0,
"HmIP-RF.00XXX%3A25.SECTION":0,
"HmIP-RF.00XXX%3A25.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A25.STATE":false,
"HmIP-RF.00XXX%3A26.ON_TIME":0,
"HmIP-RF.00XXX%3A26.PROCESS":0,
"HmIP-RF.00XXX%3A26.SECTION":0,
"HmIP-RF.00XXX%3A26.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A26.STATE":false,
"HmIP-RF.00XXX%3A27.ON_TIME":0,
"HmIP-RF.00XXX%3A27.PROCESS":0,
"HmIP-RF.00XXX%3A27.SECTION":0,
"HmIP-RF.00XXX%3A27.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A27.STATE":false,
"HmIP-RF.00XXX%3A28.ON_TIME":0,
"HmIP-RF.00XXX%3A28.PROCESS":0,
"HmIP-RF.00XXX%3A28.SECTION":0,
"HmIP-RF.00XXX%3A28.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A28.STATE":false,
"HmIP-RF.00XXX%3A29.PROCESS":0,
"HmIP-RF.00XXX%3A29.SECTION":0,
"HmIP-RF.00XXX%3A29.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A29.STATE":false,
"HmIP-RF.00XXX%3A30.ON_TIME":0,
"HmIP-RF.00XXX%3A30.PROCESS":0,
"HmIP-RF.00XXX%3A30.SECTION":0,
"HmIP-RF.00XXX%3A30.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A30.STATE":false,
"HmIP-RF.00XXX%3A31.ON_TIME":0,
"HmIP-RF.00XXX%3A31.PROCESS":0,
"HmIP-RF.00XXX%3A31.SECTION":0,
"HmIP-RF.00XXX%3A31.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A31.STATE":false,
"HmIP-RF.00XXX%3A32.ON_TIME":0,
"HmIP-RF.00XXX%3A32.PROCESS":0,
"HmIP-RF.00XXX%3A32.SECTION":0,
"HmIP-RF.00XXX%3A32.SECTION_STATUS":0,
"HmIP-RF.00XXX%3A32.STATE":false,
"HmIP-RF.00XXX%3A33.WEEK_PROGRAM_CHANNEL_LOCKS":0,
"HmIP-RF.00XXX%3A33.WEEK_PROGRAM_TARGET_CHANNEL_LOCK":0,
"HmIP-RF.00XXX%3A33.WEEK_PROGRAM_TARGET_CHANNEL_LOCKS":0,

**Comment by foxriver76** [comment]
Schaut gut aus. Hast du andere HmIP-Geräte, die korrekt funktionieren? Und hm-rpc.2 ist korrekt konfiguriert auf HmIP und die einzige HmIP-Instanz?

Du kannst mal noch schauen ob das Paramset lesbar ist, durch folgendes Skript (javascript Adapter)

```
sendTo('hm-rpc.2', 'getParamsetDescription', {ID: '000453D77B9EDF:0', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});
```

wobei du die ID durch die deines Gerätes ersetzt.

**Comment by KristianHeider** [comment]
Habe viele HMIP die seit Jahren funktionieren. hm-rpc.1 ist alte Homematic, 2 HMIP und 3 CuxD

javascript.0 script.js.Skript1: {"result":{"CONFIG_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"CONFIG_PENDING","TYPE":"BOOL","DEFAULT":false},"INSTALL_TEST":{"MIN":false,"OPERATIONS":3,"MAX":true,"FLAGS":2,"ID":"INSTALL_TEST","TYPE":"BOOL","DEFAULT":false},"ERROR_OVERHEAT":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"ERROR_OVERHEAT","TYPE":"BOOL","DEFAULT":false},"IDENTIFICATION_MODE_KEY_VISUAL":{"MIN":false,"OPERATIONS":2,"MAX":true,"FLAGS":1,"ID":"IDENTIFICATION_MODE_KEY_VISUAL","TYPE":"BOOL","DEFAULT":false,"CONTROL":"IDENTIFICATION.IDENTIFICATION_MODE_KEY_VISUAL"},"IDENTIFICATION_MODE_LCD_BACKLIGHT":{"MIN":false,"OPERATIONS":2,"MAX":true,"FLAGS":1,"ID":"IDENTIFICATION_MODE_LCD_BACKLIGHT","TYPE":"BOOL","DEFAULT":false,"CONTROL":"IDENTIFICATION.IDENTIFICATION_MODE_LCD_BACKLIGHT"},"IDENTIFY_TARGET_LEVEL":{"MIN":0,"UNIT":"100%","OPERATIONS":2,"MAX":1,"FLAGS":1,"ID":"IDENTIFY_TARGET_LEVEL","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"IDENTIFICATION.IDENTIFY_TARGET_LEVEL"},"OPERATING_VOLTAGE_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"OVERFLOW","FLAGS":1,"ID":"OPERATING_VOLTAGE_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW"]},"IDENTIFY_DURATION":{"MIN":0,"UNIT":"s","OPERATIONS":2,"MAX":8580000,"FLAGS":1,"ID":"IDENTIFY_DURATION","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"IDENTIFICATION.IDENTIFY_DURATION"},"ERROR_CODE":{"MIN":0,"OPERATIONS":5,"MAX":255,"FLAGS":9,"ID":"ERROR_CODE","TYPE":"INTEGER","DEFAULT":0},"UPDATE_PENDING":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"UPDATE_PENDING","TYPE":"BOOL","DEFAULT":false},"ERROR_UNDERVOLTAGE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"ERROR_UNDERVOLTAGE","TYPE":"BOOL","DEFAULT":false},"UNREACH":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":25,"ID":"UNREACH","TYPE":"BOOL","DEFAULT":false},"ACTUAL_TEMPERATURE":{"MIN":-3276.8,"OPERATIONS":5,"MAX":3276.7,"FLAGS":1,"ID":"ACTUAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0},"OPERATING_VOLTAGE":{"MIN":0,"OPERATIONS":5,"MAX":25.2,"FLAGS":1,"ID":"OPERATING_VOLTAGE","TYPE":"FLOAT","DEFAULT":0}},"error":null}

bei :1 kommt folgendes

javascript.0 script.js.Skript1: {"result":{"SECTION_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"UNKNOWN","FLAGS":1,"ID":"SECTION_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN"]},"PROCESS":{"MIN":"STABLE","OPERATIONS":5,"MAX":"NOT_STABLE","FLAGS":1,"ID":"PROCESS","TYPE":"ENUM","DEFAULT":"STABLE","VALUE_LIST":["STABLE","NOT_STABLE"]},"STATE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"STATE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"SWITCH_TRANSMITTER.STATE"},"SECTION":{"MIN":0,"OPERATIONS":5,"MAX":15,"FLAGS":1,"ID":"SECTION","TYPE":"INTEGER","DEFAULT":0}},"error":null}

**Comment by foxriver76** [comment]
Grundsätzlich kann der Adapter auf die Informationen zugreifen, die er benötigt um die Objekte anzulegen. Hast du schon mal die Adapter neugestartet, und evtl.das Gerät gelöscht und nochmal neu einlesen lassen?

**Comment by KristianHeider** [comment]
Danke für deine Mühe.
Nachdem ich den rpc.2 gelöscht und neu angelegt habe, ist alles wie erwartet da.
Ich hatte schon früher alle Geräte neu einlesen probiert, dass hatte nicht den gewünschten Erfolg.
Close

**Comment by foxriver76** [comment]
Freut mich dass es jetzt geht, allerdings schade dass man die Ursache nicht ausfindig machen konnte wie es zu dem Verhalten kam.
