### ISSUE TITLE
Frage zu metas

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.hm-rpc#170]
Was hat es für Auswirkung, wenn es für einige HmIP-Geräte keine Meta's gibt? Ich habe festgestellt, dass es für HmIP-BROLL und HmIP-eTRV-2 aktuell keine gibt.

**Comment by foxriver76** [comment]
In den meisten Fällen hat es keine Auswirkung. Hast du ein bestimmtes Problem? Allerdings werden die Meta-Daten geloggt, wenn ein Gerät ohne Metadaten in Betrieb genommen wird. Ich füge sie in den meisten Fällen ohne Änderung in den Adapter hinzu.

**Comment by Hirsch-DE** [comment]
Ich wollte einige Voreinstellungen über die metas gleich mit erledigen.
Deshalb hab ich mal ein Pull request  ausgelöst. ;-)
