### ISSUE TITLE
RPC/REGA communication loss to piVCCU

### ISSUE THREAD

**Issue by madjack84** [ioBroker/ioBroker.hm-rpc#176]
**Describe the bug**
Ich nutze piVCCU und ioBroker auf einem RPI3
siehe auch hier eine Beschreibung
https://homematic-forum.de/forum/viewtopic.php?f=69&t=40902&p=511292#p511292
Funktioniert beim Start auch recht gut, nur gibt es Probleme bei der Verbindung über RPC und die Werte/Objekte bekommen kein Update mehr :(

Im Hover Over in den Objekten von ioBroker ist mir aufgefallen, dass der Rega Adapter die Werte schreibt. Starte ich diesen neu, so kommen neue Werte an. 

Komischerweise steht das RPC Adapter Objekt "updated" immer auf true was auch für fehlende Kommunikation via RPC spricht. Ich habe keine weiteren Geräte mehr angelegt

**Wie kann man die RPC Schnittstelle testen um heraus zu finden woran das liegen kann und wer hier faxen macht?**
Leider bin ich was RPC angeht leider gar nicht tief drin :(

>> Edit: Debug piVCCU sudo pivccu-attach cat /var/log/messages
`May 29 00:20:02 homematic-ccu2 user.err Sniffing Mode: XmlRpc transport error calling system.listMethods({"hm-rpc.0"}) on http://192.168.188.75:2001/RPC2:
May 29 00:20:02 homematic-ccu2 user.err Sniffing Mode: XmlRpc transport error calling listDevices({"hm-rpc.0"}) on http://192.168.188.75:2001/RPC2:`

Ich habe das System mit dieser IP aufgesetzt und dann in das neue WLAN gehangen 192.168.178.24. Eine Edition der Adapter Adresse in der GUI habe ich vorgenommen.... aber wie wird das im Hintergrund verarbeitet wenn die Verbindung schonmal stand?
Eine Löschung und erneute Installation des RPC Adapters scheint Abhilfe geschaffen zu haben. Ich beobachte. Wäre aber cool wenn du dir mal anschaust ob diese IP Änderung grundlegend funktioniert :)

Der Adapter scheint sich laut log zu verbinden :/ aber hier stehe schon die beiden unterschiedlichen Adressen drin
<img width="1034" alt="Bildschirmfoto 2019-05-28 um 23 28 01" src="https://user-images.githubusercontent.com/24653087/58514650-d33a2900-81a2-11e9-86db-b1ae3b07ad54.png">

hier die Config des Adapters:
![image](https://user-images.githubusercontent.com/24653087/58516945-f87e6580-81a9-11e9-9710-7f685b1a87c1.png)

Geräteseitig ist nur eine Steckdose an der CCU dran. Kein HMIP, kein CUxD

**Versions:**
 - hm-rpc version: 1.9.11
 - hm-rega version: 2.3.3
 - JS-Controller version: 1.4.2
 - Node version: v8.16.0
 - Operating system: raspian stretch
 - CCU model: piVCCU3
 - CCU firmware:  3.45.7-23

Vielen Dank an der Stelle für deine Arbeit @foxriver76  und den Support :)

grüße
Michael

**Comment by foxriver76** [comment]
Moin, 

Gib mal als callbackadresse explizit die IP an unter der dein ioBroker erreichbar ist.

Von meinem iPhone gesendet

**Comment by madjack84** [comment]
oha... Danke für den Tip. Damit hatte ich rumgespielt und im Backup habe ich eben ausgelesen, dass grade die Callback Adresse auch gesetzt war. Evtl hab ich das übersehen :(
Sorry.

"native": {
          "homematicAddress": "192.168.253.2",
          "adapterAddress": "192.168.178.24",
          "homematicPort": "2001",
          "callbackAddress": "192.168.188.75",

**Comment by foxriver76** [comment]
Gerne. ;-)

Von meinem iPhone gesendet
