### ISSUE TITLE
Kein wieder verbinden des rpc mit cuxd nach CCU Neustart

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.hm-rpc#177]
```
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: port: 8701 }
-- | -- | -- | --
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: address: '192.168.27.42',
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: syscall: 'connect',
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: errno: 'ECONNREFUSED',
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: code: 'ECONNREFUSED',
Caught | 2019-06-29 15:22:16.103 | error | by controller[0]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
Caught | 2019-06-29 15:22:16.102 | error | by controller[0]: at exports._exceptionWithHostPort (util.js:1043:20)
Caught | 2019-06-29 15:22:16.101 | error | by controller[0]: at Object.exports._errnoException (util.js:1020:11)
Caught | 2019-06-29 15:22:16.097 | error | by controller[0]: { Error: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1 | 2019-06-29 15:22:15.996 | info | binrpc -> 192.168.27.42:8701/ init ["xmlrpc_bin://192.168.27.38:8701",""]
hm-rpc.1 | 2019-06-29 15:22:15.994 | error | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
hm-rpc.1 | 2019-06-29 15:22:15.994 | error | at exports._exceptionWithHostPort (util.js:1043:20)
hm-rpc.1 | 2019-06-29 15:22:15.994 | error | at Object.exports._errnoException (util.js:1020:11)
hm-rpc.1 | 2019-06-29 15:22:15.994 | error | Error: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1 | 2019-06-29 15:22:15.993 | error | uncaught exception: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1 | 2019-06-29 15:22:13.062 | info | Disconnected
hm-rpc.1 | 2019-06-29 15:22:13.045 | error | Ping error: Error: response timeout
```

**Comment by foxriver76** [comment]
On an uncaught exception the adapter process should be restarted by js-controller, thus  please provide information if this is the case.

**Comment by Apollon77** [comment]
But the error should be catched by the Adapter or?! ;-)

**Comment by Matten-Matten** [comment]
javascript.0	2019-06-29 15:23:21.996	info	script.js.FritzBox.FritzBox_State.WLAN: Fritzbox WLAN2.4GHz ist: true
hm-rega.0	2019-06-29 15:23:21.627	info	request state values
hm-rega.0	2019-06-29 15:23:21.626	info	deleted 0 variables
hm-rega.0	2019-06-29 15:23:21.626	info	added/updated 490 variables
hm-rega.0	2019-06-29 15:23:21.319	info	got 489 variables
hm-rega.0	2019-06-29 15:23:18.460	info	time difference local-ccu 0s
javascript.0	2019-06-29 15:23:18.451	info	script.js.Homematic_Hilfsprogramme.Werte_in_ccu_nach_Connection_is_true: Werte werden in CCU übertragen
hm-rega.0	2019-06-29 15:23:18.446	info	ReGaHSS 192.168.27.42 up
javascript.0	2019-06-29 15:23:14.301	error	script.js.Homematic_Hilfsprogramme.MATZE_im_WLAN: Error: connect ECONNREFUSED 192.168.27.47:50000
hm-rega.0	2019-06-29 15:22:56.660	error	Cannot parse answer for devices: undefined
hm-rpc.1	2019-06-29 15:22:53.230	info	Connected
hm-rpc.1	2019-06-29 15:22:53.227	info	new CUxD devices/channels after filter: 0
hm-rpc.1	2019-06-29 15:22:53.039	info	binrpc -> listDevices 912
hm-rpc.1	2019-06-29 15:22:49.198	info	binrpc client is trying to connect to 192.168.27.42:8701/ with ["xmlrpc_bin://192.168.27.38:8701","hm-rpc.1"]
hm-rpc.1	2019-06-29 15:22:49.195	info	binrpc server is trying to listen on 192.168.27.38:8701
hm-rega.0	2019-06-29 15:22:48.404	error	ReGaHSS down
hm-rpc.1	2019-06-29 15:22:47.273	info	starting. Version 1.9.13 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v6.16.0
host.ioBroker-Tinker	2019-06-29 15:22:46.188	info	instance system.adapter.hm-rpc.1 started with pid 2012
hm-rega.0	2019-06-29 15:22:18.358	error	CCU 192.168.27.42 unreachable
host.ioBroker-Tinker	2019-06-29 15:22:16.103	info	Restart adapter system.adapter.hm-rpc.1 because enabled
host.ioBroker-Tinker	2019-06-29 15:22:16.103	error	instance system.adapter.hm-rpc.1 terminated with code 0 (OK)
Caught	2019-06-29 15:22:16.103	error	by controller[0]: port: 8701 }
Caught	2019-06-29 15:22:16.103	error	by controller[0]: address: '192.168.27.42',
Caught	2019-06-29 15:22:16.103	error	by controller[0]: syscall: 'connect',
Caught	2019-06-29 15:22:16.103	error	by controller[0]: errno: 'ECONNREFUSED',
Caught	2019-06-29 15:22:16.103	error	by controller[0]: code: 'ECONNREFUSED',
Caught	2019-06-29 15:22:16.103	error	by controller[0]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
Caught	2019-06-29 15:22:16.102	error	by controller[0]: at exports._exceptionWithHostPort (util.js:1043:20)
Caught	2019-06-29 15:22:16.101	error	by controller[0]: at Object.exports._errnoException (util.js:1020:11)
Caught	2019-06-29 15:22:16.097	error	by controller[0]: { Error: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1	2019-06-29 15:22:15.996	info	binrpc -> 192.168.27.42:8701/ init ["xmlrpc_bin://192.168.27.38:8701",""]
hm-rpc.1	2019-06-29 15:22:15.994	error	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
hm-rpc.1	2019-06-29 15:22:15.994	error	at exports._exceptionWithHostPort (util.js:1043:20)
hm-rpc.1	2019-06-29 15:22:15.994	error	at Object.exports._errnoException (util.js:1020:11)
hm-rpc.1	2019-06-29 15:22:15.994	error	Error: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1	2019-06-29 15:22:15.993	error	uncaught exception: connect ECONNREFUSED 192.168.27.42:8701
hm-rpc.1	2019-06-29 15:22:13.062	info	Disconnected
hm-rpc.1	2019-06-29 15:22:13.045	error	Ping error: Error: response timeout
hm-rega.0	2019-06-29 15:21:48.324	error	CCU 192.168.27.42 unreachable
hm-rega.0	2019-06-29 15:21:48.321	error	post request error: socket hang up
javascrip

**Comment by foxriver76** [comment]
Klar sollte er das @Apollon77 allerdings sollte er mindestens neu gestartet werden und sich wieder verbinden. Habe keine CuxD Instanz am laufen, beim XML Server ist mir der Fehler jedoch nicht bekannt. Werde es mal anschauen wenn ich wieder in de bin kommende Woche.

**Comment by foxriver76** [comment]
Probier mal bitte die GitHub Version @Matten-Matten
Solltest du Hilfe benötigen, gib einfach kurz Bescheid ;-)

**Comment by Matten-Matten** [comment]
Von GitHub geladen,
Upload durchgeführt, 
Alle rpc Instanzen neu gestartet,
CCU neu gestartet
und diesmal ist auch eine saubere Verbindung da.

**Comment by foxriver76** [comment]
Danke für das Feedback. Könntest du von der korrekten Neuverbindung auch noch bitte eben das Log hier posten?
