### ISSUE TITLE
Neue Komponente - HB-UNI-Sen-CAP-MOIST

### ISSUE THREAD

**Issue by micfire** [ioBroker/ioBroker.hm-rpc#178]
Hallo, könntet ihr bitte folgende Komponente hinzufügen?

"_id": "hm-rpc.meta.VALUES.HB-UNI-Sen-CAP-MOIST.MAINTENANCE.2"

`{"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":2,"TYPE":"BOOL","UNIT":""},"DEVICE_IN_BOOTLOADER":{"DEFAULT":false,"FLAGS":9,"ID":"DEVICE_IN_BOOTLOADER","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":6,"TYPE":"BOOL","UNIT":""},"LOWBAT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":9,"ID":"LOWBAT","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":3,"TYPE":"BOOL","UNIT":""},"RSSI_DEVICE":{"DEFAULT":0,"FLAGS":1,"ID":"RSSI_DEVICE","MAX":2147483647,"MIN":-2147483648,"OPERATIONS":5,"TAB_ORDER":4,"TYPE":"INTEGER","UNIT":""},"RSSI_PEER":{"DEFAULT":0,"FLAGS":1,"ID":"RSSI_PEER","MAX":2147483647,"MIN":-2147483648,"OPERATIONS":5,"TAB_ORDER":5,"TYPE":"INTEGER","UNIT":""},"STICKY_UNREACH":{"DEFAULT":false,"FLAGS":25,"ID":"STICKY_UNREACH","MAX":true,"MIN":false,"OPERATIONS":7,"TAB_ORDER":1,"TYPE":"BOOL","UNIT":""},"UNREACH":{"DEFAULT":false,"FLAGS":9,"ID":"UNREACH","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":0,"TYPE":"BOOL","UNIT":""},"UPDATE_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"UPDATE_PENDING","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":7,"TYPE":"BOOL","UNIT":""}}}`

"_id": "hm-rpc.meta.VALUES.HB-UNI-Sen-CAP-MOIST.WEATHER.2"

`{"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"OPERATING_VOLTAGE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"OPERATING_VOLTAGE","MAX":25.5,"MIN":0,"OPERATIONS":5,"TAB_ORDER":0,"TYPE":"FLOAT","UNIT":" V"}}}`

Besten Dank

**Comment by foxriver76** [comment]
Kannst du mir bitte noch das Bild zur Verfügung stellen, siehe hier dritte Spalte 

![](https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/blob/master/Images/ccu_geraete.png)

**Comment by micfire** [comment]
![hb-uni-sen-cap-moist-t_thumb](https://user-images.githubusercontent.com/17095893/60395932-1e957d80-9b3b-11e9-86cf-f88227e29951.png)
