### ISSUE TITLE
HM-Dis-EP-WM55: EPAPER_TONE type warning

### ISSUE THREAD

**Issue by mkutscher** [ioBroker/ioBroker.hm-rpc#179]
A warning is thrown when assigning a tone to the EPAPER_TONE datapoint:

> You are assigning a string to the state "hm-rpc.0.NEQ0111110.0.EPAPER_TONE" which expects a EPAPER_TONE. Please fix your code to use a EPAPER_TONE or change the state type to string.

I think it's related to #156 , so it would be very nice to reduce the logspam.

btw. Thank you very much for this nice adapter ;-)

**Comment by foxriver76** [comment]
Should be fixed with https://github.com/ioBroker/ioBroker.hm-rpc/commit/a5bbf609f5c06a195bd26bdec3dcf3ecd9729fc6

Please note, that the device has to be deleted manually to be newly created with the correct data type.
