### ISSUE TITLE
einzelne HMIP Datenpunkte unter rpc.1

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rpc#184]
Mir ist gerade aufgefallen das von meinen HMIP Geräten Datenpunkte unter rpc.1 und rpc.2 angelegt werden. Habe ich hier S.... gebaut oder ist das ein Bug?

![LOW_BAT1](https://user-images.githubusercontent.com/36857242/61377982-9934fb80-a8a4-11e9-913b-240e75879481.jpg)

![LOW_BAT2](https://user-images.githubusercontent.com/36857242/61378009-a7831780-a8a4-11e9-8dd7-076c73c9d922.jpg)

**Comment by foxriver76** [comment]
Fragen bitte im Forum. Rega legt datenpunkte für das jeweilige device an wie low  bat Alarm. Wird das entsprechende Gerät nicht gefunden wird es grundsätzlich in der vorhanden rpc instanz angelegt. Anscheinend hättest du mal keine ip Instanz jedoch ip Geräte, dann werden diese aktuell unter hm-rpc0 generiert. Früher wurde egal welches Gerät die alarmeldungen in der 0 er Instanz generiert. Das habe ich damals abgeändert, dass dies nur noch passiert, wenn das Gerät nirgends anders gefunden wird 

Von meinem iPhone gesendet

**Comment by foxriver76** [comment]
Screenshots erst jetzt gesehen, sieht eher nach fehlkonfiguratuon aus oder als wäre die Instanz mal für up genutzt worden.
