### ISSUE TITLE
HmIP-BRC2 no data

### ISSUE THREAD

**Issue by dupan99** [ioBroker/ioBroker.hm-rpc#185]
The HmIP-BCR2 does not seem to send data via the adapter. No update PRESS_LONG and PRESS_SHORT. In addition, no icon is displayed for the HmIP-BCR2.

**Comment by foxriver76** [comment]
Probably the state will only be updated not changed also you may need a dummy program. If the icon is missing, please provide it and I will add it.

**Comment by dupan99** [comment]
![PushButton-2ch-wm_thumb](https://user-images.githubusercontent.com/21146175/61659792-abf66880-acc8-11e9-966d-b986f8d66349.png)

With a dummy program it works.  

Thank you for the quick response.

**Comment by uwe72** [comment]
> ![PushButton-2ch-wm_thumb](https://user-images.githubusercontent.com/21146175/61659792-abf66880-acc8-11e9-966d-b986f8d66349.png)
> 
> With a dummy program it works.
> 
> Thank you for the quick response.

Can you please help me, how i create a dummy programm?

**Comment by Apollon77** [comment]
Create a program in your CCU like "if "select all relevant buttons" is updated then do ... nothing (leave emoty". store this program
