### ISSUE TITLE
ENUM Werte werden nicht aktualisiert in ioBroker nach Änderung in CCU

### ISSUE THREAD

**Issue by intruder7777** [ioBroker/ioBroker.hm-rpc#186]
Nach dem ich die ENUMS in der CCU von einem Gerät geändert habe werden sie nicht in ioBroker aktualisiert. Vorgehen in ioBroker: Objekt gelöscht, REGA und RPC neugestartet mit der RPC Einstellung einmalig syncronisieren. Es werden dierekt die alten Einstellungen angelegt.
**Versions:**
 - hm-rpc version: 1.9.16
 - hm-rega version: 2.4.2
 - JS-Controller version: 1.5.14
 - Node version: 10.16.0
 - Operating system: LINUX
 - CCU model: raspberrymatic 
 - CCU firmware: 3.47.10.20190713
![2](https://user-images.githubusercontent.com/45670139/62125325-1e6cd700-b2cd-11e9-95f8-7ed0be097682.png)
![1](https://user-images.githubusercontent.com/45670139/62125326-1e6cd700-b2cd-11e9-9311-33399ff338b1.PNG)

**Additional context**

**Comment by foxriver76** [comment]
Probably duplicate of https://github.com/ioBroker/ioBroker.hm-rega/issues/34

Also wenn ich etwas zu einem Gewerk hinzufüge und rega neustarte, dann wird unter Aufzählungen alles korrekt angezeigt, bitte unter Aufzählungen prüfen, denke wenn dann ist es die Anzeige im Admin.

**Comment by foxriver76** [comment]
Also bei mir werden dann nur die einzelnen DP's unter Objekte korrekt dem Werk zugeordnet, der Channel nicht, ist allerdings keine Aufgabe von hm-rpc. Ich kann das hier nur zum Enum hinzufügen und das tut es bei mir korrekt , prüfbar im Tab Aufzählungen.

**Comment by intruder7777** [comment]
![3](https://user-images.githubusercontent.com/45670139/62126904-0ac36f80-b2d1-11e9-8584-9c0f39f8ea12.PNG)
also nach deaktivierung rega und  rpc und löschen des gerätes blieb dies bei Aufzählung übrig. die Zahlen sind der Rest un d wenn ich dort mit der Maus raufgehe zeigt er noch die SNR. des Gerätes an

**Comment by foxriver76** [comment]
Meinst du alte Enums werden nicht entfernt in iobroker oder neue nicht hinzugefügt?

Von meinem iPhone gesendet

**Comment by intruder7777** [comment]
ich hatte vorher in der CCU jedem Channel des Gerätes den Raum Aussenbeleuchtung zugewiesen und nur  dem Channel Schaltaktor das Gewerk Licht und dem Channel Messwert das Gwerk Energiemanagment. das war auch so in ioBroker vorhanden. Jetzt habe ich in der CCU nur den Channels  Status,Schaltaktor und Messwert den Raum Aussenbeleuchtung zugewiesen. Aber in ioBroker wurden nach syncronisierung wieder die alten EInstellungen übernommen und das sollte ja nicht so sein. ich vermute es doch eher ein Problem bei REGA

**Comment by foxriver76** [comment]
Bitte das Issue bei Rega anlegen und Step by Step beschreiben wie ich es reproduzieren kann. Danke
