### ISSUE TITLE
New version 1.9.19 doesn't work

### ISSUE THREAD

**Issue by charly9898** [ioBroker/ioBroker.hm-rpc#192]
After updating the new version 1.9.19 the adater doesn't work.
After the downgrade to 1.9.17 the adater works fine.

**Versions:**
  - hm-rega version: 2.4.5
  - Operating system: 4.19.42-v7+ #1219 
 - CCU model: raspberry pi 3+

**Comment by foxriver76** [comment]
Thanks for the extensive information. Maybe you could specify what exactly isn’t working or maybe an error is thrown?

**Comment by charly9898** [comment]
Die Instanz wechselt nur auf gelb. Versucht zu connecten. Bleibt aber stehen.
Gruß 
Charly 

Am 11. August 2019 17:02:38 MESZ schrieb Max Hauser <notifications@github.com>:
>Thanks for the extensive information. Maybe you could specify what
>exactly isn’t working or maybe an error is thrown?>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/ioBroker/ioBroker.hm-rpc/issues/192#issuecomment-520235118

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by foxriver76** [comment]
Ok, da ich glaube ich was verwendet habe, was ich zuvor in dem Adapter nicht der Fall war, sagt mir meine Glaskugel, dass es ein Update für deinen js-controller gibt, dass du seit langem nicht ausgeführt hast? 

Jedoch gibt es im Admin auch einen Tab log, der uns sicherer sagen könnte, wo das Problem liegt.

beste Grüße

fox

**Comment by foxriver76** [comment]
1.9.17 vorübergehend latest.

**Comment by charly9898** [comment]
ok, das war der Fehler! 
Der js-Controller war veraltet. Leider wird der Controller nicht  zum Update angezeigt
Trotzdem Danke.

**Comment by Apollon77** [comment]
> Leider wird der Controller nicht zum Update angezeigt
js-controller 1.5.14 ist stable ... also sollte angezeigt werden

**Comment by foxriver76** [comment]
1.10.0 nun latest, selbe Funktionalität wie 1.9.19, jedoch wird ein Update mit Warnung auf einen inkompatiblen js-controller verhindert, falls dies der Fall ist.
