### ISSUE TITLE
button and button.long should have write true

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.hm-rpc#193]
The type detector https://github.com/ioBroker/ioBroker.type-detector
has problem to recognize Press_short and press_long the role is correct but the parameter write is set to false. The type detector is testing this.

**Comment by foxriver76** [comment]
Is due to bitwise operator in https://github.com/ioBroker/ioBroker.hm-rpc/blob/bff0a6b7c5845609c6a17895fe005321002ef194/hm-rpc.js#L1008

Would really like to know why it has been implemented like this :weary:

**Comment by foxriver76** [comment]
Hm okay, it seems to be the logic of the rpc api, so correct basically and only buttons which are of `                'CONTROL': 'BUTTON_NO_FUNCTION.LONG'` or SHORT have OPERATIONS 4 and will result in write: false. Do you know if the specified buttons really have no functionality? Then probably they shouldn't be of role `button`

**Comment by Apollon77** [comment]
maybe it is just the "status of the buttons" ... then it makes no sense to allow them to be set

**Comment by foxriver76** [comment]
I guess it makes no sense to allow them to be set but to show a status buttons are not suitable, because in non-expert mode the admin adapter only shows a button which looks the same no matter if the state is true or false.

So either admin should not display them as button if write is false or hm-rpc has to map the logic in another way.

**Comment by TA2k** [comment]
I have no idea how hm works.
Ok then I interpret the state wrong. 
I thought it also possible to trigger the button via iobroker. 
Here are the examples:
[buttons.zip](https://github.com/ioBroker/ioBroker.hm-rpc/files/3492314/buttons.zip)

**Comment by foxriver76** [comment]
Yeah so if it’s not prohibited to use role button with write false I would assume it is as expected.
