### ISSUE TITLE
No image for "BC-RT-TRX-CyG" found.

### ISSUE THREAD

**Issue by elmarfaber** [ioBroker/ioBroker.hm-rpc#196]
Hello,
I use the version 1.10 an get the following error in the log file:
No image for "BC-RT-TRX-CyG" found.
I use homegear last version. Some days before the adapter works fine for me

Best regards 

Elmar

**Comment by foxriver76** [comment]
It’s just a hint, no error - you have to provide the image here. You can download it on your CCU then I can add it to the adapter and it will be shown in objects tab of admin.
