### ISSUE TITLE
HM-CC-RT-DN Auto mode

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.hm-rpc#198]
**Describe the bug**
The object AUTO_MODE shows the state as false, but the HM-CC-RT-DN thermostat is in Auto mode. The mode is shown in CONTROL_MODE correctly as AUTO-MODE.

**Expected behavior**
The change of AUTO_MODE should switch between Auto Mode and Manuel Mode.

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/16007760/65822806-c3af1780-e24a-11e9-9202-6214d6ce3563.png)

**Versions:**
 - hm-rpc version: 1.9.15
 - hm-rega version: 2.4.0
 - JS-Controller version: 1.15.11
 - Node version: 10.16.0
 - Operating system: ubuntu server
 - CCU model: CCU2
 - CCU firmware: 2.47.15

**Comment by foxriver76** [comment]
"type": "state",
  "common": {
    "def": false,
    "type": "boolean",
    __"read": false,__
    "write": true,
    "role": "switch",
    "name": "HK Bad:4.AUTO_MODE",
    "smartName": false
  },

please use `.4.CONTROL_MODE` to check active mode

**Comment by Jey-Cee** [comment]
Hm i think if i set AUTO_MODE to false the Control Mode has to switch to MANU, as it does on the thermostate its self.

**Comment by foxriver76** [comment]
You have to set `X.4.MANU_MODE`, to switch back to MANU MODE. It's not that user friendly, but its the logic of the API. I'm afraid, but doing extra logic in the adapter on that variety of devices, will result in a huge overhead.

**Comment by Jey-Cee** [comment]
Ok i understand. Thank you.
