### ISSUE TITLE
Falsche Werte im Datenpunkt HMIP Fensterkontakt

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.hm-rpc#204]
Laut Hinweis im Forum liefert der Adapter falsche Werte bei def / min / max

"def", "min" und "max" haben falsche Werte (müssten Zahlen sein).

https://forum.iobroker.net/post/315383
`{
  "type": "state",
  "common": {
    "def": "CLOSED",
    "type": "number",
    "read": true,
    "write": false,
    "min": "CLOSED",
    "max": "OPEN",
    "states": {
      "0": "CLOSED",
      "1": "OPEN"
    },
    "unit": "\"\"",
    "role": "value.window",
    "name": "Wohnzimmerfenster links.STATE"
  },`

**Versions:**
 - hm-rpc version: 1.10.0
 - hm-rega version: 2.4.12
 - JS-Controller version: 2.0.35

Bitte korrigieren.
Mit freundlichen Grüßen
Heiko

**Comment by foxriver76** [comment]
Jo muss allgemein gemappt werden, da so von hm-rpc geliefert. Danke

**Comment by foxriver76** [comment]
Ist gefixt, Objekte werden allerdings nicht überschrieben, somit ist neuanlegen des Objektes Voraussetzung.

**Comment by dslraser** [comment]
Danke

**Comment by dslraser** [comment]
`{
  "type": "state",
  "common": {
    "def": "CLOSED",
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "states": {
      "0": "CLOSED",
      "1": "TILTED",
      "2": "OPEN"
    },

Das ist ein Drehriff, müsste der nicht bei min 0 und max 2 haben ?

**Comment by foxriver76** [comment]
Das eleganteste wäre, wenn MIN/MAX von Typ String und VALUE_LIST existiert in den entsprechenden Metas, schaue ob MIN und MAX in VALUE_LIST sind und falls ja nehme den Key des Eintrages. So wird dann nichts mehr manuell benötigt und das inkonsistente Verhalten zwischen IP und NON-IP metas abgefangen.
