### ISSUE TITLE
Temperatur Werte wahlweise mit Komma

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.hm-rpc#205]
Hallo,
könnte man eventuell eine Option im Adapter einbauen, das man die Temperaturwerte (oder auch andere Werte) mit Komma in den Datenpunkten angezeigt bekommt ? Also eine Option ob Punkt oder Komma gewünscht ist.
Grund:
Ich verwende den Alexa2 Adapter für individuelle Ansagen z.B. für Temperaturen, z.B. für mehrere Räume hintereinander. Im Alexa2 Adapter verwende ich ssml. 
ssml Ansagen können aber kein Punkt Ansagen bzw. kann dieser nicht dafür verwendet werden. Aktuell muß ich in jedem Script/Blockly den Temperaturwert von Punkt nach Komma umrechnen.
Gruß Heiko

**Comment by foxriver76** [comment]
Also wenn du das wirklich willst, dass number Werte mit `,` angezeigt werden, hat ioBroker in den Haupteinstellungen die Funktion dies zu ändern (s. Screenshot -> Dezimaltrennzeichen). Ansonsten kann man als Adapter wenn dann einen String Wert schreiben um das so hinzubiegen. 

![Bildschirmfoto von 2019-11-03 10-19-15](https://user-images.githubusercontent.com/25484431/68082961-6f87ec00-fe23-11e9-9460-a6f0b961e8ee.png)


Allerdings baust du ja die SSML Ausgabe sicher mit einem Skript zusammen, da könnte man das ersetzen von `.` durch `,` leicht vornehmen. Kannst dein Skript ja gerne mal posten.

**Comment by dslraser** [comment]
In den Haupteinstellungen habe ich Komma stehen, trotzdem werden die Werte mit Punkt angezeigt
<img width="747" alt="Bildschirmfoto 2019-11-03 um 10 40 51" src="https://user-images.githubusercontent.com/32881445/68083248-d5c23e00-fe26-11e9-94e2-91fa8e0ef161.png">


<img width="1397" alt="Bildschirmfoto 2019-11-03 um 10 49 08" src="https://user-images.githubusercontent.com/32881445/68083327-9c3e0280-fe27-11e9-8898-8f28363c9395.png">

Hier mal als Beispiel ein RAW von einem HMIP Temperatursensor für Aussen
`{
  "from": "system.adapter.hm-rpc.0",
  "user": "system.user.admin",
  "ts": 1572268659582,
  "common": {
    "name": "Temperatursensor aussen.ACTUAL_TEMPERATURE",
    "type": "number",
    "unit": "°C",
    "role": "value.temperature",
    "def": 0,
    "min": -3276.8,
    "max": 3276.7,
    "read": true,
    "write": false
  },
`
Ich nutze Blockly für die ssml Ansagen, den Export des Blockly stelle ich gleich mal ins Forum und teile Dir den Link mit.

**Comment by foxriver76** [comment]
@Apollon77, sollte diese Dezimaltrennzeichen-Option das mit, Anzeigen oder ist das nur für Visualisierungsadapter gedacht?

**Comment by Apollon77** [comment]
wir meines wissens nach für Visus genutzt und steht per https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#formatvalue in skripten zur verfügung

**Comment by dslraser** [comment]
@foxriver76 
ich habe das mal in der "Wunschliste Blockly-Elemente" gepostet und auch mein Blockly zum umrechnen dort eingefügt.
https://forum.iobroker.net/post/320462

**Comment by foxriver76** [comment]
Denke das wäre die bessere Wahl. Ist bisschen zu feingranular für den Adapter, da so spezifische DP's bereit zu stellen. Letztendlich bräuchtest du einfach eine Umwandlung des Number Wertes in den String und dann ersetzen von `.` mit `,`:

```javascript
const stateVal = getState('hm-rpc.1.000393C99B9EDF.1.ACTUAL_TEMPERATURE').val;

log(stateVal);
// Output: 17.4 type: number

log(stateVal.toString().replace('.', ','));
// Output: 17,4 type: string
```

Weiß leider nicht, wie die Funktionen in Blockly dafür lauten.

**Comment by Apollon77** [comment]
Naja in Zukunft geht sowas ggf sich per alias.
