### ISSUE TITLE
HM-Dis-EP-WM55: Accessing EPAPER_SIGNAL from Blockly causes a type mismatch warning

### ISSUE THREAD

**Issue by Strunzdesign** [ioBroker/ioBroker.hm-rpc#207]
Hi,

if I trigger the LED on my HM-Dis-EP-WM55 via Blockly I get a warning in my logs that a type mismatch was detected. Nevertheless, the blink sequence is accepted by the device.

Versions:
- HomeMatic RPC adaptor 1.10.3
- Script Engine 4.1.12
- ReGaHSS 2.4.12

To trigger the warning:
- Set ("steuere") DEVICE:0.EPAPER_SIGNAL with string "0xF1". The LED blinks but the following log entry appears:

```
javascript.0	2019-11-10 12:25:09.676	warn	at Timer.processTimers (timers.js:223:10)
javascript.0	2019-11-10 12:25:09.675	warn	at listOnTimeout (timers.js:263:5)
javascript.0	2019-11-10 12:25:09.675	warn	at tryOnTimeout (timers.js:300:5)
javascript.0	2019-11-10 12:25:09.675	warn	at ontimeout (timers.js:438:13)
javascript.0	2019-11-10 12:25:09.675	warn	at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1314:29)
javascript.0	2019-11-10 12:25:09.675	warn	at Object.setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1258:20)
javascript.0	2019-11-10 12:25:09.674	warn	Wrong type of hm-rpc.1.XXXXXXXXXX.0.EPAPER_SIGNAL: "string". Please fix, while deprecated and will not work in next versions.
```

Interestingly, setting the EPAPER_TONE variable using the same mechanics works without that warning message. Having a look at the definition of EPAPER_TONE shows that the element is of type "string", which works fine:

```
  "common": {
    "type": "string",
    "read": false,
    "write": true,
    "states": {
      "0xC0": "Off",
      "0xC1": "Long Long",
      "0xC2": "Long Short",
      "0xC3": "Long Short Short",
      "0xC4": "Short",
      "0xC5": "Short Short",
      "0xC6": "Long",
      "0xC7": "7",
      "0xC9": "9",
      "0xCA": "A"
    },
    "name": "WZ_Schreibtisch_EPaper:0.EPAPER_TONE"
  },
```
  
However, EPAPER_SIGNAL is not of type "string", but follows the same access semantics: you write a string to it, and the state changes:
  
```
  "common": {
    "type": "EPAPER_SIGNAL",
    "read": false,
    "write": true,
    "states": {
      "0xF0": "OFF",
      "0xF1": "Red blink",
      "0xF2": "Green blink",
      "0xF3": "Orange blink"
    },
    "name": "WZ_Schreibtisch_EPaper:0.EPAPER_SIGNAL"
  },
```
  
I have no idea which of both variants is better, but both fields should be aligned. Either use a "string" within the definition, or, use a specific type such as "EPAPER_SIGNAL". However, when accessing the elements via Blockly, only the "string"-based variant does not cause a warning message here in my setup. Is it possible to align both?

Regards,
Florian

**Comment by foxriver76** [comment]
Needs to be mapped like in https://github.com/ioBroker/ioBroker.hm-rpc/commit/a5bbf609f5c06a195bd26bdec3dcf3ecd9729fc6
