### ISSUE TITLE
Keymatic 

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rpc#210]
Bei der Keymatic (HM-Sec-Key) bewirkt das Ändern des Datenpunktes :OPEN in
False zu True
True zu False
True zu True
False zu False
das öffnen der Keymatic
siehe `https://forum.iobroker.net/topic/26517/bug-adapter-hm-rpc-keymatic-open-problem/2 `

**Comment by Apollon77** [comment]
Ja. Das ist ein Button. Button werden getriggert. Die ccu versteht hier jegliche wert Angabe als so einen trigger - nicht nur true. So funktionieren „buttons“ in der ccu allgemein.

**Comment by Knallochse** [comment]
War das nicht mal so, dass man zum öffnen 2 Datenpunkte ändern musste?

**Comment by Apollon77** [comment]
Ne. Es ist eher so: es gibt einen dp der nur den Status anzeigt „aufgeschlossen oder zugeschlossen“ und da kann man auf und zu schließen mit. 

„Open“ triggert das er ganz an den Rand fährt wo die Tür direkt auf geht.

**Comment by AingTii** [comment]
Wäre dann nicht eher ein Taster angebracht anstatt true/false auswählen zu können?
Dann kommt man zumindest nicht mehr auf die Idee zu meinen nur bei true sollte was passieren.

**Comment by Knallochse** [comment]
> Wäre dann nicht eher ein Taster angebracht anstatt true/false auswählen zu können?
> Dann kommt man zumindest nicht mehr auf die Idee zu meinen nur bei true sollte was passieren.

Das fände ich auch super. So wie es jetzt ist finde es im Bezug auf die Sicherheit bedenklich.

**Comment by foxriver76** [comment]
Hm ne weil Open trigger einfach das öffnen. Zum verschließen aufschließen gibt es einen extra state.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.hm-rpc/commit/35d202d4541abb9840eb60bf37c3fa2ff044d6c3

**Comment by Knallochse** [comment]
Hab vielen Dank.
Schon wieder 😀
