### ISSUE TITLE
Gerät in ioBroker wurde gelöscht, Obwohl Option "Gerät nicht löschen" aktiv ist

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.hm-rpc#211]
Ich hatte in CCU3 ein neues Gerät angelernt. Dieses tauchte dann auch in ioBroker auf. Danach habe ich das Gerät in CCU3 gelöscht mit Werkseinstellung.
Danach war das Gerät in ioBroker auch verschwunden, aber in den Einstellungen des Adapters hatte ich die Option "Gerät nicht löschen" aktiviert.

MfG
Thomas Hirschfeld

**Comment by foxriver76** [comment]
Wenn die CCU explizit `deleteDevices` sendet, werden die Channels trotzdem gelöscht. Die Funktion ist eigentlich dafür gedacht gewesen um zu verhindern dass HmIP Gerate bei Adapterstart jedes Mal gelöscht und angelegt werden und somit alle history und co Einstellungen verloren gehen. Da bei Hmip wohl ein Bug seitens CCU besteht und falsche Daten in `newDevices` geliefert werden.

Insofern ist es zwar as designed allerdings auch irreführend für den Nutzer. Man könnte jetzt die Doku optimieren/Namensgebung der Funktion verbessern oder die Funktion tatsächlich so anpassen, dass gar nichts gelöscht wird. Dann muss man sich bewusst sein, dass auf jeden Fall tote Devices da sein werden nach dem löschen in der CCU. Aktuell bekommt es der Adapter mit wenn er aktiv ist und ein Gerät gelöscht wird.

**Comment by Hirsch-DE** [comment]
Dann würde ich vorschlagen, die Option vielleicht umzubenennen z.B. "Gerät nicht löschen bei Neustart".
