### ISSUE TITLE
rpc adapter "common.max" falsche Werte

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.hm-rpc#212]
Hi!
Ich nutze unter anderem ein HM-OU-LED16 und mehrere HM-SEC-RHS.
Dort sind im rpc-Adapter die "common.max" neuerdings falsch und beim HM-OU-LED16 lassen sich somit mit hilfe von setState die States für die Farben nicht ändern.
So sieht der Datenpunkt derzeit aus:
`
{
"type": "state",
"common": {
"def": 0,
"type": "number",
"read": true,
"write": true,
"min": 0,
"max": -1,
"states": {
"0": "OFF",
"1": "RED",
"2": "GREEN",
"3": "ORANGE"
},
"name": "HM-OU-LED16 JEQ0087074:1.LED_STATUS"
},
"native": {
"CONTROL": "NONE",
"DEFAULT": 0,
"FLAGS": 1,
"ID": "LED_STATUS",
"MAX": 3,
"MIN": 0,
"OPERATIONS": 7,
"TAB_ORDER": 1,
"TYPE": "ENUM",
"UNIT": "",
"VALUE_LIST": [
"OFF",
"RED",
"GREEN",
"ORANGE"
]
},
"from": "system.adapter.hm-rpc.0",
"ts": 1575639340908,
"_id": "hm-rpc.0.JEQ0087074.1.LED_STATUS",
"acl": {
"object": 1636,
"state": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator"
},
"user": "system.user.admin"
}
`
 Ändere ich common.max auf (in dem Fall hier) auf 3 dann passt wieder alles.
Im log ist auch nichts auffälliges.
Genaue Fehlerbeschreibung auch im Forum.
[https://forum.iobroker.net/topic/27420/rpc-adapter-states-fehlerhaft](url)

Gruß
Johnny

**Comment by foxriver76** [comment]
Notiz: https://github.com/ioBroker/ioBroker.hm-rpc/commit/acec72c690d9265c23d1146fa203cef3bb89d797

**Comment by foxriver76** [comment]
Sehe den Fehler. Fixe es heute Abend, gerade nur mobil. Danke fürs melden.
