### ISSUE TITLE
HM-Sen-DB-PCB ordner 1 fehlt

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.hm-rpc#213]
Hallo Foxriver

herzlichen Dank für deine Arbeit für HM und io. Ich habe einen HM-Sen-DB-PCB den ich versuche im io einzubinden. Leider wird nur ein Ordner 0 angelegt mit den entsprechenden States. 

Der jedoch wichtige State ob es geklingelt hat wird im Ordner 1 nicht angezeigt. Der ganze Ordner fehlt.

Viele Grüße

**Comment by foxriver76** [comment]
Hi, 

es müsste beim erstmaligen erkennen des Geräts in ioBroker von hm-rpc geloggt werden: Send this info to developer.. 

Kannst du das bitte hier posten. Und evtl noch ein Screenshot von dem aufgeklappten Channel 0 des Geräts.

**Comment by FlexerJR** [comment]
Hier im Anhang die Bilder. Hatte die Baumstruktur einmal gelöscht und jetzt wird auch Ordner 0. nicht mehr erstellt.

<img width="1090" alt="Bildschirmfoto 2019-12-20 um 10 29 47" src="https://user-images.githubusercontent.com/40354380/71244954-eb76be80-2313-11ea-8d19-7c6a9fe53ca1.png">
<img width="1094" alt="Bildschirmfoto 2019-12-20 um 10 29 33" src="https://user-images.githubusercontent.com/40354380/71244960-f03b7280-2313-11ea-8d3d-87714f77e2be.png">

**Comment by foxriver76** [comment]
du teilst der CCU mit sie solle die Nachrichten an sich selbst senden. Denke du hast die CCU IP in die callback Adresse geschrieben. Leer lassen oder ioB IP rein schreiben.

**Comment by FlexerJR** [comment]
Ja genau das wars. Jetzt gehts es. Oh man! Danke für deinen tollen Adapter und die damit verbundene Arbeit!
