### ISSUE TITLE
Reconnect problems after network issues

### ISSUE THREAD

**Issue by twonky4** [ioBroker/ioBroker.hm-rpc#215]
**Describe the bug**
I have 2 iobroker. One master and one slave system. On the slave system I have a hm-rpc adapter installed and it's working fine. But if I reboot the master system I cannot send any commands to my CCU any more. The states are stay with ack: false. If I change the STATE directly on the CCU then the iobroker state was refreshed and have ack: false, but a change again on the iobroker state will not transmitted to the CCU. If I stop and start the adapter it start working correctly.

**To Reproduce**
1. Reboot the iobroker of 2 connected iobroker systems which is the master system. A network reconnect (for example a reboot of a router) of the slave system will also trigger the same issue.
2. Try to a changed object state of the hm-rpc which is running at the slave system after the reboot/reconnected is done.
3. The changed state will not transmitted to the CCU.

**Expected behavior**
The hm-rpc should transmit changed state values to the CCU after a reboot.

**Screenshots & Logfiles**
[iobroker.2019-12-12_master.log](https://github.com/ioBroker/ioBroker.hm-rpc/files/3957712/iobroker.2019-12-12_master.log)
[iobroker.2019-12-12_slave.log](https://github.com/ioBroker/ioBroker.hm-rpc/files/3957713/iobroker.2019-12-12_slave.log)

**Versions:**
 - hm-rpc version: 1.10.3 (slave)
 - hm-rega version: 2.4.12 (slave)
 - JS-Controller version: 2.1.1 (both)
 - Node version: 10.15.3 (slave) / 8.16.0 (master)
 - Operating system: Raspbian 9 (slave) / Debian 9.9 (master)
 - CCU model: Raspberry Pi 3 B, RPI-RF-MOD
 - CCU firmware: 3.47.22.20191130

**Additional context**
I noticed it after I refreshed the versions of the adapters, JS-Controller and CCU3. So I hope the issue is on the correct place. I don't have other adapter on the slave system to test with if it's depended on hm-rpc or JS-Controller. I test with a "Funk-Schaltaktor mit Leistungsmessung".

**Comment by twonky4** [comment]
The issue still exists in hm-rpc 1.12.1.

**Comment by foxriver76** [comment]
Hui @Apollon77 irgendeine Idee warum der Adapter der auf dem Slave läuft nach Master Neustart Probleme haben könnte? Evtl. Bekommt er die StateChange Events nicht mehr? 

@twonky4 werden die stateChanges nach dem Neustart noch geloggt auf debug, sprich `setValue ...`? 

Ich vermute ja ist ein Controller issue

**Comment by twonky4** [comment]
Nein, das alla

> 2019-12-12 16:05:45.283  - [34mdebug[39m: hm-rpc.0 (17771) xmlrpc -> setValue 1 STATE: false
> 2019-12-12 16:05:45.284  - [34mdebug[39m: hm-rpc.0 (17771) setValue ["PEQ0412824:1","STATE",false] BOOL

wird nicht mehr geloggt nach dem Neustart.

**Comment by foxriver76** [comment]
19.44 Controller Neustart und danach sehe ich kein `setValue` mehr geloggt, bin allerdings gerade nur am Smartphone...

**Comment by twonky4** [comment]
Genau das habe ich auch gesehen.

**Comment by foxriver76** [comment]
Muss Ingo was zu sagen.

**Comment by Apollon77** [comment]
Wann genau war denn der master weg?

die sets kommen im Log im Sekundentakt bis 16:05:45 ... dann stoppt es. Der Master Restart war doch erst 19:44 oder wann genau war das was wie?

Das Logging das die DB weg ist sieht man schön beim Slave 19:44:08.172 ... sowas war aber nicht früher

**Comment by twonky4** [comment]
Der master restart war um 19:44:07.987. Zwischen 16:05:45 und dem restart war natürlich noch ganz viel, aber vor'm restart ging auch noch alles. Fehler sind soweit keine im restlichen log.

**Comment by Apollon77** [comment]
Kannst Du mal das Log bitte bereitstellen von master und Slave 1 min vor und nach dem Update oder so?

**Comment by Apollon77** [comment]
Ich hatte bei mir auch einmal den Fall das die redis lib die subscriptions nicht wiederhergestellt hat ... aber konnte es danach nie wieder nachvollziehen :-( und auch der COde in der Lib sieht vollkommen ok aus

**Comment by twonky4** [comment]
Update? Du meinst restart?

**Comment by Apollon77** [comment]
ja restart :-)

**Comment by twonky4** [comment]
[iobroker.2019-12-12-master.log](https://github.com/ioBroker/ioBroker.hm-rpc/files/3958050/iobroker.2019-12-12-master.log)
[iobroker.2019-12-12-slave.log](https://github.com/ioBroker/ioBroker.hm-rpc/files/3958051/iobroker.2019-12-12-slave.log)

Hier sind 2 frische log-Dateien.

Der restart war um 2019-12-12 23:11:22

**Comment by Apollon77** [comment]
Da sehe ich aber keine SET STATE?!

Also an sich ist dso alles korrekt. es kommt das connection refused als die DB we war und er versucht hat neu zu verbinden. Das versucht er alle 5s (23:11:22/27 ... und 32 wars wieder da). An sich sollte zu dem Zeitpunkt beim Reconnect auch automatisch alle subscribes die es vorher gab wieder hergestellt werden.

Wie oben geschrieben hatte ich auch schonmal den Fall das es nicht tat, konnte es aber danach nicht mehr nachvollziehen ...
Meine Idee für die 2.2 (wo ich eh gerade was am umbauen bin daran) ist einfach alle subscribes noch bei bei uns zu merken und nach reconnect selbst alle nochmal zu senden ... (obwohl es eigentlich unnötig sein sollte)

**Comment by twonky4** [comment]
Ich habe nun gerade gesehen welche Ausmaße das Problem eigentlich hat. Ich dachte das tritt nur auf, wenn ich den master neu starte. Aber das tritt auch auf, wenn mein Internet Provider die tägliche Zwangstrennung durchführt 😭 (da übers Internet verbunden)

**Comment by foxriver76** [comment]
Sprich Master und Slave sind über Internet verbunden?

**Comment by twonky4** [comment]
Genug, hat mit js-controller 1.5 auch noch super funktioniert.

**Comment by Apollon77** [comment]
Hast du logs? Wie gesagt ich baue gerade in der 2.2.0 ein das wir  uns alle subscribes merken und erneuern nachweinen
Reconnect. 

Um das Problem in der ioredis lib zu finden müsste Mannes nachvollziehen können und dort logging einbauen ... der Code an sich sieht korrekt aus. 

Denke ich habe nach dem Wochenende eine 2.2.0 auf GitHub die du testen könntest ob es mit der besser tut (müsste am Ende auch nur auf dem Slave laufen)

**Comment by twonky4** [comment]
Ja, liegt definitiv nicht am hm-rpc Adapter. Das Problem ist Adapter übergreifen.

**Comment by Apollon77** [comment]
Ich hab den Umbau fertig und ist gerade in Review. Dann sollten wir einen Controller 2.2.x auf GitHub haben der das Thema hoffentlich löst. 

Wir merken und jetzt alle subscribes und spielen sie selbst nach einem reconnect nochmal nach und verlassen uns nicht auf die redis lib. 

Wäre super wenn du dann testen könntest weil ich kann das Problem auf meinen dev Systemen nicht nachstellen - und in live hatte ich es nur auf einem meiner 2 slaves und nur bei Objekten :-(

**Comment by foxriver76** [comment]
Fixed? Bzw kann hier zugemacht werden?

**Comment by Apollon77** [comment]
@twonky4 if you like the js-Controller 2.2.x Beta GitHub test started. So please check if this solved the issue.

**Comment by twonky4** [comment]
Problem solved with js-controller versin 2.2.4
