### ISSUE TITLE
Bei HM-IP Geräten werden keine Einstellungsmöglichkeiten in den Objekten (mehr) angezeigt

### ISSUE THREAD

**Issue by Thomasjbj** [ioBroker/ioBroker.hm-rpc#216]
Hallo, erstmal vielen Dank für den Adapter, macht richtig Spaß mit dem zu arbeiten.

**Describe the bug**
Bisher war es so, dass man in den Objekten die HMIP Geräte steuern konnte, nach dem aktuellen Update (schätze ich) ist dies nicht mehr möglich, und wenn ich mich richtig erinnere, wurden außer dem "Ordner" 0 weitere angezeigt, in dem Screenshot sind es nur leere ?Datenpukte? Weiß leider nicht wie ich das genauer beschreiben soll. 
![Screenshot-24](https://user-images.githubusercontent.com/51618990/70854106-7e000380-1eb7-11ea-8f9e-b98197368366.png)
Bei der Schaltsteckdose, die im Screenshot zu sehen ist, war in der Vergangenheit mindest die Möglichkeit, sie ein- oder auszuschalten gegeben.

Bei dem Temperaturfühler fehlt wohl mindestens die Angabe von der aktuellen Temperatur und Luftfeuchtigkeit:
![Screenshot-25](https://user-images.githubusercontent.com/51618990/70854150-0383b380-1eb8-11ea-8c70-feed7fd1a0f2.png)
Als ich diesen heute eingebunden habe, bin ich auf das Problem gestoßen.

Bei den nomalen HM Geräten wird alles wie gewohnt in den Objekten, inklusive Steuerungsmöglichkeit angezeigt.

Ich hoffe ich konnte es halbwegs verständlich darstellen.

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - hm-rpc version: 1.12.1
 - hm-rega version: 2.5.1
 - JS-Controller version: 2.1.1
 - Node version: 10.17.0
 - Operating system: raspbian
 - CCU model: Raspberrymatic auf Tinkerboard S
 - CCU firmware: 3.47.22.20191130

**Comment by foxriver76** [comment]
Gibt es hierzu ein Forum Thread? Ich vermute in erster Linie, dass es ein Konfigurationsproblem ist.

Hast du IP Geräte die korrekt mit dem Adapter funktionieren? Was heißt seit Update geht es nicht, geht es denn mit einer alten Version des Adapters oder ist ein Raspberrymatic Update gemeint?

**Comment by Apollon77** [comment]
Mal Objekte neu geladen?

**Comment by Thomasjbj** [comment]
Ich habe, zur späteren Frage, alle Objekte neu geladen, Adapter mehrmals neu gestartet, Geräte gelöscht und neu hinzugefügt, leider ohne Ergebnis.

Bezüglich des Updates... leider habe ich in den letzten zwei Wochen alles aktualisiert: raspberrymatic, rega und rpc-Adapter. Da ich leider bisher noch nichts produktives mit HMIP-Geräten habe, kann ich leider nicht sagen, nach welchem Update der Fehler aufgetaucht ist. Nur dass es vor drei Wochen noch funktioniert hat.
Daher kann ich es im Nachhinein keinem der in Frage direkt zuordnen, erste Vermutung war der rpc-Adapter.

Nein, leider funktioniert im Moment keins meiner drei Geräte richtig im iobroker korrekt.
Ich versuche mal, ob ich alles nacheinander mal downgraden kann, um es einzugrenzen.

**Comment by foxriver76** [comment]
Wirft die HMIP Instanz denn Fehler im Log?

Du hast also 2 RPC Instanzen RPC und wine HMIP? Sind beide korrekt im hm-Rega Adapter hinterlegt?

**Comment by foxriver76** [comment]
Bzw kann es sein dass die Datenpunkte in der rfd Instanz sind?

**Comment by Thomasjbj** [comment]
Nein, es tauchen keine Fehler im Log auf. Ich habe insgesamt drei Instanzen, genau, einmal normal HM, dann CuxD und einmal HMIP. und alle sind richtig im REGA-Adapter zugeordnet.
Die Datenpunkt tauchen auch leider nirgends anders auf.

Aber, ich habe gerade ein bisschen mit Proxmox gespielt und schnell mal eine VM für eine blanke ioBroker-Installation erstellt, und genauso konfiguriert, wie ich sie auf dem Produktivsystem habe, und dort wird alles korrekt und änderbar dargestellt, wie ich es bisher kannte. (auch wenn dort noch einige Datenpunkte (hier die 2 und 3) ggf. noch nicht korrekt dargestellt sind.
![Screenshot-26](https://user-images.githubusercontent.com/51618990/70863633-60c84500-1f4a-11ea-9bc5-059f91425b33.png)


Testweise hatte ich auch sowohl die Adapter als auch die Raspberrymatic-Firmware einmal auf den vorherigen Stand gebracht, aber auch da hat es nicht funktioniert gehabt. Da ich sowieso vm Pi auf eine VM umsteigen will, mach ich dabei alles neu, dann sollte das Problem zumindest bei mir nicht mehr vorliegen.

**Comment by foxriver76** [comment]
Ja irgendwas passt in der HMIP RPC Instanz dann nicht, da alle States die da sind von rega angelegt wurden und nix von Rpc. Wenn das Issue jetzt noch wichtig ist Bitte Debug Log von Adapterstart der IP Instanz.

**Comment by Thomasjbj** [comment]
Okay, hier das Debug-Log vom Start der entsprechenden Instanz:

`
hm-rpc.2 | 2019-12-15 18:24:37.498 | debug | (15528) PING ok
-- | -- | -- | --
hm-rpc.2 | 2019-12-15 18:24:37.455 | debug | (15528) Send PING...
hm-rpc.2 | 2019-12-15 18:24:37.452 | debug | (15528) [KEEPALIVE] Check if connection is alive
hm-rpc.2 | 2019-12-15 18:23:09.294 | debug | (15528) system.adapter.admin.0: logging true
hm-rpc.2 | 2019-12-15 18:23:07.450 | debug | (15528) start ping interval
hm-rpc.2 | 2019-12-15 18:23:07.449 | debug | (15528) clear connecting interval
hm-rpc.2 | 2019-12-15 18:23:07.447 | info | (15528) Connected
hm-rpc.2 | 2019-12-15 18:23:07.241 | debug | (15528) xmlrpc -> 10.0.0.21:42010/ init ["https://10.0.0.25:12010","hm-rpc.2"]
hm-rpc.2 | 2019-12-15 18:22:37.238 | debug | (15528) start connecting interval
hm-rpc.2 | 2019-12-15 18:22:37.236 | debug | (15528) Connect...
hm-rpc.2 | 2019-12-15 18:22:37.233 | info | (15528) xmlrpc client is trying to connect to 10.0.0.21:42010/ with ["https://10.0.0.25:12010","hm-rpc.2"]
hm-rpc.2 | 2019-12-15 18:22:37.232 | info | (15528) xmlrpc server is trying to listen on 0.0.0.0:12010
hm-rpc.2 | 2019-12-15 18:22:35.613 | info | (15528) [META] Meta data updated
hm-rpc.2 | 2019-12-15 18:22:35.424 | info | (15528) starting. Version 1.12.1 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v10.17.0
hm-rpc.2 | 2019-12-15 18:22:34.975 | debug | (15528) States connected to redis: 10.0.0.25:9000
hm-rpc.2 | 2019-12-15 18:22:34.895 | debug | (15528) statesDB connected
hm-rpc.2 | 2019-12-15 18:22:34.893 | debug | (15528) States create PubSub Client
hm-rpc.2 | 2019-12-15 18:22:34.870 | debug | (15528) Objects connected to redis: 10.0.0.25:9001
hm-rpc.2 | 2019-12-15 18:22:34.865 | debug | (15528) Redis States: Use Redis connection: 10.0.0.25:9000
hm-rpc.2 | 2019-12-15 18:22:34.860 | debug | (15528) objectDB connected
hm-rpc.2 | 2019-12-15 18:22:34.837 | debug | (15528) Objects client initialize lua scripts
hm-rpc.2 | 2019-12-15 18:22:34.835 | debug | (15528) Objects create PubSub Client
hm-rpc.2 | 2019-12-15 18:22:34.827 | debug | (15528) Objects client ready ... initialize now
hm-rpc.2 | 2019-12-15 18:22:34.748 | debug | (15528) Redis Objects: Use Redis connection: 10.0.0.25:9001
`

**Comment by foxriver76** [comment]
Du hörst ja auf alle Interfaces. Was steht in der Callback Adresse, bzw. Screenshots der Konfiguration von hm-rpc.2 von allen Seotwn wäre hilfreich

**Comment by Thomasjbj** [comment]
Ja... da war der Fehler. Ich habe auch in den letzten Wochen einen Multihost beim ioBroker eingerichtet, da war noch die falsche Callback Adresse drinne. Jedenfalls habe ich das nun angepasst (sowie die IPC, auf der er hört) und es hat nach dem Adapterneustart alles geholt was gefehlt hatte. Danke für die Hilfe und es freut mich, dass die Adapter, wenn man von der Person vor dem Monitor absieht, einwandfrei funktionieren :-)

**Comment by foxriver76** [comment]
Top.
