### ISSUE TITLE
hm-rpc connection via HTTPS doesn't work

### ISSUE THREAD

**Issue by WolfspiritM** [ioBroker/ioBroker.hm-rpc#218]
**Describe the bug**
I tried to make my homegear setup more secure by enabling auth with https. When enabling https however the daemonURL is generated with a "https://" protocol while the rpcServer is not creating a secureServer but a regular http server. That way the connection back from for example homegear won't work as homegear will try to connect to https://callbackAddress:port via https and not http://callbackAddress:port via http.

As there is no way to define a certificate at all right now I've changed daemonUrl to be
```js
daemonURL = "http://" + callbackAddress + ':' + port;
```
instead. After that change a successful connection via https with auth (at least to homegear, not back from homegear) can be established.

I think for now this should be changed to always use http and in the future use a seperate toggle to enable https for the callbacks aswell.

**To Reproduce**
Enable https, connect with homegear, no connection can be established

**Expected behavior**
Connection can be established without issues

**Versions:**
 - hm-rpc version: 1.11.0
 - hm-rega version: <rega-version>
 - JS-Controller version: 2.0.43
 - Node version: v10.16.0
 - Operating system: linux
 - CCU model: homegear
 - CCU firmware: latest

**Comment by foxriver76** [comment]
Verstehe ich nicht ganz, du möchtest https nutzen, Homegear stellt allerdings keinen SSL geschützten Server zur Verfügung? Mehr oder minder kannst du dann auch direkt http nutzen oder was erhoffst du dir davon?

**Comment by WolfspiritM** [comment]
Homegear selbst stellt einen HTTPS server zu Verfügung und auch die Verbindung dorthin klappt ohne Probleme. Der Adapter unterstützt für Callbacks aber kein https sondern erstellt einen normalen HTTP RPC server, teilt aber homegear über init mit, dass er über HTTPS erreichbar ist:
https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/hm-rpc.js#L787-L792

Das heißt HTTPS funktioniert bis homegear (was erstmal das wichtigste ist da dort auch Username und Passwort übertragen werden) es kommen aber keine events mehr zurück.

Besser wäre hier das daemonProto für den callback fest auf http zu setzen und ggf. in Zukunft die möglichkeit zu bieten auch den Callback über HTTPS laufen zu lassen (rpc.createSecureServer)

**Comment by foxriver76** [comment]
Ah. Der erste Post las sich so als wäre der RPC-Server auf Homegear gemeint.

Würde eher direkt anstreben, die komplette Verbindung zu verschlüsseln.

**Comment by WolfspiritM** [comment]
Wichtig ist eigentlich hauptsächlich die Verbindung zu homegear (bzw. dem jeweiligen endpunkt) da hierbei username und passwort als basic mit übertragen wird (vorallem da https im Adapter pflicht für basic ist was ja durchaus sinn macht). Der Rückweg kann theoretisch verschlüsselt werden, ist aber in meinen Augen nicht ganz so wichtig und benötigt extra Konfiguration. Das komplette Verschlüsseln wäre ein enhancement, aber da https grundsätzlich nicht funktioniert würde ich mich freuen wenn bis dahin "http://" hardcoded als protokoll für die callbackadresse übergeben werden würde da das definitiv ein bug ist 🤔 

Ich denke auch es wäre sinnvoll Hin- und Rückweg getrennt konfigurierbar zu machen und damit auch zwei "https" checkboxen zu haben sowohl für den client als auch den server.

**Comment by foxriver76** [comment]
Ich habe gerade keine Zeit intensiv reinzuschauen, allerdings zwei Sachen:

1. Kann ich gerade nicht erkennen warum es in deinem Setup (Homegear ist wohl eher eine Seltenheit - kenne es auch nicht) Probleme bereitet, mit Original CCU u. Raspmatic nicht.
2. Ich denke, es ist keine große Sache SSL in beide Richtungen zu nutzen, zumal dein Vorschlag noch mehr Konfigurationsmöglichkeiten ergibt, die dem Laien nur Fragezeichen ins Gesicht zaubern. Werde es mir jedoch zeitnah anschauen und evtl. auf deinen Lösungungsvorschlag zurück kommen.

**Comment by WolfspiritM** [comment]
> Kann ich gerade nicht erkennen warum es in deinem Setup (Homegear ist wohl eher eine Seltenheit - kenne es auch nicht) Probleme bereitet, mit Original CCU u. Raspmatic nicht.
Ich glaube eher, dass die Seltenheit hier SSL ist und einfach niemand diesen Adapter per https angebunden hat. Ich kann mir nämlich nicht vorstellen wie diese falsche Implementation überhaupt mit anderen funktionieren kann, außer wenn sie sehr fehlertolerant sind und http anstelle von https probieren.

> Ich denke, es ist keine große Sache SSL in beide Richtungen zu nutzen, zumal dein Vorschlag noch mehr Konfigurationsmöglichkeiten ergibt, die dem Laien nur Fragezeichen ins Gesicht zaubern.
SSL in beide Richtungen ist grundsätzlich erhöhter Konfigurationsaufwand da Zertifikate auf beiden seiten eingerichtet werden müssen. Da ist sicher ein extra "use SSL" haken neben der auswahl für Zertifikat, Username und Passwort kein Problem.

Ich hab das Gefühl ich hab das Problem noch nicht richtig beschrieben. Im Prinzip ist es auch egal ob Homegear oder CCU. Daher hier nochmal der Versuch:  
iobroker öffnet einen HTTP Server für XML-RPC und generiert anhand der "Adapter Callback Address" und dem Port die URL unter der dieser Server erreichbar ist. Diese URL wird dann an die init methode der CCU, Homegear, etc. gesendet. Das klappt auch ohne Probleme so lange der haken bei https nicht gesetzt ist. Sobald dieser Haken aber aktiviert ist nutzt er nicht nur für den hinweg SSL (was richtig ist) sondern auch für diese Callback Addresse als protokol "https" obwohl der adapter überhaupt kein ssl spricht so das Homegear/CCU/etc. garkeine andere möglichkeit haben als den HTTP XML-RPC Server über https://callbackAdresse:port anzufragen was natürlich nicht funktioniert.

Ich hoffe das ist verständlicher :-)

**Comment by foxriver76** [comment]
> Ich glaube eher, dass die Seltenheit hier SSL ist und einfach niemand diesen Adapter per https angebunden hat. Ich kann mir nämlich nicht vorstellen wie diese falsche Implementation überhaupt mit anderen funktionieren kann, außer wenn sie sehr fehlertolerant sind und http anstelle von https probieren.

Ne, wir reden nicht aneinander vorbei. Würde ich gerne glauben, allerdings habe ich selbst ihn über https angebunden, ebenfalls weiß ich dies von diveresen anderen Nutzern. Was auch gerade mein Hauptpunkt ist, der micht etwas skeptisch macht. Alternativ hätte ich noch vermutet, dass es nur im Zusammenspiel mit einer CB-Adresse eine Rolle spielt, tut es jedoch auch nicht, da sonst die Adapteradresse als CB-Adresse mit Protokoll eingesetzt wird: https://github.com/ioBroker/ioBroker.hm-rpc/blob/50e2d02642f95478a27e4688276aab0b19dbea9b/hm-rpc.js#L785 ff.

Wie gesagt, ich schaue es mir zeitnah genauer an. ;-)

**Comment by foxriver76** [comment]
Laut CCU Log sendet die CCU tatsächlich unabhängig von unserem angegebenen Protokoll an `http://`, entsprechend wird es wohl auch erst einmal nicht möglich sein den Rückweg zu verschlüsseln, da mir aktuell nicht klar ist, wie ich gegenteiliges erzwingen kann.
