### ISSUE TITLE
Fehlende Datenpunkte bei HM-LC-Sw4-DR-2

### ISSUE THREAD

**Issue by OlaninS** [ioBroker/ioBroker.hm-rpc#219]
Für den **HM-LC-Sw4-DR-2** fehlen die Datenpunkte. Es gibt nur die vier Kanäle und darunter den Punkt 0 als State. Über diesen lässt sich der Schalter aber nicht schalten. 

Habe zwei **HM-LC-Sw4-DR** im Einsatz, welche die Datenpunkte:
   - INHIBIT
   - INSTALL_TEST
   - ON_TIME
   - STATE
   - WORKING
 
besitzen.

**Comment by foxriver76** [comment]
Bitte mehr Informationen oder noch besser das Problem erst im Forum ansprechen, da hier meist nur durch mich betreut wird, im Forum finden sich mehr kompetente User ;-) 

Werden andere Geräte der Instanz korrekt angelegt, ist die Instanz verbunden, Screenshots der Config.

**Comment by OlaninS** [comment]
So sieht es bei einem HM-LC-Sw4-DR bei mir aus. Davon habe ich zwei im Einsatz. Diese arbeiten super

 



 

Der Nachfolger HM-LC-Sw4-DR-2 zeigt nur diese Datenpunkte

 



 

Ich habe das Gerät auch schon gelöscht und neu einlesen lassen. Auch aus der CCU gelöscht und neu angelernt. Alles ohne Erfolg.

 

Adapter mäßig bin ich komplett auf dem neuesten Stand.

 

Werde es zusätzlich auch in das Forum stellen.

 

 

Von: Max Hauser <notifications@github.com> 
Gesendet: Sonntag, 5. Januar 2020 01:04
An: ioBroker/ioBroker.hm-rpc <ioBroker.hm-rpc@noreply.github.com>
Cc: OlaninS <sascha@olanin.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Fehlende Datenpunkte bei HM-LC-Sw4-DR-2 (#219)

 

Bitte mehr Informationen oder noch besser das Problem erst im Forum ansprechen, da hier meist nur durch mich betreut wird, im Forum finden sich mehr kompetente User ;-)

Werden andere Geräte der Instanz korrekt angelegt, ist die Instanz verbunden, Screenshots der Config.

**Comment by foxriver76** [comment]
Solved via forum.

**Comment by justbql** [comment]
Hallo,
kannst du mir den Link zum Beitrag im Forum schicken?
Danke, Volker
