### ISSUE TITLE
Issue hm-rega Restart automatically after sync objects"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.hm-rpc#22]
`Hey,

Nach einem resync der Objekte haben die alle ihre Seriennummern als Name. r wenn man dann hm-rega einmalig neu startet bekommen SIe die "leserlichen" Namen. Wäre es da nicht sinnvoll nach einem neustart eines hm-rpc auch den hm-rega neu zu starten?
Man sollte zusätzlich schauen falls es mehrere hm-rpc gibt das die alle laufen ...

**Comment by GermanBluefox** [comment]
Ist schon längst gemacht. Noch aktuell?

**Comment by Apollon77** [comment]
Hm ... passiert bei mir aber nicht ... rega 1.2.1/rpc 1.3.1
Hab erst die letzten Tage mehrfach gemacht. Wenn es automatisch gestartet wurde dann ohne das es im Log ersichtlich gewesen wäre (und normalerweise stehen alle Ersetzungen drin)

**Comment by jens-maus** [comment]
Hier konnte ich das Problem bzw. die Limitation auch nachvollziehen. Hier führt der Neustart oder die Wiederverbindung einer hm-rpc Instanz NICHT dazu das hm-rega neu initialisiert wird damit eine Namensgebung nach auffinden neuer devices erfolgt. IMHO sollte nach einem "newDevice" RPC call in hm-rpc dann dazu führen das die hm-rega instanz sich neu initialisiert.

**Comment by Apollon77** [comment]
... und da fielen Sie Ihm wie Schuppen von den Augen ...Ich fürchte ich hab ne Idee (nachdem ich auch schon x mal geschaut hatte).

hm-rpc schickt ne Message an hm-rega ... ich hab gerade gesehn das hm-rega in der io.package gar keine Messagebox aktiviert hat ... also kann Sie gar keine Messages empfangen ... sollte es soooooo einfach sein ?!

Ich baue die Messagebox gleich mal ein ... Das wäre dann ein "typischer Anfängerfehler" ;-)

**Comment by jens-maus** [comment]
Na wenn es so einfach ist dann würde ich sagen man müsste da mal was einbauen das beim abschicken ner message überprüft wird ob die auch ankommt und dann ggf. ne Fehlermeldung kommt mit der Nachricht das da was nicht stimmt bzgl. messagebox fehlt.

**Comment by Apollon77** [comment]
Ne ... meine Aussage  stimmt nicht. der Notify passiert über nen Datenpunkt :-( prüfe jetzt trotzdem nochmal tiefer nach

**Comment by Apollon77** [comment]
Also es sollte so funktionieren: jeder hm-rpc-Adapter hat ein "updated"-State der wird nach einem "ForceInit"-Lauf auf "true" gesetzt.
Der hm-rega hat die alle Subscribed und reagiert darauf indem er das macht und die dann auf false setzt. Letzteres findet aber nie statt :-( Das sind die Fakten

**Comment by jens-maus** [comment]
Ich schau es mir gerade an und hoffe ich finde es gleich :)

**Comment by Apollon77** [comment]
ich hab gerade mal debug logging für state changes in hm-rega commited (brache das als info weil redis unter debug alles zumüllt). Hilf Dir vllt auch .. einfach updaten von Github

**Comment by jens-maus** [comment]
Da hab ich gerade selbst schon debug info drin :) danke trotzdem...

Ich denke ich hab zumindest den Grund wieso er nicht bis zur `.updated` Abfrage kommt. Problem ist die zeile nach deiner Debug-Info. Dort wird `if(!state || state.ack)` geprüft und das problem ist das `state.ack` immer true ist (zumindest für die tests die ich hier gemacht habe). D.h. er wird da nie in den else Zweig rennen und folglich auch nie den .updated Zweig erreichen. Die frage ist nur (und da fehlt mir die Erfahrung) was der `state.ack` test erreichen soll und ob das falsch ist oder das else am Schluss nicht sein soll?!!?

**Comment by Apollon77** [comment]
Dann ist der Fehler doch im hm-rpc!! Der setzt den Datenpunkt mit ack=true was er aber nicht darf!
Der check ist korrekt. Alles was "ack=true" ist sind infos oder bestätigungen, aber keine "kommandos".

Ich würde an der Stelle bei hm-rpc das "updated" mit ack=false setzen, dann ist das das "kommando" für rega. Rega sollte dann das "false" setzen wenn es erledigt ist mit ack=true, weil es die bestätigunung ist

baust Du es ein?

**Comment by jens-maus** [comment]
jo. ich teste es gerade.

**Comment by Apollon77** [comment]
was doch ein true anstelle false für Hirnknoten auslösen kann ... habe bestimmt schon 3 mal den Code geprüft und es nie gesehn :-(

**Comment by Apollon77** [comment]
und 1.3.5 fertig :-) Ich gebe Bluefox bescheid das er zu npm pusht.

Super Arbeit! Danke!
