### ISSUE TITLE
HmIP-BDT: 3.LEVEL differs from 4.LEVEL in regards to percentage

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.hm-rpc#220]
`hm-rpc.0.XXX.3.LEVEL` states the value between 0 and 1, whilst `hm-rpc.0.XXX.4.LEVEL` states the value in percentage between 0% and 100%.

For consistency reasons I would suggest and appreciate to standardise the datapoints.
On `HmIP-BBL` it is already standardise and all datapoints show percentage values.

**3.LEVEL**
```
  "common": {
    ...
    "min": 0,
    "max": 1
  },
```

**4.LEVEL**
```
  "common": {
    ...
    "min": 0,
    "max": 100,
    "unit": "%",
  },
```

**Comment by foxriver76** [comment]
Can you please post the whole `common` and `native` part of the `3.LEVEL` object.

**Comment by Zefau** [comment]
Indeed, there is none:
```
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "role": "level",
    "name": "HmIP-BDT 0008D709ABFC0C:3.LEVEL"
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 5,
    "MAX": 1,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "DIMMER_REAL.LEVEL"
  },
```

**Comment by foxriver76** [comment]
Reported the inconsistency to eq-3 in https://github.com/eq-3/occu/issues/105. However, I will have a look if a workaround can be implemented without negative side effects.

**Comment by Zefau** [comment]
Much appreciated, thank you!

**Comment by foxriver76** [comment]
You are very welcome.
