### ISSUE TITLE
LEVEL issue on device "HmIP-eTRV-2" since Firmware 2.2.8

### ISSUE THREAD

**Issue by erlanger24** [ioBroker/ioBroker.hm-rpc#221]
It seems that from Firmware 2.2.8 on the value for LEVEL (how much open the valve is) is not shown propper any more for device like "HmIP-eTRV-2"(Homematic IP Radiator Thermostat).  
Value in ioBroker gets shown without the "%" and values seem to be wrong (just some small 0.xx values)

Same device with old firmware 2.0.2 worked fine.

**Comment by erlanger24** [comment]
Firmware 2.2.8:

{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1.01,
    "role": "level",
    "name": "#HeizRegler_Badezimmer.LEVEL",
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "10000",
        "maxLength": "960",
        "retention": "31536000",
        "changesRelogInterval": "30",
        "changesMinDelta": 0,
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1578421422896,
  "_id": "hm-rpc.2.000A1A49A0E230.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by erlanger24** [comment]
Firmware 2.0.2:

{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100,
    "unit": "%",
    "role": "level",
    "name": "#HeizRegler_Schlafzimmer.LEVEL",
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "10000",
        "maxLength": "960",
        "retention": "31536000",
        "changesRelogInterval": "30",
        "changesMinDelta": 0,
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "UNIT": "100%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1578421420581,
  "_id": "hm-rpc.2.000A18A9AA285B.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
Normally the adapter should use the existent meta data of hm-rpc.meta. 

Please show output of
```javascript
sendTo('hm-rpc.2', 'getParamsetDescription', {ID: '000A1A49A0E230:1', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});
```

**Comment by erlanger24** [comment]
Sorry wegen der doofen Frage.. aber wo mache ich das ?

**Comment by foxriver76** [comment]
Sorry, unter Skripte, neues JavaScript erstellen und mit dem Play Button starten. Dann sollte das Paramset welches die CCU liefert ausgegeben werden.

**Comment by erlanger24** [comment]
2020-01-07 22:27:50.265 - info: javascript.0 (1341) script.js.testLEVEL: {"result":{"VALVE_ADAPTION":{"MIN":false,"OPERATIONS":7,"MAX":true,"FLAGS":1,"ID":"VALVE_ADAPTION","TYPE":"BOOL","DEFAULT":false},"BOOST_TIME":{"MIN":0,"OPERATIONS":5,"MAX":2048,"FLAGS":1,"ID":"BOOST_TIME","TYPE":"INTEGER","DEFAULT":0},"PARTY_MODE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"PARTY_MODE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.PARTY_MODE"},"SET_POINT_TEMPERATURE":{"MIN":4.5,"UNIT":"�C","OPERATIONS":7,"MAX":30.5,"FLAGS":1,"ID":"SET_POINT_TEMPERATURE","TYPE":"FLOAT","DEFAULT":4.5,"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT"},"LEVEL_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"ERROR","FLAGS":1,"ID":"LEVEL_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW","UNDERFLOW","ERROR"]},"PARTY_TIME_START":{"MIN":"2000_01_01 00:00","OPERATIONS":7,"MAX":"2255_12_31 23:55","FLAGS":1,"ID":"PARTY_TIME_START","TYPE":"STRING","DEFAULT":"2000_01_01 00:00","CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_START"},"CONTROL_MODE":{"MIN":0,"OPERATIONS":2,"MAX":3,"FLAGS":1,"ID":"CONTROL_MODE","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.CONTROL_MODE"},"QUICK_VETO_TIME":{"MIN":0,"OPERATIONS":5,"MAX":2048,"FLAGS":1,"ID":"QUICK_VETO_TIME","TYPE":"INTEGER","DEFAULT":0},"FROST_PROTECTION":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"FROST_PROTECTION","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.FROST_PROTECTION"},"PARTY_SET_POINT_TEMPERATURE":{"MIN":4.5,"OPERATIONS":5,"MAX":30.5,"FLAGS":1,"ID":"PARTY_SET_POINT_TEMPERATURE","TYPE":"FLOAT","DEFAULT":4.5,"CONTROL":"HEATING_CONTROL_HMIP.PARTY_SETPOINT_TEMP"},"SET_POINT_MODE":{"MIN":0,"OPERATIONS":7,"MAX":3,"FLAGS":1,"ID":"SET_POINT_MODE","TYPE":"INTEGER","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT_MODE"},"LEVEL":{"MIN":0,"OPERATIONS":7,"MAX":1.01,"FLAGS":1,"ID":"LEVEL","TYPE":"FLOAT","DEFAULT":0},"ACTUAL_TEMPERATURE_STATUS":{"MIN":"NORMAL","OPERATIONS":5,"MAX":"UNDERFLOW","FLAGS":1,"ID":"ACTUAL_TEMPERATURE_STATUS","TYPE":"ENUM","DEFAULT":"NORMAL","VALUE_LIST":["NORMAL","UNKNOWN","OVERFLOW","UNDERFLOW"]},"DURATION_UNIT":{"MIN":"S","OPERATIONS":2,"MAX":"H","FLAGS":1,"ID":"DURATION_UNIT","TYPE":"ENUM","DEFAULT":"S","VALUE_LIST":["S","M","H"]},"SWITCH_POINT_OCCURED":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"SWITCH_POINT_OCCURED","TYPE":"BOOL","DEFAULT":false},"CONTROL_DIFFERENTIAL_TEMPERATURE":{"MIN":-10,"OPERATIONS":2,"MAX":10,"FLAGS":1,"ID":"CONTROL_DIFFERENTIAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0},"VALVE_STATE":{"MIN":"STATE_NOT_AVAILABLE","OPERATIONS":5,"MAX":"ERROR_POSITION","FLAGS":9,"ID":"VALVE_STATE","TYPE":"ENUM","DEFAULT":"STATE_NOT_AVAILABLE","VALUE_LIST":["STATE_NOT_AVAILABLE","RUN_TO_START","WAIT_FOR_ADAPTION","ADAPTION_IN_PROGRESS","ADAPTION_DONE","TOO_TIGHT","ADJUSTMENT_TOO_BIG","ADJUSTMENT_TOO_SMALL","ERROR_POSITION"]},"ACTIVE_PROFILE":{"MIN":1,"OPERATIONS":7,"MAX":3,"FLAGS":1,"ID":"ACTIVE_PROFILE","TYPE":"INTEGER","DEFAULT":1,"CONTROL":"HEATING_CONTROL_HMIP.ACTIVE_PROFILE"},"WINDOW_STATE":{"MIN":"CLOSED","OPERATIONS":7,"MAX":"OPEN","FLAGS":1,"ID":"WINDOW_STATE","TYPE":"ENUM","DEFAULT":"CLOSED","VALUE_LIST":["CLOSED","OPEN"],"CONTROL":"HEATING_CONTROL_HMIP.WINDOW_STATE"},"PARTY_TIME_END":{"MIN":"2000_01_01 00:00","OPERATIONS":7,"MAX":"2255_12_31 23:55","FLAGS":1,"ID":"PARTY_TIME_END","TYPE":"STRING","DEFAULT":"2000_01_01 00:00","CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_END"},"ACTUAL_TEMPERATURE":{"MIN":-3276.8,"OPERATIONS":5,"MAX":3276.7,"FLAGS":1,"ID":"ACTUAL_TEMPERATURE","TYPE":"FLOAT","DEFAULT":0,"CONTROL":"HEATING_CONTROL_HMIP.TEMPERATURE"},"BOOST_MODE":{"MIN":false,"OPERATIONS":6,"MAX":true,"FLAGS":1,"ID":"BOOST_MODE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"HEATING_CONTROL_HMIP.BOOST_MODE"},"DURATION_VALUE":{"MIN":0,"OPERATIONS":2,"MAX":16343,"FLAGS":1,"ID":"DURATION_VALUE","TYPE":"INTEGER","DEFAULT":0}},"error":null}

--------------

2020-01-07 22:27:50.265 - info:javascript.0 (1341) script.js.testLEVEL:{
"result":{
"VALVE_ADAPTION":{
"MIN":false,
"OPERATIONS":7,
"MAX":true,
"FLAGS":1,
"ID":"VALVE_ADAPTION",
"TYPE":"BOOL",
"DEFAULT":false
},
"BOOST_TIME":{
"MIN":0,
"OPERATIONS":5,
"MAX":2048,
"FLAGS":1,
"ID":"BOOST_TIME",
"TYPE":"INTEGER",
"DEFAULT":0
},
"PARTY_MODE":{
"MIN":false,
"OPERATIONS":5,
"MAX":true,
"FLAGS":1,
"ID":"PARTY_MODE",
"TYPE":"BOOL",
"DEFAULT":false,
"CONTROL":"HEATING_CONTROL_HMIP.PARTY_MODE"
},
"SET_POINT_TEMPERATURE":{
"MIN":4.5,
"UNIT":"�C",
"OPERATIONS":7,
"MAX":30.5,
"FLAGS":1,
"ID":"SET_POINT_TEMPERATURE",
"TYPE":"FLOAT",
"DEFAULT":4.5,
"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT"
},
"LEVEL_STATUS":{
"MIN":"NORMAL",
"OPERATIONS":5,
"MAX":"ERROR",
"FLAGS":1,
"ID":"LEVEL_STATUS",
"TYPE":"ENUM",
"DEFAULT":"NORMAL",
"VALUE_LIST":[
"NORMAL",
"UNKNOWN",
"OVERFLOW",
"UNDERFLOW",
"ERROR"
]
},
"PARTY_TIME_START":{
"MIN":"2000_01_01 00:00",
"OPERATIONS":7,
"MAX":"2255_12_31 23:55",
"FLAGS":1,
"ID":"PARTY_TIME_START",
"TYPE":"STRING",
"DEFAULT":"2000_01_01 00:00",
"CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_START"
},
"CONTROL_MODE":{
"MIN":0,
"OPERATIONS":2,
"MAX":3,
"FLAGS":1,
"ID":"CONTROL_MODE",
"TYPE":"INTEGER",
"DEFAULT":0,
"CONTROL":"HEATING_CONTROL_HMIP.CONTROL_MODE"
},
"QUICK_VETO_TIME":{
"MIN":0,
"OPERATIONS":5,
"MAX":2048,
"FLAGS":1,
"ID":"QUICK_VETO_TIME",
"TYPE":"INTEGER",
"DEFAULT":0
},
"FROST_PROTECTION":{
"MIN":false,
"OPERATIONS":5,
"MAX":true,
"FLAGS":1,
"ID":"FROST_PROTECTION",
"TYPE":"BOOL",
"DEFAULT":false,
"CONTROL":"HEATING_CONTROL_HMIP.FROST_PROTECTION"
},
"PARTY_SET_POINT_TEMPERATURE":{
"MIN":4.5,
"OPERATIONS":5,
"MAX":30.5,
"FLAGS":1,
"ID":"PARTY_SET_POINT_TEMPERATURE",
"TYPE":"FLOAT",
"DEFAULT":4.5,
"CONTROL":"HEATING_CONTROL_HMIP.PARTY_SETPOINT_TEMP"
},
"SET_POINT_MODE":{
"MIN":0,
"OPERATIONS":7,
"MAX":3,
"FLAGS":1,
"ID":"SET_POINT_MODE",
"TYPE":"INTEGER",
"DEFAULT":0,
"CONTROL":"HEATING_CONTROL_HMIP.SETPOINT_MODE"
},
"LEVEL":{
"MIN":0,
"OPERATIONS":7,
"MAX":1.01,
"FLAGS":1,
"ID":"LEVEL",
"TYPE":"FLOAT",
"DEFAULT":0
},
"ACTUAL_TEMPERATURE_STATUS":{
"MIN":"NORMAL",
"OPERATIONS":5,
"MAX":"UNDERFLOW",
"FLAGS":1,
"ID":"ACTUAL_TEMPERATURE_STATUS",
"TYPE":"ENUM",
"DEFAULT":"NORMAL",
"VALUE_LIST":[
"NORMAL",
"UNKNOWN",
"OVERFLOW",
"UNDERFLOW"
]
},
"DURATION_UNIT":{
"MIN":"S",
"OPERATIONS":2,
"MAX":"H",
"FLAGS":1,
"ID":"DURATION_UNIT",
"TYPE":"ENUM",
"DEFAULT":"S",
"VALUE_LIST":[
"S",
"M",
"H"
]
},
"SWITCH_POINT_OCCURED":{
"MIN":false,
"OPERATIONS":5,
"MAX":true,
"FLAGS":1,
"ID":"SWITCH_POINT_OCCURED",
"TYPE":"BOOL",
"DEFAULT":false
},
"CONTROL_DIFFERENTIAL_TEMPERATURE":{
"MIN":-10,
"OPERATIONS":2,
"MAX":10,
"FLAGS":1,
"ID":"CONTROL_DIFFERENTIAL_TEMPERATURE",
"TYPE":"FLOAT",
"DEFAULT":0
},
"VALVE_STATE":{
"MIN":"STATE_NOT_AVAILABLE",
"OPERATIONS":5,
"MAX":"ERROR_POSITION",
"FLAGS":9,
"ID":"VALVE_STATE",
"TYPE":"ENUM",
"DEFAULT":"STATE_NOT_AVAILABLE",
"VALUE_LIST":[
"STATE_NOT_AVAILABLE",
"RUN_TO_START",
"WAIT_FOR_ADAPTION",
"ADAPTION_IN_PROGRESS",
"ADAPTION_DONE",
"TOO_TIGHT",
"ADJUSTMENT_TOO_BIG",
"ADJUSTMENT_TOO_SMALL",
"ERROR_POSITION"
]
},
"ACTIVE_PROFILE":{
"MIN":1,
"OPERATIONS":7,
"MAX":3,
"FLAGS":1,
"ID":"ACTIVE_PROFILE",
"TYPE":"INTEGER",
"DEFAULT":1,
"CONTROL":"HEATING_CONTROL_HMIP.ACTIVE_PROFILE"
},
"WINDOW_STATE":{
"MIN":"CLOSED",
"OPERATIONS":7,
"MAX":"OPEN",
"FLAGS":1,
"ID":"WINDOW_STATE",
"TYPE":"ENUM",
"DEFAULT":"CLOSED",
"VALUE_LIST":[
"CLOSED",
"OPEN"
],
"CONTROL":"HEATING_CONTROL_HMIP.WINDOW_STATE"
},
"PARTY_TIME_END":{
"MIN":"2000_01_01 00:00",
"OPERATIONS":7,
"MAX":"2255_12_31 23:55",
"FLAGS":1,
"ID":"PARTY_TIME_END",
"TYPE":"STRING",
"DEFAULT":"2000_01_01 00:00",
"CONTROL":"HEATING_CONTROL_HMIP.PARTY_TIME_END"
},
"ACTUAL_TEMPERATURE":{
"MIN":-3276.8,
"OPERATIONS":5,
"MAX":3276.7,
"FLAGS":1,
"ID":"ACTUAL_TEMPERATURE",
"TYPE":"FLOAT",
"DEFAULT":0,
"CONTROL":"HEATING_CONTROL_HMIP.TEMPERATURE"
},
"BOOST_MODE":{
"MIN":false,
"OPERATIONS":6,
"MAX":true,
"FLAGS":1,
"ID":"BOOST_MODE",
"TYPE":"BOOL",
"DEFAULT":false,
"CONTROL":"HEATING_CONTROL_HMIP.BOOST_MODE"
},
"DURATION_VALUE":{
"MIN":0,
"OPERATIONS":2,
"MAX":16343,
"FLAGS":1,
"ID":"DURATION_VALUE",
"TYPE":"INTEGER",
"DEFAULT":0
}
},
"error":null
}

**Comment by erlanger24** [comment]
Das Gerät wird an einer CCU2 mit aktueller Firmware 2.49.18 betrieben

**Comment by foxriver76** [comment]
Danke und es handelt sich dabei um ein HMIP-Etrv-2? Haben sie anscheinend echt die Meta Daten geändert ..

**Comment by erlanger24** [comment]
Ja genau. Da wurde mit der neuen Firmware der Flüsterbetrieb eingebaut. Evtl war es deswegen nötig?  Braucht es also ein Update am Adapter ?

**Comment by foxriver76** [comment]
Hm.. wenn das jetzt Gang und Gebe wird, den Level DPs keine Einheit mehr mitzugeben, dann muss das wohl vom Adapter behandelt werden. Sehe gerade, ich habe auch HMIP eTRV-2 mit der 2.2.8 -- ich schaue es bei mir nochmal an, ansonsten werde ich was einbauen.

**Comment by erlanger24** [comment]
Ich verstehe auch nicht warum der Max Wert jetzt 1.0.1 ist..  kannst du da die Werte 0-100 überhaupt ausrechnen ?

**Comment by foxriver76** [comment]
Bitte 1.12.6 probieren - Das Gerät muss neu angelegt werden.

**Comment by erlanger24** [comment]
"%" wird jetzt angezeigt, aber die Werte selber sind noch immer zu klein. Hab jetzt Werte wie 0.01% oder auch 0.6%

**Comment by foxriver76** [comment]
Sollte nicht sein, ich kann leider gerade nichts bei mir am System probieren. Evtl hat der Rega Adapter noch die alten Units und schreibt sie rein, starte den mal bitte neu.

**Comment by erlanger24** [comment]
Neustart vom Rega Adapter hat das Problem nun gelöst. Herzlichen Dank !!

**Comment by maloross** [comment]
Leider hat sich das Problem bei mir nicht erledigt, trotz diverser Aktualisierungen, Neuinstallationen usw.
- piVCCU3 mit Firmware 3.49.17
- HmIP-eTRV-2 mit Firmware 2.2.8
- HomeMatic ReGaHSS Vers. 2.5.2
- ioB neuester Stan

**Comment by foxriver76** [comment]
Sicher dass es dasselbe Problem ist? Adapter auf 1.12.6? Gerät gelöscht und neu angelegt während 1.12.6 installiert ist?

**Comment by maloross** [comment]
Die Anzeige der Ventilstellung funktioniert nicht, als Wert steht im DP Level "0", obwohl der Thermostat aufgedreht und der Heizkörper warm ist.
Leider wird mir die Version 1.12.6 nicht zum Upgrade angezeigt und als Anfängerin habe ich bisher alle Upgrades über die Admin-Oberfläche ausgelöst.

**Comment by foxriver76** [comment]
Ist im Latest Repository, kann man im Admin kurz umstellen oben in den Systemeinstellungen. Verwahrungsort von default auf latest stellen, Adapter Liste aktualisieren dann sollte es angeboten werden. Danach wieder zurück stellen auf default (stable).

**Comment by maloross** [comment]
Vielen Dank für die Unterstützung, ich werde mal schauen, ob ich das hinbekomme.

**Comment by warp735** [comment]
was heißt denn "Gerät muss neu angelegt werden"?
Hab das komplette Gerät bei iobroker aus den Objekten gelöscht. RPC neu gestartet > Gerät war wieder da > rega neu gestartet > es wird der richtige Wert angezeigt.
10min später ist es aber wieder 0,32% statt 32% Wie bekommt man das gefixt?

**Comment by warp735** [comment]
@foxriver76 
Kannst Du dazu bitte was sagen?

**Comment by foxriver76** [comment]
So wie du es geschrieben hast. Zeig mal das RAW vom DP und Version etc

**Comment by warp735** [comment]
`{
  "type": "state",
  "common": {
    "name": "HmIP-eTRV-C 00119A499BFE4D:1.FROST_PROTECTION",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 1,
    "ID": "FROST_PROTECTION",
    "TYPE": "BOOL",
    "DEFAULT": false,
    "CONTROL": "HEATING_CONTROL_HMIP.FROST_PROTECTION"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1602527813104,
  "_id": "hm-rpc.1.00119A499BFE4D.1.FROST_PROTECTION",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

HM REGA 3.0.31
HM RPC 1.14.45

**Comment by foxriver76** [comment]
Bitte raw vom datenpunkt welcher falsch skaliert wird. Das ist ja ein Boolean da sollte nix skaliert werden müssen. ;-)

**Comment by warp735** [comment]
`{
  "type": "state",
  "common": {
    "name": "HmIP-eTRV-C 00119A499C0777:1.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1.01,
    "unit": "%",
    "role": "level",
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "",
        "maxLength": "",
        "retention": "15811200",
        "changesRelogInterval": "",
        "changesMinDelta": "",
        "aliasId": ""
      },
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": "31536000",
        "changesRelogInterval": "3600",
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1604516403880,
  "_id": "hm-rpc.1.00119A499C0777.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by foxriver76** [comment]
Gleiches Problem wie https://github.com/ioBroker/ioBroker.hm-rpc/issues/337#issuecomment-849831584

**Comment by warp735** [comment]
also auf Update des Adapters warten oder damit leben?

**Comment by SurfGargano** [comment]
Habe gleiches Problem bei neu angelegten HM-IP Etrv-c und Etrv-c-2 , Max ist 1.01 und damit wird der Level in den Objects falsch angezeigt. RPC Version is 1.15

**Comment by passuff** [comment]
Das Problem scheint immer noch aktuell. Auch bei mir sind die Werte der Ventilstellung nach we vor um Faktor 100 zu klein.
