### ISSUE TITLE
Wetterstation HmIP-SWO-PR OPERATING_VOLTAGE = 0V

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.hm-rpc#224]
Für den HmIP-SWO-PR generiert der Adapter im OPERATING_VOLTAGE DP immer 0V

![grafik](https://user-images.githubusercontent.com/205119/72325454-7053be80-36ad-11ea-9830-ac4490a3b919.png)

**Comment by foxriver76** [comment]
Und zeigt die CCU was anderes an?

**Comment by darkiop** [comment]
Hilf mir mal kurz, wo in der CCU sehe ich den Wert? In der Config kann ich ja nur den Schwellwert definieren:
![grafik](https://user-images.githubusercontent.com/205119/72331974-6cc63480-36b9-11ea-8300-70dc983ed015.png)

**Comment by foxriver76** [comment]
Glaube lässt sich nur mit einem Rega Skript abfragen.
z. B. `WriteLine(dom.GetObject('HmIP-RF.<id-des-sensors>:0.OPERATING_VOLTAGE').State());`

**Comment by darkiop** [comment]
Ok, ist auch bei der CCU 0:

![grafik](https://user-images.githubusercontent.com/205119/72334044-06dbac00-36bd-11ea-8a5e-881988e3659d.png)

Somit ein Bug seitens EQ-3?

**Comment by foxriver76** [comment]
Jop. Anscheinend auch [hier](https://homematic-forum.de/forum/viewtopic.php?t=48155) mal am Rande addressiert.

**Comment by darkiop** [comment]
Danke dir, ich hab den Anlass genutzt und das ganze nochmal an EQ-3 geschrieben. Schauen wir mal :)

**Comment by mesche** [comment]
> Danke dir, ich hab den Anlass genutzt und das ganze nochmal an EQ-3 geschrieben. Schauen wir mal :)

Gibt es hierzu bereits eine Rückmeldung von EQ-3?
