### ISSUE TITLE
Fehlende Icons - ZEL STG RM FDK und ZEL STG RM FST UP4

### ISSUE THREAD

**Issue by bogaboo** [ioBroker/ioBroker.hm-rpc#225]
Hallo,

Nur eine kosmetische Verbesserung:

Ich habe einige ROTO Geräte die baugleich zu den Homematic Geräten sind, 
aber eine andere Kennung haben, sodass im Log folgende Wartungen sind:
 
No image for "ZEL STG RM FDK" found.
No image for "ZEL STG RM FST UP4" found.

Der ZEL STG RM FDK  ist ein  HM-Sec-RHS -> Funk-Fenster-Drehgriffkontakt und 
der ZEL STG RM FST UP4 ist ein  HM-PBI-4-FM -> Funk-Tasterschnittstelle 4-fach

/bogaboo

**Comment by foxriver76** [comment]
Verlinkungen für die Items werden in der nächsten Version dann enthalten sein.
