### ISSUE TITLE
undefined method firmwareUpdateStatusChanged

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.hm-rpc#226]
This method is apparently not implemented in the adapter.

```js
xmlrpc <- undefined method firmwareUpdateStatusChanged ["hm-rpc.0","3014F711A000135709960BFF",1]
```

Not urgent, just an information.

**Comment by foxriver76** [comment]
Do you also receive an event with 0 as soon as Update is finished?

**Comment by foxriver76** [comment]
NotFound event is has its origin in xml-rpc. I will no longer log it on warn, but maybe we can open an enhancement request in hm xml-rpc when we have some more insights.
