### ISSUE TITLE
Wrong state of Homematic IP switch

### ISSUE THREAD

**Issue by JanJunius** [ioBroker/ioBroker.hm-rpc#229]
**Describe the bug**

Device used: Homematic IP Schaltsteckdose HMIP-PS für Smart Home

My configuration contains several Homematic IP switches. I can change their state in ioBroker without any problems. 
However: When I change the state via CCU, there is no change visible in ioBroker. 

**To Reproduce**
1. Switch is off, state in ioBroker is: false
2. Turn switch "on" (true) in CCU3 web interface => Switch is on

**Expected behavior**
State in iobroker should change to: true (but it stays false even after refresh)

**Versions:**

 - hm-rpc version: 1.12.6
 - hm-rega version: 2.5.3
 - JS-Controller version: 2.2.7
 - Node version: 10.16.0
 - Operating system: Linux (Raspian light Buster)
 - CCU model: CCU3
 - CCU firmware: 3.47.10

**Comment by foxriver76** [comment]
Please consider asking this question in our [forum](https://forum.iobroker.net) first.This can have several issues which are most likely not a bug on adapter side. Thank you.
