### ISSUE TITLE
Conflict in server port and homematic rpc daemon port

### ISSUE THREAD

**Issue by angelnu** [ioBroker/ioBroker.hm-rpc#23]
Hi Bluefox,

in my ioBroker setup I run the rfd daemon in the same host as iobroker. With this setup I found that the hm-rpc tries to create an rpcServer in the same port as rfd (2001). Usually the rfd daemon is started before iobroker and then hm-rpc creates the rpcServer in the next available port (2002) and then it works fine but if for any reason the rfd does not start automaticall (for example because the LAN gateway adapter cannot be connected) then the hm-rpc gets port 2001 and I cannot longer activate the rpc daemon.

Another issue is that even in the good case (hm-rpc getting started after rpc) the hm-rega does not connect to the rpcServer but to the rfd daemon. This does not work: the hm-rega adapter remains in yellow state.

I can prepare a pul request to fix this issue but I would like your advice on the best way to go:

- the most straigtforward way would be to create another setting "adapter port" in addition to the "homematic port" so that they can be configured with different addresses.
- a more elegant way might be to use a random port for the rpcServer and write it to an adapter state so that the hm-rega adapter can read it and connect to it.

**Comment by GermanBluefox** [comment]
Hello Angelnu,
of course it is limitations with the port and this was just the legacy. 
The solution is to let define port and try to find a free one if it is occupied. There is a ready function for that in adapter:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L140

Using like here:
https://github.com/ioBroker/ioBroker.web/blob/master/main.js#L359

I will be glad about pull request.

Greetings,
Bluefox

**Comment by angelnu** [comment]
Ok, I will add the new setting and use the helper at runtime to, if needed, use another port.

Is there any adapter apart from the hm-rega that needs to know this port?

**Comment by GermanBluefox** [comment]
Unfortunately hm-rega must poll and nobody wants to know about hm-rega adapter. :)
