### ISSUE TITLE
Can't controll HmIP-BSM from ioBroker

### ISSUE THREAD

**Issue by jaschkopf** [ioBroker/ioBroker.hm-rpc#230]
**Describe the bug**
I installed a HmIP-BSM switch and can't control it from ioBroker. The status in all Channels is updated correctly when I switch it manually or from Raspberrymatic webinterface. But when I switch channel 4.STATE in ioBroker objekt list the value turns red and nothing happens, except the error log entry.   

**Expected behavior**
The switch should turn true when it is controlled from ioBroker

**Screenshots & Logfiles**
(2017) xmlrpc -> setValue: no dpType for hm-rpc.1.00085A499BF485.4.STATE!

**Versions:**
 - hm-rpc version: 1.12.6
 - hm-rega version: 2.5.3
 - JS-Controller version: 2.1.1
 - Node version: 10.18.0
 - Operating system: <os-name>
 - CCU model: raspberrymatic 
 - CCU firmware: 3.49.17.20200131

**Comment by foxriver76** [comment]
restart of adapter should fix it. however it should not happen with 1.12.6, do you know if you have installed 1.12.6 via GitHub (e. g. Octocat Icon in Admin)?

**Comment by jaschkopf** [comment]
Awesome this fixed the problem. Thank you. I didn't installed it from github. I installed the latest stable version straight from Iobroker repository.

**Comment by foxriver76** [comment]
You are welcome. Thanks for the information.
