### ISSUE TITLE
HMIP-Broll LEVEL is not transmitted on manual trigger

### ISSUE THREAD

**Issue by williandalton** [ioBroker/ioBroker.hm-rpc#232]
On manual chage of the Level on the device the Level is not transmitted to ioBroker.
If the level is changed via CCU Interface or via ioBroker level is in Sync like expected

**To Reproduce**
1. Change Level via physical Buttons
2. Level 0% or 100% is transmitted to ioBroker

**Expected behavior**
Transmitted Level is in Sync with CCU

**Screenshots & Logfiles**
![iobroker](https://user-images.githubusercontent.com/45180031/75072943-c7dd1980-54f8-11ea-9634-6db37c31687f.jpg)
![ccu](https://user-images.githubusercontent.com/45180031/75072944-c90e4680-54f8-11ea-87cc-c0a1120f9a6f.jpg)

**Versions:**
 - hm-rpc version: 1.12.6
 - hm-rega version: 2.5.4
 - JS-Controller version: 2.1.1
 - Node version: v10.17.0
 - Operating system: Linux ioBroker-RasPi 4.14.30-v7+
 - CCU model: raspberrymatic
 - CCU firmware: 3.49.17.20200131

**Additional context**
Sound´s a like a replicate of https://github.com/ioBroker/ioBroker.hm-rpc/issues/87 but still exists...

**Comment by foxriver76** [comment]
Nope, in dem anderen Issue ging es um etwas anderes. Es gibt unterschiedliche Channels für den tatsächlichen Wert und den gesetzten Wert. Am besten das Forum bemühen.
