### ISSUE TITLE
Regular crashing

### ISSUE THREAD

**Issue by peterbaumert** [ioBroker/ioBroker.hm-rpc#233]
**Describe the bug**

hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
-- | -- | -- | --
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.Readable.push (_stream_readable.js:209:10)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at readableAddChunk (_stream_readable.js:275:11)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at addChunk (_stream_readable.js:294:12)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.emit (events.js:311:20)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/binrpc/lib/server.js:59:22)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.handleCall (/opt/iobroker/node_modules/binrpc/lib/server.js:96:18)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.emit (events.js:311:20)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:803:115)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | (4226) TypeError: Cannot read property 'slice' of undefined
hm-rpc.1 | 2020-02-26 13:30:17.706 | error | (4226) uncaught exception: Cannot read property 'slice' of undefined

**To Reproduce**
Just let the instance run.

**Expected behavior**
No crash

**Screenshots & Logfiles**

hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
-- | -- | -- | --
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.Readable.push (_stream_readable.js:209:10)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at readableAddChunk (_stream_readable.js:275:11)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at addChunk (_stream_readable.js:294:12)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.emit (events.js:311:20)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/binrpc/lib/server.js:59:22)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.handleCall (/opt/iobroker/node_modules/binrpc/lib/server.js:96:18)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.emit (events.js:311:20)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:803:115)
hm-rpc.1 | 2020-02-26 13:30:17.724 | error | (4226) TypeError: Cannot read property 'slice' of undefined
hm-rpc.1 | 2020-02-26 13:30:17.706 | error | (4226) uncaught exception: Cannot read property 'slice' of undefined

**Versions:**
 - hm-rpc version: 1.12.7
 - hm-rega version: 2.5.5
 - JS-Controller version: 2.2.9
 - Node version: 12.16.1
 - Operating system: Debian
 - CCU model: CCU2
 - CCU firmware: 2.51.6

**Comment by foxriver76** [comment]
Don't know why this just came up now, most likely changes on CCU side. Seems like an `unknownMethod` event is emitted by xml-rpc without params. Error is handled now.
