### ISSUE TITLE
HMIP-WRCD - Umlaute werden nicht korrekt weitergeleitet

### ISSUE THREAD

**Issue by cmartin61** [ioBroker/ioBroker.hm-rpc#234]
setzen von 
{DDBC=WHITE,DDTC=BLACK,DDI=1,DDA=CENTER,DDS=Müllplatz,DDID=1,DDC=true}
in COMBINED_PARAMETER führt zu einem unleserlichen Eintrag im Display.

Offensichtlich führt der Umlaut in 'Müllplatz' zu diesem Problem. Das 'M' wird noch dargestellt.

Trägt man 'Müllplatz' in einem Programm (webUI ccu 3.51.6) ein, wird der Umlaut korrekt dargestellt.

Gibt es einen Workarround?

**Comment by foxriver76** [comment]
HMIP-WRCD ist gemeint oder? 

Probier mal bitte `M%C3%BCllplatz`

**Comment by cmartin61** [comment]
ja -  WRCD  (Tippfehler - Sorry)
Vielen Dank für die schnelle Antwort.

Gerade versucht: es wird genau 'M%C3%BCllplatz' dargestellt - der Umlaut wird nicht ausgetauscht.

**Comment by foxriver76** [comment]
Hm, finde diesen EPAPER_COMBINED State auch gar nicht im Code. BF hatte da früher mal was gemacht. Kannst du mir mal ein Screenshot des Objektes zeigen.

**Comment by cmartin61** [comment]
vermutlich bist du beim HM-Dis-EP-WM55 unterwegs - das kann über Kanal 0 mit EPAPER_XXXX gesteuert werden. Leider gibt es da tatsächlich keinen COMBINED und alles wird einzeln gesendet.

HMIP-WRCD wird über Kanal 3 gesteuert. Da sind dann auch die Datenpunkte alle 1:1 abgelegt.

Hier der Screenshot:
![SnipImage](https://user-images.githubusercontent.com/61196381/75440251-b57d3880-595b-11ea-96e8-cf13e0eff2fb.JPG)

**Comment by foxriver76** [comment]
Und werden direkt über den Datenpunkt `DISPLAY_DATA_STRING` die Werte mit Umlaut korrekt dargestellt?

**Comment by cmartin61** [comment]
Nein - das hatte ich auch versucht. 

Nebensache:
Das Setzen des Datenpunktes löst nicht direkt eine Aktualisierung des Displays aus (ich habe echt lange gewartet >10sec)
Nach einigen hin und her klicken aktualisiert es sich dann irgendwann. Meine Erwartung: nach Display_DATA_COMMIT = true wird leider nicht erfüllt.

**Comment by cmartin61** [comment]
In der WebUI geht es.

![image](https://user-images.githubusercontent.com/61196381/75443375-8b2e7980-5961-11ea-92c9-712e60617c78.png)

Also kann das Display das wohl grundsätzlich.

Das  HM-Dis-EP-WM55 stellt  die Umlaute mit EPAPER_LINEx im Kanla 0 ohne Probleme sofort dar.

**Comment by cmartin61** [comment]
Nachtrag:
Das Sonderzeichen '°' wird übrigens von der CCU nicht unterstützt - Alles nach ° wird auf dem Display nicht angezeigt. 

Umlaute gehen aber.

**Comment by foxriver76** [comment]
Hm, probier mal noch `0x7D` anstelle des kleinen `ü`

**Comment by cmartin61** [comment]
wird dargestellt wie es ist:

![IMG_2412](https://user-images.githubusercontent.com/61196381/75444955-bcf50f80-5964-11ea-8e56-3ce26c38732c.jpg)

kein encoding

**Comment by cmartin61** [comment]
nun dachte ich mir das ein ecape vielleicht hilft ;-)
also folgendes:
M\0x7Dllplatz -> M0üllplatz

da war eine 0 zuviel, daher habe ich es mit M\x7Dllplatz versucht.

Das hat funktioniert also für das kleine 'ü' ' \x7D'

Sagst du mir bitte noch welcher Zeichensatz das ist? 

0x7D finde ich nur '}'

**Comment by cmartin61** [comment]
... ich will noch mehr Umlaute darstellen ;-)

**Comment by cmartin61** [comment]
kann ich DIN_66003 bedenkenlos nehmen?

**Comment by foxriver76** [comment]
Stichprobenartig müsste es DIN 66003 wie von dir erwähnt sein. Das wurde wohl bei den anderen Displays grundsätzlich benötigt über die XML-RPC Schnittstelle, siehe https://github.com/ioBroker/ioBroker.hm-rpc/blob/af2e27eac7300088b430702f620b4c2d0cdf547e/hm-rpc.js#L83

**Comment by foxriver76** [comment]
Ist die Funktionalität von den anderen Datenpunkten eigentlich gegeben? Ich habe ja so das Gefühl, dass da wieder bisschen was individuelles gebaut werden muss, auch wenn sie mittlerweile Steuerdatenpunkte bereitstellen.

**Comment by cmartin61** [comment]
Was soll ich sagen, die Steuerdatenpunkte sind alle wie im Megadokument beschrieben vorhanden.
Was auf jeden Fall nachvollziehbar funktioniert ist COMBINED_PARAMETER. Allerdings muss man da schon suchen und probieren, welche Parameter wie erwartet werden. Das ist leider nicht intuitiv. 
Einzige Einschränkung sind die Umlaute.

Es ist leider nicht nachvollziehbar, wie man mit den einzelnen Datenpunkten das Display wirklich steuern kann.
Werte eingeben und dann DISPLAY_DATA_COMMIT funktioniert nicht.
Wenn man die Punkte füllt wird dann irgendwann mal das Display aktualisiert. Ich hatte versucht das genauer zu ergründen, habe aber damit aufgehört, da aus meiner Sicht COMBINED_PARAMETER sowieso die bessere Lösung ist.

Toll wäre, wenn der Adapter die Umlaute austauschen würde. Das wird aber vermutlich nicht so einfach gehen - da, falls ich das richtig verstanden habe, der Datenpunkt die Daten direkt an die Schnittstelle übergibt.

Was ich mir wünschen würde (oder was für mich nachvollziehbar wäre):
Einzelne Einstellungen der Datenpunkte werden mit einem commit von DISPLAY_DATA_COMMIT für die in DISPLAY_DATA_ID eingestellte Zeile versendet.

Die BatchZeile COMBINED_PARAMETER könnte ähnlich wie beim  HUI-Adapter command, Befehle aufnehmen die auch so heißen wie die Datenpunkte und das dann zeilenweise. Es sollten auch nur die Eigenschaften der Zeilen die geändert werden soll in das Zeilenobjekt übernommen werden können.

Folgendes könnte den Text in Zeile 1 ändern und das Icon in Zeile 2 löschen  - ein explizites commit ist hier eigentlich nicht nötig, da das ja sequenziell abgearbeitet werden kann:

{DISPLAY_DATA_ID:1, DISPLAY_DATA_STRING:'neuer Text'}, {DISPLAY_DATA_ID:2, DISPLAY_DATA_ICON:0}

Aktuell müssen die Zeilen vollständig mit nicht wirklich nachvollziehbar dokumentierten Befehlsparametern aufgerufen werden.

Soviel zu meinem Wunschkonzert.

Da das bisher wohl noch niemanden gestört hat, werde ich das mit dem Mapping in substitutions einfach in meinem Code selbst tun.

Vielen herzlichen Dank für die schnelle und kompetente Unterstützung

**Comment by foxriver76** [comment]
Doch, wir können die Umlaute auf jeden Fall auf Adapterseite austauschen - ist auch das Mindeste, wa sich mir gedacht habe. Letztendlich ist es ja auch mit dem alten EPAPER Display so gewesen, dass aus den einzelnen Datenpunkten (gut die waren damals von uns selbst überhaupt erst ins Leben gerufen, ejtzt gibt es welche, die man sicher irgendwie bedienen kann) das Kommando zusammengebaut wurde. Evtl. muss es dann wieder auf so eine, leider nicht ganz so schicke, Lösung hinaus laufen.

**Comment by foxriver76** [comment]
Könntest du mir evtl noch die Meta Daten zur Verfügung stellen. Zu finden unter `hm-rpc.meta.<device-type>...` oder bei erstmaligen Hinzufügen wurden sie geloggt (logging kann erzwungen werden durch löschen des Gerätes + Meta-Daten des Gerätes) oder via Custom Command siehe https://github.com/ioBroker/ioBroker.hm-rpc#custom-commands getParamsetDescription Beispiel.

**Comment by cmartin61** [comment]
Hey, das klingt super. Ich bin gerade unterwegs und kann daher die Daten nicht hochladen. Mache ich später.

**Comment by cmartin61** [comment]
getParameterDescription: 
paramType: MASTER

{"result":{"REPEATED_LONG_PRESS_TIMEOUT_UNIT":{"MIN":"100MS","OPERATIONS":3,"MAX":"H","FLAGS":1,"ID":"REPEATED_LONG_PRESS_TIMEOUT_UNIT","TYPE":"ENUM","DEFAULT":"M","VALUE_LIST":["100MS","S","M","H"]},"LONG_PRESS_TIME":{"MIN":0,"UNIT":"s","OPERATIONS":3,"MAX":25.5,"FLAGS":1,"ID":"LONG_PRESS_TIME","TYPE":"FLOAT","DEFAULT":0.4},"TEXT_BACKGROUND_COLOR":{"MIN":"WHITE","OPERATIONS":3,"MAX":"BLACK","FLAGS":1,"ID":"TEXT_BACKGROUND_COLOR","TYPE":"ENUM","DEFAULT":"WHITE","VALUE_LIST":["WHITE","BLACK"]},"TEXT_ICON":{"MIN":"NO_ICON","OPERATIONS":3,"MAX":"CLOCK","FLAGS":1,"ID":"TEXT_ICON","TYPE":"ENUM","DEFAULT":"NO_ICON","VALUE_LIST":["NO_ICON","LAMP_OFF","LAMP_ON","PADLOCK_OPEN","PADLOCK_CLOSED","ERROR","EVERYTHING_OKAY","INFORMATION","NEW_MESSAGE","SERVICE_MESSAGE","SUN","MOON","WIND","CLOUD","THUNDERSTORM","DRIZZLE","CLOUD_AND_MOOON","RAIN","SNOW","CLOUD_AND_SUN","CLOUD_SUN_AND_RAIN","SNOWFLAKE","RAINDROP","FLAME","WINDOW_OPEN","SHUTTERS","ECO","PROTECTION_DEACTIVATED","EXTERNAL_PROTECTION","INTERNAL_PROTECTION","BELL","CLOCK"]},"REPEATED_LONG_PRESS_TIMEOUT_VALUE":{"MIN":0,"OPERATIONS":3,"MAX":63,"FLAGS":1,"ID":"REPEATED_LONG_PRESS_TIMEOUT_VALUE","TYPE":"INTEGER","DEFAULT":2},"TEXT_ALIGNMENT":{"MIN":"LEFT","OPERATIONS":3,"MAX":"RIGHT","FLAGS":1,"ID":"TEXT_ALIGNMENT","TYPE":"ENUM","DEFAULT":"CENTER","VALUE_LIST":["LEFT","CENTER","RIGHT"]},"TEXT":{"MIN":"","OPERATIONS":3,"MAX":"[0x20-0x7E]{16}","FLAGS":1,"ID":"TEXT","TYPE":"STRING","DEFAULT":"Kanal 1"},"DBL_PRESS_TIME":{"MIN":0,"UNIT":"s","OPERATIONS":3,"MAX":25.5,"FLAGS":1,"ID":"DBL_PRESS_TIME","TYPE":"FLOAT","DEFAULT":0},"TEXT_COLOR":{"MIN":"WHITE","OPERATIONS":3,"MAX":"BLACK","FLAGS":1,"ID":"TEXT_COLOR","TYPE":"ENUM","DEFAULT":"BLACK","VALUE_LIST":["WHITE","BLACK"]}},"error":null}

Ich hoffe, dass da ist, was du brauchst - ich habe auf die Schnelle nirgendwo die zulässigen Parametertypen gefunden. 

zur Sicherheit noch
paramType: VALUES

{"result":{"PRESS_SHORT":{"MIN":false,"OPERATIONS":4,"MAX":true,"FLAGS":1,"ID":"PRESS_SHORT","TYPE":"ACTION","DEFAULT":false,"CONTROL":"BUTTON_NO_FUNCTION.SHORT"},"PRESS_LONG":{"MIN":false,"OPERATIONS":4,"MAX":true,"FLAGS":1,"ID":"PRESS_LONG","TYPE":"ACTION","DEFAULT":false,"CONTROL":"BUTTON_NO_FUNCTION.LONG"}},"error":null}

Falls es ein anderer sein muss - sag mir einfach den paramType

**Comment by foxriver76** [comment]
VALUES ist richtig, allerdings für Kanal 3 also `:3` statt `:1` bitte, Dankeschön.

**Comment by cmartin61** [comment]
Kanalnummer hatte völlig übersehen - Sorry 
Values für Kanal 3:

 {"result":{"INTERVAL":{"MIN":1,"OPERATIONS":2,"MAX":15,"FLAGS":1,"ID":"INTERVAL","TYPE":"INTEGER","DEFAULT":0},"COMBINED_PARAMETER":{"MIN":"","OPERATIONS":2,"MAX":"","FLAGS":1,"ID":"COMBINED_PARAMETER","TYPE":"STRING","DEFAULT":"","CONTROL":"ACOUSTIC_DISPLAY_RECEIVER.COMBINED_PARAMETER"},"ACOUSTIC_NOTIFICATION_SELECTION":{"MIN":"LOW_BATTERY","OPERATIONS":2,"MAX":"ERROR","FLAGS":1,"ID":"ACOUSTIC_NOTIFICATION_SELECTION","TYPE":"ENUM","DEFAULT":"LOW_BATTERY","VALUE_LIST":["LOW_BATTERY","DISARMED","INTERNALLY_ARMED","EXTERNALLY_ARMED","DELAYED_INTERNALLY_ARMED","DELAYED_EXTERNALLY_ARMED","EVENT","ERROR"]},"DISPLAY_DATA_COMMIT":{"MIN":false,"OPERATIONS":2,"MAX":true,"FLAGS":1,"ID":"DISPLAY_DATA_COMMIT","TYPE":"BOOL","DEFAULT":false},"DISPLAY_DATA_STRING":{"MIN":"","OPERATIONS":2,"MAX":"[0x20-0x7E]{16}","FLAGS":1,"ID":"DISPLAY_DATA_STRING","TYPE":"STRING","DEFAULT":""},"DISPLAY_DATA_ID":{"MIN":1,"OPERATIONS":2,"MAX":5,"FLAGS":1,"ID":"DISPLAY_DATA_ID","TYPE":"INTEGER","DEFAULT":1},"DISPLAY_DATA_BACKGROUND_COLOR":{"MIN":"WHITE","OPERATIONS":2,"MAX":"BLACK","FLAGS":1,"ID":"DISPLAY_DATA_BACKGROUND_COLOR","TYPE":"ENUM","DEFAULT":"WHITE","VALUE_LIST":["WHITE","BLACK"]},"DISPLAY_DATA_ICON":{"MIN":"NO_ICON","OPERATIONS":2,"MAX":"CLOCK","FLAGS":1,"ID":"DISPLAY_DATA_ICON","TYPE":"ENUM","DEFAULT":"NO_ICON","VALUE_LIST":["NO_ICON","LAMP_OFF","LAMP_ON","PADLOCK_OPEN","PADLOCK_CLOSED","ERROR","EVERYTHING_OKAY","INFORMATION","NEW_MESSAGE","SERVICE_MESSAGE","SUN","MOON","WIND","CLOUD","THUNDERSTORM","DRIZZLE","CLOUD_AND_MOOON","RAIN","SNOW","CLOUD_AND_SUN","CLOUD_SUN_AND_RAIN","SNOWFLAKE","RAINDROP","FLAME","WINDOW_OPEN","SHUTTERS","ECO","PROTECTION_DEACTIVATED","EXTERNAL_PROTECTION","INTERNAL_PROTECTION","BELL","CLOCK"]},"DISPLAY_DATA_ALIGNMENT":{"MIN":"LEFT","OPERATIONS":2,"MAX":"RIGHT","FLAGS":1,"ID":"DISPLAY_DATA_ALIGNMENT","TYPE":"ENUM","DEFAULT":"LEFT","VALUE_LIST":["LEFT","CENTER","RIGHT"]},"REPETITIONS":{"MIN":"NO_REPETITION","OPERATIONS":2,"MAX":"INFINITE_REPETITIONS","FLAGS":2,"ID":"REPETITIONS","TYPE":"ENUM","DEFAULT":"NO_REPETITION","VALUE_LIST":["NO_REPETITION","REPETITIONS_001","REPETITIONS_002","REPETITIONS_003","REPETITIONS_004","REPETITIONS_005","REPETITIONS_006","REPETITIONS_007","REPETITIONS_008","REPETITIONS_009","REPETITIONS_010","REPETITIONS_011","REPETITIONS_012","REPETITIONS_013","REPETITIONS_014","INFINITE_REPETITIONS"]},"DISPLAY_DATA_TEXT_COLOR":{"MIN":"WHITE","OPERATIONS":2,"MAX":"BLACK","FLAGS":1,"ID":"DISPLAY_DATA_TEXT_COLOR","TYPE":"ENUM","DEFAULT":"WHITE","VALUE_LIST":["WHITE","BLACK"]}},"error":null}

**Comment by foxriver76** [comment]
Kannst du mal bitte den Adapter von GitHub aktualisieren + Upload und schauen ob man nun die Umlaute setzen kann. Sollte mittels `COMBINED_COMMAND` und `DISPLAY_DATA_STRING` gehen.

**Comment by cmartin61** [comment]
Wird gleich morgen erledigt

**Comment by cmartin61** [comment]
Installiert ist jetzt Version 1.12.9 - die hat auch das passende Label.
Ich habe rega und alle rpc neugestartet.

Leider funktioniert das jetzt noch nicht.

Ich habe deinen Code aus tools.js in meine Ersetzungsmethode eingesetzt - es hat nicht funktioniert.
ich habe einen Backslash entfernt und es hat funktioniert.

Dieser Code hat dann in meinem Skript funktioniert:

        const specialChars = {
            ' ': '\x20',
            '!': '\x21',
            '"': '\x22',
            '%': '\x25',
            '&': '\x26',
            '=': '\x27',
            '(': '\x28',
            ')': '\x29',
            '*': '\x2A',
            '+': '\x2B',
            ',': '\x2C',
            '-': '\x2D',
            '.': '\x2E',
            '/': '\x2F',
            'Ä': '\x5B',
            'Ö': '\x23',
            'Ü': '\x24',
            'ä': '\x7B',
            'ö': '\x7C',
            'ü': '\x7D',
            'ß': '\x5F',
            ':': '\x3A',
            ';': '\x3B',
            '@': '\x40',
            '>': '\x3E'
        };

**Comment by foxriver76** [comment]
Danke, ich ändere es später ab dann könntest du nochmals testen.

**Comment by cmartin61** [comment]
Na klar - mache ich gern

**Comment by foxriver76** [comment]
Habs geändert - könntest wieder Installation von GitHub + Upload des Adapters machen um die Änderungen zu bekommen., an der Versionsnummer ändert sich allerdings nichts mehr. Schon mal vielen Dank fürs Testen.

**Comment by cmartin61** [comment]
Ich habe gerade noch mal probiert, bin mir allerdings nicht sicher ob ich das update richtig gemacht habe, oder ob das update wirklich funktioniert hat.
Das Update der Version 1.12.9 läuft zwar los, aber es gibt einen Fehler in der Logausgabe:

$ ./iobroker upgrade hm-rpc@1.12.9
Update hm-rpc from @1.12.9 to @1.12.9
NPM version: 6.13.4
npm install iobroker.hm-rpc@1.12.9 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.hm-rpc@1.12.9.npm 
ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.

Danach geht es dann weiter - keine Ahnung ob das etwas zu bedeuten hat.

Nach der Installation habe ich ein upload für diesen adapter gemacht:

Also zuerst:

![image](https://user-images.githubusercontent.com/61196381/75631580-6bfb4a80-5bf4-11ea-9d90-b5389c381832.png)

dann:
![image](https://user-images.githubusercontent.com/61196381/75631586-787fa300-5bf4-11ea-839a-864cbbd0666d.png)

**Comment by cmartin61** [comment]
ich habe dann noch mal genauer hingeschaut:

Darstellung ohne Übersetzungsmethode:

'ö' -> '.'

zwei backslashs:

'ö' -> '\x76'

ein backslash:
'ö' -> 'ö'

Es sieht so aus, als hätte ich entweder die falsche Version oder deine Ersetzungsmethode wird im Code nicht aufgerufen.

**Comment by cmartin61** [comment]
habe es jetzt so versucht:
![image](https://user-images.githubusercontent.com/61196381/75631898-11afb900-5bf7-11ea-969f-5b1cc2fcc152.png)

keine Fehlermeldung bei der Installation - aber auch keine Verbesserung...

**Comment by foxriver76** [comment]
Danach noch Upload machen. Zb im Terminal `iob u hm-rpc`

**Comment by cmartin61** [comment]
jetzt auch noch mal im Terminal:
![image](https://user-images.githubusercontent.com/61196381/75634361-7ece4900-5c0d-11ea-88ca-fb7b9d24e1f3.png)

Es bleibt leider dabei. Die Umlaute werden nicht dargestellt. Vermutlich wird die Methode nicht aufgerufen.
'ö' 
![image](https://user-images.githubusercontent.com/61196381/75634505-f355b780-5c0e-11ea-846e-ac01248dd5a1.png)
 'ß'
![image](https://user-images.githubusercontent.com/61196381/75634493-b093df80-5c0e-11ea-8441-12d10aa37bd9.png)
'ü'
ist ein schwarzer Balken
 
wenn ich deine aktuelle Methode in meinem Code laufen lasse funktioniert es. Im Adapter leider nicht.

**Comment by foxriver76** [comment]
Okay, ja falls die Methode aufgerufen wird sollte auch auf debug geloggt werden was er in was umgewandelt hat. Ich schaue nochmal rein später.

**Comment by foxriver76** [comment]
So, jetzt sollte es aber passen. Hatte in meiner Logik was unterschalgen und desshalb irrtümlicherweise auf den channel geprüft statt auf den state.

**Comment by cmartin61** [comment]
Vorweg:
DISPLAY_DATA_STRING konnte ich nicht testen, da ich es nicht mehr geschafft habe das display zu aktualisieren. Früher hat es das nach einigen umherklicken irgendwann getan. Da habe ich jetzt aufgegeben.

Folgende Erkenntnisse aus dem Test von COMBINED_COMMAND:
Das Setzen einzelner Zeilen

{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=Müllplatz,DDID=3,DDC=true}

funktioniert super!

Das Setzen mehrerer Zeilen 
{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=schließt,DDID=2},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=schließt,DDID=3},{DDBC=WHITE,DDTC=BLACK,DDI=0,DDA=CENTER,DDS=öffnet,DDID=4,DDC=true}

hat noch Probleme:
Die erste Zeile geht - die anderen dann nicht mehr

**Comment by foxriver76** [comment]
Ah ich dachte da setzt man nur eine Zeile, dann muss in der Logik noch was umgebaut werden. ;-)

**Comment by foxriver76** [comment]
Sollte nun gehen.

**Comment by cmartin61** [comment]
COMBINED_COMMAND funktioniert jetzt auch für mehrere Zeilen.
Habe mein Mapping schon wieder aus meinem code entfernt. :-)

Nochmal vielen für den Support.

**Comment by foxriver76** [comment]
Top, danke für Feedback + Testen, dann schiebe ich die Version mal auf npm
