### ISSUE TITLE
missing values after reinstalling homatic 

### ISSUE THREAD

**Issue by grritvrij** [ioBroker/ioBroker.hm-rpc#235]
After a failure in iobroker, had to do a full reinstall, everything else worked fine.
Now after reinstalling homatic in iobroker I am missing a lot of values. Alarms are displayed, but the Type/Role/Value are missing on all components. Tried rebooting iobroker, reinstalling HomeMatic ReGaHSS / HomeMatic RPC. Things are displayed normally in the homatic interface, and controllable. After I reinstall and run the instance it loads the treeview and the names/id's but the values stay empty.
![bug](https://user-images.githubusercontent.com/32968632/75718253-e9958800-5cd2-11ea-93c4-bfb33cd7634a.PNG)

**Versions:**
 - hm-rpc version: 1.12.9
 - hm-rega version: 2.5.5
 - JS-Controller version: 4.4.2
 - Node version: v10.19.0
 - Operating system: docker
 - CCU model: ccu2
 - CCU firmware: 2.51.6

**Comment by foxriver76** [comment]
Most likely a configuration issue - callback address has to be the address where your ioBroker is reachable from the CCU. Is hm-rpc connected? Is there a warning or an error in your logfile?

**Comment by grritvrij** [comment]
![image](https://user-images.githubusercontent.com/32968632/75724858-8c540380-5cdf-11ea-888b-90950570023d.png)
![image](https://user-images.githubusercontent.com/32968632/75724928-af7eb300-5cdf-11ea-8940-d06291912eee.png)

It does look connected. 
And these indicator alarms seem to be written in iobroker as wel?

**Comment by foxriver76** [comment]
As mentioned before, check that callback address matches the ip of your iobroker host.

**Comment by grritvrij** [comment]
Thank you very much it works now had the ip and port behind it but that does not work greetings
