### ISSUE TITLE
Datepunkt für Batterieladung in %

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.hm-rpc#237]
Wäre es möglich die Batterieladung in % auszugeben.

Kann man aus dem aktuellen Spannungswert und der Unterspannungsgrenze berechnen.

Mehr dazu hab ich hier geschrieben:
https://forum.iobroker.net/topic/28789/script-f%C3%BCrtabelle-der-batterie-zust%C3%A4nde/799

**Comment by foxriver76** [comment]
Auf was basiert deine calcPercent Methode? Sind die Werte willkürlich?

**Comment by Scrounger** [comment]
Nein sind nicht willkürlich. 
Wenn das Gerät eine AAA Batterie hat, dann ist die Spannung bei 100% (neu eingelegte Batterie) bei 1,5V. Bei Geräten mit 2x AAA Batterien liegt die Spannung bei 3V.

Unterspannungsgrenzen kann man in den devices der ccu einstellen:
![grafik](https://user-images.githubusercontent.com/6370451/76512925-ccd91d00-6455-11ea-8572-fe6bf8d42f3d.png)

Wenn man diese Schwelle abgreifen könnte und es eine Möglichkeit gibt die Anzahl der Batterien / Spannung bei neuen Batterien aus der ccu abzugreifen, wäre die Berechnung möglich.
Allerdings kenne ich mich mit der ccu sw nicht aus, um das beurteilen zu können.

**Comment by foxriver76** [comment]
Ach so, ja da besteht allerdings weitere Problematik seitens Batterietyp und Co. z.B. hat eine Keymatic 3-4 AA Batterien. Das gibt die CCU meines Wissens nach nicht aus, es gibt allerdings ein [Skript](https://forum.iobroker.net/topic/19436/servicemeldungen-all-inclusive-f%C3%BCr-homematic/2), das versucht händisch alle Batterietypen zu hinterlegen. Dann kommt noch dazu, dass die vom User definierte Lowbat-Schwelle (an die würde ich vermutlich ran kommen) nicht tatsächlich 0 % entspricht. All in all, kann man da vermutlich maximal eine mittelmäßige Approximation erreichen. 

Ich würde das hier für den Adapter ablehnen, da ich die HM Adapter gerne auf die Kernfunktionalität beschränken würde (allerdings alle Möglichkeiten zur Verfügung stelle, individuelle Geschichten mittels Messages an Rega, RPC selbst zu verwirklichen), könnte mir allerdings vorstellen, dass man mit nem Skript was bauen kann, unter der Annahme, dass die Schwellwerte einigermaßen stimmig gesetzt sind.
