### ISSUE TITLE
HmIP-SWDO-I / HM-Sec-SCo -> State wird nicht aktualisiert

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.hm-rpc#238]
Problem mit Fensterkontakten HmIP-SWDO-I und hm-rpc 1.12.6.

Seit irgendeinem der letzten Updates des Adapters wird der State Wert nicht mehr zuverlässig von CCU3 nach iobroker übernommen.

Ein paar Mal geht die Aktualiserung für Offen/Geschlossen zum ioBroker durch, dann irgendwann nicht mehr. 

Auf der CCU3 werden die Änderungen des State korrekt angezeigt.

Ich habe mehrere der Kontakte HM-Sec-SCo/HmIP-SWDO-I und alle zeigen denselben Effekt.
Wird der Adapter hm-rpc.1 neu gestartet, dann geht es wieder eine Weile.

Ist da irgendwas bekannt dazu?

-jayvee

**Comment by foxriver76** [comment]
Hm.. Debug Log wäre hilfreich, falls das so zutrifft. Habe selbst mehrere HMIP-SWDO und einen HM-Sec-SCo und kann das Verhalten nicht feststellen. Aktualisierungen gehen nur für die genannten Geräte nicht und sonst werden Statusänderungen mitgeteilt?.. für die Geräte gibts eigentlich auch keine Sonderbehandlung, auch wäre merkwürdig, dass du hm-rpc.1 neustartest und dann sowohl HMIP als auch rfd Sensoren wieder übermittelt werden..

**Comment by JayVee2** [comment]
Debug Log gibt nichts her.
Das seltsame ist, es hat lange sehr zuverlässig funktioniert.
Ich habe noch eine ganze Reihe HmIP-PSM Messsteckdosen, die laufen auch gut und dii Stati werden aktualisiert.
Ich habe kein Problem mit rrfd Sensoren. Alle da, funktionieren gut.
ioBroker neu gestartet, CCU3 neu gestartet...

**Comment by foxriver76** [comment]
Ja, die Instanz hätte währendessen auf Debug laufen müssen. Wenn es regelmäßig auftritt, könnte man das umstellen. Auch keine Fehler im Log von hm-rpc? beim Neustart werden die Werte einmalig von hm-rega geschrieben und auf andere Art ausgelesen. Danach wartet hm-rpc auf Änderungen, die ihm von der CCU mitgeteilt werden. Also gibt es die Option, dass die Änderung niemals mitgeteilt wurde, dann würde ich aber erwarten, dass das für andere HMIP Geräte auch zutrifft.. oder eben der Adapter handelt den State nicht korrekt ab, da wurde aber niemals was angefasst und die Fenstersensoren erhalten keine Sonderbehandlung, deshalb auch eher unwahrscheinlich..

Woran macht es sich denn bemerkbar, dass der STATE in iobroker nicht aktualisiert wurde?

**Comment by JayVee2** [comment]
>> Woran macht es sich denn bemerkbar, dass der STATE in iobroker nicht aktualisiert wurde?

Ich sehe es in den Objects. Status und Datumsstempel werden nicht mehr aktualisiert und das Event kommt nicht mehr in den Skripten.

**Comment by JayVee2** [comment]
Ich habe jetzt mal die Batterien von allen Fensterkontakten getauscht (vorher 2,7V) und jetzt scheint es besser zu sein. Also merkwürdig ist trotz allem, dass es immer wieder vorkommt, dass der Status der Fensterkontakte in der CCU3 richtig angezeigt wird aber in ioBroker nicht übernommen wird.

Kann das mit einer schwachen Funkverbindung oder nicht mehr ganz vollen Batterien erklärt werden?

**Comment by foxriver76** [comment]
Nope, eigentlich nicht. Was in CCU ankommt sollte weitergeleitet werden, ist ja Aufgabe der API und nicht der Geräte. Wenn dann würde es erst gar nicht an der CCU ankommen.

**Comment by foxriver76** [comment]
Kann natürlich sein dass CCU was geloggt hat an Fehlern, Villt konnte er ioBroker währenddessen nicht erreichen.

**Comment by JayVee2** [comment]
Habe im CCU Log nichts passendes gefunden.
Seit ich die Batterien getauscht habe, ist das Problem nicht mehr regelmäßig aufgetreten. Ich werde das weiter beobachten. Beide Türkontakte laufen übrigens über PSM als Router.
