### ISSUE TITLE
iobroker does not find devices

### ISSUE THREAD

**Issue by copystring** [ioBroker/ioBroker.hm-rpc#239]
**Describe the bug**
Iobroker does not find devices

**To Reproduce**
1. Install homegear in docker
2. Configure homegear for hmland/hmcfgusb
3. pair HM-CC-RT-DN to homegear
4. Synchronize objects (once)
5. under hm-rpc.0 are no devices while the do exist in homegear

**Screenshots & Logfiles**
Homegear log in docker: https://pastebin.com/BdgmwBev

![image](https://user-images.githubusercontent.com/1298861/76789719-ac92c080-67bd-11ea-8919-ddb56ec4e19a.png)

![image](https://user-images.githubusercontent.com/1298861/76789758-c16f5400-67bd-11ea-821f-0253b61bdcff.png)

**Versions:**
 - hm-rpc version: 1.12.10
 - JS-Controller version: not sure how to find that out
 - Node version: v10.19.0
 - Operating system: ubuntu 18.04
 - CCU model: HM-USB-CFG-2

**Comment by foxriver76** [comment]
please make sure, that the provided callback address is the address from which your CCU can reach your ioBroker host

**Comment by copystring** [comment]
I guess this is what I do not understand.

**Comment by foxriver76** [comment]
which address do you use to access your iobroker admin via browser?

**Comment by copystring** [comment]
192.168.1.221

**Comment by foxriver76** [comment]
And your ccu wen interface too? ;-)

**Comment by copystring** [comment]
Not sure. Is it the one from homegear on 192.168.1.221:2001? If so, then yes.

**Comment by foxriver76** [comment]
Both in different docker containers I guess. The IP address to access one Docker container from another is normally not the same, because for one container the other one is like another Host. But I am not much into the use of Docker.

**Comment by copystring** [comment]
Yes. They are in two docker containers.
However they can both "see" each other. Also I can access homegear from another PC via homematic-manager and pair devices with it.
Seems a lot like an issue with hm-rpc...

**Comment by copystring** [comment]
Okay. installed both directly instead of in docker. It works now.
