### ISSUE TITLE
Improve support for the new HMIP-WRCR dimmer button

### ISSUE THREAD

**Issue by Strunzdesign** [ioBroker/ioBroker.hm-rpc#241]
The HMIP-WRCR is a recently published device that I received and assembled today. It is a round push button (long / short) that can be rotated clockwise and counterclockwise (distinguishing slow and fast rotation). In total, it offers three independent channels each acting like a "normal" button channel.

Accessing it using IoBroker worked well, but there are only two minor issues. After creating the mandatory dummy rule on the CCU / RaspiMatic all 1+3 channels became visible in IoBroker and all events were shown correctly. However:

1.) The device icon is missing. The latest CCU3/RasberryMatic firmware images provide one. I know, it's a new device! :-)
2.) The channel events are not named correctly yet:

Channel 0:
- Lots of stuff, everything is ok here.

Channel 1:
- PRESS_LONG:  ok, works, fine.
- PRESS_SHORT: ok, works, fine.

Channel 2:
- PRESS_LONG:  is slow rotation clockwise, "Langsames Drehen nach rechts" according to the WebUI of my german RaspberryMatic.
  Rename to ROTATE_CLOCKWISE_SLOW, ROTATE_CW_SLOW, or ROTATE_SLOW_CW.
- PRESS_SHORT: is fast rotation clockwise, "Schnelles Drehen nach rechts" according to the WebUI of my german RaspberryMatic.
  Rename to ROTATE_CLOCKWISE_FAST, ROTATE_CW_FAST, ROTATE_FAST_CW.

Channel 3:
- PRESS_LONG:  is slow rotation counterclockwise, "Langsames Drehen nach links" according to the WebUI of my german RaspberryMatic.
  Rename to: ROTATE_COUNTERCLOCKWISE_SLOW, ROTATE_CCW_SLOW, or ROTATE_SLOW_CCW.
- PRESS_SHORT: is fast rotation counterclockwise, "Schnelles Drehen nach links" according to the WebUI of my german RaspberryMatic.
  Rename to: ROTATE_COUNTERCLOCKWISE_FAST, ROTATE_CCW_FAST, or ROTATE_FAST_CCW.

Beside these minor issues, the device is already fully usable. I, for one, prefer the long naming scheme of the events, such as ROTATE_COUNTERCLOCKWISE_FAST.

Thanks for fixing these small issues for this new device, I really appreciate it.

Regards,
Florian

**Comment by foxriver76** [comment]
Can you please provide the missing icon? Rename of paramsets is normally not done in hm-rpc adapter, I would rather recommend creating a meaningful alias.

**Comment by Strunzdesign** [comment]
I extracted both pictures (full + thumb) from the firmware image, but I have no idea how to attach it to this ticket. Uploading always fails. May I send them to you via email?

Strange that the events (paramsets) have such unintuitive names. If it is not possible to rename them in the adaptor (I remember our discussions with the e-paper display. There, it was not a technical issue to rename things but more a matter of consistency... but IIRC, all these were local variables only visible inside the adaptor) then it seems we have to live with it. But to be honest, that naming is a mess and should really be changed. Or, the aliases should be created automatically, or... I don't know ;-)

I'm going to upload or send them immediately as soon as I know how.

Regards,
Florian

**Comment by foxriver76** [comment]
Of course, you can send it to me: moritz.heusinger@gmail.com

The ID basically represents the corresponding id of the paramset. But the name can be changed by the users, e.g. directly in CCU WebUI and syncing via hm-rega. Epaper is a exception, because the API did not provide the needed states, thus BF implemented extra logic in the adapter. But doing such stuff for the diversity of homematic devices would be an overkill. Sorry ;-)

**Comment by Strunzdesign** [comment]
Ok, I've sent you the files. 

I got your point regarding the additional work that was required for the e-paper, and that such effort is overkill if required for any generic future HMIP device.

I have never used aliases before, but I'm going to read about them now. However, I don't get your point of changing a name directly in the CCU WebUI. What name? The name of the PRESS_LONG event? Where can I change that in the WebUI? Or did I misunderstand you...

Regards,
Florian

**Comment by foxriver76** [comment]
You are right, only channel names can be changed ;-)

**Comment by Strunzdesign** [comment]
Hi,

sorry to say, the icon is still not shown here. I'm on version 1.13.0 now. However, I had a look into at file "images.js" and replaced the entry "HMIP-WRCR" by "HmIP-WRCR", but still no luck. I cleared the browser cache, restarted ioBroker, and even removed and re-added one of my devices, but no success yet.

```
{  
  "_id": "hm-rpc.0.AABBCCDDEEFFGG",
  "type": "device",
  "common": {
    "name": "SZ_BettLinks_Drehtaster"
  },
  "native": {
    "TYPE": "HmIP-WRCR",
    "SUBTYPE": "WRCR",
    "ADDRESS": "AABBCCDDEEFFGG",
    "RF_ADDRESS": 12345678,
    "CHILDREN": [
      "AABBCCDDEEFFGG:0",
      "AABBCCDDEEFFGG:1",
      "AABBCCDDEEFFGG:2",
      "AABBCCDDEEFFGG:3"
    ],
    "PARENT": "",
    "PARENT_TYPE": "",
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "FIRMWARE": "1.12.4",
    "AVAILABLE_FIRMWARE": "0.0.0",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
    "VERSION": 1,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "DIRECTION": 0,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 4
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1586091523770,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

It still shows the generic icon `https://IP:8081/lib/css/fancytree/device.png`.

**Comment by foxriver76** [comment]
After local change you have to do an upload `iob u hm-rpc`, your change should fix it, because `native.TYPE` has a lowercase `m` and this is the id used to access the icons.

**Comment by foxriver76** [comment]
Let me know if it works ;-)

**Comment by Strunzdesign** [comment]
Sorry, not yet. The "upload" worked, but still no icon even after clearing the cache or using a different browser. Any ideas?

**Comment by foxriver76** [comment]
After the upload let the adapter recreate the device, it should either find the correct image or log a warning that no image has been found.

**Comment by Strunzdesign** [comment]
That worked! Now all my WRCR show the correct device icons.

Thank you very much, great work! :-)
Florian

**Comment by foxriver76** [comment]
You are very welcome, I will fix it in the images file next time I am on my laptop.
