### ISSUE TITLE
Error on getParamsetDescription: Error: XML-RPC fault: Unknown paramset 

### ISSUE THREAD

**Issue by grogo08** [ioBroker/ioBroker.hm-rpc#244]
Ich wollte eigenen Module wieder einlesen und bekomme jetzt die Fehlermeldung 
`"Error on getParamsetDescription: Error: XML-RPC fault: Unknown paramset"`. 
Die Module werden mir in Objekte mit den Kanälen angezeigt, aber ich kann die Staten "long.press" und "short.press" bei den 16 Schaltern und den Ein-/Ausschalt State bei den 16 Relaisausgängen nicht mehr sehen und somit auch nicht auslesen oder schalten.

Ist etwas mit meiner io-package.json nicht mehr in Ordnung. Vor gut einem Jahr hat es noch problemlos funktioniert.  Wie kann ich diese anschauen, ob der eigene Eintrag noch vorhanden ist?

Durch eine Löschen der hm-rpc habe ich jetzt auch die Status der alten Module verloren. 

 Bitte um Hilfe

**Comment by foxriver76** [comment]
Welches Gerät verursacht den Fehler? Log könnte helfen. Das mit Paramsets ist strange. States werden bei Instanzstart neu geschrieben wenn Rega korrekt konfiguriert.
