### ISSUE TITLE
AskSin++

### ISSUE THREAD

**Issue by elmarfaber** [ioBroker/ioBroker.hm-rpc#245]
Hallo,

ich versuche gerade ein Selbstbau HomeMatic Devive (https://asksinpp.de/) einzubinden.
Ich verwende HomeGear. Anlernen funktioniert korrekt und es wird auch gesendet. 
Es erscheint im ioBroker aber es fehlen diverse Einträge in den Kanälen. Ist es überhaupt 
möglich Eigenbau Devices einzubinden?

Viele Grüße

Elmar

**Comment by foxriver76** [comment]
Ja ist möglich laufen in der gleichen Instanz erfolgreich Geräte? Was genau fehlt? Screenshot könnte mir helfen das Problem zu verstehen.

**Comment by elmarfaber** [comment]
Ja da laufen drei HomeMatic Geräte problemlos, hier ein Screenshot:
![grafik](https://user-images.githubusercontent.com/37933819/77252117-80aa8b80-6c52-11ea-8837-5c95e50f1105.png)
Das Device JPCAPM0000 Sollte unter Channel 1 und 2 Temperature und Humidity anzeigen

**Comment by foxriver76** [comment]
Wie ist denn die Geraetebezeichnung? Bzw kam beim erstmaligen hinzufügen im Adapter `send this info to developer..`? Da sieht man dann was die CCU über die XML-rpc bereitstellt. Grundsätzlich haben Leute Eigenbau Devices mit dem Adapter angebunden.

**Comment by elmarfaber** [comment]
Also es kam keine Frage "send...". Die Gerätebezeichnung ist HB-UNI-Sen-CAP-MOIST. Ich habe als erstes die xml Datei in Homegear mit homegear -o ... konvertiert, dann zu den Devices hinzugefügt. Im ioBroker habe ich dann (nachdem das Device nicht korrekt angezeigt wurde den Adapter deinstalliert, unter Objects alles gelöscht und den Adapter wieder installiert. Das Device wurde aber wieder falsch angezeigt. Unter "hm-rpc.meta" wird auch ein Device HB-UNI-Sen-CAP-MOIST angezeigt

**Comment by foxriver76** [comment]
Ja in den hinterlegten Daten gibt es auch nur Operating voltage, aber wir können mal schauen was deine api tatsächlich ausspuckt. Vielleicht wurden falsche Daten hinterlegt .. 

Kann man mittels js adapter z. B. herausfinden (instanz und Geräte Id austauschen): 

```javascript
sendTo('hm-rpc.1', 'getParamsetDescription', {ID: '000453D77B9EDF:1', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});
```

Hm was hat es denn mit dem Temp Sensor unten drunter auf sich? Scheint ja auch ein Eigenbau zu sein und scheint zu funktionieren?

**Comment by elmarfaber** [comment]
js Adapter habe ich installiert aber wie kann ich da Befehle absetzen? Gibt es da eine Kommandozeile oder so was? Ja das sind Temperatursensoren, die sind aber mit Temperatursensoren von HomeMatic nachgebaut und keine Eigenentwicklungen.

**Comment by elmarfaber** [comment]
`javascript.0 (12661) script.js.Growing_Room.Test: {"result":{"CONFIG_PENDING":{"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":4,"TYPE":"BOOL","UNIT":""},"DEVICE_IN_BOOTLOADER":{"FLAGS":9,"ID":"DEVICE_IN_BOOTLOADER","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":3,"TYPE":"BOOL","UNIT":""},"LOWBAT":{"CONTROL":"NONE","FLAGS":9,"ID":"LOWBAT","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":5,"TYPE":"BOOL","UNIT":""},"RSSI_DEVICE":{"FLAGS":1,"ID":"RSSI_DEVICE","MAX":2147483647,"MIN":-2147483648,"OPERATIONS":5,"TAB_ORDER":6,"TYPE":"INTEGER","UNIT":""},"RSSI_PEER":{"FLAGS":1,"ID":"RSSI_PEER","MAX":2147483647,"MIN":-2147483648,"OPERATIONS":5,"TAB_ORDER":7,"TYPE":"INTEGER","UNIT":""},"STICKY_UNREACH":{"FLAGS":25,"ID":"STICKY_UNREACH","MAX":true,"MIN":false,"OPERATIONS":7,"TAB_ORDER":2,"TYPE":"BOOL","UNIT":""},"UNREACH":{"FLAGS":9,"ID":"UNREACH","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":1,"TYPE":"BOOL","UNIT":""},"UPDATE_PENDING":{"FLAGS":9,"ID":"UPDATE_PENDING","MAX":true,"MIN":false,"OPERATIONS":5,"TAB_ORDER":0,"TYPE":"BOOL","UNIT":""}},"error":null}
`

**Comment by foxriver76** [comment]
Was hast du jetzt genau ausgeführt?

**Comment by elmarfaber** [comment]
Ich habe das Script 
sendTo('hm-rpc.0', 'getParamsetDescription', {ID: 'JPCAPM0000:0', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});
gestartet und das war die Ausgabe

**Comment by elmarfaber** [comment]
Mir ist gerade aufgefallen, dass im Log die Nachrichten nicht angezeigt werden...
Das sendet das Device (Ausgabe Serielle Schnittstelle):
```
<- 0E 14 84 53 F31100 FDEFEF 00 41 C2 42 4D  - 13664
+Analog     (#1): 523
+Battery      V : 175
+Humidity (#1) %: 75
<- 0E 1B 84 53 F31100 FDEFEF 00 41 AF 42 4B  - 19017
+Analog     (#1): 515
+Battery      V : 175
+Humidity (#1) %: 77
<- 0E 1C 84 53 F31100 FDEFEF 00 41 AF 42 4D  - 19652
+Analog     (#1): 532
+Battery      V : 175
+Humidity (#1) %: 73
<- 0E 1D 84 53 F31100 FDEFEF 00 41 AF 42 49  - 20289
+Analog     (#1): 516
+Battery      V : 175
+Humidity (#1) %: 77
<- 0E 1E 84 53 F31100 FDEFEF 00 41 AF 42 4D  - 20924
```

Aber im ioBroker werden keine Nachrichten vom hm-rpc Adapter angezeigt

**Comment by foxriver76** [comment]
> Ich habe das Script
> sendTo('hm-rpc.0', 'getParamsetDescription', {ID: 'JPCAPM0000:0', paramType: 'VALUES'}, res => {
> log(JSON.stringify(res));
> });
> gestartet und das war die Ausgabe

 Bitte mal :1 und :2 statt :0 denke der 0 Kanal passt.

**Comment by foxriver76** [comment]
> Mir ist gerade aufgefallen, dass im Log die Nachrichten nicht angezeigt werden...
> Das sendet das Device (Ausgabe Serielle Schnittstelle):
> 
> ```
> <- 0E 14 84 53 F31100 FDEFEF 00 41 C2 42 4D  - 13664
> +Analog     (#1): 523
> +Battery      V : 175
> +Humidity (#1) %: 75
> <- 0E 1B 84 53 F31100 FDEFEF 00 41 AF 42 4B  - 19017
> +Analog     (#1): 515
> +Battery      V : 175
> +Humidity (#1) %: 77
> <- 0E 1C 84 53 F31100 FDEFEF 00 41 AF 42 4D  - 19652
> +Analog     (#1): 532
> +Battery      V : 175
> +Humidity (#1) %: 73
> <- 0E 1D 84 53 F31100 FDEFEF 00 41 AF 42 49  - 20289
> +Analog     (#1): 516
> +Battery      V : 175
> +Humidity (#1) %: 77
> <- 0E 1E 84 53 F31100 FDEFEF 00 41 AF 42 4D  - 20924
> ```
> 
> Aber im ioBroker werden keine Nachrichten vom hm-rpc Adapter angezeigt

Und der Adapter steht auf Debug? Dann ist anzunehmen, dass die XML rpc Schnittstelle nichts sendet

**Comment by elmarfaber** [comment]
Ja der steht auf debug, also wird zwar das neue Device geladen aber die Nachrichten werden nicht gesendet, da werde ich morgen mal im homegear forum weitersuchen. 
Vielen Dank für die Hilfe !!!
