### ISSUE TITLE
Adapter hm-rpc verliert Konfig bei Update

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.hm-rpc#25]
Nach jeden Update des Adapters hm-rpc verliert diese sene "Ziel-Konfig" (rfd oder cuxd).

Vor dem Update zeigt hm-rpc.0 auf rfd und hm-rpc.1 auf cuxd.
Nach dem Update zeigen beide Instanzen auf cuxd.

Der Adapter hm-rega hat dann natürlich auch Probleme und holt quasi nichts mehr ab.

**Comment by GermanBluefox** [comment]
Muss mit js-controller 0.9.0 behoben werden.
