### ISSUE TITLE
Synchronize objects (once) does not work 

### ISSUE THREAD

**Issue by D0ctorSnuggles** [ioBroker/ioBroker.hm-rpc#251]
**Describe the bug**
"Synchronize objects (once)" does not list (and therefore also does not import) devices from my CCU3.

Firewall on the CCU3 has also been disabled even inc ase that there are no errors pointing on connection topics.

**To Reproduce**
1. Deleting ALL instances hm-rpc.x
2. Installing a new instance hm-rpc.0 (see screenshots no.1 & no. 2)
3. configuring this new instance
4. Starting instance
5. Checking Log => just connected but "ListDevices" has not been executed (see screenshot no.3)

**Expected behavior**
"ListDevices" and importing those devices should have been executed (see screenshot no. 4).

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.
no. 1
![grafik](https://user-images.githubusercontent.com/65213586/81644104-68bbe080-9427-11ea-988f-d97ca854888a.png)

no. 2
![grafik](https://user-images.githubusercontent.com/65213586/81644129-740f0c00-9427-11ea-88ca-811640c8ee43.png)

no. 3
![grafik](https://user-images.githubusercontent.com/65213586/81644399-eed82700-9427-11ea-8e0d-041fa0fc2613.png)

no. 4
![grafik](https://user-images.githubusercontent.com/65213586/81644840-cbfa4280-9428-11ea-918b-7a9e9a7d2d9c.png)

**Versions:**
 - hm-rpc version: 1.14.2
 - hm-rega version: not installed (is this adapter needed for import? did not find any information on this)
 - JS-Controller version: 3.1.4
 - Node version: 10.20.1
 - Operating system: Linux
 - CCU model: CCU3
 - CCU firmware: 3.51.6

**Additional context**
Has been verified on my second ioBroker environment using the same CCU.
Also using HomematicIP Daemon for HMIP-Devices did not work.
Changing protocoll from XML-RPC to BIN-RPC (without https) did not help.
Deleting all hm-rpc instances and lokoing for existing hm-rpc processes (ps-a) didi not lead to a problem...no hm-rpc processes were found.

All needed informatino will be provisioned in order to support resolving my issue :)
Thanx in advance!!

**Comment by foxriver76** [comment]
iobroker host is running at 192.168.81.1?

**Comment by D0ctorSnuggles** [comment]
192.168.81.1 is my router; iobroker is running on 192.168.81.63 (see configuration _adapter_)

**Comment by foxriver76** [comment]
But you put your router as callback address, thus your CCU will send all answers to your router instead of your host.

**Comment by D0ctorSnuggles** [comment]
that's what I understoodCallback adapter is the routing gateway (from a networking pov).
I just changed it to my iobroker IP but still no change :(

**Comment by D0ctorSnuggles** [comment]
I just added a new instance using the "callback adapter" as decribed by you and...it works. Thank you very much!! therefore: closed :)
