### ISSUE TITLE
HM-OU-CFM-TW Funk-Gong no RGB LED implementation

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.hm-rpc#253]
Product: https://de.elv.com/elv-homematic-komplettbausatz-mp3-funk-gong-mit-signalleuchte-hm-ou-cfm-tw-fuer-smart-home-hausautomation-141971

**Describe the bug**
It isn't possible to choose the color of the led in the ioBroker Adapter. There is no data point. In a programm in the ccu3 you can choose the color via. canalaction.

https://ibb.co/VjHJDhT

**Versions:**
 - hm-rpc version: 1.14.2
 - hm-rega version: 2.5.5
 - JS-Controller version: 3.1.4
 - Node version: 12.17.0
 - Operating system: debian latest
 - CCU model: raspberrymatic
 - CCU firmware: 3.51.6.20200420

**Comment by foxriver76** [comment]
Idk? I also don’t see a screenshot of the object structure of the device.

**Comment by DcFamas** [comment]
> 
> 
> Idk? I also don’t see a screenshot of the object structure of the device.
> 
> All parameters which are available via the xml-rpc API are created. If no parameter is there which represents this state, then either the instance is wrongly configured (but then most of the other dps won't be there too) or it's not provided over the API.
> 
> Unfortunately for non-HMIP devices I haven't found a technical documentation yet which clearly states which parameters are available via the API.

https://ibb.co/VvPFCHr

**Comment by foxriver76** [comment]
What do you mean by Admin of iobroker told you to open up the issue? Probably you mean the logging with the Paramset description. There we can find all Paramus which are available over the api.

It could also be possible that it’s configurable in the Master Params, for this you could use a script in combination with the adapter like in the examples https://github.com/ioBroker/ioBroker.hm-rpc#custom-commands

P. S. You can upload images directly on GitHub comments no need for an external host

**Comment by DcFamas** [comment]
I was on the ioBroker teamspeak server and an administration checked my installation first.
But he haven't told me how I can check what kind of parameters are available over the api.

**Comment by foxriver76** [comment]
Unter hm-rpc.meta sollte ein Channel sein der hm-ou-cmd-tw heißt und darin sollten für jeden Channel ein Objekt sein. Wenn du hinten auf den Stift drückst und dann raw, sind dort alle Parameter aufgeführt, du kannst sie ja mal hier posten. Aber wenn sie wie gesagt aufgeführt sind dann wollte sie der Adapter auch in Form von States angelegt haben.

**Comment by foxriver76** [comment]
Schau mal hier: https://homematic-forum.de/forum/viewtopic.php?f=19&t=34434&sid=80076124e15729303446c6b5a0d2cce7&start=10

Es geht wohl über Submit mit zb folgender Struktur `1,1,10800,6`

**Comment by DcFamas** [comment]
`{
  "_id": "hm-rpc.meta.VALUES.HM-OU-CFM-TW.SIGNAL_LED.4",
  "type": "meta",
  "meta": {
    "adapter": "hm-rpc",
    "type": "paramsetDescription"
  },
  "common": {},
  "native": {
    "INHIBIT": {
      "CONTROL": "NONE",
      "DEFAULT": false,
      "FLAGS": 1,
      "ID": "INHIBIT",
      "MAX": true,
      "MIN": false,
      "OPERATIONS": 7,
      "TAB_ORDER": 2,
      "TYPE": "BOOL",
      "UNIT": ""
    },
    "INSTALL_TEST": {
      "DEFAULT": false,
      "FLAGS": 3,
      "ID": "INSTALL_TEST",
      "MAX": true,
      "MIN": false,
      "OPERATIONS": 2,
      "TAB_ORDER": 4,
      "TYPE": "ACTION",
      "UNIT": ""
    },
    "ON_TIME": {
      "CONTROL": "NONE",
      "DEFAULT": 0,
      "FLAGS": 1,
      "ID": "ON_TIME",
      "MAX": 85825945.5,
      "MIN": 0,
      "OPERATIONS": 2,
      "TAB_ORDER": 1,
      "TYPE": "FLOAT",
      "UNIT": "s"
    },
    "STATE": {
      "CONTROL": "SWITCH.STATE",
      "DEFAULT": false,
      "FLAGS": 1,
      "ID": "STATE",
      "MAX": true,
      "MIN": false,
      "OPERATIONS": 7,
      "TAB_ORDER": 0,
      "TYPE": "BOOL",
      "UNIT": ""
    },
    "SUBMIT": {
      "CONTROL": "NONE",
      "DEFAULT": "",
      "FLAGS": 1,
      "ID": "SUBMIT",
      "MAX": "",
      "MIN": "",
      "OPERATIONS": 2,
      "TAB_ORDER": 3,
      "TYPE": "STRING",
      "UNIT": ""
    },
    "WORKING": {
      "DEFAULT": false,
      "FLAGS": 3,
      "ID": "WORKING",
      "MAX": true,
      "MIN": false,
      "OPERATIONS": 5,
      "TAB_ORDER": 5,
      "TYPE": "BOOL",
      "UNIT": ""
    }
  },
  "from": "system.adapter.hm-rpc.1",
  "user": "system.user.admin",
  "ts": 1588588893403,
  "acl": {
    "object": 1638
  }
}`

Das ist der Channel der LED. Der Administrator sagte mir halt ich solle das Issue öffnen weil es wohl sehr einfach für dich wäre das anzupassen.

In der Homematic Oberfläche habe ich an erster Stelle auch nur diese zwei Möglichkeiten, also "klingeln lassen", oder "led rot". Die Farben musste er extra über ein Programm > Kanalaktion einstellen.

So sieht es einfach unter Geräte aus:
![grafik](https://user-images.githubusercontent.com/35306967/83605232-d7e4aa80-a577-11ea-85ed-3031a1747349.png)

& genau das sind dann die einzigen Funktionen die ich im ioBroker auch nutzen kann. Es wäre nun aber auch toll die RGB LED komplett nutzen zu können.

Das werde ich wahrscheinlich auch über deinen oben genannten Weg hinbekommen. 

> Schau mal hier: https://homematic-forum.de/forum/viewtopic.php?f=19&t=34434&sid=80076124e15729303446c6b5a0d2cce7&start=10
> 
> Es geht wohl über Submit mit zb folgender Struktur 1,1,10800,6

Das hatte er gestern auch probiert. Zwar funktioniert der Befehl "1,1,10800,6" (Türgong, plus rote  (lang, kurz, kurz, kurz) LED) aber alle anderen Farben irgendwie dennoch nicht. 

Wenn ich das Programm direkt in der CCU ausführe:
Kanalauswahl: HM-OU-CFM-TW "seriennummer":1 sofort Kanalaktion auf 1,1,108000,50,0,0,0,0,0,0,0,0,0 
blinkt die LED entsprechend der Auswahl 1x gelb.
Kopiere ich nun diesen Befehl
1,1,108000,50,0,0,0,0,0,0,0,0,0

und füge ihn bei "submit" klingelt der Dong 1* und die LED blinkt rot wie oben beschrieben. Dasselbe passiert wenn ich nur 1,1,108000,50 einfüge.

Ich habe aber wie oben beschrieben auch kein Problem das Ganze über das Programm der CCU zu machen und ein virtual Device zu misbrauchen. Die Entscheidung ob wir das hier hinbekommen können liegt an dir ob du zur Zeit die Zeit dazu aufbringen kannst oder/und möchtest. Ich bin sowieso schon sehr dankbar für den Adapter! :)

Grüße

**Comment by foxriver76** [comment]
Naja hat nicht wirklich was mit Zeit und Lust zu tun, da das Design des Adapters es nicht vorsieht für jedes der x-hundert Homematic Geräte extra Logik im Adapter darstellen. Sondern lediglich mit der Schnittstelle kommuniziert wird. Zumal ist `SUBMIT` wohl der korrekte Datenpunkt und das Problem liegt evtl. an der API.

Daher die Frage: wenn du nur `1` in submit schreibst passiert das gleiche?

P.S. der Admin, der behauptet es wäre kein Problem, darf es gerne in Form eines PRs zur Verfügung stellen. ;-)

**Comment by DcFamas** [comment]
Hey Max,
ja er ging davon aus, dass es mittels api umgesetzt wurde seitens Homematic. Dementsprechend dachte er wahrscheinlich da fehlt einfach nur der Datenpunkt. Entsprechend dachte er es wäre "einfach". Da sind wir beide jetzt aber schlauer! :)

Bei einer einfachen `1` wird der Wert rot und nichts passiert.

Grüße
