### ISSUE TITLE
CUXD State-Monitor / Transform Devices werden nicht korrekt übertragen

### ISSUE THREAD

**Issue by volkerverkamp** [ioBroker/ioBroker.hm-rpc#255]
**Versions:**
 - hm-rpc version: v1.14.6
 - hm-rega version: 2.6.9
 - JS-Controller version: 3.1.4
 - Node version: v12.18.0
 - Operating system: Raspbian Buster
 - CCU model: piVCCU3 
 - CCU firmware: 3.51.6

Der Adapter (v1.14.6) überträgt State-Monitor und Transform Devices von CUXD nicht korrekt bzw. legt diese nicht richtig in der Objektstruktur an:

1) State Monitor Devices
Die Datenpunkte vom Kanal 3 (mit frei definierbaren Intervallen) von CUXD State-Monitor-Devices (siehe CUXD-Doku Abschnitt 5.7.2) werden nicht korrekt übertragen bzw sind leer. 

Werte aus dem WebUi:
![image](https://user-images.githubusercontent.com/51383556/83955285-955def00-a851-11ea-8cad-7e74cd57534e.png)

Der gleiche Kanal in iobroker:
![image](https://user-images.githubusercontent.com/51383556/83955312-dc4be480-a851-11ea-87cb-34ffbb4ab458.png)

Die Kanäle 1 und 2 (1h und 24h) werden korrekt übertragen.

2) Transform-Device (CUXD-Doku 5.7.1)
Ich habe mehrere Transform-Devices vom Typ "TEMPERATURE". Ich nutze diese nur zur Berechnung eines gleitenden Mittelwerts, deswegen sind die Stützpunkte in den Einstellungen leer:

![image](https://user-images.githubusercontent.com/51383556/83955214-be31b480-a850-11ea-9fd9-247f0cd7a20c.png)

In ioBroker werden die Transform-Devices fälschlicherweise als STATE-Devices angezeigt und die entsprechenden Datenpunkte sind leer:

![image](https://user-images.githubusercontent.com/51383556/83955253-149ef300-a851-11ea-9438-c02817b16431.png)

**Comment by foxriver76** [comment]
du kannst mal die meta Daten des Objektes posten siehe `hm-rpc.meta..` schätzungsweise werden die Paramset so von der xml api geliefert, evtl mal noch die Betroffenen Metas löschen und das Gerät in iob löschen und neu anlegen lassen. Vermute das Problem aber auf ccu Seite. Ähnliches gilt für den Channel 3, die Datenpunkte werden bei instanzstart mittels Rega Skript gelesen, am besten mal mit einem Rega Skript auf ccu gegen checken ob da was anderes raus kommt, ansonsten können wir nur das anzeigen was geliefert wird.

**Comment by volkerverkamp** [comment]
Wie finde ich denn die zugehörigen Meta-Einträge? Die Metas sind ja nach Gerätemodellen unterschieden, die sind aber ja bei CUXD-Geräten nur rein "virtuell" und können auch geändert werden.

**Comment by foxriver76** [comment]
Evtl ist auch dies das Problem für deinen Punkt 2. Das CuxD Gerät hat ja trotzdem eine Gerätebezeichnung nehme ich an? Für diese müsste es einen DP geben unter `hm-rpc.meta`. Probiere derzeit sowieso von dieser Meta Daten Strategie weg zu gehen, da sich Paramsets für dasselbe Device auch durch FW Updates ändern können. Evtl ist ja bei CuxD tatsächlich die Gerätebezeichnung gleich aber das Paramset eigentlich verschieden und der Meta Daten Cache macht es somit kaputt. Aber durch löschen der Meta Daten und gerät sollten wir das herausfinden können.

**Comment by volkerverkamp** [comment]
Kann ich gefahrlos den ganzen hm-rpc.meta Knoten löschen?

**Comment by foxriver76** [comment]
Jop, ich tendiere dazu in Zukunft auf diesen nicht mehr zurückzugreifen. Er wird dann sowieso neu angelegt wenn du ihn löscht und ein neues Gerät dazu kommt

**Comment by volkerverkamp** [comment]
Das Skript gibt - im Gegensatz zu iobroker die korrekten (=zum WebUI identischen) Werte aus:
![image](https://user-images.githubusercontent.com/51383556/84358968-39d09000-abc8-11ea-968c-001994030013.png)

iobroker:
![image](https://user-images.githubusercontent.com/51383556/84359033-4e148d00-abc8-11ea-9b31-d94484919301.png)

Die neue Version (ohne Meta-Cache) ist bereits installiert.

**Comment by foxriver76** [comment]
Und beim Neustart von hm-rega werden die Werte wieder falsch geschrieben oder werden sie gar nicht geschrieben?

**Comment by foxriver76** [comment]
Ach so die Datenpunkte auf der CCU sind aber als die im Adapter angelegten TIME_ON_HHH wurde vom Adapter ja nicht angelegt. Sonst würde er es vermutlich korrekt setzen.

**Comment by foxriver76** [comment]
Bzw führe mal folgendes als Javascript Skript aus via Skript Engine Adapter (`hm-rpc.1` durch die CuxD Instanz ersetzen):

```javascript
sendTo('hm-rpc.1', 'getParamsetDescription', {ID: 'CUX:39001002:3', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});
```

Ergebnis bitte mal zeigen.

**Comment by volkerverkamp** [comment]
Nach kleiner Korrektur Deines Skripts (Geräte-ID):
`sendTo('hm-rpc.2', 'getParamsetDescription', {ID: 'CUX9001001:3', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});`

Sieht die Ausgabe folgendermaßen aus:

`11.6.2020, 11:26:27.927	[info ]: javascript.0 (17663) script.js.common.testCUXD: {"result":{"TIME_ON_HHH":{"ID":"TIME_ON_HHH","UNIT":"min","TAB_ORDER":0,"OPERATIONS":5,"FLAGS":1,"TYPE":"FLOAT","MIN":0,"MAX":10080,"DEFAULT":0},"TIME_OFF_HHH":{"ID":"TIME_OFF_HHH","UNIT":"min","TAB_ORDER":1,"OPERATIONS":5,"FLAGS":1,"TYPE":"FLOAT","MIN":0,"MAX":10080,"DEFAULT":0},"SWITCH_HHH":{"ID":"SWITCH_HHH","UNIT":"","TAB_ORDER":2,"OPERATIONS":5,"FLAGS":1,"TYPE":"FLOAT","MIN":0,"MAX":999999,"DEFAULT":0},"PERCENT_ON_HHH":{"ID":"PERCENT_ON_HHH","UNIT":"%","TAB_ORDER":3,"OPERATIONS":5,"FLAGS":1,"TYPE":"INTEGER","MIN":0,"MAX":100,"DEFAULT":0},"INSTALL_TEST":{"ID":"INSTALL_TEST","UNIT":"","TAB_ORDER":4,"OPERATIONS":2,"FLAGS":3,"TYPE":"ACTION","MIN":false,"MAX":true,"DEFAULT":false}},"error":null}`

**Comment by foxriver76** [comment]
Ok das passt, bitte hm-rpc stoppen gerät löschen und wieder starten. Dann sollte es hoffentlich korrekt angelegt werden.

**Comment by volkerverkamp** [comment]
Hat leider nicht funktioniert:
![image](https://user-images.githubusercontent.com/51383556/84428579-007b3d00-ac27-11ea-8ae8-aadb63cd3c02.png)

**Comment by foxriver76** [comment]
Ich schaue nochmal, gibt evtl noch im Code zur Laufzeit Caching nach Device Typ.

**Comment by volkerverkamp** [comment]
Hab ich gemacht - Benennung der DP ist korrekt, aber jetzt sind Kanal 2 und 3 leer/null:
![image](https://user-images.githubusercontent.com/51383556/84448585-61b50780-ac4b-11ea-8ec6-028674e5babb.png)

**Comment by foxriver76** [comment]
Starte mal Rega neu. Sind die default Werte die bei Objekt Erstellung reingeschrieben werden. Wird erst bei Änderung der Werte durch hm rpc gepushed oder alles gepolt bei Rega Neustart

**Comment by volkerverkamp** [comment]
Jetzt scheinen alle Werte (Kanal 1-3) da zu sein, danke!!! Ich melde mich, falls noch was fehlen sollte  ;-)

**Comment by foxriver76** [comment]
Top, haben wir’s doch geschafft. 👍
