### ISSUE TITLE
Incomplete status results for Sensor/Actor Discovery

### ISSUE THREAD

**Issue by deeprain279** [ioBroker/ioBroker.hm-rpc#257]
Hello,

I'm currently setting up my complete new ioBroker with connection to my HomeMatic CCU.
The connection and device discovery in general is working as expected, but I'm encountering the following issue:
For some sensors/actors from homematic, I get proper channel as well as a proper channel status information (Screenshot 1). But for others sensors/actors, I only get the channel, but no or incomplete associated status information (Screenshot 2/3).

I encountered this behavior for different sensors/actors types, but also for identical ones: for one I receive a complete result, but for the other only channel without status. It also show up for basically all sensor,actor types.

In the screenshots there are three actors from the same type "Funk-Schaltaktor mit Leistungsmessung, Hutschienenmontage"

I already tested without any firewall/security applied in the CCU and I already restarted the CCU and did the adapter setup several times. For the latter, everytime with different results, i.e. one sensor/actor previously complete now with only channel and vice versa.

**To Reproduce**
Basic Adapter setup and execute a discovery, initialization job.

**Expected behavior**
All sensors,actors with complete channel and status informationen.

Screenshots
![Bildschirmfoto 2020-07-10 um 14 34 51](https://user-images.githubusercontent.com/63447514/87156112-71605400-c2bc-11ea-97f7-839d3987e910.png)
![Bildschirmfoto 2020-07-10 um 14 34 59](https://user-images.githubusercontent.com/63447514/87156129-77563500-c2bc-11ea-9f8d-70d8e0c2c512.png)
![Bildschirmfoto 2020-07-10 um 14 35 05](https://user-images.githubusercontent.com/63447514/87156140-7ae9bc00-c2bc-11ea-8465-81557ab3a4f1.png)

**Versions:**

- hm-rpc version: v1.14.13
- JS-Controller version: v3.1.6
- Node version: v12.18.2
- Operating system: Linux
- CCU model: RaspberryMatic CCU
- CCU firmware: 3.51.6.20200621

**Comment by foxriver76** [comment]
Strg + R könnte helfen ansonsten bitte zuerst ein Forum Thread aufmachen, ähnliche Geschichten wurden schon sehr oft durchgekaut. Falls beides nicht hilft, gerne wieder hier melden.
