### ISSUE TITLE
LOWBAT Anzeige des Heizungsreglers HM-CC-RT-DN funktioniert nicht

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.hm-rpc#258]
Der LOWBAT Datenpunkt hm-rpc.0.<identifier>.0.LOWBAT signalisiert den Batteriezustand nicht.
Workaround: Im Datenpunkt hm-rpc.0.<identifier>.4.FAULT_REPORTING wird schwacher Batteriezustand neben anderen Fehlern angezeigt.

Es wäre wünschenswert, wenn LOWBAT einheitlich angezeigt würde.

Fehler seit ca. 3,5 Jahren vorhanden.

**Versions:**
 - hm-rpc version: 1.14.12 (alle Versionen)
 - hm-rega version: 2.6.14 (alle Versionen)
 - JS-Controller version: (alle Versionen)
 - Node version: 8 - 12
 - Operating system: Debian
 - CCU model: PiVCC, Debmatic und CCU
 - CCU firmware: alle Versionen

**Comment by foxriver76** [comment]
Hast du die Lowbat Schwelle manuell verändert?

**Comment by Marty56** [comment]
Nein, ich habe nichts verändert. Muss jetzt aber immer umständlich in meinem Script für niedrige Batterien immer eine Sonderbehandlung für die Heizungsregeler implementieren. 
Praktisch wäre es, wenn einfach 0.LOWBAT eine niedrige Batterie signalisieren würde, wie für alle anderen Geräte auch.

**Comment by foxriver76** [comment]
Naja da kann der Adapter aber nichts machen, wenn Lowbat so von der API geliefert wird -> eq3 anhauen wenn da was kaputt ist. Und am besten vorher mal den dp auf der CCU direkt anschauen um den Adapter auszuschließen.

`LOWBAT_ALARM` nutzen, da brauchst keine Sonderbehandlung.. der DP wird explizit vom Rega Adapter hierfür erstellt, während Lowbat halt 1 zu 1 das ist was die CCU in diesem dp liefert.

**Comment by Marty56** [comment]
Danke für den Hinweis. Funktion war mir völlig unbekannt. 
Benutze den Adapter ja auch erst 3,5 Jahre :-)

LOWBAT_ALARM geht auf 1, wenn die Batteriespannung schwach ist. Ok.
Aber was soll der Wert 2 ACKNOWLEDGED?

**Comment by foxriver76** [comment]
Schau mal unter https://github.com/ioBroker/ioBroker.hm-rega#what-are-the-alarm-states-created-in-the-devices-object

**Comment by Marty56** [comment]
Danke. Dann hat LOWBAT_ALARM schon eine andere Funktion als LOWBAT.
Wenn ich eine neue Batterie einsetze und damit der LOWBAT false ist, bleibt, LOWBAT_ALARM dennoch gesetzt, solange bis per Script den Wert auf 2 setze, oder?

**Comment by foxriver76** [comment]
Soweit ich weiß, wird die Service Meldung automatisch bestätigt, wenn wieder eine ausreichend geladene Batterie eingelegt wird.
