### ISSUE TITLE
LOWBAT Datenpunkte in mehreren Kanälen vorhanden und inkonsistent 

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.hm-rpc#259]
1. Der LOWBAT Datenpunkt taucht bei einigen batteriebetriebenen HM Geräten in mehreren Kanälen auf. z.B. bei HM-Sec-RHS (Türdrehknopfsensor), HM-Sec-SC (Fensterkontakt magnetisch), HM-Sec-SCo (Fensterkontakt optisch), HM-Sec-SFA-SM(Außenalarm)

2. Beim HM-TC-IT-WM-W-EU (Thermostat) wird überflüssigerweise noch ein von der Namensgebung inkonsistenter Datenpunkt eingeführt hm-rpc.0.<identifier>.2.LOWBAT_REPORTING.

3. Beim HM-LC-Sw4-WM (4 fach Relais), HM-LC-Sw1-Pl-2 (Schaltaktor) und HM-LC-Sw2PBU-FM (Wandschalter) gibt es einen LOWBAT Datenpunkt, obwohl die Geräte überhaupt nicht mit Batterien betrieben werden können

Vermutlich sind diese Inkonsistenzen von den chaotischen Datenpunktdefinition der CCU geerbt. 
Es wäre schön, wenn sie beim Anlegen der iobroker Datenpunkt nicht mit übernommen würden.
Schwäche ist seit ca. 3,5 Jahren vorhanden.

Versions:

hm-rpc version: 1.14.12 (und alle Versionen)
hm-rega version: 2.6.14 (und alle Versionen)
JS-Controller version: (alle Versionen)
Node version: 8 - 12
Operating system: Debian
CCU model: PiVCC, Debmatic und CCU
CCU firmware: alle Versionen

**Comment by foxriver76** [comment]
Für die rfd Geräte gibt es leider keine Device Description mit der ich vergleichen könnte, allerdings ja korrekt, es wird das angelegt was die CCU liefert. Der Adapter betreibt keine Hexerei und dient hauptsächlich zum auslesen der tatsächlichen Daten. Ich verstehe auch nicht was das tatsächliche Problem ist, wenn ein nicht batteriebetriebenes Device diesen DP hat.. ja macht kein Sinn -> eq3 anhauen, jedoch im Endeffekt kein Problem. 

Ich als User erwarte dass die DPs angezeigt werden die es auch in der CCU gibt, eine Filterung durch den Adapter wird nicht statt finden.

**Comment by Marty56** [comment]
"Ich verstehe auch nicht was das tatsächliche Problem ist, wenn ein nicht batteriebetriebenes Device diesen DP hat".
-> Das ist kein Problem sondern nur ein bisschen sinnlos. Aber klar, dass ist nice to have.

"eine Filterung durch den Adapter wird nicht statt finden." Sehr schade. Mich hat das als ich mit ioBroker angefangen habe, etwas verwirrt.

Aber wenn das zu kompliziert ist, dann kann der Issue auch geschlossen werden.
