### ISSUE TITLE
Climacontrol Regulator

### ISSUE THREAD

**Issue by WeltenbummlerKA** [ioBroker/ioBroker.hm-rpc#262]
**Describe the bug**
I have 5 Climacontrol Regulators from Homematic. 4 of them get shown with the correct serial number like IEQxxxxxxx. My problem is that one isn't shown with the correct serial number. 
In Homebridge the device get listed correctly (see picture below) and in your adapter it shown a wrong serial number (see picture below).

**To Reproduce**

**Expected behavior**
Is there a possibility to change manually the serial number to the correct one?

**Screenshots & Logfiles**
![Bildschirmfoto 2020-07-29 um 04 56 45](https://user-images.githubusercontent.com/61679394/88751689-67fa3700-d158-11ea-97d7-b16ba58e14e3.png)
![Bildschirmfoto 2020-07-29 um 04 58 55](https://user-images.githubusercontent.com/61679394/88751695-6c265480-d158-11ea-9987-d5d17e50ca28.png)

**Versions:**
 - hm-rpc version: 1.14.15
 - hm-rega version: 2.6.14
 - JS-Controller version: <js-controller-version>
 - Node version: 12.18.3
 - Operating system: linux Raspberry Pi 3B
 - CCU model: CCU1
 - CCU firmware: 1.511

**Additional context**

**Comment by foxriver76** [comment]
Zeig mal die Ausgabe von (insofern die 0er Instanz korrekt ist):

```javascript
sendTo('hm-rpc.0', 'listDevices', {}, res => {
    log(JSON.stringify(res));
});
```
