### ISSUE TITLE
CUXD Werte werden verändert

### ISSUE THREAD

**Issue by Sandomor** [ioBroker/ioBroker.hm-rpc#263]
**Describe the bug**
Der Datenpunkt eines CUXD Devices (Wrapper Devices) hat auf der CCU (Raspberry Matic Vers 3.51.6.20200621) den Wert 90.7
und wird im iobroker mit 50.05 dargestellt. Dies trifft auf alle numerischen Datenpunkte zu: Min, Max, State, Median, Mean

Hier der Auszug aus dem Log von ioBroker:
hm-rpc.2.CUX9000001.1.STATE ==> UNIT: "%" (min: -99999, max: 99999) From "90.7" => "50.05"

**Versions:**
 - hm-rpc version: 1.14.15
 - hm-rega version: 2.6.14
 - Node version: 10.15.3
 - Operating system:  Linux - 
 - CCU model: raspberrymatic
 - CCU firmware: 3.51.6.20200621)

**Comment by foxriver76** [comment]
Zeig mal eines der betroffenen Objekte bitte

**Comment by Sandomor** [comment]
Hier das Objekt aus IOBroker:
`{
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1596623061745,
  "common": {
    "name": "Zisterne_%:1.STATE",
    "type": "number",
    "unit": "%",
    "role": "state",
    "def": 0,
    "min": -99999,
    "max": 99999,
    "read": true,
    "write": false
  },
  "native": {
    "ID": "STATE",
    "UNIT": "%",
    "TYPE": "FLOAT",
    "TAB_ORDER": 0,
    "OPERATIONS": 5,
    "FLAGS": 1,
    "MIN": -99999,
    "MAX": 99999,
    "DEFAULT": 0
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.2.CUX9000001.1.STATE",
  "type": "state"
}`

**Comment by Sandomor** [comment]
![temp_iob](https://user-images.githubusercontent.com/47891212/89402844-be96e080-d717-11ea-848d-e565df31cd68.png)
![temp_ccu](https://user-images.githubusercontent.com/47891212/89402846-bf2f7700-d717-11ea-99e7-f6ec90bbd96d.png)

**Comment by Sandomor** [comment]
Was ich in der Zwischenzeit mal gemacht habe:

hm-rpc.2 gestoppt - Das Device in IOB gelöscht - und hm-rpc2 wieder gestartet (mit Neueinlesen der Datenpunkte)

**Comment by Sandomor** [comment]
Hier noch der Auszug aus dem Log

<
hm-rpc.2	2020-08-05 12:39:08.622	silly	(11655) States user redis pmessage hm-rpc.2.*/hm-rpc.2.CUX9000001.1.STATE:{"val":50.05,"ack":true,"ts":1596623948620,"q":0,"from":"system.adapter.hm-rpc.2","user":"system.user.admin","lc":159662306573
hm-rpc.2	2020-08-05 12:39:08.619	debug	(11655) hm-rpc.2.CUX9000001.1.STATE ==> UNIT: "%" (min: -99999, max: 99999) From "90.5" => "50.05"
hm-rpc.2	2020-08-05 12:39:08.619	debug	(11655) binrpc <- event ["CUxD","CUX9000001:1","STATE",90.5]
hm-rpc.2	2020-08-05 12:39:08.619	debug	(11655) bin multicall <event>: CUxD,CUX9000001:1,STATE,90.5
hm-rpc.2	2020-08-05 12:38:54.848	silly	(11655) States user redis pmessage hm-rpc.2.*/hm-rpc.2.CUX9000001.1.STATE:{"val":50.05,"ack":true,"ts":1596623934847,"q":0,"from":"system.adapter.hm-rpc.2","user":"system.user.admin","lc":159662306573
hm-rpc.2	2020-08-05 12:38:54.846	debug	(11655) hm-rpc.2.CUX9000001.1.STATE ==> UNIT: "%" (min: -99999, max: 99999) From "90.4" => "50.05"
hm-rpc.2	2020-08-05 12:38:54.846	debug	(11655) binrpc <- event ["CUxD","CUX9000001:1","STATE",90.4]
hm-rpc.2	2020-08-05 12:38:54.845	debug	(11655) bin multicall <event>: CUxD,CUX9000001:1,STATE,90.4
>

**Comment by foxriver76** [comment]
Danke. Schaue dann mal tiefer rein, wenn ich wieder im Lande bin, muss hier in etwa dran liegen

https://github.com/ioBroker/ioBroker.hm-rpc/blob/91e3bfda67f892a3d42f26a82a9bcc5eb8a95453/main.js#L1094

**Comment by Sandomor** [comment]
danke...

**Comment by foxriver76** [comment]
Ah.. warum eigentlich min: -9999 und Max: 9999? das macht eigentlich gar kein Sinn, ist doch ein prozentualer Wert zwischen 0 und 100.

**Comment by Sandomor** [comment]
das wird automatisch angelegt. Natürlich kommen nur Werte zw 0 und 100 hinein...

**Comment by foxriver76** [comment]
Hm was der Adapter dort "eigentlich" korrekterweise tut ist, den Prozentwert selbst zu berechnen. Und dann landet man mit den ca. 90 bei knapp über 50 %. Die Konvertierung wird für viele andere Geräte in dieser Form benötigt - ich weiß aktuell nicht warum CuxD sich da anders verhält.

**Comment by Sandomor** [comment]
ich habe nun nach der 3 teiligen IF Anweisung

if(param[0]==='CUxD') [
            val=params[3];
            };

eingefügt - jetzt stimmt mein Wert mal - danke für den schnellen Lösungsansatz

vll gibts ja in einem Update mal einen Bugfix

**Comment by foxriver76** [comment]
Muss auf jeden Fall an einer Stelle gefixt werden. Och schaue nächste Woche im Detail.

**Comment by Sandomor** [comment]
Danke für die Hilfen - Nach Studium des Codes in dem Bereich habe ich mal als schnellen Fix die Einheit im WrapperDevice auf der CCU weggegeben - jetzt stimmen die Werte...
