### ISSUE TITLE
1.14.16

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.hm-rpc#266]
**Describe the bug**
Error messages in log

**To Reproduce**
update to 1.14.16

**Expected behavior**

**Screenshots & Logfiles**
`

host.ioBroker | 2020-08-08 18:17:23.402 | info | Restart adapter system.adapter.hm-rpc.3 because enabled
-- | -- | -- | --
host.ioBroker | 2020-08-08 18:17:23.402 | error | instance system.adapter.hm-rpc.3 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2020-08-08 18:17:23.402 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:59:22)
host.ioBroker | 2020-08-08 18:17:23.401 | error | Caught by controller[0]: at Server.handleCall (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:82:24)
host.ioBroker | 2020-08-08 18:17:23.401 | error | Caught by controller[0]: at Server.EventEmitter.emit (domain.js:482:12)
host.ioBroker | 2020-08-08 18:17:23.401 | error | Caught by controller[0]: at Server.emit (events.js:315:20)
host.ioBroker | 2020-08-08 18:17:23.401 | error | Caught by controller[0]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:903:13)
host.ioBroker | 2020-08-08 18:17:23.400 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:83:41
host.ioBroker | 2020-08-08 18:17:23.400 | error | Caught by controller[0]: at Object.encodeResponse (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:52:25)
host.ioBroker | 2020-08-08 18:17:23.400 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:90:32)
host.ioBroker | 2020-08-08 18:17:23.400 | error | Caught by controller[0]: at Object.encodeArray (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:156:44)
host.ioBroker | 2020-08-08 18:17:23.399 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19)
host.ioBroker | 2020-08-08 18:17:23.395 | error | Caught by controller[0]: TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.3 | 2020-08-08 18:17:23.277 | info | (17722) Terminated (NO_ERROR): Without reason
hm-rpc.3 | 2020-08-08 18:17:23.276 | info | (17722) terminating
hm-rpc.3 | 2020-08-08 18:17:23.114 | info | (17722) Disconnected
hm-rpc.3 | 2020-08-08 18:17:23.094 | info | (17722) binrpc -> 192.168.2.25:8701/ init ["xmlrpc_bin://192.168.2.24:8701",""]
hm-rpc.3 | 2020-08-08 18:17:23.092 | error | (17722) TypeError: argument 'obj' must be type number, string, boolean or object at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19) at
hm-rpc.3 | 2020-08-08 18:17:23.091 | error | (17722) uncaught exception: argument 'obj' must be type number, string, boolean or object
unifi.0 | 2020-08-08 18:16:40.531 | info | (1266) Update done
hm-rpc.3 | 2020-08-08 18:15:53.059 | info | (17722) Connected
hm-rpc.3 | 2020-08-08 18:15:53.057 | info | (17722) new CUxD devices/channels after filter: 0
hm-rpc.3 | 2020-08-08 18:15:53.020 | info | (17722) binrpc -> listDevices 0
hm-rpc.3 | 2020-08-08 18:15:52.996 | info | (17722) binrpc client is trying to connect to 192.168.2.25:8701/ with ["xmlrpc_bin://192.168.2.24:8701","hm-rpc.3"]
hm-rpc.3 | 2020-08-08 18:15:52.994 | info | (17722) binrpc server is trying to listen on 192.168.2.24:8701
hm-rpc.3 | 2020-08-08 18:15:52.830 | info | (17722) starting. Version 1.14.16 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.18.2, js-controller: 3.1.6
host.ioBroker | 2020-08-08 18:15:49.976 | info | instance system.adapter.hm-rpc.3 started with pid 17722
unifi.0 | 2020-08-08 18:15:41.570 | info | (1266) Update done
host.ioBroker | 2020-08-08 18:15:19.918 | info | Restart adapter system.adapter.hm-rpc.3 because enabled
host.ioBroker | 2020-08-08 18:15:19.918 | error | instance system.adapter.hm-rpc.3 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:59:22)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at Server.handleCall (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:82:24)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at Server.EventEmitter.emit (domain.js:482:12)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at Server.emit (events.js:315:20)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:903:13)
host.ioBroker | 2020-08-08 18:15:19.917 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:83:41
host.ioBroker | 2020-08-08 18:15:19.916 | error | Caught by controller[0]: at Object.encodeResponse (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:52:25)
host.ioBroker | 2020-08-08 18:15:19.916 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:90:32)
host.ioBroker | 2020-08-08 18:15:19.916 | error | Caught by controller[0]: at Object.encodeArray (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:156:44)
host.ioBroker | 2020-08-08 18:15:19.916 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19)
host.ioBroker | 2020-08-08 18:15:19.915 | error | Caught by controller[0]: TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.3 | 2020-08-08 18:15:18.686 | info | (17559) Disconnected
hm-rpc.3 | 2020-08-08 18:15:18.669 | info | (17559) binrpc -> 192.168.2.25:8701/ init ["xmlrpc_bin://192.168.2.24:8701",""]
hm-rpc.3 | 2020-08-08 18:15:18.667 | error | (17559) TypeError: argument 'obj' must be type number, string, boolean or object at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19) at
hm-rpc.3 | 2020-08-08 18:15:18.665 | error | (17559) uncaught exception: argument 'obj' must be type number, string, boolean or object

`

**Versions:**
 - hm-rpc version: <1.14.16>
 - hm-rega version: <2.6.14>
 - JS-Controller version: <3.1.6>
 - Node version: <12.18.3>
 - Operating system: < debian>
 - CCU model: < raspberrymatic>
 - CCU firmware: < latest raspberrymatic>

**Comment by foxriver76** [comment]
Please try 1.14.17

**Comment by vr6syncro** [comment]
per katze von github installiert:

`

host.ioBroker | 2020-08-08 19:29:53.064 | error | instance system.adapter.hm-rpc.3 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:59:22)
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Server.handleCall (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:82:24)
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Server.EventEmitter.emit (domain.js:482:12)
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Server.emit (events.js:315:20)
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:903:13)
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:83:41
host.ioBroker | 2020-08-08 19:29:53.063 | error | Caught by controller[0]: at Object.encodeResponse (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:52:25)
host.ioBroker | 2020-08-08 19:29:53.062 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:90:32)
host.ioBroker | 2020-08-08 19:29:53.062 | error | Caught by controller[0]: at Object.encodeArray (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:156:44)
host.ioBroker | 2020-08-08 19:29:53.062 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19)
host.ioBroker | 2020-08-08 19:29:53.062 | error | Caught by controller[0]: TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.3 | 2020-08-08 19:29:52.820 | info | (20154) Terminated (NO_ERROR): Without reason
hm-rpc.3 | 2020-08-08 19:29:52.818 | info | (20154) terminating
hm-rpc.3 | 2020-08-08 19:29:52.770 | info | (20154) Disconnected
hm-rpc.3 | 2020-08-08 19:29:52.751 | info | (20154) binrpc -> 192.168.2.25:8701/ init ["xmlrpc_bin://192.168.2.24:8701",""]
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:59:22)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Server.handleCall (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:82:24)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Server.EventEmitter.emit (domain.js:482:12)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Server.emit (events.js:315:20)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:903:13)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:83:41
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Object.encodeResponse (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:52:25)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:90:32)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Object.encodeArray (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:156:44)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19)
hm-rpc.3 | 2020-08-08 19:29:52.750 | error | (20154) TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.3 | 2020-08-08 19:29:52.749 | error | (20154) uncaught exception: argument 'obj' must be type number, string, boolean or object
unifi.0 | 2020-08-08 19:29:31.798 | info | (1266) Update done

`

**Comment by foxriver76** [comment]
Upload gemacht?

**Comment by vr6syncro** [comment]
anscheinend nicht. bislang kein fehler mehr

**Comment by vr6syncro** [comment]
zu früh gefreut

`

host.ioBroker | 2020-08-08 20:13:03.047 | info | Restart adapter system.adapter.hm-rpc.3 because enabled
-- | -- | -- | --
host.ioBroker | 2020-08-08 20:13:03.047 | error | instance system.adapter.hm-rpc.3 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2020-08-08 20:13:03.046 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:59:22)
host.ioBroker | 2020-08-08 20:13:03.046 | error | Caught by controller[0]: at Server.handleCall (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:82:24)
host.ioBroker | 2020-08-08 20:13:03.046 | error | Caught by controller[0]: at Server.EventEmitter.emit (domain.js:482:12)
host.ioBroker | 2020-08-08 20:13:03.046 | error | Caught by controller[0]: at Server.emit (events.js:315:20)
host.ioBroker | 2020-08-08 20:13:03.046 | error | Caught by controller[0]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:903:13)
host.ioBroker | 2020-08-08 20:13:03.045 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:83:41
host.ioBroker | 2020-08-08 20:13:03.045 | error | Caught by controller[0]: at Object.encodeResponse (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:52:25)
host.ioBroker | 2020-08-08 20:13:03.045 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:90:32)
host.ioBroker | 2020-08-08 20:13:03.045 | error | Caught by controller[0]: at Object.encodeArray (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:156:44)
host.ioBroker | 2020-08-08 20:13:03.044 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19)
host.ioBroker | 2020-08-08 20:13:03.041 | error | Caught by controller[0]: TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.3 | 2020-08-08 20:13:02.872 | info | (21905) Terminated (NO_ERROR): Without reason
hm-rpc.3 | 2020-08-08 20:13:02.870 | info | (21905) terminating
hm-rpc.3 | 2020-08-08 20:13:02.781 | info | (21905) Disconnected
hm-rpc.3 | 2020-08-08 20:13:02.764 | info | (21905) binrpc -> 192.168.2.25:8701/ init ["xmlrpc_bin://192.168.2.24:8701",""]
hm-rpc.3 | 2020-08-08 20:13:02.763 | error | (21905) TypeError: argument 'obj' must be type number, string, boolean or object at Object.encodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:69:19) at
hm-rpc.3 | 2020-08-08 20:13:02.762 | error | (21905) uncaught exception: argument 'obj' must be type number, string, boolean or object

`

**Comment by foxriver76** [comment]
Ist ne CuxD Instanz oder?

**Comment by vr6syncro** [comment]
ja genau. hatte die gerade auch mal geupdatet aber das brauchte auch nichts. macht bei mir auch quasi nix. also habe nur dp info-connection und updated das wars

**Comment by foxriver76** [comment]
Hui, habs gefunden. Sollte nun wieder gehen.

**Comment by vr6syncro** [comment]
scheint weg zu sein. falls es nochmal auftreten sollte werde ich berichten
