### ISSUE TITLE
HmIP „Level“ from Blind actuator HmIP-FROLL does no longer use proper percent values

### ISSUE THREAD

**Issue by captaindork** [ioBroker/ioBroker.hm-rpc#267]
Hi,
Today I recognized that i cannot properly Control my blinds via iobroker, this might have happened because of an Adapter Update to .18 or because i deleted all my objects and let the adapter create them again.

Issue is, that i could control my blind actuator level datapoints (:4,:5,:6) with values from 0 to 100 usually. Now If i put 100, then blinds move to around 16% and the datapoint shows 0.16. I yet could not figure out a solution, also if i now work with float values from 0-1 it is not really clear to me when the blinds stop...

Maybe this is because of this native part and strange unit in the Screenshot?

Can we have this back as 0-100? As this also allowed easy integration to Siri and Alexa... Thanks a lot!
![112F9F6A-8F08-4B78-B48B-47138D06CE54](https://user-images.githubusercontent.com/28271030/89734378-1d33c580-da5c-11ea-9062-9369e2510aac.jpeg)

**Comment by foxriver76** [comment]
Da wurde was geändert, das ist nun die original Unit der CCU im native, habe selbst frolls und teste später mal.

**Comment by foxriver76** [comment]
Hm kann ich leider absolut nicht nachstellen bei mir, wie wurde installiert? Was zeigt das Log beim steuern? Wie wird gesteuert?

**Comment by captaindork** [comment]
Danke fürs nachstellen, ok wenn der native part nicht relevant ist passt das. Ich habe in der Vergangenheit auch nur im common-part korrigiert und es funktionierte.

Ich habe sämtliche meiner iobroker skripte gestoppt (Helferlein für Mapping in yahka, usw..., liefen so seit Jahren), die Objekte gelöscht, die Instanz neugestartet, logging auf debug und mal manuell in den Level-State geschrieben. 0 klappt -> 100 führt zu 0.16 -> 0 klappt -> 99 führte zu 0.44 -> 15 führte zu 15% und seitdem geht alles.... LOL

Kannst gerne schließen, sollte das zurückkommen, melde ich mich... DANKE!!!

**Comment by foxriver76** [comment]
Ok.. sehr komisch.. 

Wenn’s wieder kommt bitte wieder aufmachen.
