### ISSUE TITLE
Ping error: Error: XML-RPC fault

### ISSUE THREAD

**Issue by kleinerDrache** [ioBroker/ioBroker.hm-rpc#27]
Hallo ich nutze HOMEGEAR und den HM-CFG-USB2 Funktioniert auch ganz gut. Leider bekomme ich immer wieder einträge im log : 

Ping error: Error: XML-RPC fault: : Requested method not found.

und der Adapter disconectet verbindet sich aber neu.

Eingestellt im Adapter ist im moment XML-RPC . Stelle ich um auf BIN-RPC stürzt der Adapter ab und wird neu gestartet:

Logeinträge:

Restart adapter system.adapter.hm-rpc.0 because enabled
error	instance system.adapter.hm-rpc.0 terminated with code 6 (uncaught exception)
info	binrpc -> 192.168.0.99:2001 init ["xmlrpc_bin://192.168.0.99:3000",""]
info	binrpc -> 192.168.0.99:2001 init ["xmlrpc_bin://192.168.0.99:3000",""]
TypeError:	2016-07-20 23:38:44.970	error	at TCP.onread (net.js:536:20)
TypeError:	2016-07-20 23:38:44.970	error	at Socket.Readable.push (_stream_readable.js:111:10)
TypeError:	2016-07-20 23:38:44.970	error	at readableAddChunk (_stream_readable.js:153:18)
TypeError:	2016-07-20 23:38:44.970	error	at Socket.emit (events.js:169:7)
TypeError:	2016-07-20 23:38:44.970	error	at emitOne (events.js:77:13)
TypeError:	2016-07-20 23:38:44.970	error	at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
TypeError:	2016-07-20 23:38:44.970	error	at Object.Protocol.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
TypeError:	2016-07-20 23:38:44.970	error	at Object.Protocol.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
TypeError:	2016-07-20 23:38:44.970	error	at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
TypeError:	2016-07-20 23:38:44.970	error	at Object.Protocol.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:81)
TypeError:	2016-07-20 23:38:44.970	error	Cannot read property 'toString' of null
uncaught	2016-07-20 23:38:44.956	error	exception: Cannot read property 'toString' of null
info	Connected
info	binrpc client is trying to connect to 192.168.0.99:2001 with ["xmlrpc_bin://192.168.0.99:3000","hm-rpc.0"]
info	binrpc server is trying to listen on 192.168.0.99:3000
info	starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.hm-rpc

**Comment by Apollon77** [comment]
Irgendwie sieht das fpr mich mit dem Port 3000 irgendwie nach einem Konfigurationsfehler aus!

Bitte pack das mal ins iobroker Forum zuerst und falls echt ein Bug dann ins Jira.

Und schreib mal dazu wie der Adapter konfiguriert ist!

**Comment by kleinerDrache** [comment]
lag an Homegear das einfach keine Ping Methode kannte mit Version 6.5 ist Ping eingebaut
