### ISSUE TITLE
RPC Adapter 1.14.18 Problem mit Prozentwerten (HM IP BROLL)

### ISSUE THREAD

**Issue by surfer009** [ioBroker/ioBroker.hm-rpc#270]
Hallo,
in der RPC-Adapterversion 1.14.18 (vermutlich auch schon in der 1.14.16) gibt es ein Problem mit der Übernahme der %-Werte von den HM IP Rolladenaktoren (BROLL). Steht der Rolladen auf 50% wird der Kanal 3 - Punkt Level mit 0,5% beschrieben und nicht mit 50%. In der Version 1.14.15 funktioniert alles wieder.

IO-Broker-Forum: [https://forum.iobroker.net/topic/36007/problem-mit-broll-aktoren-behangh%C3%B6he-rpc-adapter](url)

Gruß surfer ;-)

**Comment by foxriver76** [comment]
Bitte mal das Objekt neu anlegen lassen und wenn das Problem immer noch besteht mir das Objekt zeigen.

**Comment by surfer009** [comment]
Habe die 1.14.19 installiert, Objekt neu angelegt und Rolladen gefahren. Nach kurzer Zeit kommen wieder solche Werte zustande und das Ganze funktioniert wieder nicht.

![2020-08-17 17_55_31-objects - ioBroker](https://user-images.githubusercontent.com/43878494/90417725-6d420600-e0b4-11ea-8805-f49a7a748a2a.jpg)

In diesem Fall muss ich über die Homematic eine neue Kalibrierung des Aktors vornehmen, damit es dann wieder funktioniert.

**Comment by foxriver76** [comment]
Zeig mal bitte das Objekt im iobroker, Objekte hinten auf den Stift und Tab Raw

**Comment by surfer009** [comment]
anbei der Screenshot
![RAW](https://user-images.githubusercontent.com/43878494/90422952-ef81f880-e0bb-11ea-8fb0-14599eacf8f4.jpg)

**Comment by foxriver76** [comment]
Ok er nimmt irgendwie das falsche Max.. kannst du mal den Adapter auf Debug stellen und dann per Schalter fahren?

Was hier geloggt wird wäre dann interessant 
https://github.com/ioBroker/ioBroker.hm-rpc/blob/bdd58ba59d12c8e5c78868846cf314114e9074e8/main.js#L1113

**Comment by surfer009** [comment]
Ich hoffe, ich habe das so richtig gemacht und du kannst damit etwas anfangen. Beim Fahren kamen auf jeden Fall auch wieder Dezimalwerte vor.

[DEBUG.txt](https://github.com/ioBroker/ioBroker.hm-rpc/files/5086110/DEBUG.txt)

**Comment by foxriver76** [comment]
Danke, ja z. B.
```
2020-08-17 20:17:52.403 - debug: hm-rpc.1 (7024) hm-rpc.1.....3.LEVEL ==> UNIT: "100%" (min: 0, max: 1) From "0.55" => "55.00000000000001"
```
