### ISSUE TITLE
No datapoint created by eQ-3 HmIP-STHO Temperatur- und Luftfeuchtesensor

### ISSUE THREAD

**Issue by Garbracht** [ioBroker/ioBroker.hm-rpc#272]
My new Temperatur- und Luftfeuchtesensor was connected to and recognized by my CCU3 well. Data can be seen in Homematic WebUI. 
IOBroker.hm-ppc is also finding and listing the device.  

![Bildschirmfoto 2020-08-26 um 21 28 34](https://user-images.githubusercontent.com/70289122/91348367-f1e30180-e7e3-11ea-872d-14b952f37afd.png)

Does one of you know this issue and tell me what went wrong?

**Comment by foxriver76** [comment]
What kind of device is it? Have you tried to reload the admin page? Do other devices of the adapter instance work properly?

**Comment by Garbracht** [comment]
This is the new Homematic IP temperature and humidity sensor for outdoor application. 

Admin page has been reloaded. 

Other devices work properly on IP instance. Non IP devices work also properly on separate instance.   

 

Von: Max Hauser <notifications@github.com> 
Gesendet: Mittwoch, 26. August 2020 22:07
An: ioBroker/ioBroker.hm-rpc <ioBroker.hm-rpc@noreply.github.com>
Cc: Clemens Garbracht <clemens@garbracht.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] No datapoint created by eQ-3 HmIP-STHO Temperatur- und Luftfeuchtesensor (#272)

 

What kind of device is it? Have you tried to reload the admin page? Do other devices of the adapter instance work properly?

**Comment by foxriver76** [comment]
> This is the new Homematic IP temperature and humidity sensor for outdoor application. 

HmIP-STHO?

**Comment by Garbracht** [comment]
Max, thank you for your reply. 

 

See the label of the device



Do you need additional information?    

 

 

Von: Max Hauser <notifications@github.com> 
Gesendet: Freitag, 28. August 2020 13:58
An: ioBroker/ioBroker.hm-rpc <ioBroker.hm-rpc@noreply.github.com>
Cc: Clemens Garbracht <clemens@garbracht.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] No datapoint created by eQ-3 HmIP-STHO Temperatur- und Luftfeuchtesensor (#272)

 

This is the new Homematic IP temperature and humidity sensor for outdoor application.

HmIP-STHO?

**Comment by foxriver76** [comment]
Okay so I have one successfully running in my installation. Could you delete the device in the ioBroker objects tab once and restart the adapter on debug log level? Then please provide the log.

**Comment by Garbracht** [comment]
Hope this will help. New object is not visible under hm-rpc.1 

 



 

 

 

Von: Max Hauser <notifications@github.com> 
Gesendet: Freitag, 28. August 2020 14:46
An: ioBroker/ioBroker.hm-rpc <ioBroker.hm-rpc@noreply.github.com>
Cc: Clemens Garbracht <clemens@garbracht.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] No datapoint created by eQ-3 HmIP-STHO Temperatur- und Luftfeuchtesensor (#272)

 

Okay so I have one successfully running in my installation. Could you delete the device in the ioBroker objects tab once and restart the adapter on debug log level? Then please provide the log.

**Comment by foxriver76** [comment]
No, I need the log

**Comment by Garbracht** [comment]
Hello Max, 

 

is this what you need? Hope that will help. 

 

Clemens 

 

 

Von: Max Hauser <notifications@github.com> 
Gesendet: Sonntag, 30. August 2020 11:05
An: ioBroker/ioBroker.hm-rpc <ioBroker.hm-rpc@noreply.github.com>
Cc: Clemens Garbracht <clemens@garbracht.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] No datapoint created by eQ-3 HmIP-STHO Temperatur- und Luftfeuchtesensor (#272)

 

No, I need the log

**Comment by foxriver76** [comment]
Hm maybe it’s due to the email response. It seems like there is something missing in you comment
