### ISSUE TITLE
No parameter sets other than 0 visible

### ISSUE THREAD

**Issue by David91919** [ioBroker/ioBroker.hm-rpc#275]
**Describe the bug**
Cannot retrieve sensor data from CCU, only parameter sets 0 are visible in objects

**To Reproduce**
1. Go to 'Objects'
2. Click on 'hm-rpc.0 > select HMIP device and open tree'
3. Only parameter 0 are visible and are filled correctly (low-Bat, sabotage etc.)
4. Parameter set 1-7 are not available

**Expected behavior**
Parameter set 1-7, containing the actual sensor data etc.

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

![hm rpc](https://user-images.githubusercontent.com/56155511/93565741-246bbe80-f98c-11ea-8959-0b8c6b21b063.png)

[rega log.txt](https://github.com/ioBroker/ioBroker.hm-rega/files/5243916/rega.log.txt)

**Versions:**
 - hm-rpc version: <1.14.15>
 - hm-rega version: <2.6.14>
 - JS-Controller version: <4.6.17>
 - Node version: <1.17.2>
 - Operating system: raspberrypi OS Buster
 - CCU model: piVCCU
 - CCU firmware: <3.51.6-41>

**Additional context**
Running ioBroker on OMV 5 in Docker (buanet:iobroker:latest).
Tried rebooting, restarting. Updating. Stopping adapter, removing completely from system and deleting all objects.
CCU has all ports completely open

**Comment by foxriver76** [comment]
Please show both hm-rpc settings pages as screenshots. It’s most likely a configuration issue.

**Comment by David91919** [comment]
![rpc haupt](https://user-images.githubusercontent.com/56155511/93586816-2728dc80-f9a9-11ea-8aac-4cd2eeaf877c.png)
![RPC zus](https://user-images.githubusercontent.com/56155511/93586819-2a23cd00-f9a9-11ea-850b-1c619ea12660.png)
Thanks for quick reply.
Callback is set to my OMV server. 
Container details:
![container](https://user-images.githubusercontent.com/56155511/93586976-71aa5900-f9a9-11ea-9695-46bc3f3819df.png)

**Comment by David91919** [comment]
Sorry, wrong number in callback (176 instead 178) in above screenshot.
Removed all hm instances and reinstalled with correct call back address but no change

Correct setting:
![image](https://user-images.githubusercontent.com/56155511/93587831-c69a9f00-f9aa-11ea-821d-37a07abb94dc.png)

**Comment by David91919** [comment]
Now getting param set 1 and additional values in set 0:
Still no set 2,3, etc. though

![more params](https://user-images.githubusercontent.com/56155511/93588409-a7504180-f9ab-11ea-8817-325c554b2f9a.png)

**Comment by David91919** [comment]
Getting all the data now I think. False alarm :)

**Comment by foxriver76** [comment]
Getting not all new objects displayed in admin after creation is often a Common Problem, reload or cleaning cache often helps. 👍
