### ISSUE TITLE
HmIP  CONTROL_MODE DP is not getting updated

### ISSUE THREAD

**Issue by hetti72** [ioBroker/ioBroker.hm-rpc#278]
**Describe the bug**
The CONTROL_MODE datapoint for all HmIP thermostat´s (HmIP-WTH, HmIP eTRV) is not getting updated when control mode is changed in CCU or on the device. If the control mode DP is changed in IOBroker the mode changes in the CCU and on the device (as expected)

**To Reproduce**
Change the control mode for a thermostat in the CCU from manu to auto (or vice-versa)
Corresponding DP in iobroker will not be updated

**Expected behavior**
DP in iobroker should be updated when the control mode of a thermostat is changed to reflect the actual status of the device

**Versions:**
 - hm-rpc version: 1.14.23
 - hm-rega version: <2.6.14
 - Node version: 12.18.3
 - Operating system: Container on Synology
 - CCU model: raspberrymatic
 - CCU firmware: 3.53.30.20200919

**Additional context**

**Comment by foxriver76** [comment]
According to OPERATIONS parameter this datapoint will not be updated by the XML-API, thus it's `read: false`:

```
  "common": {
    "name": "HK Schlafzimmer:1.CONTROL_MODE",
    "def": 0,
    "type": "number",
    "read": false,
    "write": true,
    "min": 0,
    "max": 3,
    "role": "indicator"
  },
```

as far as i remember you need to read from `.SET_POINT_MODE`
