### ISSUE TITLE
nach Rolladenupdate (1.8.12) wertebereich zwischen 0 und 1 

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.hm-rpc#279]
nach dem update auf  1.8.12 ist der Prozentwert von 0 bis 1 das betrift HmIP-FRoll und HmIP-FBL

**Comment by foxriver76** [comment]
Mal den Adapter neugestartet?

**Comment by MeisterTR** [comment]
reboot tut gut, manchmal ist es so einfach ;)

**Comment by foxriver76** [comment]
Jop ;-) werde trotzdem mal schauen woran es liegt, dass er die Meta Daten verliert beim Update, ist mir letztens auch passiert
