### ISSUE TITLE
Add device icons for Homematic IP devices

### ISSUE THREAD

**Issue by mesche** [ioBroker/ioBroker.hm-rpc#28]
Please add the icons for Homematic IP devices to avoid log warnings

- HMIP-eTRV
- HMIP-PSM
- HMIP-BDT
- HMIP-SMI
- HMIP-WTH
- HMIP-PSM 
- HMIP-WRC2
- HMIP-SWDO 
- HMIP-SWSD
- HMIP-ASIR
- HMIP-SMO

**Comment by jens-maus** [comment]
Please note that PR #30 should resolve this issue. So one bluefox has integrated it the icons should appear.

**Comment by jens-maus** [comment]
Implemented in version 1.3.4, thus this issue can be closed.

**Comment by mesche** [comment]
Okay thank you
