### ISSUE TITLE
Impulses from the buttons of the virtual remote control are not processed correctly

### ISSUE THREAD

**Issue by roadie33** [ioBroker/ioBroker.hm-rpc#280]
**Describe the bug**
When a button of the virtual remote control is pressed, the status changes from "false" to "true" and remains at the status "true". 

**To Reproduce**
1. Go to 'raspberrymatic WebUI'
2. Click on 'Status und Bedienung -> Geraete'
3. Click on 'CCU 3'
4. Click on 'Kurzer Tastendruck' or 'Langer Tastendruck'
5. See 'iobroker objects' -> 'hm-rpc.x' -> 'BidCoS-RF' -> '1' -> 'PRESS_LONG' or PRESS_SHORT' => Value

**Expected behavior**
Since it is a button and not a switch, the status must be set back to "false" automatically. 

**Screenshots & Logfiles**
For step 1 to 4
![grafik](https://user-images.githubusercontent.com/58664090/94967522-85a09f80-04ff-11eb-9521-53b6338466b0.png)
Step 5
![grafik](https://user-images.githubusercontent.com/58664090/94967418-51c57a00-04ff-11eb-90dd-19e1b84864db.png)

**Versions:**
 - hm-rpc version: <2.6.22>
 - hm-rega version: <1.14.23>
 - JS-Controller version: <3.1.16>
 - Node version: <10.22.1>
 - Operating system: Raspberry Pi OS
 - CCU model: <CCU 3>
 - CCU firmware: <RaspberryMatic 3.53.30.20200919>

**Additional context**
No additional context

**Comment by foxriver76** [comment]
Buttons don’t depend on a specific value, they just get triggered, you have to check for updates not changes in your scripts. This is extensively discussed in forum and other issues.
