### ISSUE TITLE
.Level 0-1

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.hm-rpc#281]
Hi Foxriver!

Mit 1.14.23 zeigt er bei .Level nur von 0 - 1

![objects - ioBroker (1)](https://user-images.githubusercontent.com/45309436/95028444-95a3b500-06a0-11eb-8246-69a1d4bee25a.png)

**Comment by foxriver76** [comment]
Hm Device evtl geupdated und kein Neustart gemacht?

**Comment by Negalein** [comment]
Danke, das  wars!
