### ISSUE TITLE
Incorrect Values in HMIP BROLL

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.hm-rpc#282]
Hello Foxriver, 

just updated hm-rpc version 1.14.23. When activating my routine I noticed that the level values are incorrect.
When I change the value to 50% the roller blind travels down to 0.5%. I downgraded the adapter to previous version and it works correct. The behaviour is with this roller blind only (latest firmware version)

Best regards

**Comment by foxriver76** [comment]
Hast du vor dem Auftreten zur Laufzeit den BROLL geupdated? Danach braucht es derzeit leider einen Neustart des Adapters, siehe auch https://forum.iobroker.net/topic/37568/gelöst-verständnisfrage-zu-homematic-rollladenschalter/18
