### ISSUE TITLE
The Level is not correct in IoBroker, 100% is 101% 90%is 91%

### ISSUE THREAD

**Issue by pclars** [ioBroker/ioBroker.hm-rpc#283]
The Level is not correct in IoBroker, 100% is 101% 90%is 91%
![Screenshot_2020-10-17 objects - ioBroker](https://user-images.githubusercontent.com/67156995/96334539-da9cf380-1071-11eb-9bb2-f3f1dd244617.png)

the Problem is when i use the Voice Command to Alexa.. i Say ,,Alexa Rollladen Wohnzimmer 100%`` the Broll controlls down...
when i say ,,Alexa Rolladen Wohnzimmer 99%´´ it was 100% level...

The level configuration was not right... see Screenshot

CCU on Rasperrymatic 

  | 3.53.30.20200919
-- | --

IOT Cloud

Iobroker in Docker Container

Adapter   1.14.23

**Comment by foxriver76** [comment]
I guess this is an old issue, please check `synchronize objects once` in adapter settings to recreate the devices or delete it manually and restart the adapter
