### ISSUE TITLE
SET_POINT_MODE und CONTROL_MODE kombinieren/vereinheitlichen

### ISSUE THREAD

**Issue by QuoxelNet** [ioBroker/ioBroker.hm-rpc#284]
**Is your feature request related to a problem? Please describe.**
Die derzeitige Funktionsweise ist unterschiedlich zum Verhalten anderer Adapter/Datenpunkte. Gerade für Neueinsteiger ist das Verhalten mit zwei unterschiedlichen Datenpunkte eher verwirrend, gerade wenn man parallel noch HM-Geräte laufen hat, die nur einen Datenpunkt kennen. Zwar mag die API dieses eigenwillige Verhalten heraufbeschwören, aber dann wäre es umso schöner, wenn man das in ioBroker "geradeziehen" könnte.

**Describe the solution you'd like**
Es wäre schön, wenn SET_POINT_MODE und CONTROL_MODE von HM-IP-Geräten zu einem (neuen?) Datenpunkt zusammengefasst werden können. Damit würde die Unterscheidung zwischen Soll- und Istwert wegfallen und man hätte eine einfachere Visualisierungsmöglichkeit und ein IMHO intuitiveres Verhalten.
Eine Idee wäre es, einen Datenpunkt "MODE" einzuführen, über den ein Sollwert gesetzt werden kann, dieser setzt dann den Wert von CONTROL_MODE. Sobald dann der Istwert via SET_POINT_MODE "zurückkommt", wird der Wert von "MODE" mit gesetztem ACK-Flag aktualisiert.
Diese Variante hätte den Vorteil, dass das bisherige Verhalten beibehalten wird, aber gerade für Neueinsteiger ein neuer Datenpunkt existiert (dieser sollte dann mit ENUM-Werten vorbereitet sein und auch nicht als "Indicator" angezeigt werden), der einfacher von der Handhabung her ist.

**Describe alternatives you've considered**
Eine Alternative wäre, das Verhalten für HM-Geräte und HM-IP-Geräte insgesamt zu vereinheitlichen, damit gleichlautende Datenpunkte mit dem gleichen Verhalten für alle gleichen Gerätetypen (z.B. Heizungsaktoren) vorhanden wären. Das wäre natürlich die Luxus-Variante.

**Additional context**
Zu berücksichtigen ist, wenn man zwei unterschiedliche Datenpunkte verwendet, kann das zu Missverständnissen führen. Wenn man vom "üblichen" Verhalten ausgeht, man setzt einen DP, dieser wird rot ("ACK ausstehend") erwartet man eigentlich auch ein ACK. Dass dieses indirekt über einen anderen DP kommt, ist verwirrend...

**Comment by foxriver76** [comment]
Nach wie vor vertrete ich den Punkt, speziell in diesem Adapter solche spezifischen Sachen nicht aufzunehmen. Hauptgrund ist, dass es von diesen Fällen sehr viele gibt und durch die schnell steigende Anzahl an Geräten auch immer mehr werden. Solange hier von Seiten eq-3 nicht mehr für die einheitliche Handhabung getan wird, wird das hier auch nicht passieren. Der Adapter hier ist als Schnittstelle zur XML-RPC API zu sehen.

Der vorgeschlagene Use-Case lässt sich allerdings mit sehr geringem Aufwand in einen `alias` unter Verwendung von `read` und `write` realisieren.
