### ISSUE TITLE
CONTROL_MODE not updated when changed on CCU3

### ISSUE THREAD

**Issue by ratte-rizzo** [ioBroker/ioBroker.hm-rpc#285]
**Describe the bug**
When mode of heating control valve HmIP-eTRV-B is changed on CCU3 from AUTO to MAN or vice versa, this is not reflected in state CONTROL_MODE in ioBroker.

When CONTROL_MODE is changed from 0 to 1 or vice versa in IOB, then the mode changes on CCU3. 

**To Reproduce**
1. go to CCU3 and select a heating control valve HmIP-eTRV-B and change from AUTO mode to MAN mode
2. Check state CONTROL_MODE data point in IOB is not changing

1a. go to data point CONTROL_MODE in IOB and change value to 0 or 1
2. check that on corresponding valve in CCU3 mode is changing from AUTO to MAN mode

**Expected behavior**
Changing AUTO / MAN mode in CCU3 shall change also data point CONTROL_MODE in IOB

**Versions:**
 - hm-rpc version: 1.14.23
 - hm-rega version: 2.6.21
 - JS-Controller version: 4.8.4
 - Node version: 10.20.1
 - Operating system: Debian
 - CCU model: CCU3
 - CCU firmware: 3.53.30

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.hm-rpc/issues/278
