### ISSUE TITLE
TimeOUT Fehlermeldung (FSM)

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.hm-rpc#286]
Serwus

ich bekomme seit neuesten immer wieder mal folgende Fehlermeldung

`
hm-rpc.1 | 2020-10-29 15:13:05.343 | error | (2161) Error: XML-RPC fault: Generic error (TIMEOUT)
-- | -- | -- | --
hm-rpc.1 | 2020-10-29 15:13:05.336 | error | (2161) xmlrpc -> setValue ["000855699C3F2F:4","STATE",true] BOOL

`

Betrifft aber nicht nur dieses Gerät, eigentlich ist es mir aufgefallen da ich für mein Bad ein Skript habe mit dem ich 2 Lichter und die Heizkörper bzw Lüftung ansteuere. Ich schalte hier beide Lichter gleichzeitig bzw jetzt das zweite mit 2 Sekunden abstand. der BSM schaltet immer und exakt wie er soll aber der FSM nicht. Es kommt dann auch immer erst diese Fehlermeldung und nach ca 10-15 Sekunden schaltet der FSM dann und reagiert dann auch problemlos.

Die Fehlermeldung bekam ich heute auch in meiner Küche - wo ich auch deinen BSM und FSM verbaut habe. Der BSM hat problemlos geschaltet und der FSM hat diesen Fehler gemeldet und dann nach ca 10-15 Sekunden problemlos automatisch reagiert.

**Comment by foxriver76** [comment]
Ist kein Fehler des Adapters, sondern dein Gerät reagiert nicht. Für Ursachenforschung bitte Forum nutzen, da wird dir schneller geholfen.
