### ISSUE TITLE
HmIP-PCBS - ON Time lässt sich nicht setzen

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.hm-rpc#287]
Hallo

habe gerade festgestellt das ich die ON Time beim HmIP-PCBS nicht setzen kann.
Egal welche Zahl ich hineinschreibe sie wird nicht akzeptiert.
Es gibt aber auch keine Fehlermeldung, bei Bestätigt steht false und die Zahl ist Rot. 

bzgl der Zahl
es ist egal ob 1, 10, 200. Bei anderen Geräten wie zB FSM funktioniert das einwandfrei.

wäre super wenn du dir das mal ansehen könntest. 
vielen dank für dein mühe und tolle arbeit.

**Comment by foxriver76** [comment]
Ich habe das Device leider selbst nicht, daher kann ich maximal in der Device Doku schauen. Hilfreich wäre, wenn du das Objekt des betroffenen Datenpunkts hier zeigst. Bestätigt wird wohl auch immer `false` bleiben, da der Datenpunkt wohl write-only ist. 
![Bildschirmfoto von 2020-10-30 08-55-28](https://user-images.githubusercontent.com/25484431/97674396-c0114400-1a8d-11eb-9569-5bbd94cec16e.png)

Bei manchen Logiken von HM, muss auch nach dem setzen eines DP's noch ein anderer gesetzt werden, wie z. B. für `LEVEL2` mancher Devices, siehe https://github.com/ioBroker/ioBroker.hm-rpc/issues/206#issuecomment-549241202

Wenn kein Fehler kommt, heißt das auf jeden Fall schon mal, dass der Adapter den Wert an die CCU problemlos übertragen hat.

**Comment by foxriver76** [comment]
Angeblich funktioniert der DP nur als String obwohl explizit als number deklariert. Zumindest Stand 2015

https://homematic-forum.de/forum/viewtopic.php?t=26515

**Comment by krobipd** [comment]
was kann ich tun um das zu probieren?
habe den on_time wert auf string gesetzt - über die experten einstellungen, hat aber auch nix geändert.
wenn du mir bitte sagen könntest was ich tun soll dann werde ich das gerne machen.

**Comment by foxriver76** [comment]
Im Admin hinter dem Objekt auf den Stift, dann auf RAW, mir das mal zeigen, dann sage ich was du mal ändern kannst. Nach den Änderungen muss der Adapter dann neugestartet werden.

**Comment by krobipd** [comment]
{
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1594424395355,
  "common": {
    "name": "Eingang - GA Öffner.ON_TIME",
    "type": "number",
    "unit": "s",
    "def": 0,
    "min": 0,
    "max": 8580000,
    "read": false,
    "write": true,
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "maxLength": "1000",
        "retention": "63072000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "aliasId": ""
      }
    }
  },
  "native": {
    "UNIT": "s",
    "ID": "ON_TIME",
    "TYPE": "FLOAT",
    "MIN": 0,
    "OPERATIONS": 2,
    "MAX": 8580000,
    "FLAGS": 1,
    "DEFAULT": 0
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.1.00045709AABAC3.3.ON_TIME",
  "type": "state"
}

**Comment by foxriver76** [comment]
Ein Mal oben bei Type statt `number` `string` und unten im native statt `FLOAT` `STRING` dann mal Adapter neu starten.

**Comment by krobipd** [comment]
danke habe ich gemacht
bekomme dann aber einen fehler, also ich tippe zB 4 ein und enter. danach schalte ich das gerät ein und es gibt im log eine fehlermeldung.

`(3697) Error: XML-RPC fault: Invalid parameter or value`

ich habe aber momentan eher das gefühl das es sich hierbei entweder um ein allgemeines problem mit dem on_time handelt oder ich irgendwas falsch mache.

wenn ich im blockly sage schick on_time mit 4 und dann nach 2 sekunden das gerät einschalte - bleibt es für immer ein.
wenn ich das direkt reinschreibe dann geht es manchmal und manchmal nicht.

das selbe phänomen habe ich auch beim fsm - wenn ich on_time via blockly schicke geht es mal und mal nicht bzw nicht verlässlich.

in der webui macht man das ja auch so das man zuerst on_time setzt und dann 1-2 sekunden wartet und das gerät einschalten lässt - das funktioniert immer sehr verlässlich.

hast du sowas vl auch am laufen und kannst mir vl deine einstellung sagen? vl mach ich ja was falsch.

**Comment by foxriver76** [comment]
Hm also scheint es doch wieder so ähnlich wie mit der LEVEL2 Geschichte zu sein.. ich habe leider kein derartiges Gerät am laufen. Könnte mir aber vorstellen, dass du im Forum jemand findest, der das Problem gelöst hat.

**Comment by krobipd** [comment]
Danke für deine Zeit.
Mittlerweile ist der Status wie folgt
Die on_time wird nie (egal welches Gerät) bestätigt. Aber wenn man dann den Aktor einschaltet funktioniert es.

Warum auch immer die on_time nicht bestätigt wird weiß ich nicht. 

Jedenfalls hast du vollkommen recht dass ich da grundsätzlich ein anderen Problem noch mit habe.

Aber ich denke es ist für zukünftige Fragen bzgl on_time und Bestätigung ganz gut das Mal festzuhalten.

Ich habe zb diverse blockly Skript wo ich zuerst die on_time Festlegen und nach 2 Sekunden das Gerät einschalte, so funktioniert es.

**Comment by foxriver76** [comment]
Bestätigt wird der Wert nie da er als Write only deklariert ist von der XML rpc api, siehe Screenshot im ersten Post.
