### ISSUE TITLE
fehler beim Level einstellen beim  HM-LC-Dim

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.hm-rpc#288]
wenn ich auf 100% schalte und dann auf einen werrt !=0 wird immer auf 0 gesetzt, wenn ich von 0 auf !=100 setzte geht es 
(ich nutze die aktuelle latest)

![fehler](https://user-images.githubusercontent.com/6328382/97898806-a8111d00-1d38-11eb-95f0-5d2b559ea2ef.gif)

``` {
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100,
    "unit": "%",
    "role": "level.dimmer",
    "workingID": "WORKING",
    "name": "HM-LC-Dim1T-FM NEQ1XXXXX:1.LEVEL",
    "smartName": {
      "de": "Schalfzimmer Deckenlicht, Schlafzimmer Licht",
      "smartType": "LIGHT"
    }
  },
  "native": {
    "CONTROL": "DIMMER.LEVEL",
    "DEFAULT": 0,
    "FLAGS": 1,
    "ID": "LEVEL",
    "MAX": 1,
    "MIN": 0,
    "OPERATIONS": 7,
    "TAB_ORDER": 0,
    "TYPE": "FLOAT",
    "UNIT": "100%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1590346110271,
  "_id": "hm-rpc.0.NEQ1XXXXXX.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by foxriver76** [comment]
Welche Adapterversion?

**Comment by MeisterTR** [comment]
1.14.24 das ist die aktuelle version. Kein FW update eigentlich seit 4 Jahren für das Gerät

**Comment by foxriver76** [comment]
Für mich schaut das eigentlich erst mal gut aus. 

> hm-rpc.0 | 2020-11-02 20:48:50.737 | debug | (11918) hm-rpc.0.NEQ13XXXXX.LEVEL ==> UNIT: "100%" (min: 0, max: 1) From "0.995" => "99.5"
> hm-rpc.0 | 2020-11-02 20:48:50.737 | debug | (11918) xmlrpc <- event ["hm-rpc.0","NEQ13XXXXX:1","LEVEL",0.995]
> hm-rpc.0 | 2020-11-02 20:48:50.737 | debug | (11918) xml multicall <event>: hm-rpc.0,NEQ13XXXXX:1,LEVEL,0.995
> hm-rpc.0 | 2020-11-02 20:48:50.570 | debug | (11918) setValue ["NEQ13XXXXX","LEVEL",{"explicitDouble":0.5}] FLOAT
> hm-rpc.0 | 2020-11-02 20:48:50.570 | debug | (11918) xmlrpc -> setValue 1 LEVEL: 50

Es wird von dir 50 gesetzt und korrekt 0.5 gesendet. Nur kommt jetzt von der API das Event mit einem Level von 0.995, passt nicht zu deiner Anfrage das stimmt, aber nach so kurzen ms, aber letztendlich wirds wieder korrekt umgewandelt in die 99.5. Der aktuelle Wert hat auch keinen Einfluss auf Adapter-Ebene auf einen neu gesetzten Wert, da du oben schreibst, dass wenn von 100 auf ein anderen Wert gesetzt wird, ein falscher Wert gesetzt wird. Im Log sehe ich jetzt auch nicht das Szenario, dass 100 war und du dann etwas != 0 setzt und er auf 0 fährt, oder übersehe ich etwas? Hast du das Verhalten auch wenn du direkt über die WebUI das Gerät steuerst?

**Comment by MeisterTR** [comment]
da sitzt der Fehler vorm Rechner. hatte noch ein 5 Jahre altes ungenutztes Programm auf der CCU was das Fehlverhalten verursacht hat :(
