### ISSUE TITLE
Error: XML-RPC fault: Unknown paramset

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rpc#289]
Ich habe heute beim Neustart der hm-rpc 1 Instance (Homematic Geräte) folgende Fehlermeldung entdeckt:

1. - 2020-11-10 07:13:06.172  - [31merror[39m: hm-rpc.1 (19469) Error on getParamsetDescription for [NEQ0711636:4, 'VALUES']": Error: XML-RPC fault: Unknown paramset
2. 2020-11-10 07:13:06.173  - [32minfo[39m: hm-rpc.1 (19469) xmlrpc -> getParamsetDescription ["NEQ0711636:5","VALUES"]
3. 2020-11-10 07:13:06.178  - [31merror[39m: hm-rpc.1 (19469) Error on getParamsetDescription for [NEQ0711636:5, 'VALUES']": Error: XML-RPC fault: Unknown paramset
4. 2020-11-10 07:13:06.179  - [32minfo[39m: hm-rpc.1 (19469) xmlrpc -> getParamsetDescription ["NEQ0711636:6","VALUES"]
5. 2020-11-10 07:13:06.184  - [31merror[39m: hm-rpc.1 (19469) Error on getParamsetDescription for [NEQ0711636:6, 'VALUES']": Error: XML-RPC fault: Unknown paramset
6. 2020-11-10 07:13:06.184  - [32minfo[39m: hm-rpc.1 (19469) xmlrpc -> getParamsetDescription ["NEQ0711636:7","VALUES"]
7. 2020-11-10 07:13:06.190  - [31merror[39m: hm-rpc.1 (19469) Error on getParamsetDescription for [NEQ0711636:7, 'VALUES']": Error: XML-RPC fault: Unknown paramset
8. 2020-11-10 07:13:06.190  - [32minfo[39m: hm-rpc.1 (19469) xmlrpc -> getParamsetDescription ["NEQ0711636:8","VALUES"]
9. 2020-11-10 07:13:06.196  - [31merror[39m: hm-rpc.1 (19469) Error on getParamsetDescription for [NEQ0711636:8, 'VALUES']": Error: XML-RPC fault: Unknown paramset

Es handelt sich dabei um einen HM-Dis-EP-WM55 (Homematic  Funk-Statusanzeige mit E-Paper-Display)
Meine aktuelle Iobroker Konfiguration:

Node.js - v12.18.4 
NPM - 6.14.6
js-controller - 3.1.6
Admin - 4.1.10
HomeMatic RPC - 1.14.24

**Comment by foxriver76** [comment]
Dann sagt die CCU in `newDevices`, dass es den channel geben würde, wenn wir anfragen hat er wohl kein paramset dafür. Kann sein, dass sowas früher nicht geloggt wurde. Kannst du das Device ansteuern über ioBroker? Es scheinen ja nur die Channels 4-8 nix parat zu haben.

**Comment by Knallochse** [comment]
Ja, steuern über IoBroker geht. Es sind bei diesem Gerät (auch in der CCU) nur die Kanäle 1 und 2 konfigurier und steuerbar.
Es scheint alles zu funktionieren. Ich wollte nur mitteilen, dass diese Fehler in Log auftauchen.

**Comment by foxriver76** [comment]
Okay, danke. Taucht er bei jedem Neustart auf oder war nur einmalig?

**Comment by Knallochse** [comment]
Wenn ich nur die hm-rpc.1 Instance neu starte dann kommt der Fehler nicht. Wenn man aber "Geräte neu einlesen (einmalig)" anwählt, dann kommt der Fehler bei dem besagten Gerät wiederholt.

**Comment by foxriver76** [comment]
Okay, danke - würde das erst mal ignorieren, da Funktionalität komplett gegeben und nur behauptet wird da wären Paramsets zu holen wo keine zu holen sind. Muss seitens CCU gefixt werden
