### ISSUE TITLE
Verbindungs-Check Interval

### ISSUE THREAD

**Issue by AlGu318** [ioBroker/ioBroker.hm-rpc#29]
Das Interval in der Adapter Konfig ist dort mit "Verbindungs-Check Interval(sek)" beschrieben. Also in Sekunden. Im Code der Datei "hm-rpc.js" wird der Wert "checkInitInterval" aber unterschiedlich (Sekunden / Millisekunden) behandelt.
Z.B. bei "adapter.config.checkInitInterval * 1000"
und  "adapter.config.checkInitInterval * 1000 / 2"

Bei mir seht z.B. 7200 in der Adapter Konfig, das logging in der CCU zeigt dann jede Stunde den "CENTRAL" Fehler.

Hoffe das reicht zum nachvollziehen.
Gruß AlGu

**Comment by Apollon77** [comment]
Das ist im Code alles soweit korrekt.

Jedes halbe Intervall wird ein "PING" an die CCU gesendet und wenn es darauf keine Antwort gibt wird dann beim nächsten lauf (also "volles Intervall") die Connection erneuert ... was im Normalfall aber nicht passiert wenn immer die Pings beantwortet werden.


Welche CCU version nutzt du? 
Ich hatte auch mal die CENTRAL Fehler bei jedem ping. Nach irgendeinem Update waren die weg

**Comment by AlGu318** [comment]
Ok, dann hab ich den Code nur nicht richtig verstanden. Zu dem Fehler log bei mir:
Ich habe die aktuellste CCU Firmware 2.25.15. ioBroker und die Adapter sind auch alle aktuell.
Wie hast du den Fehler mit dem "CENTRAL" denn behoben? Hat das ggf. was mit CuxD zu tun? Wenn ich das richtig verstehe muss jede angemeldete Schnittstelle den Ping korrekt beantworten, vielleicht ist das ja das Problem mit dem "CENTRAL".

**Comment by AlGu318** [comment]
So nun habe ich alles an Programmen von der CCU in ioBroker umgebaut und danach dann CuxD deinstalliert. Den Log-Eintrag mit dem "CENTRAL" bekomme ich immer noch. Weiß sonst jemand woran das liegen könnte?
