### ISSUE TITLE
HmIPW-WTH: WINDOW_STATE sollte read only sein

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.hm-rpc#290]
Der Datenpunkt `.WINDOW_STATE` bei Thermostaten wie z.B. HmIPW-WTH sollte m.M.n. nur read only sein?

**Comment by foxriver76** [comment]
Wieso er lässt sich doch 1A beschreiben und übernimmt den Wert auch? Sobald ich ihn beschreibe setzt er die entsprechnde Open/Close Temp und zeigt auch das Fenstersymbol entsprechend an. Er wird von der API als writeable deklariert und ist dies auch. Wenn du Third Party Fenster Sensoren hast, kannst du diese so leichter mit den internen HM-Logiken verknüpfen.

**Comment by Scrounger** [comment]
Hast vollkommen recht, das man den FensterOffen Modus von außen aktivieren kann, hatte ich nicht bedacht.
