### ISSUE TITLE
HmIP-SWDO - Kanal 2 

### ISSUE THREAD

**Issue by Messiahs** [ioBroker/ioBroker.hm-rpc#294]
Nach dem Anlernen von Türkontakten (HmIP-SWDO / HmIP-SWDO-I) wird in ioBroker ein leerer Datenpunkt für Kanal 2 erstellt.
Unterhalb dieses Knoten sind aber keine states oder ähnliches angeführt.
Das sieht dann etwas komisch aus.
Schön wäre es, wenn keine leeren Kanäle erstellt werden.

Hinweis:
Grundsätzlich hat der Türkontakt einen 2. Kanal, allerdings ist dieser eher unsichtbar und dient als "Verknüpfungspartner
Backup Alarmsirene"

![image](https://user-images.githubusercontent.com/1129204/103320793-158ab280-4a37-11eb-842e-43f49ff4849c.png)

**Comment by foxriver76** [comment]
If the api has the channel we will mirror it. I’m admin you will find many dps which are not interesting for you, so I would just ignore it for now.
