### ISSUE TITLE
HM-RPC 1.14.25 Werte nur von 0-1

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.hm-rpc#295]
Mit HM-RPC 1.14.25 werden die Level nur von 0-1 angezeigt.

Mit 1.14.24 und HM-Rega 3.0.4 (musste von 3.0.6 downgraden (mit 3.0.5 bleibt der Fehler)) funktionierts wieder.

**Comment by Knallochse** [comment]
Ich kann dieses Verhalten bestätigen. Betrifft alle Geräte mit Level-Werten. (Rolladen, Dimmer, Thermostate usw.)

**Comment by kago76** [comment]
Auch ich kann dieses Verhalten bestätigen. 
HM-RPC 1.14.25 und HM-Rega 3.0.6.

Workaround: Die HM-Rega Instanz neu starten, nachdem die HM-RPC Instanz gestartet wurde.
Danach habe ich auch mit dem HM-Rega 3.0.6 wieder korrekte werden.

**Comment by UweRP** [comment]
Das Problem betrifft mich auch. Aufgefallen bisher bei einem HMIP-BROLL und bei einem HMIP-FROLL.
Merkwürdigerweise werden andere HMIP-BROLL korrekt 0-100% angezeigt.

**Comment by Knallochse** [comment]
@foxriver76 Vielen Dank für den super schnellen Fix. Scheint wieder 1a zu funktionieren 👍
