### ISSUE TITLE
Betriebszustand in Virtuellen Devices (Heizgruppen) lässt sich nicht auslesen

### ISSUE THREAD

**Issue by FreunderNacht** [ioBroker/ioBroker.hm-rpc#296]
Hallo,
in den Heizgruppen (Virtuelle Devices) lässt sich der aktuelle Betriebszustand nicht auslesen.
Das setzen eines Zustandes funktioniert allerdings.

Wenn ich den Wert in hm-rpc.1.INT0000001.1.CONTROL_MODE auf 0 ändere geht die Heizgruppe in den Automatikmodus, bei einer Änderung auf 1 geht sie in den manuellen Modus.
Ändere ich jedoch in der CCU den Betriebsmodus, wird der Wert in IO Broker nicht geändert.
Ein den Eigenschaften des Wertes hm-rpc.1.INT0000001.1.CONTROL_MODE ist nur ein Hacken bei schreiben erlaubt, der bei lesen erlaubt fehlt. 

Ich würde mir wünschen (wenn möglich), das der Wert m-rpc.1.INT0000001.1.CONTROL_MODE auch den aktuellen Betriebszustand anzeigt, damit ich diesen Wert in der VIS darstellen und mit ihm auch gleichzeitig den Betriebsmodus wechseln kann.

**Screenshots & Logfiles**
![1609710745983-heizgruppenobjekte](https://user-images.githubusercontent.com/69077006/103686122-9e9d6e80-4f8e-11eb-90fe-b8d12286afe2.jpg)
![1609710864095-heizgruppenobjekte-detail-control-mode](https://user-images.githubusercontent.com/69077006/103686130-a0ffc880-4f8e-11eb-8da7-45dc383f43ae.jpg)
![Rega-Adapter Einstellungen RPC](https://user-images.githubusercontent.com/69077006/103689104-25ece100-4f93-11eb-831c-e76c34afa832.jpg)
![Systeminformationen](https://user-images.githubusercontent.com/69077006/103686508-34d19480-4f8f-11eb-9eea-723ec4d5daa1.jpg)
https://user-images.githubusercontent.com/69077006/103687968-6ba8aa00-4f91-11eb-9912-df0169ce0ff7.mp4

**Versions:**
 - hm-rpc version: <1.14.26>
 - hm-rega version: <3.0.6>
 - JS-Controller version: <v12.20.0>
 - Node version: <v12.20.0>
 - NPM version: <6.14.8>
 - Operating system: <Linux>
 - CCU model: <CCU 3>
 - CCU firmware: <3.55.5>

Vielen Dank
MfG

Freund der Nacht

**Comment by foxriver76** [comment]
Der Zustand wird von der API als rein schreibbar zur Verfügung gestellt, sprich hier erfolgt keine Rückmeldung durch die CCU. Evtl. gibt es hier einen separaten Zustand der lesbar ist, leider habe ich gerade keine Heizgruppe eingebunden um das ad-hoc nachzuschauen.

**Comment by FreunderNacht** [comment]
@foxriver76
Wenn es da einen alternativen Daten Punkt gäbe den ich benutzen könnte würde ich den gerne nehmen.
Aufgrund von Einträgen in Foren bin ich auf diesen Datenpunkt gestoßen. 
Dirt ging es allerdings auch um Heizkörperthermostate und ich meine auch um Wandthermostat.

Es wäre auch möglich 2 verschieden Datenpunkte zu verwenden, den oben beschriebenen zum umschalten und einen anderen um den aktuellen Status auszulesen. 
Ich habe jedoch noch keinen gefunden auf dem ich den aktuellen Status sehen kann.

**Comment by foxriver76** [comment]
Insofern sich HMIP Heizgruppen verhalten wie HMIP Thermostate, ist der `SET_POINT_MODE` lesbar und wird somit auch aktualisiert durch die CCU

**Comment by FreunderNacht** [comment]
Danke @foxriver76,
hat funktioniert.

https://user-images.githubusercontent.com/69077006/104017805-10590080-51b9-11eb-9cde-40efa9601a6f.mp4
