### ISSUE TITLE
JS Controller V 3.2.2 BETA  Warn Meldung

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.hm-rpc#297]
Hallo,

nach Installation von JSC kommt folgende Warn Meldung:

`

hm-rpc.1 | 2021-01-09 09:55:41.457 | warn | (12080) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
hm-rpc.0 | 2021-01-09 09:55:37.421 | warn | (10212) State "hm-rpc.0.CENTRAL.PONG" has no existing object, this might lead to an error in future versions

`
Dies zur Info.

`Platform: Windows
RAM: 16 GB 
Node.js: v12.20.1
NPM: 6.14.10
JS Controler: 3.2.2
Admin: 4.2.0
Web: 3.2.0
Socket.io: 3.0.13
Script Engine: 4.10.8
IOT: 1.8.8
VIS: 1.3.6
HM-Rega: 3.0.6
HM-RPC: 1.14.26`

LG
Sigi

**Comment by foxriver76** [comment]
Danke fürs melden

**Comment by sigi2345** [comment]
Fehler noch da!

`

  |   |   |  
-- | -- | -- | --
hm-rpc.1 | 2021-01-09 17:02:59.663 | warn | (15860) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions

`

**Comment by foxriver76** [comment]
wie installiert? mach mal nen upload und sonst mal bitte debug logging anschalten, geht auch zur laufzeit unter system.adapter.hm-rpc.1.loglevel debug reinschreiben

**Comment by sigi2345** [comment]
`

hm-rpc.1 | 2021-01-09 18:06:32.542 | debug | (6272) system.adapter.admin.0: logging true
-- | -- | -- | --
hm-rpc.1 | 2021-01-09 18:06:10.728 | warn | (6272) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions
hm-rpc.1 | 2021-01-09 18:06:10.726 | debug | (6272) hm-rpc.1.CENTRAL.0.PONG ==> UNIT: "none" (min: none, max: none) From "Medion(Test):hm-rpc.1" => "Medion(Test):hm-rpc.1"
hm-rpc.1 | 2021-01-09 18:06:10.724 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","CENTRAL:0","PONG","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:06:10.716 | debug | (6272) PING ok
hm-rpc.1 | 2021-01-09 18:06:10.695 | debug | (6272) Send PING...
hm-rpc.1 | 2021-01-09 18:06:10.695 | debug | (6272) [KEEPALIVE] Check if connection is alive
hm-rpc.1 | 2021-01-09 18:06:00.861 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.HUMIDITY_STATUS ==> UNIT: "undefined" (min: NORMAL, max: UNDERFLOW) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:06:00.861 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","HUMIDITY_STATUS",0]
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,HUMIDITY_STATUS,0
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.ACTUAL_TEMPERATURE_STATUS ==> UNIT: "undefined" (min: NORMAL, max: UNDERFLOW) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","ACTUAL_TEMPERATURE_STATUS",0]
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,ACTUAL_TEMPERATURE_STATUS,0
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.HUMIDITY ==> UNIT: "%" (min: 0, max: 100) From "76" => "76"
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","HUMIDITY",76]
hm-rpc.1 | 2021-01-09 18:06:00.860 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,HUMIDITY,76
hm-rpc.1 | 2021-01-09 18:06:00.859 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.ACTUAL_TEMPERATURE ==> UNIT: "�C" (min: -3276.8, max: 3276.7) From "0.9" => "0.9"
hm-rpc.1 | 2021-01-09 18:06:00.859 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","ACTUAL_TEMPERATURE",0.9]
hm-rpc.1 | 2021-01-09 18:06:00.859 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,ACTUAL_TEMPERATURE,0.9
hm-rpc.1 | 2021-01-09 18:06:00.854 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.ERROR_CODE ==> UNIT: "undefined" (min: 0, max: 255) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","ERROR_CODE",0]
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,ERROR_CODE,0
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.TEMPERATURE_OUT_OF_RANGE ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","TEMPERATURE_OUT_OF_RANGE",false]
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,TEMPERATURE_OUT_OF_RANGE,false
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.OPERATING_VOLTAGE ==> UNIT: "undefined" (min: 0, max: 25.2) From "3.1" => "3.1"
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","OPERATING_VOLTAGE",3.1]
hm-rpc.1 | 2021-01-09 18:06:00.853 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,OPERATING_VOLTAGE,3.1
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.OPERATING_VOLTAGE_STATUS ==> UNIT: "undefined" (min: NORMAL, max: EXTERNAL) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","OPERATING_VOLTAGE_STATUS",0]
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,OPERATING_VOLTAGE_STATUS,0
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.RSSI_DEVICE ==> UNIT: "undefined" (min: -128, max: 127) From "-65" => "-65"
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","RSSI_DEVICE",-65]
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,RSSI_DEVICE,-65
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.UNREACH ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","UNREACH",false]
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,UNREACH,false
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.LOW_BAT ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:06:00.852 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","LOW_BAT",false]
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,LOW_BAT,false
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.DUTY_CYCLE ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","DUTY_CYCLE",false]
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,DUTY_CYCLE,false
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.CONFIG_PENDING ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:06:00.851 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","CONFIG_PENDING",false]
hm-rpc.1 | 2021-01-09 18:06:00.850 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,CONFIG_PENDING,false
hm-rpc.1 | 2021-01-09 18:04:40.711 | warn | (6272) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions
hm-rpc.1 | 2021-01-09 18:04:40.709 | debug | (6272) hm-rpc.1.CENTRAL.0.PONG ==> UNIT: "none" (min: none, max: none) From "Medion(Test):hm-rpc.1" => "Medion(Test):hm-rpc.1"
hm-rpc.1 | 2021-01-09 18:04:40.709 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","CENTRAL:0","PONG","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:04:40.707 | debug | (6272) PING ok
hm-rpc.1 | 2021-01-09 18:04:40.686 | debug | (6272) Send PING...
hm-rpc.1 | 2021-01-09 18:04:40.686 | debug | (6272) [KEEPALIVE] Check if connection is alive
hm-rpc.1 | 2021-01-09 18:04:15.022 | debug | (6272) system.adapter.admin.0: logging false
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.HUMIDITY_STATUS ==> UNIT: "undefined" (min: NORMAL, max: UNDERFLOW) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","HUMIDITY_STATUS",0]
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,HUMIDITY_STATUS,0
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.ACTUAL_TEMPERATURE_STATUS ==> UNIT: "undefined" (min: NORMAL, max: UNDERFLOW) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","ACTUAL_TEMPERATURE_STATUS",0]
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,ACTUAL_TEMPERATURE_STATUS,0
hm-rpc.1 | 2021-01-09 18:03:38.648 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.HUMIDITY ==> UNIT: "%" (min: 0, max: 100) From "76" => "76"
hm-rpc.1 | 2021-01-09 18:03:38.647 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","HUMIDITY",76]
hm-rpc.1 | 2021-01-09 18:03:38.647 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,HUMIDITY,76
hm-rpc.1 | 2021-01-09 18:03:38.647 | debug | (6272) hm-rpc.1.000EDBE9992D89.1.ACTUAL_TEMPERATURE ==> UNIT: "�C" (min: -3276.8, max: 3276.7) From "0.9" => "0.9"
hm-rpc.1 | 2021-01-09 18:03:38.647 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:1","ACTUAL_TEMPERATURE",0.9]
hm-rpc.1 | 2021-01-09 18:03:38.647 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:1,ACTUAL_TEMPERATURE,0.9
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.ERROR_CODE ==> UNIT: "undefined" (min: 0, max: 255) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","ERROR_CODE",0]
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,ERROR_CODE,0
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.TEMPERATURE_OUT_OF_RANGE ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","TEMPERATURE_OUT_OF_RANGE",false]
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,TEMPERATURE_OUT_OF_RANGE,false
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.OPERATING_VOLTAGE ==> UNIT: "undefined" (min: 0, max: 25.2) From "3.1" => "3.1"
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","OPERATING_VOLTAGE",3.1]
hm-rpc.1 | 2021-01-09 18:03:38.638 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,OPERATING_VOLTAGE,3.1
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.OPERATING_VOLTAGE_STATUS ==> UNIT: "undefined" (min: NORMAL, max: EXTERNAL) From "0" => "0"
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","OPERATING_VOLTAGE_STATUS",0]
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,OPERATING_VOLTAGE_STATUS,0
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.RSSI_DEVICE ==> UNIT: "undefined" (min: -128, max: 127) From "-59" => "-59"
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","RSSI_DEVICE",-59]
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,RSSI_DEVICE,-59
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.UNREACH ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","UNREACH",false]
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,UNREACH,false
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.LOW_BAT ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:03:38.637 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","LOW_BAT",false]
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,LOW_BAT,false
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.DUTY_CYCLE ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","DUTY_CYCLE",false]
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,DUTY_CYCLE,false
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) hm-rpc.1.000EDBE9992D89.0.CONFIG_PENDING ==> UNIT: "undefined" (min: false, max: true) From "false" => "false"
hm-rpc.1 | 2021-01-09 18:03:38.636 | debug | (6272) xmlrpc <- event ["Medion(Test):hm-rpc.1","000EDBE9992D89:0","CONFIG_PENDING",false]
hm-rpc.1 | 2021-01-09 18:03:38.635 | debug | (6272) xml multicall <event>: Medion(Test):hm-rpc.1,000EDBE9992D89:0,CONFIG_PENDING,false
hm-rpc.1 | 2021-01-09 18:03:11.007 | info | (6272) new HMIP devices/channels after filter: 0
hm-rpc.1 | 2021-01-09 18:03:10.986 | debug | }
hm-rpc.1 | 2021-01-09 18:03:10.986 | debug | }
hm-rpc.1 | 2021-01-09 18:03:10.986 | debug | emit(doc._id, {ADDRESS:(doc.native?doc.native.ADDRESS:''),VERSION:(doc.native?doc.native.VERSION:'')});
hm-rpc.1 | 2021-01-09 18:03:10.986 | debug | if (doc._id.match(/^hm-rpc\.[0-9]+\.\*?[A-Za-z0-9_-]+(\.[0-9]+)?$/)) {
hm-rpc.1 | 2021-01-09 18:03:10.986 | debug | (6272) No suitable Lua script, fallback to keys!: function(doc) {
hm-rpc.1 | 2021-01-09 18:03:10.980 | info | (6272) xmlrpc <- newDevices 62
hm-rpc.1 | 2021-01-09 18:03:10.728 | info | (6272) xmlrpc -> 0 devices
hm-rpc.1 | 2021-01-09 18:03:10.706 | debug | }
hm-rpc.1 | 2021-01-09 18:03:10.706 | debug | }
hm-rpc.1 | 2021-01-09 18:03:10.706 | debug | emit(doc._id, {ADDRESS:(doc.native?doc.native.ADDRESS:''),VERSION:(doc.native?doc.native.VERSION:'')});
hm-rpc.1 | 2021-01-09 18:03:10.706 | debug | if (doc._id.match(/^hm-rpc\.[0-9]+\.\*?[A-Za-z0-9_-]+(\.[0-9]+)?$/)) {
hm-rpc.1 | 2021-01-09 18:03:10.706 | debug | (6272) No suitable Lua script, fallback to keys!: function(doc) {
hm-rpc.1 | 2021-01-09 18:03:10.704 | info | (6272) xmlrpc <- listDevices ["Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:03:10.681 | debug | (6272) start ping interval
hm-rpc.1 | 2021-01-09 18:03:10.680 | debug | (6272) clear connecting interval
hm-rpc.1 | 2021-01-09 18:03:10.680 | info | (6272) Connected
hm-rpc.1 | 2021-01-09 18:03:10.655 | debug | (6272) start connecting interval
hm-rpc.1 | 2021-01-09 18:03:10.649 | debug | (6272) xmlrpc -> 192.168.178.99:2010/ init ["http://192.168.178.20:2010","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:03:10.648 | debug | (6272) Connect...
hm-rpc.1 | 2021-01-09 18:03:10.648 | info | (6272) xmlrpc client is trying to connect to 192.168.178.99:2010/ with ["http://192.168.178.20:2010","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:03:10.647 | info | (6272) xmlrpc server is trying to listen on 192.168.178.20:2010
hm-rpc.1 | 2021-01-09 18:03:10.507 | info | (6272) starting. Version 1.14.28 in C:/Program Files/iobroker/Test/node_modules/iobroker.hm-rpc, node: v12.20.1, js-controller: 3.2.3
hm-rpc.1 | 2021-01-09 18:03:10.318 | debug | (6272) Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.1 | 2021-01-09 18:03:09.816 | debug | (6272) statesDB connected
hm-rpc.1 | 2021-01-09 18:03:09.816 | debug | (6272) States connected to redis: 127.0.0.1:9000
hm-rpc.1 | 2021-01-09 18:03:09.801 | debug | (6272) States create User PubSub Client
hm-rpc.1 | 2021-01-09 18:03:09.800 | debug | (6272) States create System PubSub Client
hm-rpc.1 | 2021-01-09 18:03:09.792 | debug | (6272) Redis States: Use Redis connection: 127.0.0.1:9000
hm-rpc.1 | 2021-01-09 18:03:09.791 | debug | (6272) objectDB connected
hm-rpc.1 | 2021-01-09 18:03:09.788 | debug | (6272) Objects connected to redis: 127.0.0.1:9013
hm-rpc.1 | 2021-01-09 18:03:09.757 | debug | (6272) Objects client initialize lua scripts
hm-rpc.1 | 2021-01-09 18:03:09.756 | debug | (6272) Objects create User PubSub Client
hm-rpc.1 | 2021-01-09 18:03:09.755 | debug | (6272) Objects create System PubSub Client
hm-rpc.1 | 2021-01-09 18:03:09.736 | debug | (6272) Objects client ready ... initialize now
hm-rpc.1 | 2021-01-09 18:03:09.232 | debug | (6272) Redis Objects: Use Redis connection: 127.0.0.1:9013
hm-rpc.1 | 2021-01-09 18:03:04.109 | debug | (6376) [MSSG] Received: {"command":"stopInstance","message":null,"from":"system.host.Medion(Test)","callback":{"message":null,"id":4,"ack":false,"time":1610211784107},"_id":84987690}
hm-rpc.1 | 2021-01-09 18:02:40.418 | debug | (6376) system.adapter.admin.0: logging false
hm-rpc.1 | 2021-01-09 18:01:40.680 | info | (6376) new HMIP devices/channels after filter: 0
hm-rpc.1 | 2021-01-09 18:01:40.660 | debug | }
hm-rpc.1 | 2021-01-09 18:01:40.660 | debug | }
hm-rpc.1 | 2021-01-09 18:01:40.660 | debug | emit(doc._id, {ADDRESS:(doc.native?doc.native.ADDRESS:''),VERSION:(doc.native?doc.native.VERSION:'')});
hm-rpc.1 | 2021-01-09 18:01:40.660 | debug | if (doc._id.match(/^hm-rpc\.[0-9]+\.\*?[A-Za-z0-9_-]+(\.[0-9]+)?$/)) {
hm-rpc.1 | 2021-01-09 18:01:40.660 | debug | (6376) No suitable Lua script, fallback to keys!: function(doc) {
hm-rpc.1 | 2021-01-09 18:01:40.658 | info | (6376) xmlrpc <- newDevices 62
hm-rpc.1 | 2021-01-09 18:01:40.433 | info | (6376) xmlrpc -> 0 devices
hm-rpc.1 | 2021-01-09 18:01:40.397 | debug | }
hm-rpc.1 | 2021-01-09 18:01:40.397 | debug | }
hm-rpc.1 | 2021-01-09 18:01:40.397 | debug | emit(doc._id, {ADDRESS:(doc.native?doc.native.ADDRESS:''),VERSION:(doc.native?doc.native.VERSION:'')});
hm-rpc.1 | 2021-01-09 18:01:40.397 | debug | if (doc._id.match(/^hm-rpc\.[0-9]+\.\*?[A-Za-z0-9_-]+(\.[0-9]+)?$/)) {
hm-rpc.1 | 2021-01-09 18:01:40.397 | debug | (6376) No suitable Lua script, fallback to keys!: function(doc) {
hm-rpc.1 | 2021-01-09 18:01:40.396 | info | (6376) xmlrpc <- listDevices ["Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:01:40.372 | debug | (6376) start ping interval
hm-rpc.1 | 2021-01-09 18:01:40.371 | debug | (6376) clear connecting interval
hm-rpc.1 | 2021-01-09 18:01:40.371 | info | (6376) Connected
hm-rpc.1 | 2021-01-09 18:01:40.343 | debug | (6376) start connecting interval
hm-rpc.1 | 2021-01-09 18:01:40.337 | debug | (6376) xmlrpc -> 192.168.178.99:2010/ init ["http://192.168.178.20:2010","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:01:40.337 | debug | (6376) Connect...
hm-rpc.1 | 2021-01-09 18:01:40.336 | info | (6376) xmlrpc client is trying to connect to 192.168.178.99:2010/ with ["http://192.168.178.20:2010","Medion(Test):hm-rpc.1"]
hm-rpc.1 | 2021-01-09 18:01:40.336 | info | (6376) xmlrpc server is trying to listen on 192.168.178.20:2010
hm-rpc.1 | 2021-01-09 18:01:40.257 | info | (6376) starting. Version 1.14.28 in C:/Program Files/iobroker/Test/node_modules/iobroker.hm-rpc, node: v12.20.1, js-controller: 3.2.3
hm-rpc.1 | 2021-01-09 18:01:39.431 | debug | (6376) Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.1 | 2021-01-09 18:01:39.258 | debug | (6376) statesDB connected
hm-rpc.1 | 2021-01-09 18:01:39.257 | debug | (6376) States connected to redis: 127.0.0.1:9000
hm-rpc.1 | 2021-01-09 18:01:39.251 | debug | (6376) States create User PubSub Client
hm-rpc.1 | 2021-01-09 18:01:39.250 | debug | (6376) States create System PubSub Client
hm-rpc.1 | 2021-01-09 18:06:32.542 | debug | (6272) system.adapter.admin.0: logging true

`

**Comment by foxriver76** [comment]
Upload gemacht?

**Comment by sigi2345** [comment]
> Upload gemacht?

Ja

**Comment by foxriver76** [comment]
hm ok, ist ne hmip instanz oder?

**Comment by foxriver76** [comment]
hmip nutzt `0.CENTRAL.PONG` und rfd nur `CENTRAL.PONG`, daher hats da net gefunzt, dann mit 1.14.29

**Comment by sigi2345** [comment]
> hmip nutzt `0.CENTRAL.PONG` und rfd nur `CENTRAL.PONG`, daher hats da net gefunzt, dann mit 1.14.29

Warn weg! Danke
