### ISSUE TITLE
HmIP-PSM 2.STATE boolean

### ISSUE THREAD

**Issue by sgc-fireball** [ioBroker/ioBroker.hm-rpc#300]
**Describe the bug**
In most cases, if i want to turn on or off the adapter logs the following error:

Adapter | Datetime | Level | Message
-- | -- | -- | --
hm-rpc.1 | 2021-01-10 19:39:03.634 | error | (31362) Error: XML-RPC fault: Invalid parameter or value
hm-rpc.1 | 2021-01-10 19:39:03.633 | error | (31362) xmlrpc -> setValue ["0001DBE9915AD5:2","STATE",true] BOOL

**To Reproduce**
JavaScript Adapter: 
`setState('hm-rpc.1.0001DBE9915AD5.2.STATE', true);`
OR
`Alexa, schalte Steckdose ein.`

**Expected behavior**
No error message and the smartplug switch the state.

**Screenshots & Logfiles**
![example](https://user-images.githubusercontent.com/4587633/104132235-2c58cf80-537c-11eb-9849-e37173e3a7b1.PNG)

**Versions:**
 - hm-rpc version: 1.14.24
 - hm-rega version: 3.0.6
 - JS-Controller version: update to date
 - Node version: 10.22.0
 - Operating system: Raspbian 10 buster
 - CCU model: raspberrymatic
 - CCU firmware: 3.53.30.20200919

**Additional context**

**Comment by foxriver76** [comment]
Fehler kommt von der CCU kann zb unreachable per dir cycle sein

**Comment by foxriver76** [comment]
Zeig mal das raw vom Datenpunkte

**Comment by sgc-fireball** [comment]
Command:
`console.log(JSON.stringify(getObject('hm-rpc.1.0001DBE9915AD5.2.STATE')));`
Output:
`{"type":"state","common":{"name":"HMIP-PSM 0001DBE9915AD5:2.STATE","def":false,"type":"boolean","read":true,"write":false,"role":"state"},"native":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"STATE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"SWITCH_TRANSMITTER.STATE"},"from":"system.adapter.hm-rega.0","user":"system.user.admin","ts":1608385164879,"_id":"hm-rpc.1.0001DBE9915AD5.2.STATE","acl":{"object":1632,"state":1632,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}`

Command:
`console.log(JSON.stringify(getState('hm-rpc.1.0001DBE9915AD5.2.STATE')));`
Output:
` {"val":false,"ack":true,"ts":1610365336752,"q":0,"from":"system.adapter.hm-rpc.1","user":"system.user.admin","lc":1610304521419}`

Über die TinyMatic App lässt sich die Dose jeder Zeit steuern. über Alexa muss ich den Befehl meist 3-5 mal abschicken dann klappt es irgendwann. Alle anderen Geräte lassen sich sofort und ohne Probleme schalten. Diese tauchen bis jetzt ausschließlich bei den HmIP-PSM auf.

**Comment by foxriver76** [comment]
Hm.. schaut eigentlich alles gut aus. API sagt ist ein Boolean und so ist der DP auch angelegt. Einzige was sein könnte, dass ein Update  der Device-Firmware die Parameter geändert hat, dann könnte man das mal neu anlegen. Halte ich allerdings für unwahrscheinlich. Checke auch mal bitte den DC des Gerätes, wenn du da in einer Loop die Werte setzt, könnte den Fehler auch verursachen, das XML-API Paket ist da etwas unsepzifisch mit den Error Meldungen

**Comment by sgc-fireball** [comment]
Der DC liegt bei 37% im gesamten System. die HmIP-PSM haben die Firmware 2.18.14.
Was ich nachher mal testen kann ist mit einem ngrep die  Kommunikation zwischen Zentrale und iobroker.

**Comment by foxriver76** [comment]
> Der DC liegt bei 37% im gesamten System. die HmIP-PSM haben die Firmware 2.18.14.

Einfach mal das Objekt im ioBroker löschen und Adapter neustarten, dann würde er die neuen Metas ranziehen, aber ich glaube kaum, dass das jetzt was anderes als ein boolscher Wert ist.

**Comment by sgc-fireball** [comment]
T 192.168.2.83:40650 -> 192.168.2.77:2010 [AP] #32
POST / HTTP/1.1.
User-Agent: NodeJS XML-RPC Client.
Content-Type: text/xml.
Accept: text/xml.
Accept-Charset: UTF8.
Connection: Keep-Alive.
Content-Length: 261.
Host: 192.168.2.77:2010.

`<?xml version="1.0"?><methodCall><methodName>setValue</methodName><params><param><value><string>0001DBE9915C67:2</string></value></param><param><value><string>STATE</string></value></param><param><value><boolean>0</boolean></value></param></params></methodCall>`

T 192.168.2.77:2010 -> 192.168.2.83:40650 [AP] #34
HTTP/1.1 200 OK.
Content-Length: 270.
X-Frame-Options: SAMEORIGIN.
X-Content-Type-Options: nosniff.
X-XSS-Protection: 1; mode=block.
X-Robots-Tag: none.
X-Download-Options: noopen.
X-Permitted-Cross-Domain-Policies: none.
Referrer-Policy: no-referrer.
Cache-Control: private, no-cache, must-revalidate, no-transform, max-age=0.
Date: Tue, 12 Jan 2021 17:14:45 GMT.

`<?xml version="1.0" encoding="ISO-8859-1"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><i4>-5</i4></value></member><member><name>faultString</name><value>Invalid parameter or value</value></member></struct></value></fault></methodResponse>`

**Comment by sgc-fireball** [comment]
Auch nach dem einlesen selber Fehler.
`{"type":"state","common":{"name":"HMIP-PSM 0001DBE9915AD5:2.STATE","def":false,"type":"boolean","read":true,"write":false,"role":"state"},"native":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":1,"ID":"STATE","TYPE":"BOOL","DEFAULT":false,"CONTROL":"SWITCH_TRANSMITTER.STATE"},"from":"system.adapter.hm-rega.0","user":"system.user.admin","ts":1610472126870,"_id":"hm-rpc.1.0001DBE9915AD5.2.STATE","acl":{"object":1632,"state":1632,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}`

`{"val":false,"ack":true,"ts":1610477991937,"q":0,"from":"system.adapter.hm-rpc.1","user":"system.user.admin","lc":1610472120529}`

**Comment by foxriver76** [comment]
Habe gelesen der psm wird über Kanal 3 geschalten, wäre das möglich? 

Jetzt fällt mir auch oben im Objekt auf dass da write false steht, somit ein read only Parameter der api

**Comment by sgc-fireball** [comment]
..................... @foxriver76  danke .... ja write: false sollte man sehen ....
