### ISSUE TITLE
falsche default-werte in HM-SWDO

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.hm-rpc#304]
number <-> string ....
die falschen Werte sind im normalen Ablauf eher nicht zu bemerken, verursachen jedoch bei einigen Aktionen und nach Neustarts von Adaptern/Scripts diberse Probleme
`{
  "type": "state",
  "common": {
    "name": "Fenster Bad:1.STATE",
    "def": "CLOSED",
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "states": {
      "0": "CLOSED",
      "1": "OPEN"
    },
    "role": "value.window"
  },
  "native": {
    "MIN": "CLOSED",
    "UNIT": "\"\"",
    "OPERATIONS": 5,
    "MAX": "OPEN",
    "FLAGS": 1,
    "ID": "STATE",
    "TAB_ORDER": 0,
    "TYPE": "ENUM",
    "DEFAULT": "CLOSED",
    "VALUE_LIST": [
      "CLOSED",
      "OPEN"
    ],
    "CONTROL": "DOOR_SENSOR.STATE"
  },`

**Comment by foxriver76** [comment]
jop, min max wird bei hmip value listen korrekt umgewandelt def nicht, implementiere es später

**Comment by fs-plugins** [comment]
danke
