### ISSUE TITLE
HM-CC-TC possible states wrong

### ISSUE THREAD

**Issue by dg1lxs** [ioBroker/ioBroker.hm-rpc#305]
**Describe the bug**
I needed to perform a backup recovery of my iobroker combined with a new generation of the object tree of the hm-rpc adapter. After this my possible states for the SETPOINT Datapoint of my HM-CC-TC Thermostates are wrong. I can not configure a temperature, but only "VENT_CLOSED" and "VENT_OPEN"

**To Reproduce**
<img width="1468" alt="Bildschirmfoto 2021-01-19 um 13 01 01" src="https://user-images.githubusercontent.com/77673186/105032047-816ca380-5a56-11eb-8f0e-057e9ee79dba.png">

**Expected behavior**
A Temperature should be able to be set in 0.5 degree steps

**Screenshots & Logfiles**
Attached the object definition from iobroker,
[definition.txt](https://github.com/ioBroker/ioBroker.hm-rpc/files/5835713/definition.txt)

**Versions:**
 - hm-rpc version: 1.14.31
 - hm-rega version: 3.0.7
 - JS-Controller version: 3.1.6
 - Node version: v12.20.1
 - Operating system: Debian (with Docker image)
 - CCU model: raspberrymatic ccu3
 - CCU firmware: 3.53.34.20201121

**Additional context**

**Comment by foxriver76** [comment]
I think this `SPECIAL` handling hasn't changed for years (for real), but if the object was very old, this may be the case that something has changed in between.

However, I am not really aware if I will break other devices if we no longer convert `SPECIAL` attributes to `states`. Also this should only be an cosmetical problem in admin, setting a value via script should actucaly set the temperature.

**Comment by dg1lxs** [comment]
OK, the setting via script and the pen is working...
