### ISSUE TITLE
Fehlende Datenpunkte Rauchmelder HM-SEC-SD

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rpc#306]
Ich habe einen Rauchmelder HM-SEC-SD von der Zentrale abgemeldet (Gelöscht mit Werksreset) und anschließend (hat rot geblinkt - aber nach Reinigung wieder funktioniert) wieder an der Zentrale angemeldet.
Leider werden durch den hm-rpc nicht mehr alle Datenpunkte im Kanal 0 erzeugt (alle mit _ALARM Endung).
Geräte neu einlesen (einmalig) in der Instance habe ich schon mehrfach durchgeführt.
Hier ein Screenshot mit einem 2. Rauchmelder zum Vergleich. 
![image](https://user-images.githubusercontent.com/36857242/105624796-bb59f300-5e24-11eb-9b30-b2a963b9cde0.png)
Meine Konfiguration:
Node.js v12.20.0 
NPM 6.14.8
js-controller 3.1.6
hm-rega 3.0.7
hm-rpc 1.14.31

**Comment by Knallochse** [comment]
Ich möchte melden, dass nach 2 Tagen die fehlenden Datenpunkte auf einmal im Objektbaum zu sehen waren.
Ich denke das Problem ist erledigt und dieser Issue kann geschlossen werden

**Comment by foxriver76** [comment]
Manchmal liegt es auch am Admin am besten ist es mit der Kommandozeile zu schauen oder neuer privater Tab Admin ist auch relativ zuverlässig.
