### ISSUE TITLE
Error 'State "hm-rpc.1.CENTRAL.0.PONG" has no existing object' since update to js-controller 3.2

### ISSUE THREAD

**Issue by ahnungsbefreit** [ioBroker/ioBroker.hm-rpc#309]
**Describe the bug**
Using only the "stable" versions of ioBroker and all adapters, hm-rpc and hm-rega have been working without issues for months now. With the update to js-controller 3.2 and a corresponding update of hm-rega to 3.0.16, it still seem to work all fine but I get recurring error messages in the log like this:

`hm-rpc.1 | 2021-02-19 10:39:03.752 | warn | (18073) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions`

`hm-rpc.1 | 2021-02-19 10:37:33.752 | warn | (18073) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions`

`hm-rpc.1 | 2021-02-19 10:36:03.751 | warn | (18073) State "hm-rpc.1.CENTRAL.0.PONG" has no existing object, this might lead to an error in future versions`

**To Reproduce**

Update as described above, watch the log :-)

**Expected behavior**
No error message.

**Screenshots & Logfiles**
see above

**Versions:**
 - hm-rpc version: 1.14.24
 - hm-rega version: 3.0.16
 - JS-Controller version: 3.2.16
 - Node version: 12.20.2
 - Operating system: debian (VM in ProxMox)
 - CCU model: debmatic
 - CCU firmware: 3.55.10.66

**Additional context**
n/a

**Comment by foxriver76** [comment]
Already fixed in latest
