### ISSUE TITLE
HomeMatic IP type hm-rpc always deletes all devices upon startup

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.hm-rpc#31]
For some reasons I couldn't yet identify why a "HomeMatic IP" type hm-rpc always deletes all devices upon startup or reconnection, as can be seen here:

```
hm-rpc.2	2017-01-15 16:41:48.418	info	hm-rpc.2 Delete channel hm-rpc.2.XXXX.0
hm-rpc.2	2017-01-15 16:41:48.417	info	hm-rpc.2 Delete channel hm-rpc.2.XXXX.1
hm-rpc.2	2017-01-15 16:41:47.339	info	hm-rpc.2 xmlrpc <- newDevices 19
hm-rpc.2	2017-01-15 16:41:47.216	info	hm-rpc.2 device XXXX deleted
hm-rpc.2	2017-01-15 16:41:47.216	info	hm-rpc.2 Delete channel hm-rpc.2.XXXX.0
[...]
hm-rpc.2	2017-01-15 16:41:47.211	info	hm-rpc.2 xmlrpc <- deleteDevices 18
hm-rpc.2	2017-01-15 16:41:47.144	info	hm-rpc.2 xmlrpc -> 18 devices
hm-rpc.2	2017-01-15 16:41:47.119	info	hm-rpc.2 xmlrpc <- listDevices ["hm-rpc.2"]
hm-rpc.2	2017-01-15 16:41:47.081	info	hm-rpc.2 Connected
hm-rpc.2	2017-01-15 16:41:47.058	info	hm-rpc.2 xmlrpc client is trying to connect to ccupi.fritz.box:2010 with ["http://192.168.5.2:2012","hm-rpc.2"]
hm-rpc.2	2017-01-15 16:41:47.058	info	hm-rpc.2 xmlrpc server is trying to listen on 192.168.5.2:2012
hm-rpc.2	2017-01-15 16:41:46.777	info	hm-rpc.2 starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v4.7.2
```

Therefore all devices are unfortunately cleared out and then afterwards regenerated which also deletes/removes all names hm-rega is placing/renaming.

Looking at what a normal BidCos-RF (rfd) hm-rpc instance does, it seems there are some differences in the way the rpc server receives changes from the connected CCU: 
```
hm-rpc.0	2017-01-15 16:39:41.624	info	hm-rpc.0 Connected
hm-rpc.0	2017-01-15 16:39:41.463	info	hm-rpc.0 xmlrpc -> 658 devices
hm-rpc.0	2017-01-15 16:39:41.302	info	hm-rpc.0 xmlrpc <- listDevices ["hm-rpc.0"]
hm-rpc.0	2017-01-15 16:39:41.297	info	hm-rpc.0 xmlrpc <- system.listMethods ["hm-rpc.0"]
hm-rpc.0	2017-01-15 16:39:41.280	info	hm-rpc.0 xmlrpc client is trying to connect to ccupi.fritz.box:2001 with ["http://192.168.5.2:2001","hm-rpc.0"]
hm-rpc.0	2017-01-15 16:39:41.279	info	hm-rpc.0 xmlrpc server is trying to listen on 192.168.5.2:2001
hm-rpc.0	2017-01-15 16:39:41.051	info	hm-rpc.0 starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v4.7.2
```

So the question is, what to do here and how to debug this situation any further so that we can change hm-rpc that it doesn't delete all HmIP-type device upon restart or reconnection of hm-rpc?!?

**Comment by jens-maus** [comment]
After some investigation I found out that the XMLRPC interaction with the XMLRPC for HomeMaticIP works slightly different compared to the BidCos-RF :(

For debug purposes I queried the RPC server according to the documentation and here are the results:

```
XML-RPC server listening on port 2055
connected to ccu, sending init with server url
init succeeded
listDevices: test
listDevices response: [{"ADDRESS":"000213C990963D","VERSION":1}]
deleteDevices: ["test",["000213C990963D"]]
params.count: 1
newDevices: ["test",[{"TYPE":"HMIP-PS","SUBTYPE":"PS","ADDRESS":"000213C990963D","RF_ADDRESS":9593328,"CHILDREN":["000213C990963D:0","000213C990963D:1","000213C990963D:2","000213C990963D:3","000213C990963D:4","000213C990963D:5"],"PARENT":"","PARENT_TYPE":"","INDEX":0,"AES_ACTIVE":1,"PARAMSETS":["MASTER","SERVICE"],"FIRMWARE":"1.4.0","AVAILABLE_FIRMWARE":"0.0.0","UPDATABLE":true,"FIRMWARE_UPDATE_STATE":"UP_TO_DATE","VERSION":1,"FLAGS":1,"LINK_SOURCE_ROLES":"","LINK_TARGET_ROLES":"","DIRECTION":0,"GROUP":"","TEAM":"","TEAM_TAG":"","TEAM_CHANNELS":[],"INTERFACE":"","ROAMING":0,"RX_MODE":0},{"TYPE":"MAINTENANCE","SUBTYPE":"","ADDRESS":"000213C990963D:0","RF_ADDRESS":0,"CHILDREN":[],"PARENT":"000213C990963D","PARENT_TYPE":"HMIP-PS","INDEX":0,"AES_ACTIVE":1,"PARAMSETS":["MASTER","VALUES","SERVICE"],"FIRMWARE":"","AVAILABLE_FIRMWARE":"","UPDATABLE":true,"FIRMWARE_UPDATE_STATE":"","VERSION":1,"FLAGS":1,"LINK_SOURCE_ROLES":"","LINK_TARGET_ROLES":"","DIRECTION":0,"GROUP":"","TEAM":"","TEAM_TAG":"","TEAM_CHANNELS":[],"INTERFACE":"","ROAMING":0,"RX_MODE":0}]]
params.count: 1
```

Let me explain:

1. See that I am sending a proper response in the `listDevices` RPC method: `[{"ADDRESS":"000213C990963D","VERSION":1}]`
2. Note, that still the `deleteDevices` method is called with a list of devices to be deleted and in there the address of the particular device I was listing as being existent is sent by the CCU
3. In addition, the `newDevices` method is called with information on the same device, though I have explicitly stated in the `listDevices` method that I know that device already.
4. If I do the same to the BidCos-RF XMLRPC Interface and add one device to the `listDevices` response that I already know about, the `newDevices` method is called without listing this device and the `deleteDevices` method call also doesn't contain that device as it should be.

Now the question arises why does the XMLRPC for HomeMaticIP behaves different than the XMLRPC for BidCos-RF. Please also note that there is no BIN-RPC for HomeMaticIP, thought I couldn't test/use that possibility.

Currently I do believe that this might be a bug or limitation in the XMLRPC implementation for HomeMaticIP, but I am not 100% sure. Before I am going to work on a potential workaround for that problem I would like to ask here for opinions and comments?!?

**Comment by Apollon77** [comment]
Bluefox hatte mal von eq3 das DOkument hier bekommen als Infos zu HMIP
http://www.eq-3.de/service/downloads.html?id=182

Vllt steht da ja ne Info dazu drin

**Comment by jens-maus** [comment]
Das Dokument hab ich schon durch, da steht dazu nix drin. Ist wirklich mysteriös. Ich weiss nicht warum bei jedem listDevices() ein deleteDevices() mit all diesen devices geschickt wird. Irgendwie will die CCU immer das alle gemeldeten devices gelöscht werden - warum auch immer?!? Kannst du das nachvollziehen bei dir? Ich werd es auch noch einmal mit einer CCU2 probieren, ich vermute allerdings das da nichts anderes bei rüberkommt.

**Comment by Apollon77** [comment]
Hab keine HMIP Devices :-(
Aber wäre dann nicht die Idee "einfach" die Devices die gemeldet aber auch in "deleted" stehen einfach bei "deleted" rauszuwerfen wenn man die Nachricht verarbeitet?

**Comment by jens-maus** [comment]
eine Idee für einen Workaround hab ich natürlich schon. Und das ist schon so in der Art wie du darstellt. D.h. einfach bei den verschiedenen Methoden selbst die Daten analysieren – auch wenn das IMHO ne sehr unschöne Sache ist/wird. Im Grunde würde ich jetzt einfach bei `listDevices`immer einen leeren response senden, dann wird deleteDevices auch nicht gesendet von der CCU und dann müsste man selbst nur im `newDevices` eben den gemeldeten Stand mit dem aktuellen überprüfen und devices die nicht gemeldet werden selbst dann rauswerfen. Wie gesagt ein Workaround und unschön. Aber wenn das wirklich ein CCU-Bug ist dann haben wir da ggf. keine andere Wahl.

**Comment by Apollon77** [comment]
Also es sollte so funktionieren: jeder hm-rpc-Adapter hat ein "updated"-State der wird nach einem "ForceInit"-Lauf auf "true" gesetzt.
Der hm-rega hat die alle Subscribed und reagiert darauf indem er das macht und die dann auf false setzt. Letzteres findet aber nie statt :-( Das sind die Fakten

**Comment by jens-maus** [comment]
Ups, hab den commit an das falsche ticket verlinkt..

**Comment by Apollon77** [comment]
Das ist noch offen ... Commit falsch verlinkt
