### ISSUE TITLE
Support HMIP-HDM1 - Werteeingabe nicht in % nur in 0,1 Schritte zwischen 0 und 1

### ISSUE THREAD

**Issue by diba78** [ioBroker/ioBroker.hm-rpc#311]
Hallo zusammen,

ich nutze aktuell einen ERFAL Rollo mit HMIP Anbindung. Es wird hier der HMIP-HDM1 genutzt. von der Idee her sollte er wie der HMIP-BROLL funktioneren. 

Der HMIP-HDM1 ist an eine Raspberrymatic angebunden. Im IOBroker wird er auch unter HM-RPC.1 als Device erkannt. Die Steuerung läuft über Kanal 1.

Nun zu meinem Problem. Ich kann die Variable WZ Rollo Balkonfenster Aktor.LEVEL nur mit Werten 0 bis 1 in 0.10 Schritte (dabei ist 0.10 = 10%) eintragen damit der Rollo ordentlich an die richtige Postion fährt.

Der Wert selbst wird schon mit dem richtigen % Wert im Feld angezeigt.

![grafik](https://user-images.githubusercontent.com/44620652/108608494-80b58d00-73c7-11eb-942b-32120909e7ac.png)

Ich kann nicht 10 % in das Feld eintragen. Dann zickt der Rollo rum. Er fährt dann komplett runter. Da die Werte nur wie oben beschrieben eintragen kann, bekomme ich das Device auch nicht ordentlich in einer Visualisierung zu laufen.

Hier die Informationen zu den Versionen:

 - hm-rpc version: 1.14.35
 - hm-rega version: 3.0.16
 - JS-Controller version: 3.2.16
 - Node version: v12.20.2
 - Operating system: Debian Buster
 - CCU model: raspberrymatic
 - CCU firmware: 3.55.10.20210213

Wenn noch weitere Informationen benötigt werden oder ich noch etwas testen kann bitte melden.

Vielen Dank schon mal vorab.

Gruß

**Comment by foxriver76** [comment]
Mal bitte hinter dem betroffenen Datenpunkt auf den Stift -> Tab raw und das hier posten.

**Comment by diba78** [comment]
Hallo foxriver76,

hier der Output:

{
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1613845975188,
  "common": {
    "name": "WZ Rollo Balkonfenster Aktor.LEVEL",
    "type": "number",
    "unit": "%",
    "role": "level",
    "def": 0,
    "min": 0,
    "max": 1.01,
    "read": true,
    "write": true
  },
  "native": {
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "UNIT": "%",
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "DEFAULT": 0
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.1.000044827E030B.1.LEVEL",
  "type": "state"
}

Gruß

Dirk

**Comment by foxriver76** [comment]
>     "max": 1.01,

Das sollte so definitiv nicht sein.. 

Hast du das Gerät heute erst angelernt?

Lösch mal bitte das Gerät aus den Objekten und starte den Adapter neu.

**Comment by diba78** [comment]
Nein habe das Gerät am Montag an die Raspberrymatic angelerent und in den IOBroker aufgenommen.

Habe das Gerät jetzt an der Raspberrymatic abgelernt (mit Zurücksetzen in Werkseinstellungen) und wieder neu angelernt. Danach die RPC 1 Instanz pausiert im IOBroker und danach das Gerät unter den Objekten gelöscht. Danach habe ich die Instanz neu gestartet.

Hier das Ergebnis vom RAW Output:

{
  "type": "state",
  "common": {
    "name": "HmIP-HDM1 000044827E030B:1.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1.01,
    "unit": "%"
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1613859710991,
  "_id": "hm-rpc.1.000044827E030B.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Leider bleibt es bei 1.01

**Comment by diba78** [comment]
In der Raspberrymatic kann ich auch nur einen Wert von 1.00 eintragen. Bei 1.01 tut sich nix.

![grafik](https://user-images.githubusercontent.com/44620652/108610135-9a5cd180-73d3-11eb-97d8-da93eed64506.png)

**Comment by foxriver76** [comment]
Ahja sehe es jetzt, CCU liefert mal wieder super inkonsitentes Geschichten, UNIT müsste `100%` sein oder MAX: 100 .. muss ich was im Adapter einbauen um die Werte um zu skalieren

**Comment by diba78** [comment]
jup da muss ich auch 0.10 Werten arbeiten.

**Comment by foxriver76** [comment]
Siehe meinen Edit.

**Comment by foxriver76** [comment]
https://github.com/eq-3/occu/issues/111

**Comment by diba78** [comment]
Vielen Dank für deine Unterstützung. Mal schauen was daraus wird :-) ich werde mich dann mal am Thema Alias versuchen. Ich bin noch nicht so tief im Thema IOBroker drin aber das wird schon.

Ich wünsche Dir noch einen schönes Rest Wochenende

**Comment by foxriver76** [comment]
.
