### ISSUE TITLE
Gruppennamen der virtuellen Geräte werden nicht synchronisiert

### ISSUE THREAD

**Issue by darkman242** [ioBroker/ioBroker.hm-rpc#312]
Gruppennamen der virtuellen Geräte werden nicht synchronisiert

![image](https://user-images.githubusercontent.com/46793576/109466235-b9a9cd80-7a69-11eb-8088-0561093bcbab.png)
![image](https://user-images.githubusercontent.com/46793576/109466282-c9c1ad00-7a69-11eb-80ef-9b388df49d2e.png)

**Comment by darkman242** [comment]
Gruppennamen der virtuellen Geräte werden nicht synchronisiert

![image](https://user-images.githubusercontent.com/46793576/109466235-b9a9cd80-7a69-11eb-8088-0561093bcbab.png)
![image](https://user-images.githubusercontent.com/46793576/109466282-c9c1ad00-7a69-11eb-80ef-9b388df49d2e.png)

**Comment by foxriver76** [comment]
Rega korrekt konfiguriert? RPC hat kein Zugriff auf Namen

**Comment by darkman242** [comment]
Sorry, mein Fehler. Rega-Konfig fehlte wirklich noch. Funktioniert jetzt. Danke für den Hinweis.
