### ISSUE TITLE
Heizungsthermostat Valve State Wert keine Anzeige mehr

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.hm-rpc#314]
Hallo, seit dem Firmware Update (3.57.4) der CCU3 wird der Valve State Wert unter dem HM RPC Adapter (1.14.35) vom HM-CC-RT-DN Heizungsthermostat nicht mehr angezeigt, bzw. bleibt der Wert bei 0 %

![Screenshot (3450)_LI](https://user-images.githubusercontent.com/41079106/110522488-3e06eb00-8111-11eb-9775-6c2e588a9288.jpg)

LG
Sigi

`Platform: Windows
RAM: 16 GB 
Node.js: 12.21.0
NPM: 6.14.10
JS Controler: 3.2.16
Admin: 4.2.1
Web: 3.3.0
Socket.io: 3.1.4
Script Engine: 5.0.9
IOT: 1.8.13
VIS: 1.3.8
HM-Rega: 3.0.16
HM-RPC: 1.14.35
Jarvis: 2.2.0
Backitup: 2.0.0
Cloud: 4.0.9
ICal: 1.9.1
iQontrol: 1.6.3`

**Comment by foxriver76** [comment]
Dann doch vermutlich ein Problem auf CCU Seite, wenn nach CCU Update? Ohne Log kann ich nicht sehen was die ccu liefert aber vermutlich 0.

**Comment by sigi2345** [comment]
> Dann doch vermutlich ein Problem auf CCU Seite, wenn nach CCU Update? Ohne Log kann ich nicht sehen was die ccu liefert aber vermutlich 0.

2021-03-09 19:58:09.185 - debug: hm-rpc.0 (11120) hm-rpc.0.OEQ0655913.4.VALVE_STATE ==> UNIT: "%" (min: 0, max: 100) From "0" => "0"

**Comment by foxriver76** [comment]
Da liefert die CCU beispielsweise 0. Was zeigt den die ccu auf der Weboberfläche an

**Comment by sigi2345** [comment]
> Da liefert die CCU beispielsweise 0. Was zeigt denn die ccu auf der Weboberfläche an

![Screenshot (3454)](https://user-images.githubusercontent.com/41079106/110529356-74486880-8119-11eb-9fe4-6169d1b709e8.png)

**Comment by sigi2345** [comment]
Erledigt, die Ist Temp war über der Soll Temp..., da kann er ja nicht heizen.

Oh Mann,...........
