### ISSUE TITLE
HmIP-BSM PRESS_LONG

### ISSUE THREAD

**Issue by Monox83** [ioBroker/ioBroker.hm-rpc#317]
Moin, ich nutze Kanal 1 nur als Taster, bei PRESS_SHORT funktioniert es super, bei PRESS_LONG wird 4 mal der Status übermittelt.
Dummy Script ist in der CCU3 angelegt.

hm-rpc.1	2021-04-05 08:23:18.536	debug	(21405) hm-rpc.1.00085BE98FXXXX.1.PRESS_LONG ==> UNIT: "undefined" (min: false, max: true) From "true" => "true"
hm-rpc.1	2021-04-05 08:23:18.535	debug	(21405) xmlrpc <- event ["iobroker:hm-rpc.1","00085BE98FXXXX:1","PRESS_LONG",true]
hm-rpc.1	2021-04-05 08:23:18.275	debug	(21405) hm-rpc.1.00085BE98XXXX.1.PRESS_LONG ==> UNIT: "undefined" (min: false, max: true) From "true" => "true"
hm-rpc.1	2021-04-05 08:23:18.275	debug	(21405) xmlrpc <- event ["iobroker:hm-rpc.1","00085BE98FXXXX:1","PRESS_LONG",true]
hm-rpc.1	2021-04-05 08:23:18.016	debug	(21405) hm-rpc.1.00085BE98XXXX.1.PRESS_LONG ==> UNIT: "undefined" (min: false, max: true) From "true" => "true"
hm-rpc.1	2021-04-05 08:23:18.015	debug	(21405) xmlrpc <- event ["iobroker:hm-rpc.1","00085BE98FXXXX:1","PRESS_LONG",true]
hm-rpc.1	2021-04-05 08:23:17.788	debug	(21405) hm-rpc.1.00085BE98XXXX.1.PRESS_LONG ==> UNIT: "undefined" (min: false, max: true) From "true" => "true"
hm-rpc.1	2021-04-05 08:23:17.787	debug	(21405) xmlrpc <- event ["iobroker:hm-rpc.1","00085BE98FXXXX:1","PRESS_LONG",true]

Grüße Monox

**Comment by foxriver76** [comment]
Moin, 

bitte für deutschen Support das Forum als erste Anlaufstelle nutzen. Ich schätze es hat mit Einstellungen des Gerätes auf der CCU zu tun - wie das Log zeigt, wird der Status auch vier mal von der CCU übertragen. Ich habe an der Stelle erst mal kein Plan, viele andere Nutzer welche ebenfalls PRESS_LONG und im besten Fall sogar von diesem Gerät nutzen können dir eher helfen.

beste Grüße

fox
