### ISSUE TITLE
sendto listdevices command error

### ISSUE THREAD

**Issue by tobyK2** [ioBroker/ioBroker.hm-rpc#318]
**Describe the bug**
sendTo with "listDevice" not working from javascript adapter

**To Reproduce**
1. Copy & Paste example
2. Error in Log File and no return

**Expected behavior**
List of Devices

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - hm-rpc version: 1.14.35

**Additional context**

Hi,
I want to send a listDevices command to the adapter but it ends with an error. Maybe I am totally wrong but as far as I understand the adapter code, the command "listDevices" is called from line 568 with parameters, but it must be always empty (line 1548).

![Unbenannt](https://user-images.githubusercontent.com/82417898/114468698-31802180-9bec-11eb-9f7a-3e224b902b2a.PNG)

![grafik](https://user-images.githubusercontent.com/82417898/114469204-fe8a5d80-9bec-11eb-9ead-90e2ccd19b2c.png)

I checked the target system with the Homematic Manager and the listDevices is working.

Thanks and best regards

**Comment by foxriver76** [comment]
Can you show the error message and the exact code used + which type of instance is running as the sendTo target, example works correctly at least against XML-RPC HMIP and Bid-Cos, however it can be that CuxD is more sensitive or that the behaviour changed between versions.

**Comment by tobyK2** [comment]
Thank you for the feedback.

Target system: it is not a cuxd, it is a homegear instance

Javascript Adapter Code:
`sendTo('hm-rpc.0', 'listDevices', {}, res => {
    log(JSON.stringify(res));
});


sendTo('hm-rpc.0', 'getParamsetDescription', {ID: 'KEQ0806557', paramType: 'VALUES'}, res => {
    log(JSON.stringify(res));
});`


==> The "listDevices" is not working, the "getParamsetDescription" is working.
 
Log-File: bin-rpc:
![bin-rpc-listDevices-logfile](https://user-images.githubusercontent.com/82417898/114623798-0bbc5080-9cb0-11eb-934d-84a9b8cb6705.PNG)

Log-File: xml-rpc:
![xml-rpc-listDevices-logfile](https://user-images.githubusercontent.com/82417898/114623848-1d055d00-9cb0-11eb-83fe-19c9c6a42332.PNG)

I included the empty "listDevice" code in the adapter for test with xml-rpc interface:
![test_code](https://user-images.githubusercontent.com/82417898/114624131-85543e80-9cb0-11eb-9da9-2c78d72208a6.PNG)

It is working
![xml-rpc-listDevices-codetest-logfile](https://user-images.githubusercontent.com/82417898/114624183-99983b80-9cb0-11eb-9f19-fd992d7d4456.PNG)

So if you say it is working with HMIP, I think the homegear implementation is more sensitive.

**Comment by foxriver76** [comment]
Please test if 1.14.36 also works. We now no longer send undefined entries if no ID is provided on this types of commands

**Comment by tobyK2** [comment]
It is working with the new version.
Thank you
