### ISSUE TITLE
HM-IP BROLL has value greater than max - Admin5

### ISSUE THREAD

**Issue by Maja61** [ioBroker/ioBroker.hm-rpc#326]
Since Update to Admin 5.0.12 and JS-Controller 3.3.5 i got these error messages from my HM-IP BROLL which are connected to CCU2 and raspberrymatic as well. 

`hm-rpc.1	2021-05-03 08:20:04.995	warn	State value to set for "hm-rpc.1.ID_Device.1.LEVEL" has value "48" greater than max "1.01"
hm-rpc.1	2021-05-03 08:14:37.984	warn	State value to set for "hm-rpc.1.ID_Device.1.LEVEL" has value "58" greater than max "1.01"
hm-rpc.1	2021-05-03 08:12:36.893	warn	State value to set for "hm-rpc.1.ID_Device.1.LEVEL" has value "68" greater than max "1.01"
hm-rpc.1	2021-05-03 08:02:08.390	warn	State value to set for "hm-rpc.1.ID_Device.1.LEVEL" has value "68" greater than max "1.01"
hm-rpc.2	2021-05-03 08:24:17.504	warn	State value to set for "hm-rpc.2.ID_Device.1.LEVEL" has value "31" greater than max "1.01"
hm-rpc.2	2021-05-03 08:21:22.271	warn	State value to set for "hm-rpc.2.ID_Device.1.LEVEL" has value "21" greater than max "1.01"`

**Comment by foxriver76** [comment]
If you delete the affected Devices and let the adapter create them again, are they still created with max 1.01 etc?

**Comment by isi07** [comment]
Hi
I have the same with HmIP-BDT and HmIP-PDT.
Admin 5.0.13
hm-rpc 1.14.37
JS-Controller 3.3.7

HmIP-BDT
hm-rpc.2	2021-05-03 22:05:18.179	warn	(9450) State value to set for "hm-rpc.2.ID_Device_BDT.3.LEVEL" has value "40.5" greater than max "1.01"

HmIP-PDT
hm-rpc.2	2021-05-03 22:04:47.751	warn	(9450) State value to set for "hm-rpc.2.ID_DEvice_PDT.2.LEVEL" has value "15" greater than max "1.01"

**Comment by foxriver76** [comment]
Can you show me the raw of the object please.

**Comment by Maja61** [comment]
Here is one of my affected:


{
  "type": "state",
  "common": {
    "name": "HmIP-eTRV-2 000A1BE9A726A6:1.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1.01,
    "unit": "%",
    "role": "level",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": 0,
        "changesRelogInterval": "60",
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rega.1",
  "user": "system.user.admin",
  "ts": 1612022422460,
  "_id": "hm-rpc.2.000A1BE9A726A6.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment]
Was it not that way that hm-rpc has that logic that for a "%" value it handles 0..1 but for values >1 assumes 0..100 and then divides that? Then min/max needs to be adjusted to that logic?!

**Comment by foxriver76** [comment]
Yes and no, eq3 does super inconsistent stuff here. Normally they provide the unit 100% if it should be scaled. Else they will send the real percent value, with the 0 1 force scaling we also get problems with cuxd devices.
