### ISSUE TITLE
Virtual Heating devices (INTxxxxx.1.CONTROL_MODE) outputs "State value" warnings since js-controller 3.3+

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.hm-rpc#332]
**Describe the bug**
Since js-controller 3.3+ the following warning messages are returned when virtual devices (heating groups) are sending updates:

```
State value to set for "hm-rpc.3.INT0000007.1.CONTROL_MODE" has value "0" greater than max "-1"
```
**To Reproduce**
1. Make sure you have a `hm-rpc` adapter receiving updates for the `VirtualDevices` of a CCU.
2. Perform an update in the virtual group (change to AUTO/MANU Mode)
3. Watch the ioBroker logfile

**Expected behavior**
VirtualDevices retrieved from a CCU should have `MIN`, `MAX` and `DEF`

**Screenshots & Logfiles**
Looking at the RAW object output the following entries are visible:
```json
{
  "type": "state",
  "common": {
    "def": -1,
    "type": "number",
    "read": true,
    "write": false,
    "min": -1,
    "max": -1,
    "states": {
      "0": "AUTO-MODE",
      "1": "MANU-MODE",
      "2": "PARTY-MODE",
      "3": "BOOST-MODE"
    },
    "role": "indicator",
    "name": "Gruppe-HZ-FlurEG.CONTROL_MODE"
  },
  "native": {
    "UNIT": "",
    "MIN": "0",
    "MAX": "3",
    "OPERATIONS": 5,
    "FLAGS": 1,
    "ID": "CONTROL_MODE",
    "TAB_ORDER": 0,
    "TYPE": "ENUM",
    "DEFAULT": "0",
    "CONTROL": "HEATING_CONTROL.CONTROL_MODE",
    "VALUE_LIST": [
      "AUTO-MODE",
      "MANU-MODE",
      "PARTY-MODE",
      "BOOST-MODE"
    ]
  },
  "from": "system.adapter.hm-rega.0",
  "ts": 1620678065225,
  "_id": "hm-rpc.3.INT0000007.1.CONTROL_MODE",
  "user": "system.user.admin",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Please not the `min`, `max` and `def` entries all stating -1 as their accepted values. This seems to be the reason for the shown warning message. However, these values should be `min: 0`, `max: 3` and `def: 0`

**Versions:**
 - hm-rpc version: 1.14.37
 - hm-rega version: 3.0.24
 - JS-Controller version: 3.3.8
 - Node version: 12.22.1
 - Operating system: Ubuntu 20.04
 - CCU model: RaspberryMatic
 - CCU firmware: 3.57.5.20210424

**Comment by jens-maus** [comment]
Nope, it is not already fixed. Flushed all devices of the corresponding hm-rpc multiple times. However, I think I do have identified the root cause here and will submit a PR accordingly.

**Comment by foxriver76** [comment]
Yes, problem is that the logic tries to encode if type is string on value lists. This is the logic which needs to be applied for hmip

**Comment by jens-maus** [comment]
Please note, that I didn't dare to convert the strings to numbers in my PR, but perhaps it would be a good idea to do so in case the `indexOf()` match returns -1 and thus doesn't match the value list.

**Comment by foxriver76** [comment]
Yes, as stated in the PR it has to be converted, otherwise the controller will set a string `def` value to a number and will complain again ;-)
