### ISSUE TITLE
Homematic IP Geräte verschwinden im iobroker

### ISSUE THREAD

**Issue by sbehnsen** [ioBroker/ioBroker.hm-rpc#335]
Nach der Installation werden im iobroker die an die CCU3 angeschlossenen Homematic IP Geräte kurz angezeigt. Allerdings ohne Daten. Nur die Kanäle, die Gewerk und Raum anzeigen haben die Eingestellten Werte.
Danach verschwinden diese aber wieder aus dem iobroker.
Das synchronize objects (once) Flag scheint dabei keinen Unterschied zu machen.
Danach sehe ich nur `..info/connection` auf `true `und `updated `leer.
Zum Testen habe ich eine CCU3 mit einer Wetterstation und einem Heizkörperthermostat (beides Homematic IP) angeschlossen.

**Comment by Apollon77** [comment]
Bittte prüfen was in der Einstellung zu "geräte löschen "e eingestellt ist. Es gibt einen Bug in der CCU wodurch sowas passieren kann das Geräte als gelöscht gemeldet werden

**Comment by sbehnsen** [comment]
Don't delete device on adaptor start ist aktiv (also harken gesetzt)

**Comment by foxriver76** [comment]
Callback Adresse? Frage fürs Forum eher..

**Comment by sbehnsen** [comment]
Wenn es an Addressen oder ports liegen würde, dann müsse es ja gar nicht gehen, oder?
Forum: im io-broker allgemein forum?

**Comment by sbehnsen** [comment]
problem gelöst: Kleiner Vorschlag zur Verbesserung: In der readme (die man über das "?" bei der Installation des Adapters bekommt) auch darauf hinweisen, das 127.0.0.1 und 0.0.0.0 keine gute Idee sind...
Ich hatte fälschlicherweise 127.0.0.1 angegeben und nicht die IP meines io-broker...
