### ISSUE TITLE
HmIP-MP3P: Falsche Prozent beim Level Status

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.hm-rpc#337]
hallo 

da ich gerade etwas mit der Ansteuerung rumspiele habe ich einen Prozentfehler entdeckt.

unter hm-rpc.1.xxx.5.LEVEL steht zB 1% obwohl das 100% sein sollten.
auch unter hm-rpc.1.xxx.1.LEVEL steht zB 0,6 % obwohl das 60 % sein sollten.

das sind immer die jeweiligen Status Kanäle von zB dem Dimmer/MP3 usw.

Vielen Dank für deine Mühen. 

Adapter Version
RPC 1.14.38
Regahss: 3.0.25

**Comment by foxriver76** [comment]
RAW des Objekts zeigen bitte

**Comment by krobipd** [comment]
du meinst das hier? 

> {
  "type": "state",
  "common": {
    "name": "Flur - Klingel - Dimmer Status.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1.01,
    "unit": "%",
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "500",
        "maxLength": "1500",
        "retention": "63072000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 5,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "DIMMER_REAL.LEVEL",
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1603561924809,
  "_id": "hm-rpc.1.001518A9A59E13.5.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

> {
  "type": "state",
  "common": {
    "name": "Flur - Klingel - MP3 - Status.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1.01,
    "unit": "%",
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "500",
        "maxLength": "1500",
        "retention": "63072000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "aliasId": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 5,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "ACOUSTIC_SIGNAL_TRANSMITTER.LEVEL",
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1603561926482,
  "_id": "hm-rpc.1.001518A9A59E13.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
Der Logik nach handelt der Adapter richtig, CCU müsste als Unit `100%` liefern um eine Skalierung zu wünschen.

Ob ich dafür nochmal einen Workaround baue muss ich schauen, Problem wurde bereits an eq3 gemeldet.

**Comment by krobipd** [comment]
sorry stell mich mal ganz doof an - verzeihung
aber die CCU zeigt ja 100% an aber im adapter steht 1%. inwiefern ist das ein CCU Fehler?
die ccm zeigt 60 % an, der adapter 0.6%.

**Comment by krobipd** [comment]
oh sorry, du hast vollkommen recht
scheinbar haben die dafür einen workaround in der ccu
hab mir gerade die technische doku angesehen und da ist der Fehler auch drin.

der wert sollte ja von 0 bis 100 gehen und nicht bis 1.01

<img width="863" alt="Bildschirmfoto 2021-05-27 um 19 39 11" src="https://user-images.githubusercontent.com/27220902/119872093-5ffb5700-bf23-11eb-966d-205b915fe43c.png">

**Comment by krobipd** [comment]
ich habe mir jetzt einwenig die technische doku angesehen
und dabei mir mal den Dimmer (HmIP-BDT) angesehen der exakt das selbe verhalten und Fehler hat

die doku sagt hier bei Channel 3 (Status channel)
8.3.4.1.2. Parameter LEVEL - werte von 0.0 bis 1.01
der adapter zeigt das auch in diesem Verhältnis an

ABER
auf Channel 4 (virtual receiver)
8.3.5.1.2. Parameter LEVEL - wetter von 0.0 bis 1.01
der adapter zeigt werte von 0 bis 100 an.

daher meine bitte, da ja scheinbar schon ein workaround Vorhand ist, baue ihn bitte auch die die Status.level ein damit dort die werte auch stimmen - auch wenn das ein Fehler seitens eq3 sein mag aber für den user nicht nachvollziehbar wenn die ccu alles richtig anzeigt aber der adapter bei Status.level nicht aber beim eigentlichen Aktor dann schon.

**Comment by foxriver76** [comment]
Alles was in `native` steht ist das sogenannte Paramset. Hie gliedert die CCU als UNIT `%` wenn sie eine Skalierung fordert `100%`, mehr Workaround ist da nicht, wenn die Unit 100% ist wird * 100 skaliert bei datenerhalt und vor senden / 100.

**Comment by krobipd** [comment]
dein Ansatz ist natürlich technisch natürlich vollkommen richtig.

vl könntest du ja über eine Option im Adapter nachdenken
"Level Prozente umrechnen" - ein/aus
wenn die option eingeschaltet ist soll der adapter die werte auf 100% umrechnen
und sonst original belassen.

es ist ja auch so das alle hmip geräte die einen level haben das selbe problem haben.

**Comment by ppb1308** [comment]
Gibt es hier irgendwelche Neuigkeiten?
