### ISSUE TITLE
State value to set for "hm-rpc.1.INT0000002.1.CONTROL_MODE" has value "1" greater than max "-1"

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.hm-rpc#341]
Hallo,

ich bekomme schon seit einiger Zeit von allen Geräten diesen Fehler "State value to set for "hm-rpc.1.INT0000002.1.CONTROL_MODE" has value "1" greater than max "-1""

Möchte das hier mal als Bug melden.

Grüße

**Comment by foxriver76** [comment]
Bitte Gerät neu anlegen lassen mit aktueller Version, sollte bereits gefixt sein.
