### ISSUE TITLE
Value for RSSI_DEVICE  >  (max) 127

### ISSUE THREAD

**Issue by nobl** [ioBroker/ioBroker.hm-rpc#346]
**Describe the bug**
hm-rpc.1 State value to set for "hm-rpc.1.x.0.RSSI_DEVICE" has value "128" greater than max "127"

**Versions:**
 - hm-rpc version: 1.14.41
 - hm-rega version:  3.0.26
 - JS-Controller version: 5.1.3
 - Node version: 12.21.0
 - Operating system: <os-name>
 - CCU model: raspberrymatic
 - CCU firmware: 3.57.5.2021052

**Additional context**
HM-IP Devices showing this issue: HmIP-DBB, HmIP-BSL (there might be more - but those two I can confirm)

Had the devices recreated in ioBroker - same problem.

**Comment by foxriver76** [comment]
Are there also values greater than 128? And could you please show the raw of the object.

**Comment by nobl** [comment]
I haven't seen values > 128 so far.
But quite possible it is the same issue for all RSSI states and the min is on -128 already.

```
{
  "type": `"state",`
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi",
    "name": "x:y.RSSI_DEVICE"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1624288036371,
  "_id": "hm-rpc.1.x.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by KoMa1978** [comment]
Same happened today for a "HmIP-ASIR".

**Comment by Herbert-Testmann** [comment]
hm-rpc.1 | 2021-08-09 19:32:03.802 | warn | State value to set for "hm-rpc.1.0007D5699E96BA.0.RSSI_DEVICE" has value "128" greater than max "127"
-- | -- | -- | --
hm-rpc.1 | 2021-08-09 19:07:14.349 | warn | State value to set for "hm-rpc.1.0010DD8989804A.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:23.297 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:19.472 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:17.316 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:09.560 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:06.436 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:05.951 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:04:02.756 | warn | State value to set for "hm-rpc.1.00255BE98A84E1.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.1 | 2021-08-09 19:03:31.475 | warn | State value to set for "hm-rpc.1.000A9A499F57DF.0.RSSI_DEVICE" has value "128" greater than max "127"

**Comment by ahnungsbefreit** [comment]
I have the same issue for various devices...

**Comment by foxriver76** [comment]
Probably the best way to get this fixed from my experience is if eq3 is contacted directly https://www.eq-3.de/service.html because GitHub issues seem to be mainly ignored.

**Comment by Berchemer** [comment]
Same here:

Only HMIP devices seem to be affected,

hm.rega is "v3.0.33"
hm.rpc is "v1.14.50"

I didn't see such warning messages, before I added an AccesPoint into the Network.
 Could this be the cause of the problem?

**Comment by baerenwaldfreund** [comment]
Also ich bekomme die Meldungen auch noch immer, obwohl kein Gerät eine RSSI von >127 hat. Alle liegen dauerhaft deutlich unter 100. Ich meine, dass die Meldungen erst mit dem admin-adapter 5 aufgetreten sind.

**Comment by JayVee2** [comment]
Ich kann bestätigen, dass das Problem erst mit Ergänzen eines HmiP-HAP auftritt.

**Comment by foxriver76** [comment]
Das sollte man mal dringend an eq3 weitergeben, im Adapter kann ich das nicht handhaben außer dirty 128 abzulehnen o.ä. da dies aber wohl eindeutig nur mit einem HMIP HAP passiert, ist da sicher ein Fehler Seitens eq3

**Comment by helje5** [comment]
I think the RSSI values are reported as UInt8, i.e. w/ the high bit set for negative values. E.g. `211` is actually `-45` (dBm).

And there seem to be two special values:
- 0: UNREACH=false, but CONFIG_PENDING=true
- 1: Seems to mean "no value", e.g. if UNREACH=true or if the device has no sender

**Comment by Berchemer** [comment]
> Same here:
> 
> Only HMIP devices seem to be affected,
> 
> hm.rega is "v3.0.33" hm.rpc is "v1.14.50"
> 
> I didn't see such warning messages, before I added an HMIP-AccesPoint into the Network. Could this be the cause of the problem?

Supplement:
RaspberryMatic v3.61.5.20211113 is on my CCU3.
HMIP-Hap has v2.4.12.

**Comment by baerenwaldfreund** [comment]
Die Ausgabe der Warnung könnte man doch ganz einfach programmtechnisch begegnen:

if (RSSI==128) keine Warnung ausgeben;

Die Warnungen müllen immer fleißig den Log zu... :-/

Spricht was dagegen?
