### ISSUE TITLE
State value HmIP-PDT and HmIP-BDT

### ISSUE THREAD

**Issue by isi07** [ioBroker/ioBroker.hm-rpc#347]
**Describe the bug**
Hello
I have two issues with the state  value of dim level in HmIP-PDT and HmIP-BDT

For HmIP-PDT:
The device is actually dimmed at 15%.
hm-rpc.2.XXX.2.LEVEL is correctly showing 15% dim level as status
but I receive warn message from hm-rega
"State value to set for "hm-rpc.2.000DD709B035EA.2.LEVEL" has value "15" greater than max "1.01""

For HmIP-BDT
The device is actually dimmed at 50%
hm-rpc.2.YYY.3.LEVEL is incorrectly shown only 0,5%
hm-rpc.2.YYY.4.LEVEL is showing the correct 50%

**Expected behavior**
Correct % of dim level should be shown and no warn message in log.

**Versions:**
 - hm-rpc version: 1.14.41
 - hm-rega version: 3.0.26
 - JS-Controller version: 3.3.14
 - Node version: 12.22.1
 - Operating system: docker
 - CCU model: raspberrymatic
 - CCU firmware: 3.57.5.20210525

**Additional context**

**Comment by isi07** [comment]
Sehe gerade, dass das Problem schon in #337 diskutiert ist.
Dazu kommt, dass jetzt etwas später der HmIP-PDT als hm-rpc.2.XXX.2.LEVEL auch mit 0,15% angezeigt wird.

**Comment by Rapptor33** [comment]
Hallo, habe bei mir bei den HMIP-eTRV die selbe Thematik.
`
<html><body>


hm-rpc.1 | 20806 | 2021-08-29 11:14:23.725 | warn | State value to set for "hm-rpc.1.000397098BCAE6.1.LEVEL" has value "8" greater than max "1.01"
-- | -- | -- | -- | --
hm-rpc.1 | 20806 | 2021-08-29 11:14:21.749 | warn | State value to set for "hm-rpc.1.000397098BC501.1.LEVEL" has value "8" greater than max "1.01"


</body>
</html>`

**Comment by kopierschnitte** [comment]
Kann ich beim HMIP-eTRV und einer dazugehörigen Heizungsgruppe auch bestätigen. Der Wert müsste mit 100 multipliziert werden...
