### ISSUE TITLE
Warn-Message from hm-rpc "No image for  XXX found."

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.hm-rpc#348]
**Describe the bug**
It's only a warning message from _**hm-rpc.2**_ inside the LOG:

No image for "HmIP-DLD" found.
No image for "HmIP-KRCK" found.

**Versions:**
 - hm-rpc version: 1.14.41
 - hm-rega version: 3.0.25
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: ProxMox-Ubuntu 20.04.2
 - CCU model: raspberrymatic 3.57.5.20210525
 - CCU firmware: 3

**Comment by foxriver76** [comment]
Then please provide the images from ccu

**Comment by Berchemer** [comment]
Here are both files in high resolution and as thumbnails.

DLD is the "Door Lock Drive" (Türschlossantrieb)
KRCK is the "Key Ring Remote Control – access control" (Schlüsselbundfernbedienung – Zutritt)

![HmIP-KRCK](https://user-images.githubusercontent.com/44316663/123548640-ea72e880-d765-11eb-9e11-b0a78959d5c1.png)
![214_hmip-dld](https://user-images.githubusercontent.com/44316663/123548694-2312c200-d766-11eb-8d5b-fe36e07e730b.png)
![HmIP-KRCK_thumb](https://user-images.githubusercontent.com/44316663/123548734-56ede780-d766-11eb-8f72-adecd9256918.png)
![214_hmip-dld_thumb](https://user-images.githubusercontent.com/44316663/123548733-56555100-d766-11eb-8d04-471a36c636e9.png)
