### ISSUE TITLE
Zuordnung von gerät zu Rolle stimmt vereinzelt nicht

### ISSUE THREAD

**Issue by udochrist** [ioBroker/ioBroker.hm-rpc#35]
Hallo,
Das tab "Objekte" im iobroker admin für hm.rpc.0 irritiert mich sehr.
Für einige meiner Geräte (z.b optischer fensterkontakt) wird als Rolle "blind" auf dem device anstelle "sensor" angezeigt. Der Channel zeigt wiederum sensor. Analog gibt es auch "switch" auf dem device und "Sensor" auf dem Channel. 

Ich habe auch wandthermostate die als Light.dimmer angezeigt werden.
Logs, Screenshots usw natürlich gerne. Ich habe recht viele Geräte und Typen angeschlossen, ggfls kommt da aufgrund der Menge oder des Typs durcheinander.

Grüße
Udo

**Comment by udochrist** [comment]
Auch in der Version 1.4.2 noch falsch. Die hm.rpc Objekte zeigen in der GUI falsche Rollen.

**Comment by Apollon77** [comment]
Ein paar mehr konkrete Details wären richtig super. Bei was fr Device-Typen hättest Du andere Rollen erwartet und welche werden vergeben aktuell?

**Comment by udochrist** [comment]
Sehr gerne. Hier mal screenshots aus der WebGUI. leider verschieben sich die spaltenköpfe nicht mit den Spalten beim Resize.

Hier mal 3 Screenshots von oben nach unten. Sind viele Geräte angeschlossen.
Bei der Benamung:
Gerätename enthält Button --> UP Taster     HM-RC-2-PBU-FM      (erwartet button)
Gerätename enthält Switch --> UP  Schalter HM-LC-Sw1PBU-FM   (erwartet switch)
einige der Kontakter sind interessanterweise "button", die anderen "sensor", evtl auch "blind"
für ein gerät hat RPC -> Rega die namenszuorndnung nicht geklapp. (MEQ, Wandthermostat.)
Hie und da ist ein dimmer mal ein "button" und ein button (6er taster Batterie) ein "Switch".
bei einem 2er up schalt Aktor ist der 1er schalter ein "Switch", der 2er ein "button".

![hm-rpc-liste-1](https://cloud.githubusercontent.com/assets/869637/23298211/0b0bf3a4-fa7d-11e6-8152-924bccb0000f.PNG)
![hm-rpc-liste-2](https://cloud.githubusercontent.com/assets/869637/23298212/0b0cb7b2-fa7d-11e6-8e40-caf4d364a268.PNG)
![hm-rpc-liste-3](https://cloud.githubusercontent.com/assets/869637/23298210/0b0ba264-fa7d-11e6-8026-2a1cb2d6404e.PNG)

mehr Infos und Tests natürlich gerne wie schon angeboten!

Grüße
Udo

**Comment by GermanBluefox** [comment]
Besteht das Problem immer noch?
