### ISSUE TITLE
Wrong role

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.hm-rpc#354]
**Describe the bug**
My HM smoke detectors were not properly detected under Lovelace. During the error analysis it came out that the object State is not assigned the correct role. Only after the manual change to sensor.fire.alarm the devices were displayed correctly under Lovelace.
It would be advantageous if the role for the smoke detectors would be adjusted.

**Files:**
I have attached a JSON file with and without the change here.
[HM_devices_JSON.zip](https://github.com/ioBroker/ioBroker.hm-rpc/files/6764827/HM_devices_JSON.zip)

**Screenshots & Logfiles**
See the following issue
https://github.com/ioBroker/ioBroker.lovelace/issues/221

**Versions:**
 - hm-rpc version: 1.14.62
 - hm-rega version: 3.0.29
 - JS-Controller version: 3.3.14
 - Node version: 14.16.1
 - Operating system: Docker Container
 - CCU model: pivccu
 - CCU firmware: 3.57.5

**Comment by foxriver76** [comment]
Thanks for reporting. Fixed in 1.14.43. Needs a `Read devices anew` run to be applied
