### ISSUE TITLE
error message while re-adding device

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.hm-rpc#356]
Due to communication problems I readded a RHS to the CCU
in the iobroker log the following warning came up:
```
hm-rpc.0  2021-07-08 14:01:51.311  warn  (13416) xmlrpc <- undefined method readdedDevice with parameters ["ioBroker01:hm-rpc.0",["JRT0001572","JRT0001572:0","JRT0001572:1"]]
```

**Comment by foxriver76** [comment]
What exactly means readding? How to reproduce? And any issues besides from the warning? I have added this logging  a while ago to get more information about existing events not used by the adapter.
