### ISSUE TITLE
RPC Adapter legt HM62Server auf CCU nach ca. 100 Stunden lahm

### ISSUE THREAD

**Issue by Gerti1972** [ioBroker/ioBroker.hm-rpc#358]
Sobald der RPC Adapter läuft, auch ohne dass irgendwelche Geräte darüber geschaltet werden, einfach nur als Listener, geht der HM62Server Prozess auf der CCU3 nach ca. 100 Stunden reproduzierbar in die Knie (der Speicher läuft immer weiter voll, sobald der RPC Dienst läuft). Sensoren blinken erst vermehrt orange, bevor grün bestätigt wird, öffnet man die Einstellungen eines z.B. Wandthermostat, dann dauert es 10 oder mehr Sekunden bis etwas angezeigt wird, statt sonst etwa 3 Sekunden. Aktoren die per Routing über einen HAP angesprochen werden, lassen sich dann quasi nicht mehr schalten.

Ich hatte sonst noch immer den Historian laufen, der ja erstmal auch nur ein Listener ist und eigentlich nichts anders machen sollte als der RPC Adapter. Der kann problemlos nebenher laufen, ohne das es zu diesem Ausfall kommt.

Vor 10 Tagen habe ich zusätzlich mal den Home Assistant aufgesetzt, der ja ebenfalls wie der RPC Adapter arbeiten sollte und auch damit läuft es ohne Probleme.

Irgendetwas macht der RPC Adapter vom iobroker anders, dass es zu diesem Problem kommt.

Der Fehler tritt anscheinend nicht bei allen auf, es gibt aber mehrere User mit diesem Problem. 
Angefangen hat es bei mir vermutlich irgendwann im Februar 2021.

Den RPC-Adapter aktivieren

**Versions:**
 - hm-rpc version: 1.14.41
 - hm-rega version: 3.0.29
 - JS-Controller version: <js-controller-version>
 - Node version: v12.18.1
 - Operating system: Docker
 - CCU model: CCU3 
 - CCU firmware: 3.59.6

**Additional context**
Siehe hierzu auch https://homematic-forum.de/forum/viewtopic.php?f=65&t=65523

**Comment by Apollon77** [comment]
The providing a debug log would be a good idea as start. Till now this issue was never reported in iobroker forum or github ...

**Comment by Gerti1972** [comment]
What kind of Logfile?
It seems that the issue happens only on the CCU and even within the extended Logfile of the CCU we can't find any hint whats wrong.

**Comment by foxriver76** [comment]
Ich wüsste leider ad-hoc nicht was sich da mit Einfluss geändert haben sollte. Man könnte jetzt natürlich auch ne Version von vor Februar mal nehmen und schauen ob das Verhalten dann wirklich weg ist.. natürlich nicht so schick wenn es Wochen dauert bis das Problem aufkommt.
