### ISSUE TITLE
Warnmeldungen (zur Information)

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rpc#359]
**Versions:**
 - hm-rpc version: <1.14.43>
 - hm-rega version: <3.0.29>
 - JS-Controller version: <3.2.16>
 - Node version: <12.22.1>
 - Operating system: <docker>
 - CCU model: <raspberrymatic>
 - CCU firmware: <3.59.6.20210703>

Seit dem letzten Update des hm-rpc Adapters habe ich folgende Warn und Fehlermeldungen.
Dies betrifft nur die normalen Homematic Geräte (kein IP).
Zum Teil werden Datenpunkte _ALARM im Kanal 1 angemahnt. Da sollten sich doch im Kanal 0 befinden.

`[{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[6 Einträge] State \"hm-rpc.1.UNITEMP002.0.LOWBAT_ALARM\" has no existing object, this might lead to an error in fu","ts":1626573063137},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[4 Einträge] State \"hm-rpc.1.UNITEMP001.0.LOWBAT_ALARM\" has no existing object, this might lead to an error in fu","ts":1626573063055},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-7_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062819},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-6_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062775},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-5_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062731},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-4_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062686},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-3_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062641},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-2_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062597},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[3 Einträge] State \"hm-rpc.1.MEQ0538725.1.ERROR-1_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062553},{"date":"Heute 03:51","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.MEQ0538725.0.UNREACH_ALARM\" has no existing object, this might lead to an error in f","ts":1626573062508},{"date":"Heute 03:47","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.MEQ0380604.0.UNREACH_ALARM\" has no existing object, this might lead to an error in f","ts":1626572859583},{"date":"Heute 03:47","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.papa111111.0.UNREACH_ALARM\" has no existing object, this might lead to an error in f","ts":1626572859268},{"date":"Heute 03:45","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.UNITEMP001.0.UNREACH_ALARM\" has no existing object, this might lead to an error in f","ts":1626572750698},{"date":"Heute 03:36","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"State \"hm-rpc.1.MEQ0538725.0.STICKY_UNREACH_ALARM\" has no existing object, this might lead to an err","ts":1626572174605},{"date":"Heute 03:34","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"State \"hm-rpc.1.UNITEMP001.0.STICKY_UNREACH_ALARM\" has no existing object, this might lead to an err","ts":1626572078611},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"State \"hm-rpc.1.MEQ0380604.0.STICKY_UNREACH_ALARM\" has no existing object, this might lead to an err","ts":1626571551251},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.OEQ0351446.1.ERROR-2_ALARM\" has no existing object, this might lead to an error in f","ts":1626571530278},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.OEQ0351446.1.ERROR-1_ALARM\" has no existing object, this might lead to an error in f","ts":1626571530232},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.MEQ1597335.0.LOWBAT_ALARM\" has no existing object, this might lead to an error in fu","ts":1626571529491},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"State \"hm-rpc.1.papa111111.0.STICKY_UNREACH_ALARM\" has no existing object, this might lead to an err","ts":1626571527703},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.STICKY_SABOTAGE-1_ALARM\" has no existing object, this might lead to an ","ts":1626571526569},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.STICKY_POWER-1_ALARM\" has no existing object, this might lead to an err","ts":1626571526525},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.STICKY_BATTERY-1_ALARM\" has no existing object, this might lead to an e","ts":1626571526481},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.ERROR_SABOTAGE-1_ALARM\" has no existing object, this might lead to an e","ts":1626571526435},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.ERROR_POWER-1_ALARM\" has no existing object, this might lead to an erro","ts":1626571526390},{"date":"Heute 03:25","severity":"<span class='logWarn logSeverity'>warn</span>","from":"hm-rega.0","message":"[2 Einträge] State \"hm-rpc.1.LEQ0801502.0.ERROR_BATTERY-1_ALARM\" has no existing object, this might lead to an er","ts":1626571526366},`

**Versions:**
 - hm-rpc version: <1.14.43>
 - hm-rega version: <3.0.29>
 - JS-Controller version: <3.2.16>
 - Node version: <12.22.1>
 - Operating system: <docker>
 - CCU model: <raspberrymatic>
 - CCU firmware: <3.59.6.20210703>

**Comment by foxriver76** [comment]
>  Zum Teil werden Datenpunkte _ALARM im Kanal 1 angemahnt. Da sollten sich doch im Kanal 0 befinden.

Ist meistens so, aber nicht immer kann auch in anderen Kanälen angesiedelt sein.

Weiß leider aktuell nicht woran es liegt.. vorallem dass das hm-rpc Update was geändert hat ist merkwürdig

**Comment by Knallochse** [comment]
Mir ist eben aufgefallen, das in meiner rpc.1 Instanz (Homematic alt / Kein IP) unter Objekte keine Datenpunkte mit _Alarm vorhanden waren. In den anderen Istanzen (Cuxd; HMIP und Virtuelle Geräte) waren die _ALARM datenpunkte vorhanden.
Das würde die Warnmeldungen von (siehe oben) vielleicht erklären???
Mir ist leider nicht genau bekannt, seit wann. 

Habe jetzt auf die neue Rega 3.0.30 installiert, und unter dieser Version wurden die _Alarm Datenpunkte wieder angelegt.

Wenn du der Meinung bist, dass diese Sachen zusammen gehören könnte dieses Issues eigentlich geschlossen werden.

Fehler/Warnmeldungen hatte ich während der Installation nicht.

**Comment by foxriver76** [comment]
Bitte falls es wieder vorkommt -> Issue ernet eröffnen
