### ISSUE TITLE
Unterstützung von HM-Dis-EP-WM55

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.hm-rpc#36]
Das E-Paper Display von Homematic wird falsch dagestellt, sodass es i.v.m iobroker nicht zu verwenden ist. es wäre super wenn dieses mit eingebunden werden kann...

**Comment by Apollon77** [comment]
Falsch heisst genau?

**Comment by MeisterTR** [comment]
Entschuldigung, das hätte ich tatsächlich besser ausführen können, Es werden acht Kanäle angezeigt, soweit richtig, jedoch sind alle Taster, Short und Longpress, jedoch wird über die Kanäle auch der Test des Oled disp. eingestellt, dieses ist zur zeit über iobroker nciht möglich, gibt es eine Möglichkeit das zu ändern?
![unbenannt](https://cloud.githubusercontent.com/assets/6328382/25334907/fdefe980-28f0-11e7-835e-c953c00a6a39.JPG)

**Comment by Apollon77** [comment]
Da hat Bluefox was gemacht, oder ?!

**Comment by MeisterTR** [comment]
Jep das ist erledigt 


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer <notifications@github.com> Datum: 30.06.17  12:47  (GMT+01:00) An: "ioBroker/ioBroker.hm-rpc" <ioBroker.hm-rpc@noreply.github.com> Cc: MeisterTR <rensen26@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [ioBroker/ioBroker.hm-rpc] Unterstützung von HM-Dis-EP-WM55 (#36) 
Da hat Bluefox was gemacht, oder ?!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ioBroker/ioBroker.hm-rpc","title":"ioBroker/ioBroker.hm-rpc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ioBroker/ioBroker.hm-rpc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Apollon77 in #36: Da hat Bluefox was gemacht, oder ?!"}],"action":{"name":"View Issue","url":"https://github.com/ioBroker/ioBroker.hm-rpc/issues/36#issuecomment-312236969"}}}

**Comment by cmartin61** [comment]
Kurze Frage:
Habe gerade ein HM-Dis-EP-WM55 eingebunden und es werden genau wie im Screenshot vom 24.04.2017 alle Kanäle als Taster angezeigt - was genau muss ich tun, damit die Kanäle korrekt dargestellt werden?
Vielen Dank für die Unterstützung.

**Comment by foxriver76** [comment]
Mir wäre nicht bekannt, dass da etwas nicht geht. Welche Kanäle sollten denn anders sein? Ich schätze bf hat Kanäle ergänzt damals.

**Comment by cmartin61** [comment]
Nach der Theorie hat dieses Gerät 8 Kanäle. Kanal 1 und 2 sind Taster. Kanal 3 sollte nach HM Doku das Display steuern. Die anderen Kanäle machen irgendwas. Dort sind Texte hinterlegt (mir ist gerade nicht klar wozu das gut sein soll). 
Wenn das Gerät in den iobroker geladen wird, sind nach wie vor alle 8 Kanäle Taster (so wie das von MeisterTR schon dokumentiert worden ist).

Mir ist allerdings aufgefallen, dass die Steuerung des Display im iobroker über Kanal 0 erfolgen kann (EPAPER_LINE2-4). Da dies genau das ist, was ich tun will, ist mir egal, dass Kanal 3-8 Taster sind.
Leider ist das nicht ganz intuitiv, zumal HM Kanal 3 zur Steuerung des Displays angibt. Daher stolpert man über Kanal 3 als Taster, der so etwas nicht zulässt.

Ich denke bf hat die Funktionen des Kanal 3 in Kanal 0 übernommen und das funktioniert toll, wenn man es erst gefunden hat.

Vielen Dank für die schnelle Antwort.
