### ISSUE TITLE
CUxD - Devices: Warn logs for RSSI values > 0

### ISSUE THREAD

**Issue by KoMa1978** [ioBroker/ioBroker.hm-rpc#364]
After upgrading HM-RPC adapter to v1.14.43, I get the following warning for CUxD - Devices:

State value to set for "hm-rpc.2.CUX3505002.0.RSSI_PEER" has value "55" greater than max "0"

This happens for all ENOCEAN Devices I have. If I remember correctly, the last installed version I had was 1.14.41 that didn't had these warnings

**Comment by foxriver76** [comment]
Can you please show the raw object of hm-rpc.2.CUX3505002.0.RSSI_PEER

**Comment by KoMa1978** [comment]
{
  "type": "state",
  "common": {
    "def": -255,
    "type": "number",
    "read": true,
    "write": false,
    "min": -255,
    "max": 0,
    "unit": "dBm",
    "role": "value.rssi",
    "name": "Wettersensor_NORD:0.RSSI_PEER"
  },
  "native": {
    "ID": "RSSI_PEER",
    "UNIT": "dBm",
    "TAB_ORDER": 0,
    "OPERATIONS": 5,
    "FLAGS": 1,
    "TYPE": "INTEGER",
    "MIN": -255,
    "MAX": 0,
    "DEFAULT": -255
  },
  "from": "system.adapter.hm-rega.0",
  "ts": 1603447875562,
  "_id": "hm-rpc.2.CUX3505001.0.RSSI_PEER",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

**Comment by foxriver76** [comment]
Hm okay, but then I think it's because of the js-controller update. And basically the definition says the range is -255 to 0 but it gives 55. I am not sure where the paramsets (like min max) of CuxD devices come from, can you configure them yourself?

**Comment by KoMa1978** [comment]
No I can't configure them ... CUxD provides the data.

And yes, I updated js-controller as well to 3.3.15.

I think there is something wrong with RSSI values at all ... CUXD, HM-RF and HM-IP have completely different ranges and HM-RF values in iobroker for example are >0 while these values in HomeMatic are <0 and they are completely different ... not only a missing "-". But this is another question ;-)

This is a Homematic RF device:
```
{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -2147483648,
    "max": 2147483647,
    "role": "value.rssi",
    "unit": "dBm",
    "name": "Dekolicht_Weihnachten:0.RSSI_DEVICE"
  },
  "native": {
    "DEFAULT": 0,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "MAX": 2147483647,
    "MIN": -2147483648,
    "OPERATIONS": 5,
    "TAB_ORDER": 5,
    "TYPE": "INTEGER",
    "UNIT": ""
  },
  "from": "system.adapter.hm-rega.0",
  "ts": 1561129849794,
  "_id": "hm-rpc.0.KEQ1059934.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}
```
This is a Homematic IP device:
```
{
  "type": "state",
  "common": {
    "name": "Sonst_Server-ESXi02:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1610984076222,
  "_id": "hm-rpc.3.00021A498C75D2.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

How can we proceed? should I open an issue for js-controller?

**Comment by KoMa1978** [comment]
BTW, I now "corrected" the values and get no more errors on these devices but a restart of the adapter set them back to "broken" defaults

```
{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -255,
    "max": 255,
    "unit": "dBm",
    "role": "value.rssi",
    "name": "Wettersensor_SUED:0.RSSI_PEER"
  },
  "native": {
    "ID": "RSSI_PEER",
    "UNIT": "dBm",
    "TAB_ORDER": 0,
    "OPERATIONS": 5,
    "FLAGS": 1,
    "TYPE": "INTEGER",
    "MIN": -255,
    "MAX": 255,
    "DEFAULT": 0
  },
  "_id": "hm-rpc.2.CUX3505002.0.RSSI_PEER",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1627485100521
}
```

**Comment by foxriver76** [comment]
There is nothing js-controller can do except from not logging a warning.

RSSI values are really inconsistent in the API, I guess the only one working 100 % correctly is HMIP. But basically it needs to be fixed on CCU side. The RSSI values in rega scripts are also real value +256 -> https://github.com/jens-maus/RaspberryMatic/issues/897

**Comment by foxriver76** [comment]
> the adapter set them back to "broken" defaults

you should check "do not delete devices" in the adapter config

**Comment by KoMa1978** [comment]
In general I do not recreate devices on restart. but since a Restart of the hm-rpc instance brings the behavior back means to me, the easiest way to fix this is to change the default "max" from "0" to "255" (+255)

**Comment by KoMa1978** [comment]
Sounds similar to #346 

Today I rolled HM-RPC adapter back to 1.14.41 but the issue still exists. Means I have to correct my initial post. Where are these defaults configured?

**Comment by KoMa1978** [comment]
And some more investigations ... as CuXD is emulating known HM devices maybe this is the cause of the issue ...

The CUxD Enocean Weather Sensor is emulated as HM-WDS100-C6-O and the window handle sensors as "HM-Sec-RHS" maybe this is the cause for using wrong defaults.

```
{
  "_id": "hm-rpc.2.CUX3505001",
  "type": "device",
  "common": {
    "name": "Wettersensor_NORD",
    "icon": "/icons/WeatherCombiSensor_thumb.png"
  },
  "native": {
    "ADDRESS": "CUX3505001",
    "AES_ACTIVE": 0,
    "FLAGS": 1,
    "VERSION": 1,
    **"TYPE": "HM-WDS100-C6-O",**
    "PARENT": "",
    "FIRMWARE": "1.0",
    "CHILDREN": [
      "CUX3505001:0",
      "CUX3505001:1",
      "CUX3505001:2"
    ],
    "PARAMSETS": [
      "MASTER"
    ]
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1627485271628,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```
