### ISSUE TITLE
Minimum set temperatur for Virtual devices

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.hm-rpc#365]
The set temperature for virtual devices have a minimum value of 5 degrees.
But 5 degrees ist not OFF, so I used 4,5.

The valves will go to OFF, but the log shows

`State value to set for "hm-rpc.3.INT0000003.1.SET_TEMPERATURE" has value "4.5" less than min "5.0"`

Maybe the minimum value should be set to e.g. 0.

**Comment by foxriver76** [comment]
https://github.com/eq-3/occu/issues/112#issuecomment-890469054

**Comment by peoples0815** [comment]
This means, there ist no other way to set the members of the group to off and remove the warning messages instead of turning off all warning messages of this adapter at the moment?

**Comment by foxriver76** [comment]
Workaround could be: edit the object and set the min property to 4.5

**Comment by DcFamas** [comment]
Same issue here
`State value to set for "hm-rpc.1.INT0000004.1.CONTROL_MODE" has value "0" greater than max "-1"`

Will it be fixed in the next version? Or should we edit the virtual devices manually?

**Comment by foxriver76** [comment]
> Same issue here
> `State value to set for "hm-rpc.1.INT0000004.1.CONTROL_MODE" has value "0" greater than max "-1"`
> 
> Will it be fixed in the next version? Or should we edit the virtual devices manually?

This specific case should be fixed if you let the adapter recreate the object

**Comment by DcFamas** [comment]
@foxriver76 worked! :)
