### ISSUE TITLE
listBidcosInterfaces Implementieren

### ISSUE THREAD

**Issue by AlGu318** [ioBroker/ioBroker.hm-rpc#38]
Hallo,

ist es möglich die XMLRPC Methode "listBidcosInterfaces" einzubauen, dann könnte man daraus die DutyCycle-Werte auslesen und müsste keinen Code auf der CCU mehr ausführen. Oder gibt es schon eine Möglichkeit dies zu machen?

Vielen Dank und Gruß
AlGu

**Comment by GermanBluefox** [comment]
DutyCyclie ist jetzt implemented. Oder?

**Comment by Apollon77** [comment]
DutyCycle an sich ist drin
