### ISSUE TITLE
Unknown XML-RPC tag 'TITLE' only for Virtual Devices on version 1.14.45

### ISSUE THREAD

**Issue by MadErstam** [ioBroker/ioBroker.hm-rpc#383]
I have configured HM-RPC with three instances for HM devices, HMIP devices and virtual devices. The first two instances work fine, while hm-rpc.2 for virtual devices continuously gives me error messages "Unknown XML-RPC tag 'TITLE' only for Virtual Devices".

The CCU is configured to use authentication. Firewall settings are set to block ports and no access, with the four ports 42001, 42010, 48181 and 49292 listed as enabled ports. 
![image](https://user-images.githubusercontent.com/71971104/133889051-e48022a6-dd09-43cf-a96a-cdd4a98d9723.png)

Username and password in all three hm-rpc instances is the same. Use https is enabled. HomeMatic address is the same on all three instances. Ports are obviously different, with Virtual Devices using HomeMatic Port 49292, Daemon Virtual Devices and Protocol XML-RPC.
![image](https://user-images.githubusercontent.com/71971104/133889069-a0cb0b7e-c84d-4499-88eb-f7e2a8086ec6.png)

Here is the iobroker log:

Source | Time | Log Level | Message
--- | --- | --- | ---
hm-rpc.2 | 2021-09-18 14:39:07.466 | info | Terminated (NO_ERROR): Without reason
hm-rpc.2 | 2021-09-18 14:39:07.465 | debug | Plugin sentry destroyed
hm-rpc.2 | 2021-09-18 14:39:07.464 | info | terminating
hm-rpc.2 | 2021-09-18 14:39:07.456 | error | Cannot call init: [http://192.168.178.11:49292, ""] Unknown XML-RPC tag 'TITLE'
hm-rpc.2 | 2021-09-18 14:39:07.438 | info | xmlrpc -> 192.168.178.12:49292/groups/ init ["http://192.168.178.11:49292",""]
hm-rpc.2 | 2021-09-18 14:39:07.351 | error | Init not possible, going to stop: Unknown XML-RPC tag 'TITLE'
hm-rpc.2 | 2021-09-18 14:39:07.334 | debug | xmlrpc -> 192.168.178.12:49292/groups/ init ["http://192.168.178.11:49292","LH2io:hm-rpc.2"]
hm-rpc.2 | 2021-09-18 14:38:37.436 | error | Init not possible, going to stop: Unknown XML-RPC tag 'TITLE'
hm-rpc.2 | 2021-09-18 14:38:37.333 | debug | xmlrpc -> 192.168.178.12:49292/groups/ init ["http://192.168.178.11:49292","LH2io:hm-rpc.2"]
hm-rpc.2 | 2021-09-18 14:38:07.332 | debug | start connecting interval
hm-rpc.2 | 2021-09-18 14:38:07.331 | debug | Connect...
hm-rpc.2 | 2021-09-18 14:38:07.330 | info | xmlrpc client is trying to connect to 192.168.178.12:49292/groups/ with ["http://192.168.178.11:49292","LH2io:hm-rpc.2"]
hm-rpc.2 | 2021-09-18 14:38:07.330 | info | xmlrpc server is trying to listen on 192.168.178.11:49292
hm-rpc.2 | 2021-09-18 14:38:07.141 | info | starting. Version 1.14.45 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.22.4, js-controller: 3.3.15
hm-rpc.2 | 2021-09-18 14:38:06.499 | debug | Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.2 | 2021-09-18 14:38:05.919 | debug | statesDB connected
hm-rpc.2 | 2021-09-18 14:38:05.918 | debug | States connected to redis: 127.0.0.1:9000
hm-rpc.2 | 2021-09-18 14:38:05.898 | debug | States create User PubSub Client
hm-rpc.2 | 2021-09-18 14:38:05.896 | debug | States create System PubSub Client
hm-rpc.2 | 2021-09-18 14:38:05.882 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
hm-rpc.2 | 2021-09-18 14:38:05.880 | debug | objectDB connected
hm-rpc.2 | 2021-09-18 14:38:05.870 | debug | Objects connected to redis: 127.0.0.1:9001
hm-rpc.2 | 2021-09-18 14:38:05.805 | debug | Objects client initialize lua scripts
hm-rpc.2 | 2021-09-18 14:38:05.804 | debug | Objects create User PubSub Client
hm-rpc.2 | 2021-09-18 14:38:05.802 | debug | Objects create System PubSub Client
hm-rpc.2 | 2021-09-18 14:38:05.800 | debug | Objects client ready ... initialize now
hm-rpc.2 | 2021-09-18 14:38:05.738 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 3.3.15
 - Node version: 12.22.4
 - Operating system: Linux (Raspberry PI OS)
 - CCU model: piVCCU
 - CCU firmware: 3.59.6

**Comment by foxriver76** [comment]
username password correct?

**Comment by foxriver76** [comment]
btw http is strange for a ccu port starting with 4

**Comment by MadErstam** [comment]
Yes, tested a number of times.

**Comment by foxriver76** [comment]
Special chars in password or something like that? Maybe the virtual devices api has a problem with that. If you use default user admin make sure the first letter is uppercase. I have no active vd instance but tested multiple times.

**Comment by MadErstam** [comment]
No special characters. First letter in user name is capital A (Admin). I also tried adding a second user, also user name starting with capital letter and password using simply characters and numbers. Password size is also not the issue, Admin password is only 8 characters, while the other user's password is 16 characters long.

I compared time and again the settings of the different instances, they are identical except for the differences that should be there (daemon and port number).

**Comment by MadErstam** [comment]
Here is the second page of the adapter settings:
![image](https://user-images.githubusercontent.com/71971104/133891767-98a41204-547b-469e-b54f-5611d0cae39d.png)

**Comment by foxriver76** [comment]
Tried it right now, CCU firewall exact the same settings as you and worked flawlessly. Only difference I can see is that I am running Raspberrymatic  but also on 3.59.6 (3.59.6.20210807). Pretty unsure if this makes a difference. Have you tried rebooting the CCU after changing the fw settings?

**Comment by MadErstam** [comment]
Thank you, that seems to have been the issue. After rebooting the CCU, the hm-rpc connected also for virtual devices. Thank you!
