### ISSUE TITLE
Jalousien fahren nicht auf 100%

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.hm-rpc#388]
**Describe the bug**
HmIPW-DRBL (Rollladen/Jalousien-Aktor)
Wenn man über den Datenpunkt LEVEL oder COMBINED_PARAMETER einen Wert von 100% Behanghöhe setzt, fährt die Jalousie nach Erreichen der 100% wieder ein Stück zurück auf 95%.

Dies macht sich aber nur bei Jalousien und nicht bei Rollläden bemerkbar.

Direkt in der CCU über ein Programm, Direktverknüpfung oder direkte Bedienung gibt es diese Phänomen nicht.

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: debian
 - CCU model: CCU3
 - CCU firmware: 3.59.6

**Additional context**

**Comment by foxriver76** [comment]
Vielen Dank für Ihre Anfrage. 

Damit einer unserer Servicemitarbeiter sich Ihrem Anliegen schnellstmöglich annehmen kann, benötigen wir noch weitere Informationen. Bitte ergänzen Sie die Fehlerbeschreibung um folgende Aspekte:

- ein Auszug aus dem Log auf der Stufe "debug" 
-  "raw" Darstellung des betroffenen Objektes

**Comment by Schmakus** [comment]
Hallo,
ich habe einige Versuche gemacht. Folgendes habe ich herausgefunden:

Ausgangssituation: Behanghöhe z.B. 50% / Lamellenposition 0%
Fall 1:
1) Setzen des **LEVEL** Datenpunkts mit Wert 100
==> Ergebnis: Jalousie fährt auf 100% und dann wieder zurück auf ca. 95%

Fall 2:
1) Setzen des LEVEL_2 Datenpunkts mit Wert 100
2) Setzen des LEVEL Datenpunkts mit Wert 100
==> Ergebnis: Jalousie fährt auf 100% und verbleibt dort

Selbiges Verhalten auch, wenn man den COMBINED_PARAMETER setzt!
=> "L=100,L2=0: führt  zu einem Zurückfahren der Jalousie, wenn diese am Endpunkt angekommen ist.
=> "L=100,L2=100": Die Jalousie verbleibt an der Endposition

Meinem Verständnis nach, dürfte es absolut keine Rolle spielen, welchen Wert die Lamellenposition hat, wenn man auf 100% Behanghöhe fährt. Bedeutet, die CCU und/oder der ioBroker Adapter sollten den Wert der Lamellenposition völlig ignorieren, wenn eine Behanghöhe von 100% angefahren wird. Bei 100% gibt es keine Lammenposition.

Selbiges Verhalten zeigen die Jalousien, wenn direkt in der CCU einen Wert von 100% vorgibt. Die Jalousie fährt wieder ein Stück zurück, sofern zuvor die Lamellen nicht 100% waren.

Fazit: Ich denke es ist sogar ein Problem der CCU?!

RAW der beiden Datenpunkte:
`{
  "type": "state",
  "common": {
    "name": "EQ3-3.1-Jalousie_Essen_Sued_A.LEVEL",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100,
    "unit": "%",
    "role": "level",
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "number_unit": "",
        "linkedId": "Jalousien.Essen_Süd.LEVEL",
        "name": "Jalousien Essen Süd Level",
        "role": "",
        "mergeSettingsOnRestart": false,
        "expertSettings": false,
        "number_convertTo": "",
        "number_maxDecimal": "",
        "number_min": "",
        "number_max": "",
        "number_calculation": "",
        "number_calculation_readOnly": "",
        "number_to_boolean_condition": "",
        "number_to_boolean_value_true": "",
        "number_to_boolean_value_false": "",
        "number_to_string_condition": "",
        "number_to_duration_convert_seconds": "",
        "number_to_duration_format": "",
        "number_to_datetime_convert_seconds": "",
        "number_to_datetime_format": "",
        "number_to_multi_condition": "",
        "boolean_convertTo": "",
        "boolean_to_string_value_true": "",
        "boolean_to_string_value_false": "",
        "string_convertTo": "",
        "string_prefix": "",
        "string_suffix": "",
        "string_to_boolean_value_true": "",
        "string_to_boolean_value_false": "",
        "string_to_number_unit": "",
        "string_to_number_maxDecimal": "",
        "string_to_number_calculation": "",
        "string_to_number_calculation_readOnly": "",
        "string_to_duration_format": "",
        "string_to_datetime_parser": "",
        "string_to_datetime_format": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "UNIT": "100%",
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "BLIND_VIRTUAL_RECEIVER.LEVEL"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1609582958026,
  "_id": "hm-rpc.1.00165A49924753.10.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

`{
  "type": "state",
  "common": {
    "name": "EQ3-3.1-Jalousie_Essen_Sued_A.LEVEL_2",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 100,
    "unit": "%",
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "number_unit": "",
        "linkedId": "Jalousien.Essen_Süd.Lamellen",
        "name": "Jalousien Essen Süd Lamellen",
        "role": "",
        "mergeSettingsOnRestart": false,
        "expertSettings": false,
        "number_convertTo": "",
        "number_maxDecimal": "",
        "number_min": "",
        "number_max": "",
        "number_calculation": "",
        "number_calculation_readOnly": "",
        "number_to_boolean_condition": "",
        "number_to_boolean_value_true": "",
        "number_to_boolean_value_false": "",
        "number_to_string_condition": "",
        "number_to_duration_convert_seconds": "",
        "number_to_duration_format": "",
        "number_to_datetime_convert_seconds": "",
        "number_to_datetime_format": "",
        "number_to_multi_condition": "",
        "boolean_convertTo": "",
        "boolean_to_string_value_true": "",
        "boolean_to_string_value_false": "",
        "string_convertTo": "",
        "string_prefix": "",
        "string_suffix": "",
        "string_to_boolean_value_true": "",
        "string_to_boolean_value_false": "",
        "string_to_number_unit": "",
        "string_to_number_maxDecimal": "",
        "string_to_number_calculation": "",
        "string_to_number_calculation_readOnly": "",
        "string_to_duration_format": "",
        "string_to_datetime_parser": "",
        "string_to_datetime_format": ""
      }
    }
  },
  "native": {
    "MIN": 0,
    "UNIT": "100%",
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL_2",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "BLIND_VIRTUAL_RECEIVER.LEVEL_2"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1609582958238,
  "_id": "hm-rpc.1.00165A49924753.10.LEVEL_2",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by foxriver76** [comment]
Ja, es ist definitiv ein Problem in der XML-API, siehe auch https://github.com/ioBroker/ioBroker.hm-rpc/issues/206#issuecomment-549241202

Man kann hierzu leider nur eq3 nerven und hoffen, dass sie es zeitnah fixen. Gerne hier das Problem ergänzen https://github.com/eq-3/occu/issues/104

**Comment by Schmakus** [comment]
Temporär wäre es doch sicher möglich, dass wenn eine Behanghöhe von 100% über den LEVEL Datenpunkt oder COMBINED_PARAMETER Datenpunkt gesetzt wir, dass der Adapter selbständig eine Lamellenposition von 100% an die CCU übergibt?

**Comment by foxriver76** [comment]
Villt könnte man es über das native CONTROL `BLIND_VIRTUAL_RECEIVER.LEVEL` identifizieren, wenn diese immer und nur die problembehafteten Devices beinhalten. Das Problem bei HM ist, dass mir da die Übersicht fehlt bei der Vielzahl an Geräten + teilweise Wildwuchs an Paramsets.

**Comment by Schmakus** [comment]
Selbst in der CCU selbst muss man immer zuerst die Lamellenposition und anschließend die Behanghöhe angeben.
Alternativ den kombinierten Parameter. 
Soweit eigentlich kein Problem, wenn man das Prinzip verstanden hat. Ist bei anderen Devices ähnlich.
Aber unlogisch ist halt, wenn man eine Behanghöhe von 100% vorgibt, dass dann der Aktor dennoch eine Lamellenposition anfahren möchte, bzw. seine alte Position behalten möchte. Auf ist halt Auf. Da gibt es keine Lamellenposition. :-)

Richtigerweise müsste dies EQ3 umsetzen.
