### ISSUE TITLE
"Level" einer HomematicIP Heizugsgruppe ist um Faktor 100 falsch

### ISSUE THREAD

**Issue by benjholl** [ioBroker/ioBroker.hm-rpc#390]
Auf der CCU3: Gruppe "HmIP-Heizungssteuerung".
In ioBroker wird der Ventilstatus (Objekt: "LEVEL") in "Prozent/100" angezeigt: z.B. statt 80% wird 0.8% angezeigt

Anmerkung: in der "letzten Heizperiode" (Winter 2020/2021) waren mit der damals aktuellen Version ausgegebenen Werte korrekt.

**"To Reproduce**
1. Objekt "Level" einer HmIP-Heizugssteuerung-Gruppe in iobroker beobachten

**Expected behavior**
Anzeige in iobroker mit 100 multiplizieren

**Screenshots & Logfiles**

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 5.1.3
 - Node version: 5.1.3
 - Operating system: linux
 - CCU model: CCU3
 - CCU firmware: 3.57.5

**Additional context**

**Comment by foxriver76** [comment]
Duplicate of https://github.com/ioBroker/ioBroker.hm-rpc/issues/311
