### ISSUE TITLE
HMIP-Wired - no events in ioBroker (if configured as push button)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.hm-rpc#401]
**Describe the bug**

I've added the HmIPW-DRI16 with an `hm-rpc` instance over XML-RPC to ioBroker. Everything works fine. But I get no event on `hm-rpc.0.0016DBE993023F.1.STATE` when the contact is closed.

**To Reproduce**

1. Configure CCU3, HMIPW-DRAP and HmIPW-DRI16
2. Don't configure anything else. No direct device connections, no programs.
3. Connect everything as explained in the documentation (https, auth enabled, ...)
4. Push the button connected to channel 1

**Expected behavior**

You should the the state `hm-rpc.0.0016DBE993023F.1.STATE` changing to `true`

**Screenshots & Logfiles**

<img width="1480" alt="Screenshot 2021-10-22 at 11 43 41" src="https://user-images.githubusercontent.com/1959049/138432717-93cc7589-c3b3-4629-9ec2-3e9d88d39942.png">

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: debian bullseye
 - CCU model: CCU3
 - CCU firmware: 3.59.6

**Additional context**

It is working, when channel 1 on the HmIPW-DRI16 is configured as `contact` instead of `push button`. As explained [here](https://forum.iobroker.net/topic/21688/homematic-ip-wired-eingangsmodul-und-iobroker/30?_=1634895093403&lang=en-US) (ioBroker Forum).

**Comment by FRAMELIFTER** [comment]
@klein0r 
thanks for your issue / question!
without this post, i had never found the solution; searched for hours, thought their must be something wrong with my config, resetet my ccu, recreated my iobrokeradapter...nothing changed this behaivior 
but i only needed this little dummyscript...

**Comment by Apollon77** [comment]
@FRAMELIFTER hm ... Readme includes that info too https://github.com/ioBroker/ioBroker.hm-rpc#additional-information
