### ISSUE TITLE
RSSI-DEVICE > 127 Warnung

### ISSUE THREAD

**Issue by dotcom84** [ioBroker/ioBroker.hm-rpc#402]
Für einige meiner Geräte (u.a. eine Außensirene) bekomme ich periodisch folgende Zeilen ins Log-File geschrieben:

`State value to set for "hm-rpc.0.00209AXXXXXXXX.0.RSSI_DEVICE" has value "128" greater than max "127"`

**Comment by whitecapx** [comment]
Same here - ich habe es zum ersten Mal festgestellt, nachdem ich einen alten HMIP-HAP als zusätzliches LAN Gateway an meiner CCU3 angelernt habe. Vorher habe ich den Fehler im ioBroker nie gesehen.

**Comment by Negalein** [comment]
dito
```
State value to set for "hm-rpc.0.00019BE98BA026.0.RSSI_DEVICE" has value "128" greater than max "127"
State value to set for "hm-rpc.0.00115A49A5B2BE.0.RSSI_DEVICE" has value "128" greater than max "127"
```

**Comment by Namborner** [comment]
Das gleiche Problem haben ich auc
<img width="1432" alt="Bildschirmfoto 2021-11-24 um 21 12 28" src="https://user-images.githubusercontent.com/95048433/143487827-61c8647b-8f28-4c3e-b4dd-58cb6f1cbc83.png">
h.

**Comment by JackDaniel007** [comment]
das selbe auch beim diesem datenpunkt
hm-rpc.1
29941	2021-11-29 12:19:56.765	warn	State value to set for "hm-rpc.1.CUX3500001.0.RSSI_PEER" has value "86" greater than max "0"

**Comment by Christoph-sans-e** [comment]
Ich habe da Wandthermostate als auch Rollladenaktoren, die das verursachen. Gibt es hierfür schon eine Lösung?

**Comment by afuerhoff** [comment]
Das selbe bei mir. Wenn ich dann nach dem Objekt sehe ist aber alles ok. Scheint nur sehr kurz aufzutreten. 

State value to set for "hm-rpc.3.00109D898C36F4.0.RSSI_DEVICE" has value "128" greater than max "127"
--
State value to set for "hm-rpc.3.0014DA499ED74A.0.RSSI_DEVICE" has value "128" greater than max "127" 

State value to set for "hm-rpc.3.000BD569A36B4E.0.RSSI_DEVICE" has value "128" greater than max "127"

**Comment by foxriver76** [comment]
Kann mal jemand so ein Objekt zeigen mit native etc und dazu die hm-rpc Version

**Comment by afuerhoff** [comment]
hm-rpc Version 1.14.50

![image](https://user-images.githubusercontent.com/50245893/146647405-3fefb864-01a3-4926-ad15-e2270f43660a.png)

{
  "_id": "hm-rpc.3.00109D898C36F4",
  "type": "device",
  "common": {
    "name": "EG.WoZi.FS2",
    "icon": "/icons/152_hmip-swdo-i_thumb.png"
  },
  "native": {
    "TYPE": "HmIP-SWDO-I",
    "SUBTYPE": "SWDO-I",
    "ADDRESS": "00109D898C36F4",
    "RF_ADDRESS": 4205136,
    "CHILDREN": [
      "00109D898C36F4:0",
      "00109D898C36F4:1",
      "00109D898C36F4:2"
    ],
    "PARENT": "",
    "PARENT_TYPE": "",
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "FIRMWARE": "1.16.10",
    "AVAILABLE_FIRMWARE": "0.0.0",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
    "VERSION": 2,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "DIRECTION": 0,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 4
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1637318871734,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
Danke, der Dp ist allerdings leider vom Device und nicht der rssi State. Bitte den posten.

**Comment by afuerhoff** [comment]
Sorry. Ich hoffe jetzt ist es richtig.

{
  "type": "state",
  "common": {
    "name": "EG.WoZi.FS2:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1637318871779,
  "_id": "hm-rpc.3.00109D898C36F4.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by JayVee2** [comment]
Dito, Problem: Werte werden nicht in die Datenbank geschrieben.

**Comment by Baenker** [comment]
#346

**Comment by ChristianWieck1977** [comment]
Hallo zusammen,
ich habe auch seit Monaten regelmäßig vergleichbare Meldungen - egal ob Homematic oder HUE Geräte - z.B.

<html>
<body>


hm-rpc.2 | 2022-01-28 09:47:33.012 | warn | State value to set for "hm-rpc.2.HU-Hue_play_2.1.WHITE" has value "530000" greater than max "100"
-- | -- | -- | --
hm-rpc.2 | 2022-01-28 09:47:32.980 | warn | State value to set for "hm-rpc.2.HU-Hue_play_1.1.WHITE" has value "530000" greater than max "100"
hm-rpc.2 | 2022-01-28 09:47:22.930 | warn | State value to set for "hm-rpc.2.HU-Hue_Play_3.1.WHITE" has value "200000" greater than max "100"
hm-rpc.2 | 2022-01-28 09:47:22.890 | warn | State value to set for "hm-rpc.2.HU-Hue_play_2.1.WHITE" has value "340000" greater than max "100"
hm-rpc.2 | 2022-01-28 09:47:22.864 | warn | State value to set for "hm-rpc.2.HU-Hue_play_1.1.WHITE" has value "530000" greater than max "100"


</body>
</html>

**Comment by FreunderNacht** [comment]
Hi,
bei mir auch das selbe Problem:

<html>
<body>


hm-rpc.0 | 2022-01-29 15:28:17.933 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
-- | -- | -- | --
hm-rpc.0 | 2022-01-29 15:26:15.700 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.0 | 2022-01-29 15:23:59.202 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.0 | 2022-01-29 15:19:28.652 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.0 | 2022-01-29 15:08:28.913 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.0 | 2022-01-29 15:05:35.445 | warn | State value to set for "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE" has value "128" greater than max "127"
hm-rpc.0 | 2022-01-29 15:00:06.648 | warn | State value to set for "hm-rpc.0.000A9709AABD30.0.RSSI_DEVICE" has value "128" greater than max "127"


</body>
</html>

![Screenshot](https://user-images.githubusercontent.com/69077006/151665859-7627a5e7-301d-446c-8fdd-5543357a4abd.jpg)

`{
  "type": "state",
  "common": {
    "name": "Wetterstation:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1608563413062,
  "_id": "hm-rpc.0.00185BE9922B49.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

`
  "type": "state",
  "common": {
    "name": "Wandthermostat Küche:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1608563413873,
  "_id": "hm-rpc.0.000A9709AABD30.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by foxriver76** [comment]
Objekte müssen neu angelegt werden, z. B. durch einen neu einlesen run

**Comment by JayVee2** [comment]
OK, danke.

**Comment by Negalein** [comment]
hab heute mit 1.15.12 wieder den Fehler bekommen.

`hm-rpc.0 | 2022-03-25 21:03:24.075 | warn | State value to set for "hm-rpc.0.000E5BE9A05450.0.RSSI_DEVICE" has value "128" greater than max "127"`

**Comment by gogo-111** [comment]
Ich habe auch noch immer das Problem bei mir taucht es auch der erste mal auf nachdem ich einen alten HMIP-HAP als zusätzliches LAN Gateway an meiner CCU3 angelernt habe. Vorher habe ich den Fehler im ioBroker nie gesehen.

**Comment by ChristianWieck1977** [comment]
Gibt es Neuigkeiten zu der Fehlermeldung ?
Mein Iobroker Log ist weiter voll mit solchen Meldungen:
`<html>
<body>


hm-rpc.2 | 2022-12-08 15:43:28.049 | warn | State value to set for "hm-rpc.2.HU-Hue_lightst.1.WHITE" has value "405000" greater than max "100"
-- | -- | -- | --
hm-rpc.2 | 2022-12-08 15:43:28.033 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "405000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:43:28.019 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "405000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:29:08.999 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "405000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:58.891 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "405000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:48.784 | warn | State value to set for "hm-rpc.2.HU-Hue_lightst.1.WHITE" has value "405000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:38.690 | warn | State value to set for "hm-rpc.2.HU-Hue_lightst.1.WHITE" has value "400000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:38.672 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "400000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:38.656 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "400000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:28.560 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "645000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:28.545 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "645000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:18.466 | warn | State value to set for "hm-rpc.2.HU-Hue_lightst.1.WHITE" has value "645000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:18.450 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "645000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:28:18.434 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "645000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:23:45.642 | warn | State value to set for "hm-rpc.2.HU-Hue_lightst.1.WHITE" has value "200000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:23:45.618 | warn | State value to set for "hm-rpc.2.HU-Hue_light02.1.WHITE" has value "200000" greater than max "100"
hm-rpc.2 | 2022-12-08 15:23:45.603 | warn | State value to set for "hm-rpc.2.HU-Hue_light01.1.WHITE" has value "200000" greater than max "100"


</body>
</html>`

**Comment by ChristianWieck1977** [comment]
Beim Neueinlesen erfolgt mittlerweile folgende Ergänzung im LOG:
<html>
<body>


warn | Object HU-Hue_light02.1.WHITE is invalid: obj.common.min (2000) needs to be less than or equal to obj.common.max (100)
-- | --



</body>
</html>
