### ISSUE TITLE
HmIP-eTRV-2 Prozentangabe Level fehlerhaft

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.hm-rpc#406]
**Describe the bug**
Betroffenes Device: HmIP-eTRV-2 Heizkörperthermostat
Der Prozentwert vom Datenpunkt "Level" ist Faktor 100 zu klein. Aus 34% werden 0.34%

**To Reproduce**
Unter Objekte wird der falsche Wert angezeigt

**Expected behavior**
Der korrekte Wert in Prozent wird angezeigt

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/50245893/139957035-8f76b526-ce97-43aa-b0b5-c85ae6dd4640.png)
![image](https://user-images.githubusercontent.com/50245893/139958112-19cb3132-ed0e-4a0b-a7d1-70eec2d8b0f1.png)

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.32
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Linux
 - CCU model: CCU3
 - CCU firmware: 3.59.6

**Additional context**
-

**Comment by foxriver76** [comment]
Duplicate of https://github.com/ioBroker/ioBroker.hm-rpc/issues/337
