### ISSUE TITLE
 HM-LC-Sw1-Pl-DN-R1 wrong UNREACH

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.hm-rpc#413]
**Describe the bug**
The switch  HM-LC-Sw1-Pl-DN-R1 shows a wrong value in the datapoint UNREACH.
Although there is not connectivity error in the Homematic CCU and the switch is also working fine, UNREACH is always true.

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.32
 - JS-Controller version:3.3
 - Node version: 14
 - Operating system: Debian Buster
 - CCU model: Debmatic
 - CCU firmware: 3.59.6.78

**Comment by foxriver76** [comment]
Execute https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rega/master/regascripts/datapoints.fn on your ccu and check if it's also true there if so, problem on CCU side. If not, is Rega configured correctly? If hm-rpc misses an update beacuse not running hm-rega will resync everything on adapter start, up from there it is supposed that hm-rpc gets alle updates.

**Comment by Marty56** [comment]
This is the result of the script.
The switch in question has the serial number OEQ0074537
In output below it only has one entry
"BidCos-RF.OEQ0074537%3A1.STATE":false
it seems that it does not show any UNREACH.


`{"BidCos-RF.KEQ0181811%3A0.ERROR_POWER":0,
"BidCos-RF.KEQ0181811%3A0.STICKY_POWER":0,
"BidCos-RF.KEQ0181811%3A0.ERROR_SABOTAGE":0,
"BidCos-RF.KEQ0181811%3A0.STICKY_SABOTAGE":0,
"BidCos-RF.KEQ0181811%3A0.ERROR_BATTERY":0,
"BidCos-RF.KEQ0181811%3A0.STICKY_BATTERY":0,
"BidCos-RF.KEQ0181811%3A1.STATE":false,
"BidCos-RF.KEQ0181811%3A1.ERROR_POWER":0,
"BidCos-RF.KEQ0181811%3A1.ERROR_SABOTAGE":0,
"BidCos-RF.KEQ0181811%3A1.ERROR_BATTERY":0,
"BidCos-RF.KEQ0181811%3A1.LOWBAT":false,
"BidCos-RF.KEQ0181811%3A2.STATE":false,
"BidCos-RF.KEQ0181811%3A2.ERROR_POWER":0,
"BidCos-RF.KEQ0181811%3A2.ERROR_SABOTAGE":0,
"BidCos-RF.KEQ0181811%3A2.ERROR_BATTERY":0,
"BidCos-RF.KEQ0181811%3A2.LOWBAT":false,
"BidCos-RF.KEQ0193875%3A1.BRIGHTNESS":177,
"BidCos-RF.KEQ0193875%3A1.MOTION":false,
"BidCos-RF.KEQ0364088%3A1.BRIGHTNESS":58,
"BidCos-RF.KEQ0364088%3A1.MOTION":false,
"BidCos-RF.KEQ0364088%3A1.ERROR":0,
"BidCos-RF.QEQ0216919%3A1.PRESS_SHORT":false,
"BidCos-RF.QEQ0216919%3A2.PRESS_SHORT":false,
"BidCos-RF.OEQ0125847%3A1.STATE":false,
"BidCos-RF.OEQ0125847%3A2.STATE":false,
"BidCos-RF.OEQ1426087%3A1.STATE":false,
"BidCos-RF.OEQ1426087%3A1.ERROR":0,
"BidCos-RF.OEQ1426087%3A1.LOWBAT":false,
"BidCos-RF.KEQ0091971%3A1.STATE":false,
"BidCos-RF.KEQ0091971%3A1.ERROR":0,
"BidCos-RF.KEQ0091971%3A1.LOWBAT":false,
"BidCos-RF.JEQ0716826%3A1.STATE":false,
"BidCos-RF.JEQ0716826%3A1.ERROR":0,
"BidCos-RF.JEQ0716826%3A1.LOWBAT":false,
"BidCos-RF.MEQ0030321%3A0.LOWBAT":false,
"BidCos-RF.MEQ0030321%3A1.STATE":false,
"BidCos-RF.MEQ0030321%3A1.ERROR":0,
"BidCos-RF.MEQ0030321%3A1.LOWBAT":false,
"BidCos-RF.JEQ0346261%3A1.STATE":1,
"BidCos-RF.JEQ0346261%3A1.ERROR":0,
"BidCos-RF.JEQ0346261%3A1.LOWBAT":false,
"BidCos-RF.LEQ0413828%3A1.LEVEL":1.000000,
"BidCos-RF.KEQ0122349%3A4.STATE":false,
"BidCos-RF.MEQ0030320%3A1.STATE":false,
"BidCos-RF.MEQ0030320%3A1.ERROR":0,
"BidCos-RF.MEQ0030320%3A1.LOWBAT":false,
"BidCos-RF.KEQ0091274%3A1.STATE":false,
"BidCos-RF.KEQ0091274%3A1.LOWBAT":false,
"BidCos-RF.LEQ0133105%3A0.UNREACH":false,
"BidCos-RF.LEQ0133105%3A0.STICKY_UNREACH":true,
"BidCos-RF.LEQ0133105%3A1.LEVEL":1.000000,
"BidCos-RF.JEQ0113772%3A1.LEVEL":1.000000,
"BidCos-RF.KEQ0092076%3A1.STATE":false,
"BidCos-RF.KEQ0092076%3A1.ERROR":0,
"BidCos-RF.KEQ0092076%3A1.LOWBAT":false,
"BidCos-RF.OEQ0222393%3A0.LOWBAT":false,
"BidCos-RF.OEQ0222393%3A1.STATE":false,
"BidCos-RF.OEQ0222393%3A1.ERROR":0,
"BidCos-RF.OEQ0222393%3A1.LOWBAT":false,
"BidCos-RF.NEQ1707349%3A1.PRESS_SHORT":false,
"BidCos-RF.NEQ1707349%3A2.PRESS_SHORT":false,
"BidCos-RF.NEQ1707349%3A3.PRESS_SHORT":false,
"BidCos-RF.NEQ1707349%3A4.PRESS_SHORT":false,
"BidCos-RF.NEQ1707349%3A4.PRESS_LONG":false,
"BidCos-RF.MEQ0704434%3A1.ENERGY_COUNTER":560937.799805,
"BidCos-RF.MEQ0704434%3A1.POWER":511.000000,
"BidCos-RF.LEQ0856717%3A4.CONTROL_MODE":0,
"BidCos-RF.LEQ0856717%3A4.FAULT_REPORTING":0,
"BidCos-RF.LEQ0856717%3A4.BATTERY_STATE":3.000000,
"BidCos-RF.LEQ0856717%3A4.VALVE_STATE":66,
"BidCos-RF.LEQ0856717%3A4.BOOST_STATE":0,
"BidCos-RF.LEQ0856717%3A4.ACTUAL_TEMPERATURE":21.300000,
"BidCos-RF.LEQ0856717%3A4.SET_TEMPERATURE":21.500000,
"BidCos-RF.LEQ0856717%3A4.PARTY_TEMPERATURE":5.000000,
"BidCos-RF.LEQ0856717%3A4.PARTY_START_TIME":0,
"BidCos-RF.LEQ0856717%3A4.PARTY_START_DAY":1,
"BidCos-RF.LEQ0856717%3A4.PARTY_START_MONTH":1,
"BidCos-RF.LEQ0856717%3A4.PARTY_START_YEAR":0,
"BidCos-RF.LEQ0856717%3A4.PARTY_STOP_TIME":0,
"BidCos-RF.LEQ0856717%3A4.PARTY_STOP_DAY":1,
"BidCos-RF.LEQ0856717%3A4.PARTY_STOP_MONTH":1,
"BidCos-RF.LEQ0856717%3A4.PARTY_STOP_YEAR":0,
"BidCos-RF.KEQ0154367%3A0.UNREACH":false,
"BidCos-RF.KEQ0154367%3A0.STICKY_UNREACH":true,
"BidCos-RF.KEQ0154367%3A1.LEVEL":0.100000,
"BidCos-RF.REQ0391463%3A1.LEVEL":1.000000,
"BidCos-RF.OEQ1426115%3A0.UNREACH":false,
"BidCos-RF.OEQ1426115%3A0.STICKY_UNREACH":true,
"BidCos-RF.OEQ1426115%3A1.STATE":false,
"BidCos-RF.OEQ1426115%3A1.ERROR":0,
"BidCos-RF.OEQ1426115%3A1.LOWBAT":false,
"BidCos-RF.KEQ0162251%3A1.STATE":false,
"BidCos-RF.KEQ0162251%3A1.ERROR":0,
"BidCos-RF.KEQ0162251%3A1.LOWBAT":false,
"BidCos-RF.OEQ0074537%3A1.STATE":false,
"BidCos-RF.KEQ0171230%3A1.STATE":false,
"BidCos-RF.QEQ0215176%3A1.PRESS_SHORT":false,
"BidCos-RF.QEQ0215176%3A2.PRESS_SHORT":false,
"BidCos-RF.LEQ0503173%3A1.STATE":false,
"BidCos-RF.LEQ0503173%3A1.ERROR":0,
"BidCos-RF.LEQ0503173%3A1.LOWBAT":false,
"BidCos-RF.KEQ0091968%3A0.UNREACH":false,
"BidCos-RF.KEQ0091968%3A0.STICKY_UNREACH":true,
"BidCos-RF.KEQ0091968%3A1.STATE":false,
"BidCos-RF.KEQ0091968%3A1.ERROR":0,
"BidCos-RF.KEQ0091968%3A1.LOWBAT":false,
"BidCos-RF.OEQ0222411%3A1.STATE":false,
"BidCos-RF.OEQ0222411%3A1.ERROR":0,
"BidCos-RF.OEQ0222411%3A1.LOWBAT":false,
"BidCos-RF.LEQ0855638%3A4.CONTROL_MODE":0,
"BidCos-RF.LEQ0855638%3A4.FAULT_REPORTING":0,
"BidCos-RF.LEQ0855638%3A4.BATTERY_STATE":2.500000,
"BidCos-RF.LEQ0855638%3A4.VALVE_STATE":63,
"BidCos-RF.LEQ0855638%3A4.BOOST_STATE":0,
"BidCos-RF.LEQ0855638%3A4.ACTUAL_TEMPERATURE":21.300000,
"BidCos-RF.LEQ0855638%3A4.SET_TEMPERATURE":21.500000,
"BidCos-RF.LEQ0855638%3A4.PARTY_TEMPERATURE":5.000000,
"BidCos-RF.LEQ0855638%3A4.PARTY_START_TIME":0,
"BidCos-RF.LEQ0855638%3A4.PARTY_START_DAY":1,
"BidCos-RF.LEQ0855638%3A4.PARTY_START_MONTH":1,
"BidCos-RF.LEQ0855638%3A4.PARTY_START_YEAR":0,
"BidCos-RF.LEQ0855638%3A4.PARTY_STOP_TIME":0,
"BidCos-RF.LEQ0855638%3A4.PARTY_STOP_DAY":1,
"BidCos-RF.LEQ0855638%3A4.PARTY_STOP_MONTH":1,
"BidCos-RF.LEQ0855638%3A4.PARTY_STOP_YEAR":0,
"BidCos-RF.KEQ0155331%3A1.LEVEL":1.000000,
"BidCos-RF.LEQ0415291%3A1.LEVEL":1.000000,
"BidCos-RF.MEQ0398170%3A1.PRESS_SHORT":false,
"BidCos-RF.MEQ0398170%3A2.PRESS_SHORT":false,
"BidCos-RF.LEQ0567712%3A1.TEMPERATURE":0,
"BidCos-RF.LEQ0567712%3A1.HUMIDITY":93,
"BidCos-RF.LEQ0567612%3A1.TEMPERATURE":17.100000,
"BidCos-RF.LEQ0567612%3A1.HUMIDITY":58,
"BidCos-RF.LEQ0567580%3A1.TEMPERATURE":80.000000,
"BidCos-RF.LEQ0567580%3A1.HUMIDITY":99,
"BidCos-RF.LEQ1461663%3A1.TEMPERATURE":21.300000,
"BidCos-RF.LEQ1461663%3A1.HUMIDITY":51,
"BidCos-RF.LEQ1461663%3A2.CONTROL_MODE":0,
"BidCos-RF.LEQ1461663%3A2.LOWBAT_REPORTING":false,
"BidCos-RF.LEQ1461663%3A2.COMMUNICATION_REPORTING":false,
"BidCos-RF.LEQ1461663%3A2.WINDOW_OPEN_REPORTING":false,
"BidCos-RF.LEQ1461663%3A2.BATTERY_STATE":2.700000,
"BidCos-RF.LEQ1461663%3A2.BOOST_STATE":0,
"BidCos-RF.LEQ1461663%3A2.ACTUAL_TEMPERATURE":21.300000,
"BidCos-RF.LEQ1461663%3A2.ACTUAL_HUMIDITY":51.000000,
"BidCos-RF.LEQ1461663%3A2.SET_TEMPERATURE":21.500000,
"BidCos-RF.LEQ1461663%3A2.PARTY_TEMPERATURE":5.000000,
"BidCos-RF.LEQ1461663%3A2.PARTY_START_TIME":0,
"BidCos-RF.LEQ1461663%3A2.PARTY_START_DAY":1,
"BidCos-RF.LEQ1461663%3A2.PARTY_START_MONTH":1,
"BidCos-RF.LEQ1461663%3A2.PARTY_START_YEAR":0,
"BidCos-RF.LEQ1461663%3A2.PARTY_STOP_TIME":0,
"BidCos-RF.LEQ1461663%3A2.PARTY_STOP_DAY":1,
"BidCos-RF.LEQ1461663%3A2.PARTY_STOP_MONTH":1,
"BidCos-RF.LEQ1461663%3A2.PARTY_STOP_YEAR":0,
"BidCos-RF.NEQ0956252%3A1.PRESS_SHORT":false,
"BidCos-RF.KEQ0971413%3A0.UNREACH":false,
"BidCos-RF.KEQ0971413%3A0.STICKY_UNREACH":true,
"BidCos-RF.KEQ0971413%3A1.STATE":false,
"BidCos-RF.KEQ0971413%3A2.ENERGY_COUNTER":21532.799988,
"BidCos-RF.KEQ0971413%3A2.POWER":0,
"BidCos-RF.KEQ0971413%3A2.CURRENT":0,
"BidCos-RF.KEQ0971413%3A2.VOLTAGE":230.000000,
"BidCos-RF.KEQ0971413%3A2.FREQUENCY":49.990000,
"BidCos-RF.KEQ0154978%3A1.LEVEL":1.000000,
"BidCos-RF.LEQ0767961%3A1.LEVEL":0,
"BidCos-RF.KEQ0155115%3A1.LEVEL":1.000000,
"BidCos-RF.KEQ0165510%3A1.STATE":false,
"BidCos-RF.KEQ0165510%3A1.ERROR":0,
"BidCos-RF.KEQ0165510%3A1.LOWBAT":false,
"BidCos-RF.OEQ1426127%3A1.STATE":false,
"BidCos-RF.OEQ1426127%3A1.ERROR":0,
"BidCos-RF.OEQ1426127%3A1.LOWBAT":false,
"BidCos-RF.MEQ1656349%3A1.STATE":false,
"BidCos-RF.MEQ1656349%3A1.ERROR":0,
"BidCos-RF.MEQ1656349%3A1.LOWBAT":false,
"BidCos-RF.KEQ0162215%3A1.STATE":false,
"BidCos-RF.KEQ0162215%3A1.ERROR":0,
"BidCos-RF.KEQ0162215%3A1.LOWBAT":false}`

**Comment by Marty56** [comment]
I have also restarted iobroker and told the rpc Adapter to "Geräte einmal neu einlesen".

**Comment by foxriver76** [comment]
Another thing is, that the `UNREACH_ALARM` is what actually represents the unreach service message of the CCU. So it can be, that `UNREACH` is only available via RPC API..

**Comment by Marty56** [comment]
UNREACH_ALARM says 0 not Alarm

**Comment by foxriver76** [comment]
This is fine according to your initial post there is no service message present.

**Comment by Marty56** [comment]
Do you need more information? 
Will the issue fixed or do I have to create specific a script for this switch to check connectivity?

**Comment by foxriver76** [comment]
There is nothing to fix for more.. if you want information about service message, `_ALARM` datapoints are always the way to go. AFAIK I cannot get dps which are only avaiable in RPC via Rega so they can run out of sync again and again

**Comment by Marty56** [comment]
OK. ich habe jetzt ein Alias für die fehlende UNREAD Funktion geschrieben.
Ich hoffe, dass mach Sinn.
`{
  "type": "state",
  "common": {
    "name": "Stehlampe im Obergeschoss",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.unreach",
    "alias": {
      "id": "hm-rpc.0.OEQ0074537.0.UNREACH_ALARM",
      "val": "val == 0 ? false : true"
    }
  },
  "native": {},
  "_id": "alias.0.OG_Stehlampe_alive",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1637923231844
}`

**Comment by foxriver76** [comment]
Jein, 0 und 2 ist quasi keine aktive unreach service message. 1 ist aktive unreach service message https://github.com/ioBroker/ioBroker.hm-rega#what-are-the-alarm-states-created-in-the-devices-object

**Comment by Marty56** [comment]
Ok. Ich verstehe das jetzt so, dass dieser Schalter keinen Status übermittelt, ob er erreichbar ist oder nicht.

**Comment by Marty56** [comment]
Ich habe gerade den Schalter aus der Dose gezogen und dann einen Schaltbefehl gegeben.
In der CCU wird "gestörte Kommunikation" also quasi UNREACH korrekt angezeigt.

in iobroker verändert sich weder UNREACH not UNREACH_ALARM. Schade.

**Comment by foxriver76** [comment]
Er übermittelt ihn evtl. schon, aber dann nur in dem Moment wenn er sich ändert. D. h. bei Adapterneustart etc kann das Event verpasst werden und kommt vermutlich nie wieder.

UNREACH_ALARM wird gepollt (Rega Einstellung servicemessages, kann also das poll intervall dauern bis der DP aktualisiert)

**Comment by Marty56** [comment]
Alles zurück. Nach der Aktion wurde jetzt UNREACH auf false gesetzt. Das wäre ja ok.
Kapiere das Verhalten nicht.
