### ISSUE TITLE
IP-Geräte funktionieren nicht

### ISSUE THREAD

**Issue by Seehofweg** [ioBroker/ioBroker.hm-rpc#42]
RPC ist laut Anleitung eingerichtet, die Geräte werden auch unter "Objekte" angezeigt. Beí den normalen HM-Geräten passt alles, sprich Status (z. B. bei Tastern) wird sauber unter Objekte angezeigt.
IP-Geräte sind alle sichtbar, mit allen "Funktionen". Der Status wird allerdings nicht angezeigt...und über Scripte funktionieren die IP-Geräte auch nicht. Ich habe das gefunden, allerdings komme ich damit nicht weiter:

------------------------------

> Configuration
> 
> native.adapterAddress has to be the ip under which the host that is running the adapter itself is reachable. This address is used by the CCU to connect to the adapter.
> 
> native.homematicAddress is the IP of the HomeMatic CCU respectively the Host that is running the BidCos-Service(s)

------------------------------

Kann mir jemand helfen?

![ansicht_objekte](https://user-images.githubusercontent.com/29658208/27558899-faafd528-5abe-11e7-8170-e8fc8a78cffd.png)
![rega](https://user-images.githubusercontent.com/29658208/27558901-fab449d2-5abe-11e7-9933-0f7e8948e726.png)
![rpc](https://user-images.githubusercontent.com/29658208/27558900-fab431c2-5abe-11e7-9eaf-a40edf10e99c.png)

**Comment by Apollon77** [comment]
Geht alles nicht oder nur die Taster, wie im beispiel, nicht?
Taster sind teilweise interessant weil tastesignale grundsätzlich ohne Tricks nicht an ioBroker weitergemeldet weren. Man muss da in der CCU ein Dummy-Programm anlegen (Es reicht ein "Wenn tasteX, tue nichts". Erst dann bekommt man Tastersignale!

**Comment by Seehofweg** [comment]
Keines der IP-Geräte funktioniert, zumindest habe ich bisher nur den 6-fach Taster und Bewegungsmelder (innen) getestet. Der Bewegungsmelder ist in der CCU in einem Programm verknüpft, werde dies heute Abend aber nochmal mit dem Dummy-Programm testen. Danke dir.

**Comment by Seehofweg** [comment]
Ja, das war es. Die Schalter funktionieren. Vielen Dank. 

Jetzt habe ich gerade nur noch das Problem, dass die Verbindung zwischen den beiden raspberry (HM und iobroker) ein paar Mal am Tag komplett abbricht. Auch stoppen und starten der HM-Instanzen bringt die beiden nicht zusammen. Erst ein Neustart der raspberry.

**Comment by Apollon77** [comment]
Da am besten mal im Forum schauen, da gibt es threads dazu ...
