### ISSUE TITLE
ReplaceDevice is not understood

### ISSUE THREAD

**Issue by FChristian** [ioBroker/ioBroker.hm-rpc#420]
**Describe the bug**
When a device is replaced within the CCU ("Gerät tauschen"), the XML sends a ReplaceDevice message to the adapter, but this is not understood.

**To Reproduce**
1 Replace a device in a CCU, e.g. a defective switch actor or similar
2 see error in ioBroker Log: 
"xmlrpc <- undefined method replaceDevice with parameters ["iobroker:hm-rpc.0","LEQ0797xxx","MEQ0697xxx"]"

**Expected behavior**
replace device ;)

**Versions:**
 - hm-rpc version: v1.14.50
 - hm-rega version: v3.0.33
 - JS-Controller version: 3.3.21
 - Node version: 3.3.21
 - Operating system: Debian Bullseye
 - CCU model: Raspberrymatic x86
 - CCU firmware: 3.59.6.20211009

**Additional context**
Don't know if it is really a bug, or just not implemented :)

**Comment by foxriver76** [comment]
Thanks for reporting, yes it's basically just not implemented, and to get to know more of these methods there exists a log line.

The question is, has the adapter correctly added the new objects + removed the old objects? Maybe you can show some more log if there are deletions + creations without restarting the adapter.

**Comment by FChristian** [comment]
Unfortunately, on ioBroker nothing else happend besides from the dropout of the warning line :(
The CCU itself fulfilled the replacement process completely.

**Comment by foxriver76** [comment]
> ["iobroker:hm-rpc.0","LEQ0797xxx","MEQ0697xxx"]

Welches ist das alte Gerät, welches das neue? Eigentlich müssen wir daraufhin ja nur das eine löschen, das andere hinzufügen wie es auch beim Adapterstart passieren würde insofern `Geräte nicht löschen` nicht angehakt ist

**Comment by FChristian** [comment]
Richtig. LEQ ist das alte, MEQ das neue.
Die CCU löscht das alte und fügt das neue an genau die Stelle des alten, heißt es werden automatisch die Einstellungen übernommen, Programme angepasst, Direktverknüpfungen aktualisiert usw.

ioBroker hat das Thema während der Aktion schlichtweg ignoriert ;)
Leider hat's bei uns heute Nacht einen RCD geschmissen und der USV Akku ist offenbar tot, sodass der Server nicht sauber runtergefahren und neu gestartet ist. Aber es sieht heute so aus als wäre bei einem Neustart das alte Gerät gelöscht und das neue aufgenommen worden (Raumzuordnung stimmt auch, Blocklys leider nicht).
