### ISSUE TITLE
send it to developer....

### ISSUE THREAD

**Issue by simpixo** [ioBroker/ioBroker.hm-rpc#43]
habe dies im Log angezeigt bekommen, somit sende ich es zum Entwickler ;-)

hm-rpc.0 | 2017-09-02 21:28:34.915 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
-- | -- | -- | --
hm-rpc.0 | 2017-09-02 21:28:34.914 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2-Team.SMOKE_DETECTOR_TEAM_V2.3"
hm-rpc.0 | 2017-09-02 21:28:34.896 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-09-02 21:28:34.895 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_FREQUENCY.16"
hm-rpc.0 | 2017-09-02 21:28:34.884 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-09-02 21:28:34.884 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_VOLTAGE.16"
hm-rpc.0 | 2017-09-02 21:28:34.874 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-09-02 21:28:34.873 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_CURRENT.16"
hm-rpc.0 | 2017-09-02 21:28:34.857 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-09-02 21:28:34.857 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_POWER.16"
hm-rpc.0 | 2017-09-02 21:28:34.831 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BOOT":{"CONTROL":"POWERMETER.BOOT","DEFAULT":false,"FLAGS":3,"ID":"BOOT","MA
hm-rpc.0 | 2017-09-02 21:28:34.830 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.POWERMETER.16"
hm-rpc.0 | 2017-09-02 21:28:34.754 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0 | 2017-09-02 21:28:34.754 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.SWITCH.16"
hm-rpc.0 | 2017-09-02 21:28:34.679 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:34.678 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.MAINTENANCE.16"
hm-rpc.0 | 2017-09-02 21:28:34.522 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR_ALARM_TEST":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR_ALARM_
hm-rpc.0 | 2017-09-02 21:28:34.522 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2.SMOKE_DETECTOR.5"
hm-rpc.0 | 2017-09-02 21:28:34.457 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:34.456 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2.MAINTENANCE.5"
hm-rpc.0 | 2017-09-02 21:28:33.804 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0 | 2017-09-02 21:28:33.804 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-4-3.KEY.7"
hm-rpc.0 | 2017-09-02 21:28:33.667 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:33.666 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-4-3.MAINTENANCE.7"
hm-rpc.0 | 2017-09-02 21:28:33.365 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0 | 2017-09-02 21:28:33.363 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1PBU-FM.SWITCH.9"
hm-rpc.0 | 2017-09-02 21:28:33.312 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:33.310 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1PBU-FM.MAINTENANCE.9"
hm-rpc.0 | 2017-09-02 21:28:33.007 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE","MAX":255,"MIN"
hm-rpc.0 | 2017-09-02 21:28:33.007 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.SWITCH_TRANSMIT.22"
hm-rpc.0 | 2017-09-02 21:28:32.914 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ACTUAL_HUMIDITY":{"CONTROL":"THERMAL_CONTROL.HUMIDITY","DEFAULT":0,"FLAGS":1
hm-rpc.0 | 2017-09-02 21:28:32.912 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.THERMALCONTROL_TRANSMIT.22"
hm-rpc.0 | 2017-09-02 21:28:32.516 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"HUMIDITY":{"AutoconfRoles":"WEATHER","CONTROL":"NONE","DEFAULT":0,"FLAGS":1,
hm-rpc.0 | 2017-09-02 21:28:32.514 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.WEATHER_TRANSMIT.22"
hm-rpc.0 | 2017-09-02 21:28:32.476 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:32.474 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.MAINTENANCE.22"
hm-rpc.0 | 2017-09-02 21:28:32.067 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-09-02 21:28:32.066 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.VIRTUAL_DIMMER.13"
hm-rpc.0 | 2017-09-02 21:28:31.898 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-09-02 21:28:31.896 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.DIMMER.13"
hm-rpc.0 | 2017-09-02 21:28:31.702 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:31.702 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.MAINTENANCE.13"
hm-rpc.0 | 2017-09-02 21:28:31.204 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0 | 2017-09-02 21:28:31.200 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.SWITCH.26"
hm-rpc.0 | 2017-09-02 21:28:31.129 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:31.127 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.MAINTENANCE.26"
hm-rpc.0 | 2017-09-02 21:28:30.784 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0 | 2017-09-02 21:28:30.784 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-Key4-2.KEY.4"
hm-rpc.0 | 2017-09-02 21:28:30.728 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:30.727 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-Key4-2.MAINTENANCE.4"
hm-rpc.0 | 2017-09-02 21:28:30.391 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-09-02 21:28:30.389 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-Key.KEYMATIC.7"
hm-rpc.0 | 2017-09-02 21:28:30.006 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:30.004 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-Key.MAINTENANCE.7"
hm-rpc.0 | 2017-09-02 21:28:29.528 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0 | 2017-09-02 21:28:29.528 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-MOD-Re-8.SWITCH.6"
hm-rpc.0 | 2017-09-02 21:28:29.262 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:29.262 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-MOD-Re-8.MAINTENANCE.6"
admin.0 | 2017-09-02 21:28:29.210 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)
hm-rpc.0 | 2017-09-02 21:28:26.241 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"LOWBAT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"LOWBAT","MAX":true
hm-rpc.0 | 2017-09-02 21:28:26.239 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS30-OT2-SM.WEATHER.5"
hm-rpc.0 | 2017-09-02 21:28:26.186 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,
hm-rpc.0 | 2017-09-02 21:28:26.186 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS30-OT2-SM.MAINTENANCE.5"
hm-rpc.0 | 2017-09-02 21:28:25.768 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR","MAX":7,"MIN":0,
hm-rpc.0 | 2017-09-02 21:28:25.768 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SCo.SHUTTER_CONTACT.3"
hm-rpc.0 | 2017-09-02 21:28:25.709 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-09-02 21:28:25.708 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SCo.MAINTENANCE.3"
hm-rpc.0 | 2017-09-02 21:28:25.329 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR","MAX":7,"MIN":0
hm-rpc.0 | 2017-09-02 21:28:25.326 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-RHS.ROTARY_HANDLE_SENSOR.14"
hm-rpc.0 | 2017-09-02 21:28:25.216 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATION
hm-rpc.0 | 2017-09-02 21:28:25.213 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-RHS.MAINTENANCE.14"
hm-rpc.0 | 2017-09-02 21:28:24.829 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ACTUAL_TEMPERATURE":{"CONTROL":"HEATING_CONTROL.TEMPERATURE","DEFAULT":0,"F
hm-rpc.0 | 2017-09-02 21:28:24.820 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-CC-RT-DN.CLIMATECONTROL_RT_TRANSCEIVER.29"
hm-rpc.0 | 2017-09-02 21:28:24.351 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATION
hm-rpc.0 | 2017-09-02 21:28:24.351 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-CC-RT-DN.MAINTENANCE.29"
hm-rpc.0 | 2017-09-02 21:28:23.935 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"HUMIDITY":{"AutoconfRoles":"WEATHER","DEFAULT":0,"FLAGS":1,"ID":"HUMIDITY",
hm-rpc.0 | 2017-09-02 21:28:23.935 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS10-TH-O.WEATHER.5"
hm-rpc.0 | 2017-09-02 21:28:23.890 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true
hm-rpc.0 | 2017-09-02 21:28:23.887 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS10-TH-O.MAINTENANCE.5"
hm-rpc.0 | 2017-09-02 21:28:23.857 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALU
hm-rpc.0 | 2017-09-02 21:28:23.857 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_FREQUENCY.16"
hm-rpc.0 | 2017-09-02 21:28:23.839 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALU
hm-rpc.0 | 2017-09-02 21:28:23.839 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_VOLTAGE.16"
hm-rpc.0 | 2017-09-02 21:28:23.813 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALU
hm-rpc.0 | 2017-09-02 21:28:23.813 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_CURRENT.16"
hm-rpc.0 | 2017-09-02 21:28:23.789 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALU
hm-rpc.0 | 2017-09-02 21:28:23.788 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_POWER.16"
hm-rpc.0 | 2017-09-02 21:28:23.688 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BOOT":{"CONTROL":"POWERMETER.BOOT","DEFAULT":false,"FLAGS":3,"ID":"BOOT","M
hm-rpc.0 | 2017-09-02 21:28:23.681 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.POWERMETER.16"
hm-rpc.0 | 2017-09-02 21:28:23.646 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":t
hm-rpc.0 | 2017-09-02 21:28:23.646 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.SWITCH.16"
hm-rpc.0 | 2017-09-02 21:28:23.584 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATION
hm-rpc.0 | 2017-09-02 21:28:23.582 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.MAINTENANCE.16"
hm-rpc.0 | 2017-09-02 21:28:23.247 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATI
hm-rpc.0 | 2017-09-02 21:28:23.246 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Bl1PBU-FM.BLIND.8"
hm-rpc.0 | 2017-09-02 21:28:23.188 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATION
hm-rpc.0 | 2017-09-02 21:28:23.186 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Bl1PBU-FM.MAINTENANCE.8"

**Comment by GermanBluefox** [comment]
Unfortunately it is not the full information. You should copy it from log file. 
```
{
	"type": "meta",
	"meta": {
		"adapter": "hm-rpc",
		"type": "paramsetDescription"
	},
	"common": {},
	"native": {
		"CONFIG_PENDING": {
			"DEFAULT": false,
			"FLAGS": 9,
			"ID": "CONFIG_PENDING",
			"MAX": true
-------------- Nothing here------------
```
