### ISSUE TITLE
new CUxD devices/channels after filter: 0 binrpc -> listDevices 54

### ISSUE THREAD

**Issue by HGB-123** [ioBroker/ioBroker.hm-rpc#431]
**Describe the bug**
Ich bekomme alle 3 Minuten die folgende Meldung:

<html><body>

hm-rpc.0 | 2022-01-14 20:50:23.642 | info | new CUxD devices/channels after filter: 0
-- | -- | -- | --
hm-rpc.0 | 2022-01-14 20:50:23.487 | info | binrpc -> listDevices 54
hm-rpc.0 | 2022-01-14 20:46:53.150 | info | new CUxD devices/channels after filter: 0
hm-rpc.0 | 2022-01-14 20:46:53.001 | info | binrpc -> listDevices 54

</body>
</html>

**Versions:**
 - hm-rpc version: 1.15.0
 - hm-rega version: 3.0.33
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Linux DietPi 5.10.81-meson64
 - CCU model: raspberrymatic
 - CCU firmware: 3.37.8.20180929

Danke für Eure EInschätzung oder Hilfe.

**Comment by Apollon77** [comment]
Mal cuxd bzw die CCU restarted?

**Comment by HGB-123** [comment]
ja, den Raspberry Pi habe ich mehrfach rebootet. Alle 3:30 Minuten kommen die beiden Meldung, ohne Unterbrechung.
