### ISSUE TITLE
Missing valve position [%] for HMIP-eTRV-e

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.hm-rpc#437]
I'm using mostly HM-CC-RT-DN where the valve position in [%] is shown as "valve_status".
Now I bought one HMIP-eTRV-e for testing and "valve_status" says "ADAPTION_DONE". That's literally not wrong for sure, but I'm missing the measured position. Could you please add it as another object?

**Comment by foxriver76** [comment]
How can I add it? I think we already get all possible values which can be obtained via xml-rpc

**Comment by passuff** [comment]
How can I check what is available? In the ccu/raspberrymatic web view I can see the valve status. Not sure how all this works. But I think this value is elementary and I can't imagine it's not available...

**Comment by Baxxy13** [comment]
The eTRV-E should show the `LEVEL` Datapoint in Channel:1, like every other IP-Radiator-Thermostat.
All Datapoints are listed in the "HmIP_Device_Documentation", downloadable from eQ-3

**Comment by passuff** [comment]
You're totally right. I was too much used to the legacy devices. Anyway the scale seems wrong by factor 100.

![image](https://user-images.githubusercontent.com/39516113/151373453-af809681-f827-4c99-9e00-4d58d8d3c691.png)

![image](https://user-images.githubusercontent.com/39516113/151373583-0efb574a-d939-494d-969e-691d35d6be54.png)
