### ISSUE TITLE
Gruppen INT Devices - Fehler im Log beim einlesen

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.hm-rpc#443]
Bekomme Massig Fehler beim Einlesen von Gruppen INT Devices:

PlatformBetriebssystem:linux
Node.js:v14.19.0
NPM:6.14.16
JS-Controller: 4.0.0
RPC Version: 1.15.0

Beispiel:

<html>
<body>

hm-rpc.2 | 2022-02-02 13:00:38.903 | info | State value to set for "hm-rpc.2.INT0000005.2.STATE" has to be type "boolean" but received type "string"
-- | -- | -- | --
hm-rpc.2 | 2022-02-02 13:00:38.846 | warn | This object will not be created in future versions. Please report this to the developer.
hm-rpc.2 | 2022-02-02 13:00:38.845 | warn | Object hm-rpc.2.INT0000005.2.STATE is invalid: Default value has to be type "boolean" but received type "string"
hm-rpc.2 | 2022-02-02 13:00:38.839 | warn | This object will not be created in future versions. Please report this to the developer.
hm-rpc.2 | 2022-02-02 13:00:38.838 | warn | Object INT0000005.2.STATE is invalid: Default value has to be type "boolean" but received type "string"
hm-rpc.2 | 2022-02-02 13:00:38.826 | info | xmlrpc -> getParamsetDescription ["INT0000005:2","VALUES"]
hm-rpc.2 | 2022-02-02 13:00:38.819 | info | State value to set for "hm-rpc.2.INT0000005.1.PARTY_START_TIME" has to be type "number" but received type "string"
hm-rpc.2 | 2022-02-02 13:00:38.767 | warn | This object will not be created in future versions. Please report this to the developer.
hm-rpc.2 | 2022-02-02 13:00:38.766 | warn | Object hm-rpc.2.INT0000005.1.PARTY_START_TIME is invalid: obj.common.min has an invalid type! Expected "number", received "string"
hm-rpc.2 | 2022-02-02 13:00:38.760 | warn | This object will not be created in future versions. Please report this to the developer.
hm-rpc.2 | 2022-02-02 13:00:38.759 | warn | Object INT0000005.1.PARTY_START_TIME is invalid: obj.common.min has an invalid type! Expected "number", received "string"
hm-rpc.2 | 2022-02-02 13:00:38.751 | info | State value to set for "hm-rpc.2.INT0000005.1.PARTY_TEMPERATURE" has to be type "number" but received type "string"

</body>
</html>

**Comment by MarkSau** [comment]
Zusatz: Habe den entsprechenden Objektbaum auch schon gelöscht. Keine Auswirkungen. Fehler bleiben.

**Comment by foxriver76** [comment]
Zeig mal bitte raw von so einem Objekt. Native wäre wichtig

**Comment by MarkSau** [comment]
[hm-rpc.2.INT0000001.json.txt](https://github.com/ioBroker/ioBroker.hm-rpc/files/7987725/hm-rpc.2.INT0000001.json.txt)

**Comment by foxriver76** [comment]
Thx, min max def alles als String gekommen.

**Comment by MarkSau** [comment]
hi...danke für den schnellen Fix...Aber....
ich habe da einen Wiedergabe Fehler gemacht..im log stehen noch viel viel mehr andere Objekte...
tut mir leid...
[hm-rpc.2.log.txt](https://github.com/ioBroker/ioBroker.hm-rpc/files/7989123/hm-rpc.2.log.txt)
[hm-rpc.2.json.txt](https://github.com/ioBroker/ioBroker.hm-rpc/files/7989137/hm-rpc.2.json.txt)

**Comment by foxriver76** [comment]
Der fix ist nicht Objekt spezifisch, kommen die Meldungen mit der neuen Version noch?

**Comment by MarkSau** [comment]
Ja

**Comment by foxriver76** [comment]
Ah zeig mal so ein Boolean aber String def Objekt bitte

**Comment by MarkSau** [comment]
Hab im Moment nur das Handy...aber in den zwei Files oben ist alles drin
