### ISSUE TITLE
startInstance hm-rpc.1: cannot find start file!

### ISSUE THREAD

**Issue by haselchen** [ioBroker/ioBroker.hm-rpc#445]
Moin Moin,

habe eben das Update auf die Version 1.15.2 durchgeführt.
Lief für 2 Instanzen ohne Fehler durch.
Als sie aber nach dem Update gestartet werden sollten ,kam im Log dieser Fehler:

<html><body>

host.IOBroker | 2022-02-04 01:14:30.672 | error | startInstance hm-rpc.1: cannot find start file!
-- | -- | -- | --
host.IOBroker | 2022-02-04 01:14:30.589 | error | startInstance hm-rpc.0: cannot find start file!

</body>
</html>

System läuft auf einer NAS.
Admin 5.0.31
JSController 3.2.16
Nodejs 12.22.10

**Comment by foxriver76** [comment]
Ah 3.2.16 had a bug with determining Start file from pack json

**Comment by Apollon77** [comment]
upgrade js-controller .. 3.3.22 is stable
