### ISSUE TITLE
LEVEL <0 warning

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker.hm-rpc#459]
Ich bekomme immer wieder diese Warnung:

hm-rpc.0  warn | State value to set for "hm-rpc.0.MEQ1471077.1.LEVEL" has value "-0.5" less than min "0"

Es handelt sich hierbei um einen Homematic Fenstermotor, den man tatsächlich mit -0.5 abschließt.
Der negative Wert ist hier also tatsächlich richtig und sollte keine Warnung erzeugen.

**Comment by foxriver76** [comment]
Please provide raw object

**Comment by foxriver76** [comment]
Òk, we need some special logic here, which corrects min/max if provided + special is provided and one of the special values is greater than max or less than min

**Comment by foxriver76** [comment]
Bitte mal das Objekt mit 1.15.12 neu anlegen lassen und Feedback geben ob min nun korrekt ist.

**Comment by aski71** [comment]
Sieht gut aus. Danke.

**Comment by Draexl** [comment]
Wurde damit auch das Thema behandelt das bei Heizthermostaten wenn sie auf "OFF" stehen (also 4,5) dies keinen Fehler im Log auswirft?

**Comment by foxriver76** [comment]
Kommt drauf an ob dies über ein `SPECIAL` Attribut kenntlich gemacht wird, kannst du mir ein solches Objekt zeigen?

**Comment by foxriver76** [comment]
Ne, ist dadurch leider nicht gefixt.
