### ISSUE TITLE
Send this info to developer: _id: 'hm-rpc.meta.VALUES.HM-ES-TX-WM.POWERMETER_IGL

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.hm-rpc#46]
http://forum.iobroker.net/viewtopic.php?f=22&t=8394

Drücke Strg+A und danach Strg+C, um den Inhalt in die Zwischenablage zu kopieren. Klicke irgendwo, um das Fenster zu schliessen.
hm-rpc.1   2017-10-08 15:59:06.270   warn   Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'ERROR_ALARM_TEST':{'CONTROL':'NONE','DEFAULT':0,'FLAGS':9,'ID':'ERROR_ALARM_TEST','MAX':1,'MIN':0,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'ENUM','UNIT':'','VALUE_LIST':['NO_ERROR','ALARM_TEST_FAILED']},'ERROR_SMOKE_CHAMBER':{'CONTROL':'NONE','DEFAULT':0,'FLAGS':9,'ID':'ERROR_SMOKE_CHAMBER','MAX':1,'MIN':0,'OPERATIONS':5,'TAB_ORDER':1,'TYPE':'ENUM','UNIT':'','VALUE_LIST':['NO_ERROR','DEGRADED_SMOKE_CHAMBER']},'INSTALL_TEST':{'DEFAULT':false,'FLAGS':3,'ID':'INSTALL_TEST','MAX':true,'MIN':false,'OPERATIONS':4,'TAB_ORDER':4,'TYPE':'ACTION','UNIT':''},'LOWBAT':{'CONTROL':'NONE','DEFAULT':false,'FLAGS':1,'ID':'LOWBAT','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':3,'TYPE':'BOOL','UNIT':''},'STATE':{'CONTROL':'DANGER.STATE','DEFAULT':false,'FLAGS':1,'ID':'STATE','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':2,'TYPE':'BOOL','UNIT':''}}}
hm-rpc.1   2017-10-08 15:59:06.269   warn   Send this info to developer: _id: 'hm-rpc.meta.VALUES.HM-Sec-SD-2.SMOKE_DETECTOR.5'
hm-rpc.1   2017-10-08 15:59:06.147   warn   Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'INSTALL_TEST':{'DEFAULT':false,'FLAGS':3,'ID':'INSTALL_TEST','MAX':true,'MIN':false,'OPERATIONS':4,'TAB_ORDER':1,'TYPE':'ACTION','UNIT':''},'STATE':{'CONTROL':'DANGER.STATE','DEFAULT':false,'FLAGS':1,'ID':'STATE','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'BOOL','UNIT':''}}}
hm-rpc.1   2017-10-08 15:59:06.146   warn   Send this info to developer: _id: 'hm-rpc.meta.VALUES.HM-Sec-SD-2-Team.SMOKE_DETECTOR_TEAM_V2.3'
hm-rpc.1   2017-10-08 15:59:05.980   warn   Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'AES_KEY':{'DEFAULT':0,'FLAGS':0,'ID':'AES_KEY','MAX':127,'MIN':0,'OPERATIONS':1,'TAB_ORDER':7,'TYPE':'INTEGER','UNIT':''},'CONFIG_PENDING':{'DEFAULT':false,'FLAGS':9,'ID':'CONFIG_PENDING','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':2,'TYPE':'BOOL','UNIT':''},'DUTYCYCLE':{'DEFAULT':false,'FLAGS':9,'ID':'DUTYCYCLE','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':4,'TYPE':'BOOL','UNIT':''},'LOWBAT':{'DEFAULT':false,'FLAGS':9,'ID':'LOWBAT','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':3,'TYPE':'BOOL','UNIT':''},'RSSI_DEVICE':{'DEFAULT':0,'FLAGS':1,'ID':'RSSI_DEVICE','MAX':2147483647,'MIN':-2147483648,'OPERATIONS':5,'TAB_ORDER':5,'TYPE':'INTEGER','UNIT':''},'RSSI_PEER':{'DEFAULT':0,'FLAGS':1,'ID':'RSSI_PEER','MAX':2147483647,'MIN':-2147483648,'OPERATIONS':5,'TAB_ORDER':6,'TYPE':'INTEGER','UNIT':''},'STICKY_UNREACH':{'DEFAULT':false,'FLAGS':25,'ID':'STICKY_UNREACH','MAX':true,'MIN':false,'OPERATIONS':7,'TAB_ORDER':1,'TYPE':'BOOL','UNIT':''},'UNREACH':{'DEFAULT':false,'FLAGS':9,'ID':'UNREACH','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'BOOL','UNIT':''}}}
hm-rpc.1   2017-10-08 15:59:05.979   warn   Send this info to developer: _id: 'hm-rpc.meta.VALUES.HM-Sec-SD-2.MAINTENANCE.5'
hm-rpc.1   2017-10-08 15:56:15.303   warn   Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'BOOT':{'CONTROL':'POWERMETER_IGL.BOOT','DEFAULT':false,'FLAGS':3,'ID':'BOOT','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':4,'TYPE':'BOOL','UNIT':''},'ENERGY_COUNTER':{'CONTROL':'POWERMETER_IGL.ENERGY_COUNTER','DEFAULT':0,'FLAGS':1,'ID':'ENERGY_COUNTER','MAX':838860.699219,'MIN':0,'OPERATIONS':5,'TAB_ORDER':2,'TYPE':'FLOAT','UNIT':'Wh'},'GAS_ENERGY_COUNTER':{'CONTROL':'POWERMETER_IGL.GAS_ENERGY_COUNTER','DEFAULT':0,'FLAGS':1,'ID':'GAS_ENERGY_COUNTER','MAX':2147483.644531,'MIN':0,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'FLOAT','UNIT':'m3'},'GAS_POWER':{'CONTROL':'POWERMETER_IGL.GAS_POWER','DEFAULT':0,'FLAGS':1,'ID':'GAS_POWER','MAX':16777.214996,'MIN':0,'OPERATIONS':5,'TAB_ORDER':1,'TYPE':'FLOAT','UNIT':'m3'},'POWER':{'CONTROL':'POWERMETER_IGL.POWER','DEFAULT':0,'FLAGS':1,'ID':'POWER','MAX':167772.149902,'MIN':0,'OPERATIONS':5,'TAB_ORDER':3,'TYPE':'FLOAT','UNIT':'W'}}}
hm-rpc.1   2017-10-08 15:56:15.300   warn   Send this info to developer: _id: 'hm-rpc.meta.VALUES.HM-ES-TX-WM.POWERMETER_IGL.1'

**Comment by GermanBluefox** [comment]
Thank you.
