### ISSUE TITLE
Update auf die 1.15.5

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.hm-rpc#466]
Hallo.
Seit dem Update auf die 1.15.5 wird die Instanzen für CUxD und für Virtual Device nicht mehr grün..
In beiden Fällen erhalte ich die unten stehenden Fehlermeldungen, IP mit Port wohl belegt.
Was ist damit gemeint?
Die zwei anderen Instanzen für RFD und Homematic IP werden grün.

``<html>
<body>

hm-rpc.1 | 2022-02-15 05:34:00.058 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
hm-rpc.1 | 2022-02-15 05:34:00.057 | info | terminating
hm-rpc.1 | 2022-02-15 05:34:00.049 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:34:00.049 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:34:00.049 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:33:59.986 | info | starting. Version 1.15.5 in C:/Program Files/iobroker/iobroker003/node_modules/iobroker.hm-rpc, node: v14.19.0, js-controller: 3.3.22
hm-rpc.1 | 2022-02-15 05:33:29.022 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:33:29.022 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:33:29.022 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:33:28.957 | info | starting. Version 1.15.5 in C:/Program Files/iobroker/iobroker003/node_modules/iobroker.hm-rpc, node: v14.19.0, js-controller: 3.3.22
hm-rpc.1 | 2022-02-15 05:32:57.883 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:32:57.883 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:32:57.883 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:32:57.818 | info | starting. Version 1.15.5 in C:/Program Files/iobroker/iobroker003/node_modules/iobroker.hm-rpc, node: v14.19.0, js-controller: 3.3.22
hm-rpc.1 | 2022-02-15 05:32:26.880 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hm-rpc.1 | 2022-02-15 05:32:26.879 | info | terminating
hm-rpc.1 | 2022-02-15 05:32:26.871 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:32:26.871 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:32:26.871 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:32:26.806 | info | starting. Version 1.15.5 in C:/Program Files/iobroker/iobroker003/node_modules/iobroker.hm-rpc, node: v14.19.0, js-controller: 3.3.22
hm-rpc.1 | 2022-02-15 05:31:55.853 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:31:55.852 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:31:55.852 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:31:55.699 | info | starting. Version 1.15.5 in C:/Program Files/iobroker/iobroker003/node_modules/iobroker.hm-rpc, node: v14.19.0, js-controller: 3.3.22
hm-rpc.1 | 2022-02-15 05:31:24.764 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hm-rpc.1 | 2022-02-15 05:31:24.763 | info | terminating
hm-rpc.1 | 2022-02-15 05:31:24.754 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 10.111.112.39:2000
hm-rpc.1 | 2022-02-15 05:31:24.754 | error | Error: listen EADDRINUSE: address already in use 10.111.112.39:2000 at Server.setupListenHandle [as _listen2] (net.js:1331:16) at listenInCluster (net.js:1379:12) at doListen (net.js:1516:7) at processTicksAndRejections (internal/process/task_queues.js:83:21)
hm-rpc.1 | 2022-02-15 05:31:24.754 | error | uncaught exception: listen EADDRINUSE: address already in use 10.111.112.39:2000

</body>
</html>``

**Comment by UweRP** [comment]
Konnte das Problem lösen indem ich bei **Adapter** Port den **Homematic** Port eingetragen habe.
![hm-rpc 1 CuXD Port geaendert](https://user-images.githubusercontent.com/17329042/153996399-2fe9f7f0-011f-4c52-82ce-a16fdfab60ef.jpg)

Was mich verwundert, in der alten Version des hm-rpc Adapter hat noch eine 0 (null) funktioniert, auch für meine RFD Instanz reicht dort eine 0

![hm-rpc 0 RFD](https://user-images.githubusercontent.com/17329042/153996643-3f2b691d-e390-429c-a106-be0561e3cf1d.png)

**Comment by foxriver76** [comment]
An dem Handling hat sich nichts geändert. Vermutlich eher Zufall dass da bei dir noch was unter dem Port läuft.

**Comment by danyial** [comment]
Ich musste auch den Port änder, damit er wieder grün wird...
