### ISSUE TITLE
State value to set for "hm-rpc.xyz.0.RSSI_DEVICE" has value "128" greater than max "127"

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.hm-rpc#469]
I'm getting the following error message from a lot of hmip devices:
`hm-rpc.1 | 2022-02-15 17:08:27.272 | warn | State value to set for "hm-rpc.1.000E5D89A9454A.0.RSSI_DEVICE" has value "128" greater than max "127"`

I can adjust it my self, but it should be done by the adaptor imho.

`{
  "type": "state",
  "common": {
    "name": "Temperatur Wohnzimmer Anbau:0.RSSI_DEVICE",
    "role": "value.rssi",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    **"max": 127,**
    "unit": "dBm"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    **"MAX": 127,**
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644928513459,
  "_id": "hm-rpc.1.xyz.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by pphlwmarcel** [comment]
Still in Version 1.15.8 I'm getting this warn messages in Log

`2022-03-16 08:56:14.030 | warn | State value to set for "hm-rpc.2.xxxxxxxxxxxx.0.RSSI_DEVICE" has value "128" greater than max "127"`

Do I have to adjust some datapoints manually or is it still a bug in the adapter?

**Comment by foxriver76** [comment]
The adapter does only fix objects on "recreation", thus use a "Geräte neueinlesen" (Synchronize objects) run.
