### ISSUE TITLE
HMW-IO-12-FM with wrong objects

### ISSUE THREAD

**Issue by hennott** [ioBroker/ioBroker.hm-rpc#47]
Hi .. I´ve HMW-IO-4-FM and HMW-IO-12-FM wired interfaces but just the HMW-IO-4-FM is imported correctly. The HMW-IO-12-FM has only STATE as object but most of them are set as button input. 

I tried to set them manually what works but I´ve to add nearly 240 Objects for PRESS_SHORT and PRESS_LONG .. is there a solution to import them with correct Objects?

In the "io-package.json" there is no section for the HMW-IO-12-FM and HMW-IO-4-FM.

**Comment by GermanBluefox** [comment]
How does look like the meta description of this object? 
hm-rpc.0.BLBLA00888.1  => native 
![image](https://user-images.githubusercontent.com/4582016/33188353-8ad917e0-d099-11e7-9a3f-4a73b4d9fa39.png)

**Comment by foxriver76** [comment]
more than one year old and no meta information provided
