### ISSUE TITLE
... has value "128" greater than max "127"

### ISSUE THREAD

**Issue by baerenwaldfreund** [ioBroker/ioBroker.hm-rpc#471]
Der Fehler besteht bei der v1.15.6 weiterhin:

`<html><body>

hm-rpc.1 | 2022-02-20 11:28:37.742 | warn | State value to set for "hm-rpc.1.xxxxxxxxxxxxxxxxx.0.RSSI_DEVICE" has value "128" greater than max "127"
-- | -- | -- | --

</body>
</html>`

Siehe auch [hier](https://github.com/ioBroker/ioBroker.hm-rpc/issues/346#issue-926328650).

**Comment by foxriver76** [comment]
Please use 1.15.7, previous versions had a bug not creating devices correct. Also you have to use read devices anew, else hm-rpc won't touch the objects

**Comment by raschy** [comment]
I got an error message in ioBroker today: State value to set for "hm-rpc.1.00155D899126BD.0.RSSI_DEVICE" has value "128" greater than max "127"

![hm-rpc1_RSSI-Device](https://user-images.githubusercontent.com/75622810/236497954-a114f15f-13d6-4869-ac10-932cf06e6761.png)

This was also displayed in the RaspberryMatic as a "communication error" (or something).

Here is the raw from the data point:
{
  "type": "state",
  "common": {
    "name": "HmIP-SWDM 00155D899126BD:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644767827664,
  "_id": "hm-rpc.1.00155D899126BD.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

I use the  hm-rpc v1.15.16
