### ISSUE TITLE
Send this info to developer : hm-rpc.meta.VALUES.HmIP-SWDO-I.SHUTTER_CONTACT

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.hm-rpc#48]
http://forum.iobroker.net/viewtopic.php?t=8714

host.lemaker	2017-10-27 15:32:24.363	info	object change system.adapter.hm-rpc.2
hm-rpc.2	2017-10-27 15:32:24.219	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"STATE":{"MIN":"CLOSED","UNIT":"\"\"","OPERATIONS":5,"MAX":"OPEN","FLAGS":1,
hm-rpc.2	2017-10-27 15:32:24.215	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-SWDO-I.SHUTTER_CONTACT.1"
hm-rpc.2	2017-10-27 15:32:24.126	info	xmlrpc -> getParamsetDescription ["xxxxxxxxxxxxxxxxx:1","VALUES"]
hm-rpc.2	2017-10-27 15:32:23.470	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"SABOTAGE":{"MIN":false,"OPERATIONS":5,"MAX":true,"FLAGS":9,"ID":"SABOTAGE",
hm-rpc.2	2017-10-27 15:32:23.468	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HmIP-SWDO-I.MAINTENANCE.1"
hm-rpc.2	2017-10-27 15:32:23.260	info	xmlrpc -> getParamsetDescription ["00109709xxxxxx:0","VALUES"]
hm-rpc.2	2017-10-27 15:32:23.144	warn	No image for "HmIP-SWDO-I" found.

**Comment by holger05** [comment]
I can not reproduce this error anymore.
The entry is now available in the object list. Perhaps already fixed with an update the last weeks.

But the icon is still wrong. See attachment.
![device](https://user-images.githubusercontent.com/33962350/33217063-ba2fc546-d136-11e7-8857-6e976e08af61.png)

**Comment by holger05** [comment]
Here is the right icon:
![152_hmip-swdo-i_thumb](https://user-images.githubusercontent.com/33962350/33217190-3505f5ce-d137-11e7-8ffe-993c544b69b7.png)

**Comment by foxriver76** [comment]
icon is already fixed (https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/admin/icons/152_hmip-swdo-i_thumb.png) and problem did not occur again.
