### ISSUE TITLE
Send this info to developer

### ISSUE THREAD

**Issue by FuXXz** [ioBroker/ioBroker.hm-rpc#50]
hm-rpc.0 | 2017-11-26 17:26:46.081 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
-- | -- | -- | --
hm-rpc.0 | 2017-11-26 17:26:46.080 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.SWITCH.26"
hm-rpc.0 | 2017-11-26 17:26:46.056 | info | binrpc -> getParamsetDescription ["OEQ0654075:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:46.003 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:46.003 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.MAINTENANCE.26"
hm-rpc.0 | 2017-11-26 17:26:45.973 | info | binrpc -> getParamsetDescription ["OEQ0654075:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.862 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-11-26 17:26:45.862 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1T-FM.DIMMER.21"
hm-rpc.0 | 2017-11-26 17:26:45.736 | info | binrpc -> getParamsetDescription ["OEQ0570544:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.703 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,
hm-rpc.0 | 2017-11-26 17:26:45.702 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1T-FM.MAINTENANCE.21"
hm-rpc.0 | 2017-11-26 17:26:45.678 | info | binrpc -> getParamsetDescription ["OEQ0570544:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.540 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BRIGHTNESS":{"DEFAULT":0,"FLAGS":1,"ID":"BRIGHTNESS","MAX":255,"MIN":0,"OPER
hm-rpc.0 | 2017-11-26 17:26:45.540 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sen-MDIR-WM55.MOTION_DETECTOR.5"
hm-rpc.0 | 2017-11-26 17:26:45.527 | info | binrpc -> getParamsetDescription ["OEQ0539060:3","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.466 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0 | 2017-11-26 17:26:45.465 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sen-MDIR-WM55.KEY.5"
hm-rpc.0 | 2017-11-26 17:26:45.437 | info | binrpc -> getParamsetDescription ["OEQ0539060:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.382 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:45.382 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sen-MDIR-WM55.MAINTENANCE.5"
hm-rpc.0 | 2017-11-26 17:26:45.349 | info | binrpc -> getParamsetDescription ["OEQ0539060:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.114 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0 | 2017-11-26 17:26:45.114 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-PB-6-WM55.KEY.7"
hm-rpc.0 | 2017-11-26 17:26:45.093 | info | binrpc -> getParamsetDescription ["OEQ0283950:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:45.048 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:45.048 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-PB-6-WM55.MAINTENANCE.7"
hm-rpc.0 | 2017-11-26 17:26:44.941 | info | binrpc -> getParamsetDescription ["OEQ0283950:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.884 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0 | 2017-11-26 17:26:44.883 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-SCI-3-FM.SHUTTER_CONTACT.10"
hm-rpc.0 | 2017-11-26 17:26:44.869 | info | binrpc -> getParamsetDescription ["OEQ0132046:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.830 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:44.829 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-SCI-3-FM.MAINTENANCE.10"
hm-rpc.0 | 2017-11-26 17:26:44.803 | info | binrpc -> getParamsetDescription ["OEQ0132046:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.677 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-11-26 17:26:44.677 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1T-Pl-3.VIRTUAL_DIMMER.17"
hm-rpc.0 | 2017-11-26 17:26:44.625 | info | binrpc -> getParamsetDescription ["MEQ1567118:2","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.399 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0 | 2017-11-26 17:26:44.399 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1T-Pl-3.DIMMER.17"
hm-rpc.0 | 2017-11-26 17:26:44.332 | info | binrpc -> getParamsetDescription ["MEQ1567118:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.233 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:44.233 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1T-Pl-3.MAINTENANCE.17"
hm-rpc.0 | 2017-11-26 17:26:44.067 | info | binrpc -> getParamsetDescription ["MEQ1567118:0","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:44.058 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-11-26 17:26:44.053 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_FREQUENCY.16"
hm-rega.0 | 2017-11-26 17:26:44.044 | info | got state values
hm-rpc.0 | 2017-11-26 17:26:44.014 | info | binrpc -> getParamsetDescription ["LEQ0530627:6","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.975 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-11-26 17:26:43.975 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_VOLTAGE.16"
hm-rpc.0 | 2017-11-26 17:26:43.933 | info | binrpc -> getParamsetDescription ["LEQ0530627:5","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.888 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-11-26 17:26:43.888 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_CURRENT.16"
hm-rpc.0 | 2017-11-26 17:26:43.858 | info | binrpc -> getParamsetDescription ["LEQ0530627:4","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.829 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0 | 2017-11-26 17:26:43.825 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_POWER.16"
hm-rpc.0 | 2017-11-26 17:26:43.800 | info | binrpc -> getParamsetDescription ["LEQ0530627:3","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.719 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BOOT":{"CONTROL":"POWERMETER.BOOT","DEFAULT":false,"FLAGS":3,"ID":"BOOT","MA
hm-rpc.0 | 2017-11-26 17:26:43.719 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.POWERMETER.16"
hm-rpc.0 | 2017-11-26 17:26:43.441 | info | binrpc -> getParamsetDescription ["LEQ0530627:2","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.404 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0 | 2017-11-26 17:26:43.404 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.SWITCH.16"
hm-rpc.0 | 2017-11-26 17:26:43.218 | info | binrpc -> getParamsetDescription ["LEQ0530627:1","VALUES"]
hm-rpc.0 | 2017-11-26 17:26:43.166 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0 | 2017-11-26 17:26:43.166 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.MAINTENANCE.16"

**Comment by GermanBluefox** [comment]
Can you please extract this info from log files? As you can see the json is not complete

**Comment by BuZZy1337** [comment]
@FuXXz any new informations regarding this? As Bluefox mentioned you have to extract this directly from the logfile.
