### ISSUE TITLE
Update 1.5.8: Komplette Anlage funktioniert nicht mehr

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.hm-rpc#503]
**Describe the bug**
Nach dem Update auf die 1.5.8 (von 1.5.0) funktioniert die komplette Anlage nicht mehr (HmIP & HmIP Wired).
Status wird nicht mehr übermittelt und schalten eines Aktors dauert 30s. Nach 3-5 schaltversuchen verabschiedet sich Raspimatic mit einem Watch Dog reset regahss restarted.
Wenn man die Instanz deaktiviert und Raspimatic neustartet, funktioniert wieder alles.

**To Reproduce**
1. hm-rpc instanz aktivieren
2. aktor schalten (über iobroker oder raspimatic)

**Screenshots & Logfiles**
iobroker log:
```
2022-03-14 07:48:50.552  - error: hm-rpc.0 (12831) Init not possible, going to stop: Unexpected end
2022-03-14 07:49:05.542  - error: hm-rpc.0 (12831) Init not possible, going to stop: Unexpected end
2022-03-14 07:49:20.540  - error: hm-rpc.0 (12831) Init not possible, going to stop: Unexpected end
2022-03-14 07:50:37.708  - error: hm-rpc.0 (12889) Init not possible, going to stop: Unexpected end
```

Auszug raspimatic log, diese Meldung kommen für alle Aktoren und Sensoren:
```
Mar 14 14:40:39 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000XXXXXX:6","ENERGY_COUNTER"}, result: [faultCode:-5,faultString:"Unknown Parameter value for value key: ENERGY_COUNTER"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Mar 14 14:40:39 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1035, params: {"000XXXXXX:6","ENERGY_COUNTER"}) [CallGetValue():iseXmlRpc.cpp:1435]
Mar 14 14:40:39 homematic-raspi local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0.000000 [ReadValue():iseDOMdpHSS.cpp:124]
Mar 14 14:40:39 homematic-raspi local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"000XXXXXX:6","ENERGY_COUNTER"}, result: [faultCode:-5,faultString:"Unknown Parameter value for value key: ENERGY_COUNTER"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
Mar 14 14:40:39 homematic-raspi local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1035, params: {"000XXXXXX:6","ENERGY_COUNTER"}) [CallGetValue():iseXmlRpc.cpp:1435]
```

**Versions:**
 - hm-rpc version: 1.5.8
 - hm-rega version: 3.0.35
 - JS-Controller version: 4.0.19
 - Node version: 14.19.0
 - Operating system: ubuntu 20.04 LTS
 - CCU model: raspberrymatic intel nuc
 - CCU firmware: 3.61.7.20220226

**Additional context**
Ich hab ein paar Versionen getestet und der Fehler tritt ab 1.15.5 auf.

**Comment by foxriver76** [comment]
Irgendwelche Besonderheiten im Setup, z. B. mehrere CCUs?

**Comment by Keule00** [comment]
Hallo

Ich habe auch Probleme nach dem gestrigen Update von 1.5.0 auf 1.5.8

Kein Totalausfall, aber mein HM-IP Wandthermostat funktioniert nicht mehr, wie vorher. Bzw. die Verbindung zwischen Raspberrymatic und iobroker.
Die Kommunikation von RasperryMatic zu iobroker funktioniert (Solltemperatur übertragen). Aber von iobroker zu Raspberymatic (Solltemperatur eingestellt im NodeRED Dashboard)  nicht. Die eingestellte Temp. erscheint zwar in den iobroker-Objekten, aber wird nicht nicht zur RaspberryMatic übertragen.

**Comment by tigerjoerg** [comment]
Hallo zusammen,
ich habe ebenfalls das gleiche Problem. 
Ich bekomme keine Verbindung mehr zur CCU2, zur RaspberyMatic funktioniert die Verbindung.

`<html>
<body>


host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | instance system.adapter.hm-rpc.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:81:21)
host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | Caught by controller[0]: at doListen (net.js:1503:7)
host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | Caught by controller[0]: at listenInCluster (net.js:1366:12)
host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | Caught by controller[0]: at Server.setupListenHandle [as _listen2] (net.js:1318:16)
host.iobroker(SmartHome) | 2022-03-14 18:54:47.584 | error | Caught by controller[0]: Error: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.1 | 2022-03-14 18:54:47.491 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.1 | 2022-03-14 18:54:47.491 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.1 | 2022-03-14 18:54:47.491 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | instance system.adapter.hm-rpc.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:81:21)
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | Caught by controller[0]: at doListen (net.js:1503:7)
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | Caught by controller[0]: at listenInCluster (net.js:1366:12)
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | Caught by controller[0]: at Server.setupListenHandle [as _listen2] (net.js:1318:16)
host.iobroker(SmartHome) | 2022-03-14 18:54:37.468 | error | Caught by controller[0]: Error: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 18:54:37.375 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 18:54:37.375 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.0 | 2022-03-14 18:54:37.375 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000


</body>
</html>`

**Comment by Scrounger** [comment]
> Irgendwelche Besonderheiten im Setup, z. B. mehrere CCUs?

Hab noch einen HmIP-HAP als Gateway konfiguriert. Den kann ich aber ausschließen, da ich natürlich als erstes mal Homematic im Verdacht für die Probleme hatte und ewig nicht auf die Idee kam das es am Adapter liegen könnte ;-)

Wie kann ich helfen, debug / silly logs? Logs vom Raspimatic - welche? Da es leider Produktivsystem ist, kann ich nur bedingt testen.

**Comment by foxriver76** [comment]
Ich denke es liegt definitiv am Adapter, aber evtl. nur unter bestimmten Konstellationen, da ich einen Fall im Forum hatte, welcher bislang ungelöst ist, da waren allerdings mehre CCUs  + mehrere iob __master__ im Einsatz.


Wenn es schnell repdouzierbar ist, wäre ein Debug Log von hm-rpc interessant. Am Besten inkl. Schaltvorgänge. Da der komplette Code auf TS portiert wurde, wurde so ziemlich jede Zeile angefasst und ich kanns leider nicht schnell eingrenzen.

**Comment by tigerjoerg** [comment]
der Adpater lief auch noch vor dem Update ohne Probleme.
Hier das Debug-Logfile - Schaltvorgänge funktionieren nicht. Alle drei Statusmeldungen sind rot:

- Verbunden mit Host
- Lebenszeichen
- Verbunden mit Gerät oder Dienst

`<html>
<body>


hm-rpc.0 | 2022-03-14 19:26:56.018 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
hm-rpc.0 | 2022-03-14 19:26:56.018 | debug | Plugin sentry destroyed
hm-rpc.0 | 2022-03-14 19:26:56.018 | info | terminating
hm-rpc.0 | 2022-03-14 19:26:56.003 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:26:56.003 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.0 | 2022-03-14 19:26:56.003 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:26:55.919 | info | starting. Version 1.15.8 in C:/iobroker/SmartHome/node_modules/iobroker.hm-rpc, node: v14.9.0, js-controller: 4.0.21
hm-rpc.0 | 2022-03-14 19:26:55.648 | debug | Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.0 | 2022-03-14 19:26:24.150 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hm-rpc.0 | 2022-03-14 19:26:24.150 | debug | Plugin sentry destroyed
hm-rpc.0 | 2022-03-14 19:26:24.150 | info | terminating
hm-rpc.0 | 2022-03-14 19:26:24.150 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:26:24.150 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.0 | 2022-03-14 19:26:24.150 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:26:24.071 | info | starting. Version 1.15.8 in C:/iobroker/SmartHome/node_modules/iobroker.hm-rpc, node: v14.9.0, js-controller: 4.0.21
hm-rpc.0 | 2022-03-14 19:26:23.615 | debug | Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.0 | 2022-03-14 19:25:51.934 | debug | start connecting interval
hm-rpc.0 | 2022-03-14 19:25:51.934 | debug | xmlrpc -> 192.168.69.238:2001/ init ["http://192.168.69.250:2000","iobroker(SmartHome):hm-rpc.0:bd62297f06cc52fe76064587d86639da"]
hm-rpc.0 | 2022-03-14 19:25:51.918 | debug | Connect...
hm-rpc.0 | 2022-03-14 19:25:51.918 | info | xmlrpc client is trying to connect to 192.168.69.238:2001/ with ["http://192.168.69.250:2000","iobroker(SmartHome):hm-rpc.0:bd62297f06cc52fe76064587d86639da"]
hm-rpc.0 | 2022-03-14 19:25:51.918 | info | xmlrpc server is trying to listen on 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:51.918 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hm-rpc.0 | 2022-03-14 19:25:51.918 | debug | Plugin sentry destroyed
hm-rpc.0 | 2022-03-14 19:25:51.918 | info | terminating
hm-rpc.0 | 2022-03-14 19:25:51.903 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:51.903 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.0 | 2022-03-14 19:25:51.903 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:51.825 | info | starting. Version 1.15.8 in C:/iobroker/SmartHome/node_modules/iobroker.hm-rpc, node: v14.9.0, js-controller: 4.0.21
hm-rpc.0 | 2022-03-14 19:25:51.030 | debug | Plugin sentry Initialize Plugin (enabled=true)
hm-rpc.0 | 2022-03-14 19:25:19.355 | debug | start connecting interval
hm-rpc.0 | 2022-03-14 19:25:19.355 | debug | xmlrpc -> 192.168.69.238:2001/ init ["http://192.168.69.250:2000","iobroker(SmartHome):hm-rpc.0:822a7009fa9935c0600b82c8a4d5fcc4"]
hm-rpc.0 | 2022-03-14 19:25:19.355 | debug | Connect...
hm-rpc.0 | 2022-03-14 19:25:19.355 | info | xmlrpc client is trying to connect to 192.168.69.238:2001/ with ["http://192.168.69.250:2000","iobroker(SmartHome):hm-rpc.0:822a7009fa9935c0600b82c8a4d5fcc4"]
hm-rpc.0 | 2022-03-14 19:25:19.340 | info | xmlrpc server is trying to listen on 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:19.340 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
hm-rpc.0 | 2022-03-14 19:25:19.340 | debug | Plugin sentry destroyed
hm-rpc.0 | 2022-03-14 19:25:19.340 | info | terminating
hm-rpc.0 | 2022-03-14 19:25:19.340 | error | Exception-Code: EADDRINUSE: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:19.340 | error | Error: listen EADDRINUSE: address already in use 192.168.69.250:2000 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at doListen (net.js:1503:7) at processTicksAndRejections (internal/process/task_queues.js:81:21)
hm-rpc.0 | 2022-03-14 19:25:19.340 | error | uncaught exception: listen EADDRINUSE: address already in use 192.168.69.250:2000
hm-rpc.0 | 2022-03-14 19:25:19.262 | info | starting. Version 1.15.8 in C:/iobroker/SmartHome/node_modules/iobroker.hm-rpc, node: v14.9.0, js-controller: 4.0.21
hm-rpc.0 | 2022-03-14 19:25:18.749 | debug | Plugin sentry Initialize Plugin (enabled=true)


</body>
</html>`

**Comment by tigerjoerg** [comment]
noch eine Info:

Die Verbindung über folgenden Daemon und folgendes Protokoll funktioniert:
**Daemon CUxD
Protokoll BIN-RPC**

Über folgenden Daemon und über folgendes Protokoll nicht:
**Daemon	rfd
Protokoll XML-RPC

Daemon HomeMatic IP
Protokoll XML-RPC**

Vielleicht helfen die Infos noch

**Comment by Burgruine** [comment]
Hallo,
hatte auch die Probleme mit der Version 1.15.8. Konnte Geräte von Vis aus schalten, aber es kahm kein Status von der Homematic z.B. Wetterstation Temperatur, nach Neustart funktionierte es wieder für ca. eine Stunde. Da ich mit dem HomeMatic ReGaHSS Adapter Probleme mit den Variablen hatte machte ich ein downgrade von 3.0.37 auf 3.0.33. Danach funktionierten die Variablen wieder und der HM RPC Adapter auch wieder.

**Comment by Keule00** [comment]
> Hallo
> 
> Ich habe auch Probleme nach dem gestrigen Update von 1.5.0 auf 1.5.8
> 
> Kein Totalausfall, aber mein HM-IP Wandthermostat funktioniert nicht mehr, wie vorher. Bzw. die Verbindung zwischen Raspberrymatic und iobroker. Die Kommunikation von RasperryMatic zu iobroker funktioniert (Solltemperatur übertragen). Aber von iobroker zu Raspberymatic (Solltemperatur eingestellt im NodeRED Dashboard) nicht. Die eingestellte Temp. erscheint zwar in den iobroker-Objekten, aber wird nicht nicht zur RaspberryMatic übertragen.

Ich habe den Fehler gefunden. Es lag nicht am Adapter.
Ich hatte in Node-RED eine falsche Einstellung im Programm. Als Type stand "value" statt "command".

![03](https://user-images.githubusercontent.com/55344277/158435867-e38b5ad3-d30b-4eb6-a0d5-f181896cd214.JPG)


Warum es aber bisher immer funktionier hat, weiß ich nicht

**Comment by tigerjoerg** [comment]
ich bin nun zurück auf den Adapter 1.15.2

Das gleiche Fehlerbild ist ab der Version 1.15.3

**Comment by flenny** [comment]
Hier auch. Objekte synchronisieren seit 1.15.3 nicht mehr. Auch mit 1.15.9 nicht. Bin jetzt zurück auf 1.15.2

**Comment by foxriver76** [comment]
Ok, dann bleibt mir aktuell noch die angesprochene Idee, bitte 1.5.10 testen.

**Comment by flenny** [comment]
> Ok, dann bleibt mir aktuell noch die angesprochene Idee, bitte 1.5.10 testen.

Klappt leider auch nicht. Ich hab dir [hier](https://github.com/ioBroker/ioBroker.hm-rpc/files/8291803/debug.log) noch den Log-Output während dem Startup der Version 1.15.10/1.15.3 und 1.15.2. Gibts noch einen "besseren" Log als der direkt aus dem iobroker Webinterface?

Herzlichen Dank schon mal im Voraus für den tollen Support 👍🏼

**Comment by kopierschnitte** [comment]
Bei mir zeigt es sich so, dass ab 1.15.3 Werte z. T. gar nicht (HmIP-Temperatursensoren) oder erst 45min nach dem Adapterstart (PRESS-Events von HmIP-Tastern) aktualisiert werden. Getestet habe ich bis einschließlich 1.15.10.
Fehlermeldungen im Log gibt's keine und die CCU ist RaspberryMatic.

**Comment by foxriver76** [comment]
Geräte werden allerdings neu angelegt? Ist iwie super weird und ich sehe in den Diffs bislang nix was dazu führen könnte.

**Comment by flenny** [comment]
Ich habe bei mir auch die RaspberryMatic CCU im Einsatz. Geräte werden bei mir ab 1.15.3 nicht neu angelegt/synchronisiert. Der Haken in den Adapter-Einstelllungen (Objekte einmal synchronsieren, oder so ähnlich) bleibt nachdem der Adapter neu gestartet wurde drin. Mit 1.15.2 und vorherigen Version wird die Einmal-Synchronisieren-Option normalerweise automatisch wieder deaktivert.

**Comment by foxriver76** [comment]
Eventuell Docker dazwischen (Port Mapping) oder irgendwas was böse wäre, falls sich der Port ändert? Das wäre das einzige was ich im Log an Unterschied sehe.

**Comment by kopierschnitte** [comment]
Bei mir nicht. RM auf RPi4 und ioBroker als VM unter ESXi.

**Comment by juersei** [comment]
FYI: I am running ioBroker in a docker container on a Synology DS920. Many of my sensors etc. are connected via MQTT and homematic, several are redundant, therefore I can always compare the MQTT values with the homematic values. hat was the reason that I found my homematic (-IP only)  values stuck compared to the ones deliverd by the MQTT connected sensors.

**Comment by foxriver76** [comment]
Bitte 1.15.11 Testen ich schiebe sie später auch ins stable. Falls damit noch Probleme, hier wieder melden.

**Comment by flenny** [comment]
@foxriver76 1.15.11 tut wunderbar! Thx! 🙏🏼

**Comment by tigerjoerg** [comment]
@foxriver76 : Bei mir ebenfalls. Danke für die schnelle Hilfe

**Comment by kopierschnitte** [comment]
@foxriver76 Hier auch alles ok. Danke!

**Comment by Scrounger** [comment]
@foxriver76 
Mit der 1.15.11 scheint alles wieder zu funktionieren, danke für den schnellen fix!
