### ISSUE TITLE
Keine RSSI-Werte bei HomeMatic ("klassische Sensoren")

### ISSUE THREAD

**Issue by joergeli** [ioBroker/ioBroker.hm-rpc#506]
Version:  hm-rpc v1.15.8

Ich bekomme bei den "klassischen" HomeMatic-Sensoren unter z.B. hm-rpc.0.OEQ1425263.0.**RSSI_DEVICE** bei allen Sensoren nur 0 dBm angezeigt.

Bei den HomeMatic **IP**-Sensoren werden die RSSI-Werte korrekt angezeigt.

Bei einem ioBroker-Kollegen ist es ebenso, siehe:

[HomeMatic rpc - keine RSSI-Werte](https://forum.iobroker.net/topic/53345/homematic-rpc-keine-rssi-werte)

**Comment by foxriver76** [comment]
Ja da kommt für die bidcos Geräte keine Updates rein über XML rpc wie es scheint. Kann da meines Wissens nach nix machen leider, evtl. Mal bei eq3 anfragen/issue eröffnen

**Comment by joergeli** [comment]
Danke für die Rückmeldung!
Wie im ioBroker-Forum geschrieben, kann ich mir ja per JS über die rssilist.cgi helfen - ist letztendlich auch nicht soooo wichtig.
Wenn ich mir die Antworten im eq3/ELV-Forum so anschaue, lasse ich das lieber, denn wenn ich schreibe, daß die RSSI-Werte in der HomeMatic-GUI korrekt angezeigt werden und "lediglich" nicht in ioBroker ankommen, welche Antwort würde ich dann wohl erwarten können ? ;-))

**Comment by foxriver76** [comment]
Hm naja, die XML-RPC Api ist ja ein Feature von eq3 und darüber kommen die von bidcos Geräten definitiv nicht, aber das Paramset wird gekostet weshalb auch das Objekt angelegt wird. Also mmn definitiv ein Bug auf eq3 Seite. Für hmip senden sie es ja schließlich
