### ISSUE TITLE
hm-rpc nutz falschen Port

### ISSUE THREAD

**Issue by PlanLos23** [ioBroker/ioBroker.hm-rpc#509]
Nach dem Update auf die 1.15.9 funktionierte die Abfrage der Werte auf der CCU3 nicht mehr.
Hintergrund des Fehlers ist der Zugriff auf einen neuen, vorher nicht genutzten Port (Port 2000).
Diesen hatte ich in der Firewall geblockt.

![image](https://user-images.githubusercontent.com/26043395/159010141-e6bd9e44-6177-49aa-a564-5603048d1a20.png)

In der Instanz sind aber die Werte korrekt eingetragen.

![image](https://user-images.githubusercontent.com/26043395/159010274-a8db5fe7-a3ee-45f4-90ae-86d8cf4eb818.png)

Wenn ich den Adapter Port auf 2001 ändere, springt der Port in dem Log auf die 2002.

![image](https://user-images.githubusercontent.com/26043395/159010557-c61ab1fb-cb44-485e-9bf4-007cf7636846.png)

Es scheint als wenn hier ein Fehler des hm-rpc vorliegt.

 - hm-rpc version: 1.15.9
 - hm-rega version: 3.0.35
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: Docker Container
 - CCU model: CCU3
 - CCU firmware: 3.61.7

**Comment by foxriver76** [comment]
Naja das Verhalten hat sich leicht geändert. Wenn adapter Port 0 war wurde vorher der Homematic port angezogen in deinem Fall 2001, jetzt wird stattdessen der default 2000 angezogen. 

Dass der Port eine Nummer höher angezogen wird liegt dann daran dass der gewählte Port belegt ist.

**Comment by foxriver76** [comment]
1.5.11 nutzt wieder die alte Logik zur Port Ermittlung

**Comment by PlanLos23** [comment]
Da jetzt der Port 2000 bei mir nun auch freigegeben ist, laufen ja beide Varianten. ;)
Danke für die schnelle Rückmeldung.
