### ISSUE TITLE
Datenpunkt bleibt auf unbestätigt

### ISSUE THREAD

**Issue by uwe72** [ioBroker/ioBroker.hm-rpc#511]
Kann über iobroker einen Homematic Schalter ordnungsgemäß schalten.

Warum wird der Datenpunkt nicht als bestätigt angezeigt? So wie ich das Konzept (ack/bestätigt) verstehe, arbeitet der Adapter (hm) die unbestätigten Änderungen ab und wenn er sie abgearbeitet hat setzt er bestätigt auf true. Warum passiert dies hier nicht, obwohl die Lampe geschaltet wurde? 

![image](https://user-images.githubusercontent.com/61848539/159163977-451ce9ff-6edf-4294-aa18-dcfc78d1b968.png)

**Comment by Apollon77** [comment]
> arbeitet der Adapter (hm) die unbestätigten Änderungen ab und wenn er sie abgearbeitet hat setzt er bestätigt auf true. 

Denkfehler ... Der Adapter arbeitet Sie ab und das Gerät meldet den neuen Status und basierend darauf setzt der Adapter den Status neu mit dem Wert welcher vom Gerät zurückkam.
Wenn es also "rot" bleibt heisst das, dass das Gerät keine Rückmeldung gegeben hat und damit ist der Zustand unbekannt.

Warum lässt sich schön mit einem Temperaturwert für ein thermostat erklären: Du sendes 23,3 und der Adapter setzt 23,5 (weil er rundet) und damit ist der Wert der wirklich im gerät steht halt ein anderer ... daher setzt niucht der Adapter einfach den Wert auf das gesendete

**Comment by Apollon77** [comment]
Steht irgendwas im Log? Wird es denn geschaltet?

**Comment by uwe72** [comment]
Im Log steht nichts. Geschaltet wird die Lampe.

Könnte mir in der Tat vorstellen, dass das Device (nicht beste Empfang an der Stelle) nicht wirklich dem Adapter eine Rückmeldung gibt.

Leider kann ich vom ioBroker nicht zuverlässig den Zustand eines Devices abfragen, bei dem beispielsweise in der CCU3 "Gerätekommunikations gestört" angezeigt wird.

**Comment by Apollon77** [comment]
> Leider kann ich vom ioBroker nicht zuverlässig den Zustand eines Devices abfragen, bei dem beispielsweise in der CCU3 "Gerätekommunikations gestört" angezeigt wird.

Naja wenn die CCU3 was das Kommunikations-Gateway keine Verbidnung hat wie soll ioBroker da mehr sagen? in den States des Channel 0 siehst du aber UNREACH zb dann auf true

**Comment by uwe72** [comment]
Habe gerade wieder den Fall, dass für ein Device in ioBroker unreach=true dargestellt wird:
![image](https://user-images.githubusercontent.com/61848539/159668804-976b3aea-7374-4c5f-b34d-a156f9927012.png)

In der CCU3 lässt sich das Device aber ordnungsgemäß schalten:
![image](https://user-images.githubusercontent.com/61848539/159668921-57e3c6f4-3d08-4a82-808a-76e2ec0f8058.png)

![image](https://user-images.githubusercontent.com/61848539/159668971-fdb65df4-c50a-4cd0-882c-cdb0413c53e3.png)

**Comment by Baenker** [comment]
Unreach ist der falsche Datenpunkt. Guck mal UNREACH_ALRAM und der steht lt. Deinen Screenshot richtig und somit wie auf der CCU...

**Comment by uwe72** [comment]
Hört sich gut an. Kannst Du mir noch bei UNREACH_ALARM sagen was ACKNOWLEDGED meint?

**Comment by Baenker** [comment]
if(status == 0){
                status_text = 'keine Störung';
            }
            else if(status == 1){
                status_text = 'Störung';    
            }
            else if(status == 2){
                status_text = 'bestätigte Störung';    
            }    
    }

Wobei in dem Fall Störung durch Kommunikationsstörung ersetzen…

**Comment by Baenker** [comment]
zu dem anderen Problem kann ich übrigens auch noch etwas sagen. Bei Schaltern muss man ein dummy Programm auf der ccu schreiben damit ioBroker den Tastendruck richtig mitbekommt. Ich habe dafür eine Variable auf der ccu anglegt die ich bei jeden Tagendruck immer auf true setze. Das reicht und schon funktioniert der Schalter auch.
