### ISSUE TITLE
Custom Commands funktionieren teilweise nicht, oder ich mache es nicht richtig

### ISSUE THREAD

**Issue by Baxxy13** [ioBroker/ioBroker.hm-rpc#512]
**Describe the bug**
Zu Testzwecken wollte ich mal die Custom commands ausprobieren, speziell `setValue` und `putParamset`. Aktuell bekomme ich aber nur Fehlermeldungen sobald eine ID involviert ist. `listDevices` funktioniert hingegen problemlos.

**To Reproduce**
1. im Javascript-Adapter ein Script (mit einem der Custom commands Beispiele) anlegen und die ID entsprechend anpassen
2. das Script laufen lassen
3. im Log die Fehlermeldungen sehen

**Expected behavior**
Korrekte Ausführung des Scriptes mit entsprechender Reaktion beim angesprochenem IP-Gerät

**Screenshots & Logfiles**
Testscript:
```
sendTo('hm-rpc.1', 'setValue', {ID: '000E9A498E8514.1', paramType: 'SET_POINT_TEMPERATURE', params: 15}, res => {
    log(JSON.stringify(res));
});

//hm-rpc.1.000E9A498E8514.1.SET_POINT_TEMPERATURE
```
Fehlermeldung Script:
```
21.3.2022, 17:07:32.689	[info ]: javascript.0 (6644) Stop script script.js.Skript_1
21.3.2022, 17:07:37.756	[info ]: javascript.0 (6644) Start javascript script.js.Skript_1
21.3.2022, 17:07:37.763	[info ]: javascript.0 (6644) script.js.Skript_1: registered 0 subscriptions and 0 schedules
21.3.2022, 17:07:37.786	[info ]: javascript.0 (6644) script.js.Skript_1: {"error":{"code":-2,"faultCode":-2,"faultString":"Invalid device"}}
```
Fehlermeldung rpc.1 - Adapter:
`hm-rpc.1 | 2022-03-21 17:07:37.780 | error | Cannot call setValue: XML-RPC fault: Invalid device`

Screenshot Javascript:
![iob_javascript_custom_command_not_working](https://user-images.githubusercontent.com/54898249/159304423-a0ef9473-fddf-4885-806c-7c6e1f9702e6.JPG)
Screenshot Objektbaum:
![iob_sthd_Objektbaum](https://user-images.githubusercontent.com/54898249/159304505-3afd0af3-dd04-4f80-97fb-4443d2cbce67.JPG)
Screenshot Objektansicht:
![iob_sthd_Objektansicht](https://user-images.githubusercontent.com/54898249/159304573-3be96705-1e68-4dba-bd17-ec8cb3555479.JPG)

**Versions:**
 - hm-rpc version: 1.15.11
 - hm-rega version: 3.0.35
 - JS-Controller version: 5.2.21
 - Node version: <node-version>
 - Operating system: Debian Bullseye als VM in VirtualBox
 - CCU model: RaspberryMatic als VM in Virtualbox
 - CCU firmware: 3.61.7.20220226

**Additional context**
Da ich nicht so firm beim ioBroker und in Javascript bin gehe ich jetzt erstmal von aus das ich das irgendwie falsch mache. 
Vielleicht kann jemand mal die korrekte Handhabung aufzeigen.
Andernfalls ist es möglicherweise tatsächlich ein Fehler.

**Comment by foxriver76** [comment]
Marty wieso reißt du nicht in die Zukunft zu dem Zeitpunkt an dem ich die Frage schon beantwortet habe.

> * JS-Controller version: 5.2.21

Marty wieso reißt du nicht in die Zukunft zu dem Zeitpunkt an dem ich die Frage schon beantwortet habe. Achso, ohne die Frage gibt es diese Parallelwelt nicht. Paradox.

Homematric trennt ids von channels mittels Doppelpunkt und nicht Punkt. Bitte für Fragen Forum nutzen, das schont Entwickler-Ressourcen. Danke
