### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by hugooberstein** [ioBroker/ioBroker.hm-rpc#513]
Hallo ,
ich kann seit ein paar Tagen den Adapter nicht mehr upgraden:

                                                                                This upgrade of "hm-rpc" will introduce the following changes:                  ==========================================================================      -> 1.15.11:                                                                     fallback to old adapter port determination logic (closes #509)                                                                                                  -> 1.15.10:                                                                     we use our own set of forbidden chars again                                     ==========================================================================                                                                                      Would you like to upgrade hm-rpc from @1.15.9 to @1.15.11 now? [(y)es, (n)o]: y Update hm-rpc from @1.15.9 to @1.15.11                                          NPM version: 8.5.5                                                              Installing iobroker.hm-rpc@1.15.11... (System call)                             host.raspberrypi Cannot install iobroker.hm-rpc@1.15.11: 217

Reboot, apt Update und upgrade haben nicht geholfen, auch nich iob fix.

Was kann ich noch tun?

Wo kann ich mehr über den Fehler:
host.raspberrypi Cannot install iobroker.hm-rpc@1.15.11: 217
Finden?

Vielen Dank

Hugo

**Comment by foxriver76** [comment]
npm meckert da bei dir. Um den Fehler sichtbar zu machen `iob upgrade hm-rpc --debug`

**Comment by hugooberstein** [comment]
Vielen Dank, nun habe ich mehr Informationen. Vielleicht hast du noch ne Lösung bitte für mich?

npm ERR! code ENOTEMPTY                                                         npm ERR! syscall rename                                                         npm ERR! path /opt/iobroker/node_modules/abbrev                                 npm ERR! dest /opt/iobroker/node_modules/.abbrev-5eNud0FY                       npm ERR! errno -39                                                              npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/abbrev' -> '/opt/iobroker/node_modules/.abbrev-5eNud0FY'                                                                                                            npm ERR! A complete log of this run can be found in:                            npm ERR!     /home/iobroker/.npm/_logs/2022-03-21T19_53_55_612Z-debug-0.log     host.raspberrypi Cannot install iobroker.hm-rpc@1.15.11: 217

**Comment by foxriver76** [comment]
Schau mal ob der Folder `/opt/iobroker/node_modules/.abbrev-5eNud0FY'` existiert und falls ja den löschen.
