### ISSUE TITLE
Ping Request verursacht Warnmeldung in cuxd

### ISSUE THREAD

**Issue by libertyx82** [ioBroker/ioBroker.hm-rpc#52]
Hallo,

seit der V 1.12 des cuxd erzeugt der Verbindungs-Check eine Warnmeldung

`unknown request method 'ping' 'ping'`

Diese Warnmeldung wird erzeugt, da es sich bei Ping um keine gültige RPC Methode handelt.
siehe [https://homematic-forum.de/forum/viewtopic.php?f=37&t=40823#p405129](https://homematic-forum.de/forum/viewtopic.php?f=37&t=40823#p405129)

**Comment by Matten-Matten** [comment]
MIT ADAPTER VERSION 1.6.1  - GEFIXT!

Vielen Dank.

**Comment by Apollon77** [comment]
Very interesting because noone changed anything!!

**Comment by Apollon77** [comment]
Could you please be so kind and test 1.6.0 and 1.5.1 (should be available via Admin) where it stopped sending Pings in the error log?

**Comment by libertyx82** [comment]
The Ping for CUxD is disabled with V1.6.1(not 1.6.0) see [Changelog](https://github.com/ioBroker/ioBroker.hm-rpc#161-2018-03-15)

**Comment by BuZZy1337** [comment]
@Apollon77 https://github.com/ioBroker/ioBroker.hm-rpc/commit/16cf02c79c6e57ddf7d2b7790149d0a4ba916115#diff-0854083bf65ba3726a2fc46ef4049de3R1406 here it was changed.. Only start pinging if daemon !== CUxD

@libertyx82 you can install the newest Github Version of hm-rpc over the ioBroker webinterface.

**Comment by Apollon77** [comment]
Grrr ... checked all commits but overseen that one :-(

**Comment by libertyx82** [comment]
2 Kommentare vorher findest du die Antwort, du musst die Version manuell installieren oder warten bis sie im Rep ist.

> @libertyx82 you can install the newest Github Version of hm-rpc directly over the ioBroker webinterface.

Die Warnmeldung taucht mit der V1.6.1 auch nicht mehr auf.
