### ISSUE TITLE
HmIP-MOD-TM Datenpunkt ändert nicht

### ISSUE THREAD

**Issue by bloop16** [ioBroker/ioBroker.hm-rpc#527]
Guten Tag,

Der Datenpunkt Door_Command ändert sich seit einem der letzten Adapter Updates nicht mehr.
Gerät: HmIP-MOD-TM

![image](https://user-images.githubusercontent.com/84281085/162810607-4d0c4a6a-a7e4-4deb-a12f-15acdc540ecf.png)

**Versions:**
 - hm-rpc version: 1.15.11
 - hm-rega version: 3.0.39
 - JS-Controller version: 4.0.21
 - Node version: v14.19.0
 - Operating system: Raspbian
 - CCU model: <raspberrymatic>
 - CCU firmware: 3.63.8.20220330

**Comment by foxriver76** [comment]
Everything correctly configured on adapter side, there is no logic to exclude single datapoints, thus either adapter receives no updates and there is an problem or if single dps are not updated, ccu is not sending them anymore for whatever reasons.
