### ISSUE TITLE
Probleme mit SET_TEMPERATURE bei Heizungssteuerungsgruppen

### ISSUE THREAD

**Issue by Draexl** [ioBroker/ioBroker.hm-rpc#539]
Bei Heizungssteuerungsgruppen kommt im Log folgende Meldung: 

`State value to set for "hm-rpc.1.INT0000012.1.SET_TEMPERATURE" has value "4.5" less than min "5.0"`

Die 4,5 kommen ja davon das die Thermostate auf OFF gestellt werden können. Im Hintergrund ist da ja 4,5°.

Kann das angepasst werden?

**Comment by PalmManiac** [comment]
Das kommt bei mir seit heute auch. Ich hab mir nen Wolf gesucht, wo plötzlich die 5Grad min herkommen sollen, da ja 4,5Grad = OFF die Minimaltemp darstellt, hab aber nichts gefunden. Schön, dass es nicht nur bei mir so ist.

**Comment by ds-1982** [comment]
Selbe Meldung bei mir im Log, seit ich die Thermostate auf OFF gestellt habe.

**Comment by foxriver76** [comment]
Witzigerweise haben HMIP Heizgruppen den korrekten Minimalwert von 4.5 von eq-3 bekommen. Nur Bidcos Gruppen haben inkorrekterweise 4.5
