### ISSUE TITLE
Send this to developer....

### ISSUE THREAD

**Issue by simpixo** [ioBroker/ioBroker.hm-rpc#54]
hm-rpc.0	2018-01-03 13:13:03.784	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0	2018-01-03 13:13:03.784	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2-Team.SMOKE_DETECTOR_TEAM_V2.3"
hm-rpc.0	2018-01-03 13:13:03.709	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:13:03.709	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_FREQUENCY.16"
hm-rpc.0	2018-01-03 13:13:03.701	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:13:03.701	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_VOLTAGE.16"
hm-rpc.0	2018-01-03 13:13:03.694	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:13:03.694	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_CURRENT.16"
hm-rpc.0	2018-01-03 13:13:03.686	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:13:03.685	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.CONDITION_POWER.16"
hm-rpc.0	2018-01-03 13:13:03.672	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BOOT":{"CONTROL":"POWERMETER.BOOT","DEFAULT":false,"FLAGS":3,"ID":"BOOT","MA
hm-rpc.0	2018-01-03 13:13:03.672	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.POWERMETER.16"
hm-rpc.0	2018-01-03 13:13:03.636	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0	2018-01-03 13:13:03.635	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.SWITCH.16"
hm-rpc.0	2018-01-03 13:13:03.611	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:03.611	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl-DN-R1.MAINTENANCE.16"
hm-rpc.0	2018-01-03 13:13:03.309	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR_ALARM_TEST":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR_ALARM_
hm-rpc.0	2018-01-03 13:13:03.309	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2.SMOKE_DETECTOR.5"
hm-rpc.0	2018-01-03 13:13:03.285	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:03.285	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SD-2.MAINTENANCE.5"
hm-rpc.0	2018-01-03 13:13:02.914	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0	2018-01-03 13:13:02.914	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-4-3.KEY.7"
hm-rpc.0	2018-01-03 13:13:02.891	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:02.890	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-4-3.MAINTENANCE.7"
hm-rpc.0	2018-01-03 13:13:02.577	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0	2018-01-03 13:13:02.576	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1PBU-FM.SWITCH.9"
hm-rpc.0	2018-01-03 13:13:02.556	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:02.556	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1PBU-FM.MAINTENANCE.9"
hm-rpc.0	2018-01-03 13:13:02.233	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE","MAX":255,"MIN"
hm-rpc.0	2018-01-03 13:13:02.233	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.SWITCH_TRANSMIT.22"
hm-rpc.0	2018-01-03 13:13:02.192	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ACTUAL_HUMIDITY":{"CONTROL":"THERMAL_CONTROL.HUMIDITY","DEFAULT":0,"FLAGS":1
hm-rpc.0	2018-01-03 13:13:02.192	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.THERMALCONTROL_TRANSMIT.22"
hm-rpc.0	2018-01-03 13:13:01.852	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"HUMIDITY":{"AutoconfRoles":"WEATHER","CONTROL":"NONE","DEFAULT":0,"FLAGS":1,
hm-rpc.0	2018-01-03 13:13:01.852	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.WEATHER_TRANSMIT.22"
hm-rpc.0	2018-01-03 13:13:01.815	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:01.814	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-TC-IT-WM-W-EU.MAINTENANCE.22"
hm-rpc.0	2018-01-03 13:13:01.448	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0	2018-01-03 13:13:01.448	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.VIRTUAL_DIMMER.13"
hm-rpc.0	2018-01-03 13:13:01.105	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0	2018-01-03 13:13:01.104	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.DIMMER.13"
hm-rpc.0	2018-01-03 13:13:00.769	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:00.767	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Dim1TPBU-FM.MAINTENANCE.13"
hm-rpc.0	2018-01-03 13:13:00.391	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0	2018-01-03 13:13:00.391	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.SWITCH.26"
hm-rpc.0	2018-01-03 13:13:00.363	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:00.363	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Sw1-FM.MAINTENANCE.26"
hm-rpc.0	2018-01-03 13:13:00.021	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INSTALL_TEST":{"DEFAULT":false,"FLAGS":3,"ID":"INSTALL_TEST","MAX":true,"MIN
hm-rpc.0	2018-01-03 13:13:00.021	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-Key4-2.KEY.4"
hm-rpc.0	2018-01-03 13:13:00.002	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:13:00.002	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-RC-Key4-2.MAINTENANCE.4"
hm-rpc.0	2018-01-03 13:12:59.663	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0	2018-01-03 13:12:59.662	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-Key.KEYMATIC.7"
hm-rpc.0	2018-01-03 13:12:59.303	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:59.302	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-Key.MAINTENANCE.7"
hm-rpc.0	2018-01-03 13:12:58.866	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0	2018-01-03 13:12:58.866	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-MOD-Re-8.SWITCH.6"
hm-rpc.0	2018-01-03 13:12:58.832	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:58.832	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-MOD-Re-8.MAINTENANCE.6"
hm-rpc.0	2018-01-03 13:12:58.400	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"LOWBAT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"LOWBAT","MAX":true
hm-rpc.0	2018-01-03 13:12:58.400	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS30-OT2-SM.WEATHER.5"
hm-rpc.0	2018-01-03 13:12:58.380	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,
hm-rpc.0	2018-01-03 13:12:58.380	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS30-OT2-SM.MAINTENANCE.5"
hm-rpc.0	2018-01-03 13:12:58.122	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR","MAX":7,"MIN":0,
hm-rpc.0	2018-01-03 13:12:58.121	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SCo.SHUTTER_CONTACT.3"
hm-rpc.0	2018-01-03 13:12:58.095	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:58.094	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-SCo.MAINTENANCE.3"
hm-rpc.0	2018-01-03 13:12:57.816	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ERROR":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":9,"ID":"ERROR","MAX":7,"MIN":0,
hm-rpc.0	2018-01-03 13:12:57.816	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-RHS.ROTARY_HANDLE_SENSOR.14"
hm-rpc.0	2018-01-03 13:12:57.681	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:57.681	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-Sec-RHS.MAINTENANCE.14"
hm-rpc.0	2018-01-03 13:12:56.629	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"ACTUAL_TEMPERATURE":{"CONTROL":"HEATING_CONTROL.TEMPERATURE","DEFAULT":0,"FL
hm-rpc.0	2018-01-03 13:12:56.628	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-CC-RT-DN.CLIMATECONTROL_RT_TRANSCEIVER.29"
hm-rpc.0	2018-01-03 13:12:56.251	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:56.251	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-CC-RT-DN.MAINTENANCE.29"
hm-rpc.0	2018-01-03 13:12:56.030	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"HUMIDITY":{"AutoconfRoles":"WEATHER","DEFAULT":0,"FLAGS":1,"ID":"HUMIDITY","
hm-rpc.0	2018-01-03 13:12:56.030	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS10-TH-O.WEATHER.5"
hm-rpc.0	2018-01-03 13:12:55.999	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"CONFIG_PENDING":{"DEFAULT":false,"FLAGS":9,"ID":"CONFIG_PENDING","MAX":true,
hm-rpc.0	2018-01-03 13:12:55.998	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-WDS10-TH-O.MAINTENANCE.5"
hm-rpc.0	2018-01-03 13:12:55.957	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:12:55.957	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_FREQUENCY.16"
hm-rpc.0	2018-01-03 13:12:55.950	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:12:55.949	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_VOLTAGE.16"
hm-rpc.0	2018-01-03 13:12:55.924	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:12:55.924	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_CURRENT.16"
hm-rpc.0	2018-01-03 13:12:55.912	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DECISION_VALUE":{"CONTROL":"NONE","DEFAULT":0,"FLAGS":1,"ID":"DECISION_VALUE
hm-rpc.0	2018-01-03 13:12:55.912	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.CONDITION_POWER.16"
hm-rpc.0	2018-01-03 13:12:55.894	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"BOOT":{"CONTROL":"POWERMETER.BOOT","DEFAULT":false,"FLAGS":3,"ID":"BOOT","MA
hm-rpc.0	2018-01-03 13:12:55.893	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.POWERMETER.16"
hm-rpc.0	2018-01-03 13:12:55.861	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"INHIBIT":{"CONTROL":"NONE","DEFAULT":false,"FLAGS":1,"ID":"INHIBIT","MAX":tr
hm-rpc.0	2018-01-03 13:12:55.861	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-PMSw1-Pl.SWITCH.16"
hm-rpc.0	2018-01-03 13:12:55.833	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:55.575	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"DIRECTION":{"DEFAULT":0,"FLAGS":3,"ID":"DIRECTION","MAX":3,"MIN":0,"OPERATIO
hm-rpc.0	2018-01-03 13:12:55.545	warn	Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"AES_KEY":{"DEFAULT":0,"FLAGS":0,"ID":"AES_KEY","MAX":127,"MIN":0,"OPERATIONS
hm-rpc.0	2018-01-03 13:12:55.544	warn	Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-LC-Bl1PBU-FM.MAINTENANCE.8"

**Comment by GermanBluefox** [comment]
This is not full information. Please read the info next time directly from log file.
