### ISSUE TITLE
Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-TX-WM.POWERMETER_IGL.1"

### ISSUE THREAD

**Issue by cschellhas** [ioBroker/ioBroker.hm-rpc#56]
Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-ES-TX-WM.POWERMETER_IGL.1"
--
 Send this info to developer: {'type':'meta','meta':{'adapter':'hm-rpc','type':'paramsetDescription'},'common':{},'native':{'BOOT':{'CONTROL':'POWERMETER_IGL.BOOT','DEFAULT':false,'FLAGS':3,'ID':'BOOT','MAX':true,'MIN':false,'OPERATIONS':5,'TAB_ORDER':4,'TYPE':'BOOL','UNIT':''},'ENERGY_COUNTER':{'CONTROL':'POWERMETER_IGL.ENERGY_COUNTER','DEFAULT':0,'FLAGS':1,'ID':'ENERGY_COUNTER','MAX':838860.699219,'MIN':0,'OPERATIONS':5,'TAB_ORDER':2,'TYPE':'FLOAT','UNIT':'Wh'},'GAS_ENERGY_COUNTER':{'CONTROL':'POWERMETER_IGL.GAS_ENERGY_COUNTER','DEFAULT':0,'FLAGS':1,'ID':'GAS_ENERGY_COUNTER','MAX':2147483.644531,'MIN':0,'OPERATIONS':5,'TAB_ORDER':0,'TYPE':'FLOAT','UNIT':'m3'},'GAS_POWER':{'CONTROL':'POWERMETER_IGL.GAS_POWER','DEFAULT':0,'FLAGS':1,'ID':'GAS_POWER','MAX':16777.214996,'MIN':0,'OPERATIONS':5,'TAB_ORDER':1,'TYPE':'FLOAT','UNIT':'m3'},'POWER':{'CONTROL':'POWERMETER_IGL.POWER','DEFAULT':0,'FLAGS':1,'ID':'POWER','MAX':167772.149902,'MIN':0,'OPERATIONS':5,'TAB_ORDER':3,'TYPE':'FLOAT','UNIT':'W'}}}

**Comment by BuZZy1337** [comment]
The "_id" line is missing.
Logfile should look like that:

Line 1:
 `2018-02-11 14:53:36.392 - warn: hm-rpc.0 Send this info to developer: _id: "hm-rpc.meta.VALUES.HM-PB-2-WM55.MAINTENANCE.8"`

Line 2: 
`2018-02-11 14:53:36.394 - warn: hm-rpc.0 Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription ..................................`

Please post Line 1 - which includes the _id.

**Comment by BuZZy1337** [comment]
Has already been added (io-package.json Line 1864) by Commit d4fff0d26d4dea70a03cf9422900edafe1e34f38.

**Comment by BuZZy1337** [comment]
@Apollon77 can you close this issue? I hate issues which are solved but remain open on github.. :smile:

**Comment by Apollon77** [comment]
Sure!!

**Comment by Apollon77** [comment]
Thank you!
