### ISSUE TITLE
HM-ES-TX-WM - no update after restarting ioBroker

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.hm-rpc#563]
**Describe the bug**
After restarting of ioBroker (in the docker-container) HM-ES-TX-WM (ELV Homematic Bausatz Zählersensor-Sendeeinheit Strom/Gas) gets no update.

**To Reproduce**
1. restart ioBroker in docker-container (or docker itself)
2. `hm-rpc.1.REQxxxxxxx.1.ENERGY_COUNTER`, `hm-rpc.1.REQxxxxxxx.1.POWER` etc. gets no update
3. if instance will be restarted manually, everything works as expected. (in my installation `hm-rpc.1`)
4. there is no error in the log

**Expected behavior**
after restarting of ioBroker in the docker-container, also HM-ES-TX-WM should get updates

**Versions:**
 - hm-rpc version: v.1.15.12
 - hm-rega version: v3.0.10
 - JS-Controller version: v4.0.23
 - Node version: v14.19.1
 - Operating system: docker (buanet v6.1.0)
 - CCU model: CCU3
 - CCU firmware: 3.63.8
 - HM-ES-TX-WM: v1.0

**Comment by foxriver76** [comment]
The initial updates of datapoints only happen on start of hm-Rega instance. Later on what is pushed to hm-rpc we have no influence on. Thus make sure hm-Rega is configured correctly. Also there is no difference between a full system restart and a manual instance restart on adapter level. And it would be strange if it only affects one device because there exists no special handling on device level. 

So if you think hm-Rega is not updating the initial values correctly let me know, else please specify the problem in more detail.

**Comment by foxriver76** [comment]
Is it about not getting an initial update on adapter start or is it about not getting any updates during runtime of the adapter?

**Comment by ice987987** [comment]
Is it about not getting an initial update on initial adapter start from docker-container. There are no updates till a manual restart happens.

**Comment by captaindork** [comment]
I am experiencing a similar issue with my hm-sec-key also in a Docker environment. Maybe it is the same Topic… After a restart/recreate of the docker, I get no updates for HomeMatic Devices (while HomeMaticIP in the separate hm-rpm instance work fine). Restarting the HomeMatic hm-rpc instance does not help, but there are two options that fixes the behavior: 1) restart of rm-rega 2) full resync of the devices via the tickbox in hm-rpc.
Maybe it is some issue in the „order“ the instances start??? I would be glad to solve this, as aside of a daily backitup, I am doing weekly backups of my full Docker environment running on Proxmox-LXC and everytime the scheduled backup ran, I need to manually restart rega… any further hint?

**Comment by foxriver76** [comment]
Initial updates are performed by hm-rega, so please ensure that all hm-rpc instances are correctly linked to the rega instance.
