### ISSUE TITLE
Datenpunkt um Heizungsventil ein- und ausschalten 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.hm-rpc#579]
Hallo,

ist es (technisch) möglich einen Datenpunkt einzubauen um HomaticIP-Thermostate ein- und aus zu schalten?

So lässt sich der Wechsel der Heizperioden noch leichter steuern. 

Ich meine folgende Schaltfläche aus der CCU3:

![Screenshot_20220523-191531_Chrome~2](https://user-images.githubusercontent.com/66136363/169878197-a8afba2e-9a6d-494f-88d4-fab22ebb5d01.jpg)

**Comment by Baenker** [comment]
Dafür bedarf es keinen extra Datenpunkt. Einfach Heizung auf manuellen Modus und 4,5 Grad stellen und schon ist sie aus. Das ist auch das (vermute ich mal) was die ccu macht wenn man das knöpfen drückt. Ich nutze einen eigenen Datenpunkt unter userdata „Heizperiode“ true oder false. Wenn dort der Wert geändert wird schalte ich alle Heizungen in den manuellen Modus und auf 4.5 Grad. Bei true überprüfe ich noch was für ein Tag ist damit er dann auch gleichzeitig das richtig Heizprofil auswählt
