### ISSUE TITLE
hm-rpc.1	2018-02-23 16:27:47.854 warn No image for "HmIP-SAM" found

### ISSUE THREAD

**Issue by mrieglhofer** [ioBroker/ioBroker.hm-rpc#58]
Ist auch in /opt/iobroker/node_modules/iobroker.hm-rpc/lib/images.js nicht enthalten.

**Comment by GermanBluefox** [comment]
Can you provide image?

23 февр. 2018 г. 16:29 пользователь "mrieglhofer" <notifications@github.com>
написал:

**Comment by BuZZy1337** [comment]
See line 261 in images.js - the HmIP-SAM is existing.

`
'HmIP-SAM':               '149_hmip-sam_thumb.png',
`

and

`
ioBroker.hm-rpc/admin/icons/149_hmip-sam_thumb.png
`

is existing too..?!
Which version of hm-rpc Adapter are you using in ioBroker?

**Comment by GermanBluefox** [comment]
Please reopen if still actual.
