### ISSUE TITLE
HmIP-WKP - warn-Message in LOG-file

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.hm-rpc#584]
HMIP-Keypad HmIP-WKP

hm-rega is: v3.0.40
hm-rpc is: v1.15.12

When starting the adapter, the following warning message is written to the ioBroker log:

> State value to set for "hm-rpc.2.xxxSerialNumberxxx.0.CODE_ID" has value "32" greater than max "8

**Comment by Berchemer** [comment]
Is there any way to solve this problem?

**Comment by foxriver76** [comment]
Can you please show the raw object.

**Comment by Berchemer** [comment]
Which Raw-Objekt?
I would like to add the Object-Structure from the object-view if you meat that. If that is wrong or not enough, please explain what you need more  :-)
But as I don't know which part of the objects-file could problematic for security reasons I would like to ask you to send me a mail adress of yours where I can directly send the file to ;-)

**Comment by foxriver76** [comment]
Go in the objects view in admin and behind `hm-rpc.2.xxxSerialNumberxxx.0.CODE_ID`there is a pen, click on the pen, then it should display a json file with the heading object data, in previous admin versions it was named `raw` AFAIR.

**Comment by Flauschi83** [comment]
I will just provide as the other guy is lost in the internet ;)

`{
  "type": "state",
  "common": {
    "name": "Keypad Haustuer:0.CODE_ID",
    "role": "",
    "def": 1,
    "type": "number",
    "read": true,
    "write": false,
    "min": 1,
    "max": 8
  },
  "native": {
    "MIN": 1,
    "OPERATIONS": 5,
    "MAX": 8,
    "FLAGS": 1,
    "ID": "CODE_ID",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "MAINTENANCE.CODE_ID"
  },
  "from": "system.adapter.hm-rega.1",
  "user": "system.user.admin",
  "ts": 1659901473860,
  "_id": "hm-rpc.3.002E9F2990B587.0.CODE_ID",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Berchemer** [comment]
A second Raw-Object:
The one you wanted (and after that the json of the complete object):

`{
  "type": "state",
  "common": {
    "name": "0OG - Veranda - Keypad 01:0.CODE_ID",
    "role": "",
    "def": 1,
    "type": "number",
    "read": true,
    "write": false,
    "min": 1,
    "max": 8
  },
  "native": {
    "MIN": 1,
    "OPERATIONS": 5,
    "MAX": 8,
    "FLAGS": 1,
    "ID": "CODE_ID",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "MAINTENANCE.CODE_ID"
  },
  "_id": "hm-rpc.2.xxxSerialNumberxxx.0.CODE_ID",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1664782868058
}`

Here the complete json-code of the device:

`{
  "_id": "hm-rpc.2.xxxSerialNumberxxx",
  "type": "device",
  "common": {
    "name": "0OG - Treppenhaus - Schloss - Hauseingangstuer",
    "icon": "/icons/HmIP-DLD.png"
  },
  "native": {
    "TYPE": "HmIP-DLD",
    "SUBTYPE": "DLD",
    "ADDRESS": "xxxSerialNumberxxx",
    "RF_ADDRESS": 6526231,
    "CHILDREN": [
      "xxxSerialNumberxxx:0",
      "xxxSerialNumberxxx:1",
      "xxxSerialNumberxxx:2",
      "xxxSerialNumberxxx:3",
      "xxxSerialNumberxxx:4",
      "xxxSerialNumberxxx:5",
      "xxxSerialNumberxxx:6",
      "xxxSerialNumberxxx:7",
      "xxxSerialNumberxxx:8",
      "xxxSerialNumberxxx:9",
      "xxxSerialNumberxxx:10"
    ],
    "PARENT": "",
    "PARENT_TYPE": "",
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "FIRMWARE": "1.4.10",
    "AVAILABLE_FIRMWARE": "1.4.10",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
    "VERSION": 2,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "DIRECTION": 0,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 3
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1647007658886,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by mbhomie007** [comment]
Warnings in LOG still present.
hm-rpc v1.15.16

`State value to set for "hm-rpc.2.00XXXXXXXXXXXXX5.0.CODE_ID" has value "32" greater than max "8"`

Can we fix this topic?

**Comment by mbhomie007** [comment]
`{
  "type": "state",
  "common": {
    "name": "Keypad:0.CODE_ID",
    "role": "",
    "def": 1,
    "type": "number",
    "read": true,
    "write": false,
    "min": 1,
    "max": 8
  },
  "native": {
    "MIN": 1,
    "OPERATIONS": 5,
    "MAX": 8,
    "FLAGS": 1,
    "ID": "CODE_ID",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "MAINTENANCE.CODE_ID"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1674057425707,
  "_id": "hm-rpc.2.SERIALXXXXX.CODE_ID",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by mbhomie007** [comment]
Hallo @foxriver76

Kann der Fehler im Log irgendwie gefixt werden?

Der Log ist zugespamt mit:
 "State value to set for "hm-rpc.2.00XXXXXXXXXXXXX5.0.CODE_ID" has value "32" greater than max "8""

Benötigst du weitere Infos? 
Vielleicht kann ich behilflich sein?

**Comment by mbhomie007** [comment]
@foxriver76 

I have installed the new version 1.15.18.

But the warn messages are still present.


![Screenshot 2023-05-10 142122](https://github.com/ioBroker/ioBroker.hm-rpc/assets/64688879/b869898a-5f84-4a11-9139-00dc959067ea)

{
  "type": "state",
  "common": {
    "name": "Keypad Garage vorne:0.CODE_ID",
    "role": "",
    "def": 1,
    "type": "number",
    "read": true,
    "write": false,
    "min": 1,
    "max": 8
  },
  "native": {
    "MIN": 1,
    "OPERATIONS": 5,
    "MAX": 8,
    "FLAGS": 1,
    "ID": "CODE_ID",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "MAINTENANCE.CODE_ID"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1682768412187,
  "_id": "hm-rpc.2.00XXXXXXXXXXXXXXXXX5.0.CODE_ID",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
you have to perform a force reinit (checkbox in adapter config) run to fix the paramsets

**Comment by mbhomie007** [comment]
Thank you for your fast response.

I thought, it will be automatically done with a adapter update/restart.

It works 🥇
