### ISSUE TITLE
No image for "HmIP-WKP" found.

### ISSUE THREAD

**Issue by Flauschi83** [ioBroker/ioBroker.hm-rpc#586]
Hey Hey, the new keypad wants to get a proper image ;)

No image for "HmIP-WKP" found.

**Comment by gehtnixx** [comment]
Same here

**Comment by foxriver76** [comment]
I can only add it if someone provides the image.

**Comment by foxriver76** [comment]
Just take it from CCU "devices", like shown here

<img width="737" alt="Bildschirmfoto 2022-06-15 um 13 46 20" src="https://user-images.githubusercontent.com/25484431/173819856-dc20d33f-0e58-461e-8641-dfb49ef2e84e.png">

**Comment by gehtnixx** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/104681809/173821744-0fabe676-4683-45d0-889b-15f2bce21541.png">

**Comment by gehtnixx** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/104681809/173821873-81ee65c0-c831-4e49-8802-905c3534542e.png">

**Comment by foxriver76** [comment]
You should be able to right click and download only the image.

**Comment by gehtnixx** [comment]
![94A54AB7-BC27-4B25-9D78-F50C97D1C272](https://user-images.githubusercontent.com/104681809/173875574-f3191414-69ad-48ef-835a-810cdf78ca11.png)
