### ISSUE TITLE
HmIP-DLD field type number does not accept numbers

### ISSUE THREAD

**Issue by olli-70** [ioBroker/ioBroker.hm-rpc#599]
when trying to set status of field hm-rpc.2.XXXXXXXXXXXX.1.LOCK_TARGET_LEVEL with javascript setState adapter only states are accepted "LOCKED", "UNLOCKED" or "OPEN" but this causes warning due the field is type number. Quering the field with getState returns a number

**Comment by foxriver76** [comment]
Try to use the corresponding numbers which can be found e.g. in the raw object.
