### ISSUE TITLE
Include master area within adapter

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.hm-rpc#60]
Is there any reason why the master area datapoints of homematic components are not included within the adapter? - only value area....
It would be very useful to have read / write access to the master area of homematic adapters.
E.g. set switch time parameters or change valve parameters (valve offset, valve maximum position etc)

**Comment by Apollon77** [comment]
I consider this kind of a duplicate to #34 .

Master paremeter are not pushed as updated from homematic and always needs to be requested at the device. Because of this that data are currently not automatically available.
See #34 for the plan (as soon as I find time for it).
