### ISSUE TITLE
RPC - HMIP-FWI: Fehler "warn State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20""

### ISSUE THREAD

**Issue by Ondastm** [ioBroker/ioBroker.hm-rpc#617]
**Describe the bug**
The RPC adapter returns periodic error messages from HMIP-FWI, which are as follows. There was no user input at the time
```
2022-07-01 06:26:23.990 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 07:42:24.911 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 05:30:41.622 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 03:43:41.546 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 01:57:10.515 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20
```

**To Reproduce**
Install as below.
iobroker on ccu2 with HMIP-FWI, 
no user input necessary,
repeated occurrence of the above error message

**Expected behavior**
no error message, clean processing of the value 31

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/32570464/176895752-717e1ced-b22b-469e-9088-ae0fb28d50df.png)

![image](https://user-images.githubusercontent.com/32570464/176895807-0a53c683-b801-460d-ae69-efc9b551dd99.png)

![image](https://user-images.githubusercontent.com/32570464/176895854-dedcdeaa-4403-4d83-af48-46fc6e3e8b98.png)

```
2022-07-01 06:26:23.990 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 07:42:24.911 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 05:30:41.622 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 03:43:41.546 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
2022-07-01 01:57:10.515 - warn: hm-rpc.3 (3701) State value to set for "hm-rpc.3.002BDD89B07938.0.CODE_ID" has value "31" greater than max "20"
```

**Versions:**
 - hm-rpc version: <1.15.12>
 - hm-rega version: <3.0.40>
 - JS-Controller version: <cant't find it>
 - NODE.JS: V14.19.1
 - Operating system: <Linux>
 - CCU model: <CCU2>
 - CCU firmware: <2.61.7>

**Additional context**

**Comment by nikmaier** [comment]
Just got the same problem.
The problem is that after reading a correct value, the code ID 31 is ALWAYS sent automatically after a few seconds:

![warning](https://user-images.githubusercontent.com/69574329/177723850-3bcd787a-5707-4b97-9a0f-bec5c9ea1019.JPG)

**Comment by ciddi89** [comment]
have nearly the same issue with the hm ip keypad

hm-rpc.0 | 2022-07-27 22:58:28.805 | warn | State value to set for "hm-rpc.0.002E9F2990B473.0.CODE_ID" has value "32" greater than max "8"
-- | -- | -- | --

**Comment by jk-andersen** [comment]
I am experiencing some kind of similar issues with:
Thermostat "HmIP-eTRV-C" and a corresponding heating-group.

`<html>
<body>


hm-rpc.3 | 2022-08-01 07:48:07.402 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"
-- | -- | -- | --
hm-rpc.2 | 2022-08-01 07:48:07.175 | warn | State value to set for "hm-rpc.2.000A9D898F8F44.1.ACTIVE_PROFILE" has value "8" greater than max "6"
hm-rpc.3 | 2022-08-01 07:48:04.475 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"
hm-rpc.2 | 2022-08-01 07:48:04.306 | warn | State value to set for "hm-rpc.2.000A9D898F8F44.1.ACTIVE_PROFILE" has value "8" greater than max "6"
hm-rpc.3 | 2022-08-01 07:40:49.788 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"
hm-rpc.2 | 2022-08-01 07:40:49.544 | warn | State value to set for "hm-rpc.2.000A9D898F8F44.1.ACTIVE_PROFILE" has value "8" greater than max "6"
hm-rpc.3 | 2022-08-01 07:33:47.845 | warn | State value to set for "hm-rpc.3.INT0000005.1.ACTIVE_PROFILE" has value "8" greater than max "3"
hm-rpc.3 | 2022-08-01 07:30:04.046 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"
hm-rpc.3 | 2022-08-01 07:30:03.631 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"
hm-rpc.2 | 2022-08-01 07:30:03.355 | warn | State value to set for "hm-rpc.2.000A9D898F8F44.1.ACTIVE_PROFILE" has value "8" greater than max "6"
hm-rpc.3 | 2022-08-01 07:01:56.338 | warn | State value to set for "hm-rpc.3.INT0000003.1.ACTIVE_PROFILE" has value "8" greater than max "3"


</body>
</html>`

**Comment by derzico** [comment]
I do also have the same issue.

<html>
<body>


hm-rpc.0 | 2022-10-24 06:34:04.414 | warn | State value to set for "hm-rpc.0.002E9F299924D8.0.CODE_ID" has value "32" greater than max "8"
-- | -- | -- | --
hm-rpc.0 | 2022-10-24 05:58:37.214 | warn | State value to set for "hm-rpc.0.002BDF298FF3EB.0.CODE_ID" has value "31" greater than max "20"
hm-rpc.0 | 2022-10-24 04:47:39.071 | warn | State value to set for "hm-rpc.0.002E9F299924D8.0.CODE_ID" has value "32" greater than max "8"
hm-rpc.0 | 2022-10-24 04:11:13.967 | warn | State value to set for "hm-rpc.0.002BDF298FF3EB.0.CODE_ID" has value "31" greater than max "20"
hm-rpc.0 | 2022-10-24 03:38:53.698 | warn | State value to set for "hm-rpc.0.002BDF298FF3EB.0.CODE_ID" has value "31" greater than max "20"


</body>
</html>

**Comment by foxriver76** [comment]
@Ondastm can you provide the ioBroker object of `hm-rpc.3.002BDD89B07938.0.CODE_ID`

**Comment by nikmaier** [comment]
@foxriver76 
Hallo, ich kann es auch bereitstellen, was genau brauchst du für Infos vom Objekt:

![image](https://user-images.githubusercontent.com/69574329/236430279-f0797a2e-6a7e-40c1-9abd-f0559b75e8d8.png)

`{
  "type": "state",
  "common": {
    "name": "Haustuer_Wiegand_0.CODE_ID",
    "role": "",
    "def": 1,
    "type": "number",
    "read": true,
    "write": true,
    "min": 1,
    "max": 40,
    "custom": {
      "history.0": {
        "enabled": true,
        "aliasId": "",
        "changesOnly": true,
        "debounce": "1000",
        "changesRelogInterval": "0",
        "changesMinDelta": "0",
        "maxLength": "960",
        "retention": "0"
      }
    }
  },
  "native": {
    "MIN": 1,
    "OPERATIONS": 7,
    "MAX": 20,
    "FLAGS": 1,
    "ID": "CODE_ID",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "MAINTENANCE.CODE_ID"
  },
  "_id": "hm-rpc.1.002BDF298BB504.0.CODE_ID",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1657181204416
}`
