### ISSUE TITLE
automatically update device icons via script

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.hm-rpc#659]
hallo

hab dir mal die aktuellen devices icons angehängt.
gibt es eigentlich einen Grund warum das nicht automatisch in deinen adapter übernommen wird? 
[devices.zip](https://github.com/ioBroker/ioBroker.hm-rpc/files/9411290/devices.zip)

**Comment by Apollon77** [comment]
Wie sollte das denn automatisch übernommen werden? ;-) Gibts das irgendwo als offizielle Quelle? ;-)

**Comment by foxriver76** [comment]
I can implement to grep the icons from the source.
