### ISSUE TITLE
 HM-PB-4-WM Tastendruck auf .INSTALL_TEST statt .PRESS_SHORT

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.hm-rpc#66]
Version 1.6.1

Ein Tastendruck beim Taster HM-PB-4-WM wird im Datenpunkt .INSTALL_TEST signalisiert, statt beim Datenpunkt .PRESS_SHORT

**Comment by Apollon77** [comment]
Please provide adapter debug log

**Comment by ruhr70** [comment]
muss ich mir mal angewöhnen :-)

Druck auf Taste 1 des Tasters:

`
hm-rpc.1 | 2018-04-02 22:33:14.015 | debug | redis pmessage io.hm-rpc.1.* io.hm-rpc.1.FEQ0052402.1.INSTALL_TEST {"val":true,"ack":true,"ts":1522701194015,"q":0,"from":"system.adapter.hm-rpc.1","lc":1522450839666}
-- | -- | -- | --
hm-rpc.1 | 2018-04-02 22:33:14.015 | debug | hm-rpc.1.FEQ0052402.1.INSTALL_TEST ==> UNIT: "" (min: false, max: true) From "true" => "true"
hm-rpc.1 | 2018-04-02 22:33:14.015 | debug | binrpc <- event ["hm-rpc.1","FEQ0052402:1","INSTALL_TEST",true]
hm-rpc.1 | 2018-04-02 22:33:14.014 | debug | bin multicall : hm-rpc.1,FEQ0052402:1,INSTALL_TEST,true

`

**Comment by Apollon77** [comment]
Aus dem Log kann ich nur herauslesen das genau das so von der CCU gesendet wurde.
