### ISSUE TITLE
keine Warnung ""Send this info to the developer" im Log File 

### ISSUE THREAD

**Issue by grogo08** [ioBroker/ioBroker.hm-rpc#67]
Hallo,

ich bastel gerade an den Homebrew Projekte rum und wollt mir auch eigene Devices mit Arduino erstellen.

Hier habe ich zu Testzwecken ein HBW-1W-T10 (https://github.com/jfische/HBW-1W-T10) erstellt, das in der CCU2 Zentrale auch angezeigt wird. Leider gibt es im IOBroker unter hm-rpc.0 keinen Eintrag zu dem Device. Die temperaturwerte sind in den Kanälen 1-10 hinterlegt.

Auch mein eigenes Device HBW-TER-MOD42 mit 4 binären Ausgängen und 2 binären Eingängen wird dort nicht angezeigt. 

Leider bekomme ich auch keinen Eintrag im Log File "send this info to developer", so dass sich hier auch kein LOG posten könnte.

Kann mir jmd weiterhefen? Habe den neusten Adapter "HomeMatic RPC" mit Version 1.6.0 geladen.

Die Komponente HBW-1W-T10 ist ein etwa so wie die Komponente HB-UNI-Sen-TEMP-DS18B20. Leider konnte mir der Issue https://github.com/ioBroker/ioBroker.hm-rpc/issues/63 nicht weiterhelfen.

![objekte](https://user-images.githubusercontent.com/38010879/38203726-792fc742-36a0-11e8-92ad-d3bd84c53c47.JPG)

**Comment by Apollon77** [comment]
Aber dein Screenshot zeigt Objekte für ein Device - nur ist da in den Channels nichts gefüllt. Ist der Screenshot das Ergebnis eines Syncs? Dann wäre das Device ja da und die Channel auch, nur die  States fehlen.

**Comment by Apollon77** [comment]
Das weisst zumindestens schonmal darauf hin das das Device gemeldet wird. Dann fehlt nur die Meta-Definition! Da das Device von Dir stammt kannst Du das ggf sogar selbst liefern?

Hier steht das für die anderen Devices drin und müste entsprechend ergänzt werden: https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/io-package.json#L282
Beispiele sollten da genug da sein :-)

**Comment by grogo08** [comment]
Ich hab mich mal an den Beispielen und dem ersten Sensor HBW-1W-T10 versucht. Einige Stellen, die mir nicht ganz klar sind habe ich mit ?? gekennzeichnet. z.B. die abschließende Zahl in der Zeile "_id": und die Einträge FLAGS, OPERATIONS und TAB_ORDER.

Kannst du mir hier helfen? Ich habe mal die XML-Installationsdatei der CCU2  (PDF) und die Struktur der Datei mit abgelegt.

Und kann ich auf die Variablen im TEMPSENSOR.MASTER zugreifen, oder muss ich diese vielleicht auch in VALUES verschieben? Im Beispiel finde ich nur die VALUES-Einträge der einzelnen Module. 

Herzlichen Dank

        {
            "_id": "hm-rpc.meta.VALUES.HBW-1W-T10.MAINTENANCE.??19",
            "type": "meta",
            "meta": {
                "adapter": "hm-rpc",
                "type": "paramsetDescription"
            },
            "common": {},
            "native": {
		"UNREACH": {
                    "DEFAULT": false,
                    ??"FLAGS": 9,
                    "ID": "UNREACH",
                    "MAX": true,
                    "MIN": false,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 0,
                    "TYPE": "BOOL",
                    "UNIT": ""
                },
                "STICKY_UNREACH": {
                    "DEFAULT": false,
                    ????"FLAGS": 25,
                    "ID": "STICKY_UNREACH",
                    "MAX": true,
                    "MIN": false,
                    ??"OPERATIONS": 7,
                    ??"TAB_ORDER": 1,
                    "TYPE": "BOOL",
                    "UNIT": ""
                },
                "CONFIG_PENDING": {
                    "DEFAULT": false,
                    ??"FLAGS": 9,
                    "ID": "CONFIG_PENDING",
                    "MAX": true,
                    "MIN": false,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 2,
                    "TYPE": "BOOL",
                    "UNIT": ""
                },
            }
        },

        {
            "_id": "hm-rpc.meta.MASTER.HBW-1W-T10.TEMPSENSOR.??19",
            "type": "meta",
            "meta": {
                "adapter": "hm-rpc",
                "type": "paramsetDescription"
            },
            "common": {},
            "native": {
		"SEND_DELTA_TEMP": {
                    "DEFAULT": 0.5,
                    ??"FLAGS": 1,
                    "ID": "SEND_DELTA_TEMP",
                    "MAX": 25,
                    "MIN": 0.1,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 0,
                    "TYPE": "FLOAT",
                    "UNIT": "°C"
                },
                "SEND_MIN_INTERVAL": {
                    "DEFAULT": 10,
                    ??"FLAGS": 25,
                    "ID": "SEND_MIN_INTERVAL",
                    "MAX": 3600,
                    "MIN": 5,
                    ??"OPERATIONS": 7,
                    ??"TAB_ORDER": 1,
                    "TYPE": "INTEGER",
                    "UNIT": "s"
                },
                "SEND_MAX_INTERVAL": {
                    "DEFAULT": 150,
                    ??"FLAGS": 9,
                    "ID": "SEND_MAX_INTERVAL",
                    "MAX": 3600,
                    "MIN": 5,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 2,
                    "TYPE": "INTEGER",
                    "UNIT": "s"
                },
                "ONEWIRE_TYPE": {
                    "DEFAULT": 150,
                    ??"FLAGS": 9,
                    "ID": "ONEWIRE_TYPE",
                    "MAX": 254,
                    "MIN": 0,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 2,
                    "TYPE": "INTEGER",
                    "UNIT": ""
                },
            }
        },

        {
            "_id": "hm-rpc.meta.VALUES.HBW-1W-T10.TEMPSENSOR.??19",
            "type": "meta",
            "meta": {
                "adapter": "hm-rpc",
                "type": "paramsetDescription"
            },
            "common": {},
            "native": {
                "hmw_analog_input_values": {
		    "CONTROL": "NONE",
		    ??"AutoconfRoles": "WEATHER",
                    "DEFAULT": -273.15,
                    ??"FLAGS": 9,
                    "ID": "SEND_MAX_INTERVAL",
                    "MAX": 327.67,
                    "MIN": -273.15,
                    ??"OPERATIONS": 5,
                    ??"TAB_ORDER": 2,
                    "TYPE": "FLOAT",
                    "UNIT": "?"
                },

            }
        },

![struktur_xml_file](https://user-images.githubusercontent.com/38010879/38290675-ad10f5f8-37dc-11e8-9bed-41ac3fa1dcbd.JPG)
[hbw_1w_t10_XML.pdf](https://github.com/ioBroker/ioBroker.hm-rpc/files/1874477/hbw_1w_t10_XML.pdf)

**Comment by Apollon77** [comment]
@BuZZy1337 kannst Du mal drauf schauen, bist da glaube ich tiefer drin als ich :-)) Danke

**Comment by BuZZy1337** [comment]
@Apollon77 Bin gerade im Urlaub, schaue mir das Freitag/Samstag mal genauer an, da bin ich wieder zuhause..  Mir ist letztens aber aufgefallen,  dass aus irgend einem Grund die io-package.json Dateien wohl "nicht richtig geladen" werden. Die States werden teilweise nicht angelegt.. Im Telegram Adapter fehlt mir zum Beispiel dieser Datenpunkt: https://github.com/ioBroker/ioBroker.telegram/commit/c0986b07857ce641b840d29c4f7cb85172950fc8

![screenshot_20180404-093425](https://user-images.githubusercontent.com/6979405/38294706-0943f5e6-37ec-11e8-8dea-e44ddca12f86.png)

Auch aus der io-package.json Datei vom hm-rpc Adapter werden bei mir nicht alle meta Datenpunkte angelegt.
@GermanBluefox wurde da irgend was geändert an dem processing von den io-package.json Dateien?

**Comment by Apollon77** [comment]
Seit js-controller 1.2.7 (https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md#127-2018-03-06) sollte das tun. Und ja, vorher wurden die io-package Instance vars nur einmalig bei der Instanzerstellung angelegt und nie aktualisiert.
Welche js-controller Version hast Du?

**Comment by BuZZy1337** [comment]
Ach shit.. 1.2.3 hab ich installiert.. Ich Depp hab den "Hosts" tab im Webinterface ausgeblendet und dementsprechend nie "realisiert" dass ein Update für den Controller verfügbar ist.. Gleich mal ein Update machen.. :smiley:
Melde mich wieder.. Sorry! Haha

**Comment by BuZZy1337** [comment]
@grogo08 hast du denn die Schritte mit dem Löschen von dem meta Ordner und dem neu synchronisieren probiert wie ich es in https://github.com/ioBroker/ioBroker.hm-rpc/issues/63 beschrieben habe?
Die log Einträge "send this info to developer" kommt gleich am anfang wenn der rpc adapter gestartet wird, du musst also eventuell ein bisschen scrollen bis du die Einträge findest.

**Comment by BuZZy1337** [comment]
Lösch einfach den kompletten hm-rpc.meta Ordner inklusive aller Unterobjekte. Dann im hm-rpc Adapter Geräte neu synchronisieren (einmalig) anklicken und speichern. Dann müsste dein log voll sein mit "send this info to developer".

**Comment by grogo08** [comment]
Habe die Einträge alle gelöscht.
![start](https://user-images.githubusercontent.com/38010879/38322750-9989e774-383b-11e8-9462-4f8e8a13f7f3.JPG)
Danach habe ich die Geräte neu synchronisiert, und ich bekomme auch Einträge von den HM-Komponenten mit "Send Info to developer"
![eintraege](https://user-images.githubusercontent.com/38010879/38322797-b6d0bf24-383b-11e8-822f-9438ae4f2399.JPG)
Aber leider sind die einzigen Einträge über meine beiden Devices diese:
![hbw_eintraege](https://user-images.githubusercontent.com/38010879/38322816-c5f75026-383b-11e8-9ffa-b9eb39917b01.JPG)
und am Ende sehen die Objekte wieder so aus und keine Einträge im hm-rpc.0:
![obejkte_ende](https://user-images.githubusercontent.com/38010879/38322866-f5c306f6-383b-11e8-9d41-ce14540c692e.JPG)

Hat leider noch nichts gebracht.

**Comment by BuZZy1337** [comment]
Stell das loglevel für die hm-rpc Instanz mal auf debug.
Dann nochmal den hm-rpc.meta Ordner löschen und nochmal die Geräte neu synchronisieren.
Wenn du überhaupt keine Meldung deines selbst erstellen Gerätes bekommst stimmt irgendwas in der Geräteconfig / XML / ParamSet von deinem Gerät auf der CCU Seite nicht.

Mich würde ein Screenshot von der Gerätestatusseite deines Gerätes auf der CCU interessieren. Läuft das Gerät denn einwandfrei auf der CCU?

Und wie gesagt, loglevel von hm-rpc auf debug, hm-rpc.meta löschen und dann nochmal neu synchronisieren.

**Comment by BuZZy1337** [comment]
Achso.. Was ich übrigens merkwürdig finde, wieso sind deine beiden selbst gemachten Geräte keinem hm-rpc Ordner untergeordnet? Wie sieht denn deine hm-rpc und hm-rega config aus?

**Comment by BuZZy1337** [comment]
@grogo08 gibt's Neuigkeiten diesbezüglich?

**Comment by grogo08** [comment]
Hi, ja, herzlichen Dank 

Mir fehlte tatsächlich die Instanz für die Wired Geräte, hab mich etwas in die Irre führen lassen, weil die Geräte schon im root angezeigt wurden.

Bin jetzt fleissig dran die Ein- und Ausgänge auf ein Adruino Mega zu erweitern und komme bestimmt nochmal auf euch zu, wenn das Modul fertig ist und ich es richtig eingebunden haben möchte, jetzt kann ich auf jeden Fall schon Ausgänge schalten und Eingänge einlesen.

Besten Dank für die schnellen Antworten, 

grogo08
