### ISSUE TITLE
Absturz beim Schaltaktor mit Leistungsmessung

### ISSUE THREAD

**Issue by Apfelcheck** [ioBroker/ioBroker.hm-rpc#68]
Beim Schaltaktor mit Leistungsmessung treten reguläre Abstürze auf, wenn man über das binäre RPC-Format angeschlossen wird. Dann wird der Adapter nicht mehr zugreifbar - siehe log. Man sieht auch die letzten Werte, die bei mir bei der kumulierten Leistungsaufnahme viele Nachkommastellen an Stelle einer bim XLM angezeigt hatten.

**Comment by Apollon77** [comment]
Dann bitte Log mit angeben :-)

**Comment by Baenker** [comment]
läuft bei mir ohne Probleme. Dabei ist es egal wie geschaltet wird. Also per vis oder per Alexa oder über den Objekte Reiter.

**Comment by GermanBluefox** [comment]
Ohne Log kann man nichts sagen. Bitte reopen, wenn log da ist.
