### ISSUE TITLE
Script "dom.GetObject(55088).State(true)" ignored, because still pending.

### ISSUE THREAD

**Issue by holofury** [ioBroker/ioBroker.hm-rpc#689]
Hallo,

von diesen Meldungen erhalte ich regelmäßig Warnungen im Log:

hm-rega.0 | 2022-09-19 15:48:28.355 | warn | Script "dom.GetObject(55088).State(true)" ignored, because still pending.

Was löst diese Meldung aus?
Bzw. wie gehe ich vor um herauszufinden, was  die Meldungen auslösen könnte?

**Comment by holofury** [comment]
Problem besteht immer noch :-(

**Comment by foxriver76** [comment]
Ist ein Problem in deinem Skript vermutlich für setzt zwei mal hinter einander den State 55088 auf den selben wert

**Comment by holofury** [comment]
Danke für die Antwort.
So bin ich zumindest mal drauf gekommen, mal bei den Objekten nach 55088 zu suchen...

Und zwar ist das ein Homematic-Script, mit dem ich das Heizungsprogramm in Abhängigkeit einer Systemvariable (Anwsenheit) steuere.
Soweit nichts außergewöhnliches, aber die Systemvariable wird tatsächlich ggf. mehrfach auf true gesetzt.
Ich ändere das Script mal ab, dass erst geprüft wird, ob der Wert schon auf true steht, bevor er erneut geschrieben wird.
Vielleicht hilft das ja schon.

**Comment by holofury** [comment]
Nach 3 Wochen "Testphase" kann ich berichten, dass die Anpassung des Scripts den gewünschten Erfolg gebracht hat.
Die Meldung taucht nun nicht mehr im Log auf.

Vielen Danke für die Hilfe!
