### ISSUE TITLE
Logging fehlerhaft

### ISSUE THREAD

**Issue by eierfeile** [ioBroker/ioBroker.hm-rpc#719]
**Describe the bug**
Aktiviert man im iobroker das Logging für einen bestimmten Datenpunkt von einem Homematic Aktor in Telegram, wird jede Aktualisierung an Telegram gesendet. 
![image](https://user-images.githubusercontent.com/55989475/196397269-717b5ca5-7e18-4ece-a34c-2fc4a6aa4428.png)

![image](https://user-images.githubusercontent.com/55989475/196397421-04b7e970-e5ce-4150-b0a8-f1e8ce95c735.png)

Bei anderen Aktoren klappt das fehlerfrei. Lt. iobroker Facebook-Gruppe liegt die Ursache vermutlich am Trigger im Homematic Adapter. Der Trigger sei vermutlich falsch angelegt und müsste change:"ne" sein.

Konnte das Fehlerbild mit verdeckten Fenster- und Fenstergriff-Sensoren reproduzieren.

Ich nutze das stable repository. iobroker läuft im docker container. nodejs v16.17.0, npm 8.15.0. Alle Adapter sind aktuell.

Danke für Deine/Eure Arbeit!

**Comment by eierfeile** [comment]
Wie soll ich den DP aufzeichnen? Du meinst im History Adapter?

**Comment by foxriver76** [comment]
Genau

**Comment by Apollon77** [comment]
duplicate [Telegram](https://github.com/iobroker-community-adapters/ioBroker.telegram/issues/324) ??

**Comment by eierfeile** [comment]
das komische ist: Ich habe das Verhalten nur bei Homematic Aktoren. Bei Shelly funktioniert das Logging...

**Comment by quotschmacher** [comment]
@eierfeile (was ein lustiger name) - ich hab das gestern erst wieder mit der aktuellen beta getestet mit einem adapter, der alle 10 minuten einen webservice abfragt und es kam bei telegram alle 10 minuten der selbe wert - dann habe ich recht schnell wieder deaktiviert.
![image](https://user-images.githubusercontent.com/50583947/196544288-655a287b-dc14-4104-a39c-33680791793a.png)

**Comment by eierfeile** [comment]
also ich habe die Werte nun per History Adapter aufgezeichnet. Was auffällt ist:
1. in Telegram werden mehr Änderungen übertragen als sie tatsächlich stattgefunden haben, **aber** auch
2. Werte auch mehrfach übertragen werden

![image](https://user-images.githubusercontent.com/55989475/196683885-cea7801f-cabc-4af1-9eb9-2728601d1a98.png)

**Comment by Apollon77** [comment]
Ja und all das ist in dem Telegram Issue von oben genau so beschrieben. Das Featrue im Telegram ist schon immert so ... was jetzt gewünscht ist ist eine Erweiterung das auch nur Wert-Änderungen gemeldet wertden. Das muss jemand einbauen. Also Telegram issue bitte ansehen und mit 2Daumen hoch" beim ersten post euer Interesse Zeigen. Keine "Me too" posts dort nötig ;)
