### ISSUE TITLE
On CCU Reboot the hm-rpc no longer gets CUxD Events

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.hm-rpc#73]
On CCU Reboot the hm-rpc no longer gets CUxD Events. Need hm-rpc restart after CCU reboot to get events (e.g. value changes) again.

I have not encountered problems with HM-RF, HM Wired or HMIP. Only CUxD.

Version 1.6.2, but Problem also exists with 1.6.1. (Maybe the problem occurs with disabeling the ping for CUxD in 1.6.1?).

**Comment by GermanBluefox** [comment]
It is because CUxD does not support pings. Please write about it to the developer of CUxD.

**Comment by Hypnos3** [comment]
Die Anfrage gab es schon von Apollon. 

Antwort von Uwe ist:
Dafür nutzt die ReGaHss die Methode system.listMethods. Das könnte ioBroker ja auch tun.

Das hätte ich auch gesagt:
CuxD ist doch nicht im luftleeren Raum. Man bekommt doch den Status sicher anders heraus. Notfalls startet der hm-rega Adapter halt die hm-rpc neu. 

Ich habe auch nicht wirklich ein Problem. Ich werde es bei mir selbst mit einem Javascript lösen, was den Adapter neu startet wenn die CCU wieder erreichbar ist. Ich hatte nur auf eine Lösung gehofft, die auch anderen hilft. Aber anhand der Reaktion und des Kommentars komme ich eher zu dem Schluss das dies scheinbar nicht gewünscht ist.

**Comment by Hypnos3** [comment]
Siehe https://homematic-forum.de/forum/viewtopic.php?t=43629

**Comment by Apollon77** [comment]
Then, we should use that method as ping replacement. Maybe also for ccu stuff so that it is a general solution again?

**Comment by Hypnos3** [comment]
Hallo,

CUxD 2.1.0 unterstützt jetzt die BINRPC Ping-Methode --> [forum](https://homematic-forum.de/forum/viewtopic.php?f=37&t=15298).
Damit kann das wieder aktiviert werden.

Gruß

**Comment by Apollon77** [comment]
please verify and close if it works!

**Comment by Hypnos3** [comment]
Ich hatte bei den letzten Neustarts von der CCU zumindest keine Probleme mehr.
