### ISSUE TITLE
Update LOWBAT and UNREACH on some devices not done

### ISSUE THREAD

**Issue by DieWaldfee** [ioBroker/ioBroker.hm-rpc#741]
Hi together,

I got a confusing error while writing a script to check the LOWBAT and UNREACH values to get a telegram message, if something is to do. 

2 window sensors and 1 "Hutschienenaktor" (dont know the englisch word - maybe DIN rail actuator) couldn´t update the LOWBAT and/or the UNREACH value. I have about 60-80 devices and with all others it works fine.
In CCU3 the values are ok and fine. LOWBAT is false while in ioBroker it is still true. etc.

- I updated at first the CCU3 to 3.65.11. No effect updating to ioBroker
- I checkt the update-state of the adapters - they are fine for now and at the other devices it works a i expect it.
- I startet to rereade the devices at startup of the instance - no effect ...LOWBAT is still true...

Solution: 
I delete the complete datapoint - after reread the devices at start of the instance: LOWBAT is false! 

Maybe it is possible to generate a "Check value at start" option to the instance like the existing option to reread the device list at startup oh the hm-rpc.0. Maybe it is possible to trigger such a "check of state and value" with a datapoint. It seems to be nessesary to trigger for these datapoints whcht are not changing maybe over years. Especially for device that dont have any battery at all (DIN rail actuator) - they will never have a change on this value (why ever it got true at LOWBAT).

with gest regards :-)

**Comment by DieWaldfee** [comment]
Hi together,

the LOWBAT is still not updates. One of my devices got bad batteries an marked with LOWBOT in Homematic CCU3, but not updated to iobroker. 
Is this a problem of CCU3 or ioBroker? Do i need som actions on CCU3 to get this work?

One possible solution is to install NodeRed on the CCU3, fetch the signal an send it via MQTT. Maybe there is a smarter solution.

rega V3.0.40
hm V1.15.12
CCU3 3.65.11

With best regards

**Comment by Baenker** [comment]
Du benutzt die falschen Datenpunkte. Du musst Dir die Datenpunkte LOWBAT_ALARM angucken. Generell immer die mit ALARM. Diese werden richtig gesetzt.

**Comment by DieWaldfee** [comment]
@Baenker: danke für deinen Tipp. Ich teste das aus, und melde mich hier im Post - habe gerade kein Gerät mit geringer Batterie :-)
...aber bei so veielen Geräten im Einsatz sollte das nicht lange dauern...
Gruß DieWaldfee

**Comment by DieWaldfee** [comment]
Hallo zusammen,
...und so, wie @Baenker es beschrieben hat funktioniert es auch einwandfrei! Danke.
![image](https://user-images.githubusercontent.com/66571311/218568299-575a3578-adef-454e-9687-93223981e57f.png)
Gruß DieWaldfee
