### ISSUE TITLE
Valve Level in data points incorrect

### ISSUE THREAD

**Issue by wendefeuer** [ioBroker/ioBroker.hm-rpc#756]
With the Homematic radiator thermostats IP (HmIP-eTRV-E-S, HmIP-eTRV-B-2 R4M) the opening levels are not correctly reproduced. Data point: 1.LEVEL the factor is too small by a factor of 100. The value is correct for the standard components.

**Comment by gidhap** [comment]
Same issue here with thermostat HmIP-eTRV-2 Firmware 2.2.8

RAW

`{
  "type": "state",
  "common": {
    "name": "LEVEL",
    "role": "level",
    "def": 0,
    "type": "number",
    "read": true,
    "write": true,
    "min": 0,
    "max": 1.01,
    "unit": "%"
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 7,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "HEATING_CONTROL_HMIP.LEVEL",
    "UNIT": "%"
  },
  "from": "system.adapter.hm-rpc.2",
  "user": "system.user.admin",
  "ts": 1670417335649,
  "_id": "hm-rpc.2.000A1D8998080B.1.LEVEL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"`

**Comment by guc206** [comment]
Same issue here with thermostat HmIP-eTRV-E-S with Firmware 1.2.0
In RaspberryMatic is the value ok: 80%
![HM-IP-eTRV-E-01](https://user-images.githubusercontent.com/100609099/216835483-69d459f7-210e-4fa9-8269-c37148eb966f.png)
But in iobroker there is 0,8%
![HM-IP-eTRV-S-02](https://user-images.githubusercontent.com/100609099/216835490-459b1250-66b7-4a07-9828-31962340bdb8.png)

**Comment by Ersthelfer** [comment]
I can confirm the error. 
The value must be multiplied by 100
Or the unity must not be "%"
