### ISSUE TITLE
State value to set for "hm-rpc.1.INT0000004.1.ACTIVE_PROFILE" has value "4" greater than max "3"

### ISSUE THREAD

**Issue by tmycgn** [ioBroker/ioBroker.hm-rpc#764]
Aktive Profile werden nur im Bereich 1-3 erlaubt. Möglich ist jedoch ein Bereich 1-6:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/82310796/206790588-ba587624-79fc-4c15-9d44-f992e9442370.png">

**Screenshots & Logfiles**
`State value to set for "hm-rpc.1.INT0000004.1.ACTIVE_PROFILE" has value "4" greater than max "3"
`

**Versions:**
 - hm-rpc version: v1.15.16
 - hm-rega version: v3.0.43
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Linux
 - CCU model: CCU3 / RaspMatic 3.65.11.20221005

**Comment by PEPITO82** [comment]
Habe wohl ein ähnliches Problem. Erhalte regelmäßig im Log diese Einträge für das HMIP-WKP (Keypad):

"State value to set for "hm-rpc.1.002E9F29992BB1.0.CODE_ID" has value "32" greater than max "8""

![image](https://user-images.githubusercontent.com/117452571/229490460-e1925172-5a43-4bc6-b991-d2128b3223b7.png)

hm-rpc version: v1.15.16
hm-rega version: v3.0.46

**Comment by foxriver76** [comment]
```
  "native": {
    "MIN": 1,
    "OPERATIONS": 7,
    "MAX": 3,
    "FLAGS": 1,
    "ID": "ACTIVE_PROFILE",
    "TYPE": "INTEGER",
    "DEFAULT": 1,
    "CONTROL": "HEATING_CONTROL_HMIP.ACTIVE_PROFILE"
  },
  ```
