### ISSUE TITLE
Within fresh installation almost no states from CCU3 are visible within iobroker

### ISSUE THREAD

**Issue by jomjol** [ioBroker/ioBroker.hm-rpc#765]
**Describe the bug**
Within a fresh install within a docker environment (buanet/iobroker:latest, only hm-rpc, hm-rega) only the alam indicators are found:

I'm aware of various posts to this problem and tried to solve this now since 2 days with all possible and impossible (unplausible) ideas / hacks. But no success so far.
An older installation (4 year old) was working without problems. Due to various reasons I reseted everything and copied the setting for homematic 1:1 (yes I have checked several times!). But now the system is not usable anymore!

**To Reproduce**
n.a.

**Expected behavior**
All states are found and can be used within iobroker

**Screenshots & Logfiles**
![grafik](https://user-images.githubusercontent.com/30766535/206901064-4d5ee61d-974c-4c5d-8f1d-710bf42844cb.png)

No error message or comparable listed:
![grafik](https://user-images.githubusercontent.com/30766535/206901098-b4949e9a-b5dd-4649-a478-b476c35bce35.png)

**Versions:**
 - hm-rpc version: 1.15.16
 - hm-rega version: 3.0.43
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: buanet/iobroker:lastest (11.12.2022)
 - CCU model: CCU3
 - CCU firmware: 3.65.11

**Additional context**
This is a real road blocker and show stopper for iobroker and homematic - and I'm really not a beginner :-)

**Comment by foxriver76** [comment]
Pretty much the cb from ccu to iob is not working so, ja the cb address correct? 192.168.178.1 I would assume a router at this ip.

**Comment by jomjol** [comment]
Yes checked - here are my detailed settings:
hm-rpc:
![grafik](https://user-images.githubusercontent.com/30766535/206902738-7e30286f-bf95-4765-bec6-162a108ba310.png)
![grafik](https://user-images.githubusercontent.com/30766535/206902746-3b086f8c-55ec-43d5-9802-422caa695d3e.png)

hm-rega:
![grafik](https://user-images.githubusercontent.com/30766535/206902768-0145acee-c109-4d0d-8508-f7a3d6f48b29.png)

**Comment by foxriver76** [comment]
So your iobroker is reachable at the host on 192.168.178.1?

If yes, then I can only imagine firewall, especially if the host is running Ubuntu or wrongly mapped ports. 

I am not familiar with the docker image, can you show the compose to check that port 2001 is mapped to 2001 or another appropriate network mode is chosen

**Comment by jomjol** [comment]
Port 2001 is to CCU3, right? Therefore I don't need to map it into the docker, do I?

**Comment by foxriver76** [comment]
![Bildschirmfoto 2022-12-11 um 13 26 02](https://user-images.githubusercontent.com/25484431/206903483-fd8069e7-727f-404f-86fa-2a136644979e.png)
27d-691e04a260df.png)

If the adapter port is set to 0 like in your scenario, the adapter tries to mimic the HM port. If it's not available it will take another one, but in nearly all cases it should be available, as it is in yours according to the log.

![Bildschirmfoto 2022-12-11 um 13 29 22](https://user-images.githubusercontent.com/25484431/206903584-f1788599-6edb-4eeb-becf-3e1b5361b451.png)

The RPC API is a push API, the adapter registers it's on server address where it listens to events. In your case  `http://192.168.178.1:2001` is registered at RPC API

![Bildschirmfoto 2022-12-11 um 13 30 23](https://user-images.githubusercontent.com/25484431/206903614-fc4834be-b980-4f67-99d2-ae1771664011.png)

**Comment by jomjol** [comment]
Well, that is strange. I do not map 2001:2001 in the docker. I didn't do this in the for years working version as well.

But now trying to map, the docker container throws a strang error, that I cannot interprate up to now ("status 500"). I checked all other docker instances, none is using 2001 - strange!

But a new hint to follow. I keep you updated.

**Comment by jomjol** [comment]
You made my day (actually 2,5 days :-) :-)):
1) Instead of the blocker 2001 port I used a free high port (12001)
2) Callback address **IS NOT** the router, but the direct docker adress!

Especially the second point is very disturbing, as it is said in the documentation, to use the router IP:

**Comment by foxriver76** [comment]
Not sure who has written this part of docs, I assume router for the container is meant. Which is pretty much is the host of the machine,  where the container runs. 

Should be optimized I totally agree.

**Comment by jomjol** [comment]
Just made a commit with some explaining words.
