### ISSUE TITLE
No connection to device or service, Init not succesfull ?

### ISSUE THREAD

**Issue by schneie74** [ioBroker/ioBroker.hm-rpc#776]
Hello,
when trying to start hm-rpc for Homematic IP I do get below DEBUG in the log and the Instance is showing yellow status as 'No connection to device or service'

hm-rpc.1 | 2022-12-20 15:50:18.759 | info | xmlrpc  client is trying to connect to 192.168.0.141:2010/ with  ["http://192.168.178.141:2011","raspberry4B:hm-rpc.1:6588166fd4ecb41a486ab19d843ad7f5"]
-- | -- | -- | --
hm-rpc.1 | 2022-12-20 15:50:18.758 | info | xmlrpc server is trying to listen on 192.168.178.141:2011
hm-rpc.1 | 2022-12-20 15:50:18.566 | info | starting. Version 1.15.12 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v16.19.0, js-controller: 4.0.23

I am running a DEBMATIC CCU3 installation on a PI4B with CCU firmware 3.65.11.97 (as the previous firmware was not able to find HmIP devices..)

The XML-API is installed, but as no original CCU3 I am not able to check the authentication settings.

Does this not work with my constellation or did I do something wrong ?

Thanks in advace

Erik

**Comment by schneie74** [comment]
I am not sure what log should be missing ? Is it correct that I try to use port 2010 but in the Initialization it uses port **2011** ["http://192.168.178.141:**2011**","raspberry4B:hm-rpc.1:6588166fd4ecb41a486ab19d843ad7f5"]  ?

**Comment by foxriver76** [comment]
Probably the callback address is wrongly configured
