### ISSUE TITLE
Only 2 Channel at HMIP-BBL

### ISSUE THREAD

**Issue by boebo** [ioBroker/ioBroker.hm-rpc#777]
In my objects only two channels are filled for the HGMIP-BBL. 
All other channels appear empty.

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/100808314/208940599-8b7e72ba-5049-4a0a-9f01-f1e49e34fe14.png)

**Versions:**
 - hm-rpc version: 1.15.12
 - hm-rega version: 3.0.40
 - JS-Controller version: 4.0.23
 - Node version: 16.18.1
 - Operating system: Linux (Proxmox LXC)
 - CCU model: raspberrymatic
 - CCU firmware: 3.65.11.20221218

**Comment by foxriver76** [comment]
Then only these channels are controllable via xml-api
