### ISSUE TITLE
EPAPER_TONE [object Object] _id is not defined

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.hm-rpc#78]
since last update I receive the following error messages if I want to change the value of the object "EPAPER_TONE" of the HM-Dis-EP-WM55

`
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:278:10)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.hm-rpc/hm-rpc.js:404:30)
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | ReferenceError: _id is not defined
hm-rpc.0 | 2018-06-23 16:05:19.750 | error | message hm-rpc.0.NEQ1463223.0.EPAPER_TONE [object Object] _id is not defined

`

**Comment by GermanBluefox** [comment]
Fixed on git

**Comment by GermanBluefox** [comment]
Is in latest tomorrow
