### ISSUE TITLE
Values ​​are not updated. Adapter green.

### ISSUE THREAD

**Issue by New-three** [ioBroker/ioBroker.hm-rpc#791]
I sometimes have the problem that the status of a Homematic button is not updated.
If I press a wired button, the time stamp is not updated. The adapter is green. The object is only updated after a restart.

Can I look somewhere to see what could be causing this?

iobroker and the rpc adapter have the latest version. IoBroker is installed on a Synology Nas in Docker.

**Comment by Apollon77** [comment]
You know that buttons are normally not reported at all? There is a trick to attach a script to the button press in CCU that "does nothing" ... then the button nstates are reported. see also https://github.com/ioBroker/ioBroker.hm-rpc#additional-information

**Comment by New-three** [comment]
Ok, but if I restart the adapter it works for a while.

I don't understand that with the dummy program.
i have to put every button on which i want to evaluate the keystroke into a program?

**Comment by Apollon77** [comment]
>  i have to put every button on which i want to evaluate the keystroke into a program?

yes
<img width="923" alt="Bildschirm­foto 2022-12-31 um 15 08 02" src="https://user-images.githubusercontent.com/11976694/210139467-7bed2163-8fd8-46e4-9fa6-755f5b801cce.png">

that way
