### ISSUE TITLE
Objekte press_short oder press_long werden nicht geändert

### ISSUE THREAD

**Issue by thomke67** [ioBroker/ioBroker.hm-rpc#808]
Hallo,

in den IObroker Objekten finde ich unter hm-rpc.1.xxxxx einige Geräte mit deren Status. Darunter sind auch Schalter.
Alles funktioniert wie beschrieben und gewünscht bis auf:
Ich hätte mir gewünscht, dass auch dort der Status press_short bzw. press_long beim Drücken kurzzeitig auf true gesetzt werden.
Dies ist aber leider nicht der Fall.
Muss ich da irgendwo etwas in irgendwelchen Einstellungen ändern? 
Ich möchte gerne von einem Schalter aus durch einen langen Tastendruck ein Script auslösen. Klappt aber nicht, weil sich der Status nicht ändert und dann habe ich keinen Trigger.
Ich hoffe, dass ich das nachvollziehbar beschrieben habe.

mfg
Thomas

Node.js: v16.19.0
NPM: 8.19.3
IObroker & Homematic aktuell
Homematic im Container auf Raspi

**Comment by foxriver76** [comment]
Dummy Programm anlegen

**Comment by Apollon77** [comment]
@thomke67 https://github.com/ioBroker/ioBroker.hm-rpc#additional-information ... da stehts auch
