### ISSUE TITLE
Homematic IP Weather Sensor HM-IP-SWO-PL

### ISSUE THREAD

**Issue by knowhowseeker** [ioBroker/ioBroker.hm-rpc#818]
Only Channel 0 is showing states. After having the adapter running for 24hours, I'm not getting any States (Values) in other Channels.
![Screenshot 2023-02-02 154845](https://user-images.githubusercontent.com/41070573/216357079-0260795b-43e1-49b4-b6eb-e99f0061d0a3.jpg)

**Comment by Apollon77** [comment]
Did you tried to refresh/resync alll datapoint infos? In Admin of the instance there is a checbox. tick and save and check after next run

**Comment by foxriver76** [comment]
looks like rega is properly configured and rpc not. In forum people can help you faster, support here is pretty limited

**Comment by knowhowseeker** [comment]
Checkbox for refresh was set, but I used https which didn't work. I changed now in the rpc adapter to no https and it seems to work. Thanks for your fast response.
