### ISSUE TITLE
HmIP-Broll falscher Level nach Nutzung der Tasten

### ISSUE THREAD

**Issue by NicoK-86** [ioBroker/ioBroker.hm-rpc#87]
Hallo,
ich habe folgendes Problem ich habe den Rolladenaktor HmIP-Broll und sobald ich die Tasten benutze wird im iobroker nur noch der Level mit 0 oder 99,5% angezeigt je nachdem ob ich öffnen oder schließen benutzt hatte, in der CCU2 steht allerdings der korrekte Wert. 
Ich habe hm-rpc Version 1.7.6 installiert.
Weiß jemand wie ich den korrekten Wert in den iobroker übertragen kann?

Danke schon mal.

**Comment by captaindork** [comment]
Duplicate of #44
