### ISSUE TITLE
Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.hm-rpc#872]
**Describe the bug**

Log:
Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
hm-rpc.1 | 2023-04-07 15:08:22.838 | info | State value to set for "hm-rpc.1.0008DD899C4B19.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 15:08:22.813 | info | State value to set for "hm-rpc.0.0008DD899C4B19.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 15:06:53.469 | info | State value to set for "hm-rpc.0.000DDD89A9783B.2.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 15:06:53.429 | info | State value to set for "hm-rpc.1.000DDD89A9783B.2.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:59:55.140 | info | State value to set for "hm-rpc.1.0008DD89B3289E.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:59:55.138 | info | State value to set for "hm-rpc.0.0008DD89B3289E.3.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:58:37.593 | info | State value to set for "hm-rpc.1.000E1D89A26526.1.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:58:37.589 | info | State value to set for "hm-rpc.0.000E1D89A26526.1.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:57:28.793 | info | State value to set for "hm-rpc.1.0008DD89A2C45A.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:57:28.792 | info | State value to set for "hm-rpc.0.0008DD89A2C45A.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:54:20.409 | info | State value to set for "hm-rpc.0.0008DD89B3289E.3.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:54:20.400 | info | State value to set for "hm-rpc.1.0008DD89B3289E.3.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:52:47.627 | info | State value to set for "hm-rpc.1.000E1D89A262A2.1.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:52:47.620 | info | State value to set for "hm-rpc.0.000E1D89A262A2.1.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:51:08.898 | info | State value to set for "hm-rpc.0.0008DD89A2BE47.3.SECTION" has to be type "number" but received type "string"
hm-rpc.1 | 2023-04-07 14:51:08.892 | info | State value to set for "hm-rpc.1.0008DD89A2BE47.3.SECTION" has to be type "number" but received type "string"
hm-rpc.0 | 2023-04-07 14:51:04.603 | info | State value to set for "hm-rpc.0.0008DD89A2BE47.3.SECTION" has to be type "number" but received type "string"

**Expected behavior**
Adjustment of field types necessary?

**Versions:**
 - hm-rpc version: 1.15.16
 - hm-rega version: 3.0.46

 - CCU model: CCU3
 - CCU firmware: 3.69.6

Any idea? Any suggestions?

**Comment by foxriver76** [comment]
you can try to recreate devices via forceReinit run of hm-rpc. Maybe the firmware of this device has changed?

**Comment by MichaelSchaaf999** [comment]
Dear Max,

how to we „forceReinit“ run of hm-rpc?

Thanks in advance & best regards
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Max Hauser ***@***.***>
Antworten an: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Datum: Freitag, 7. April 2023 um 15:24
An: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device (Issue #872)


you can try to recreate devices via forceReinit run of hm-rpc. Maybe the firmware of this device has changed?

**Comment by foxriver76** [comment]
In Adapter Settings "Geräte neueinlesen"

**Comment by MichaelSchaaf999** [comment]
Danke! Rpc.0 oder rpc.1? Oder beide?

Liebe Grüße
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Max Hauser ***@***.***>
Antworten an: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Datum: Freitag, 7. April 2023 um 15:27
An: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device (Issue #872)


In Adapter Settings "Geräte neueinlesen"

**Comment by krobipd** [comment]
> In Adapter Settings "Geräte neueinlesen"

done but the problem still remains.

> State value to set for "hm-rpc.1.xxx.3.SECTION" has to be type "number" but received type "string"

**Comment by MichaelSchaaf999** [comment]
done, too, several times.
But the problem still persists.

**Comment by innriver** [comment]
Hallo,
ich habe das gleiche Problem! Bei mir ist der state "SECTION" im Kanal 3 der HmIP-FROLL. Hier ist kein Wert vorhanden. Ich habe den Aktor gelöscht und neu eingelesen - bringt eine Änderung.

**Comment by innriver** [comment]
Habe folgende Änderung in der neuen CCU Software gefunden:
Der Konfigurationsparameter „DELAY-COMPENSATION“ wurde für den HmIP-FROLL entfernt, da er nicht unterstützt wird.
Kann nicht sagen ob das was damit zu tun hat.

**Comment by isi07** [comment]
Bei mir kommen auch die Meldungen - auch nach Neueinlesen der Geräte.

**Comment by foxriver76** [comment]
Was schreibt die CCU denn in den Section State rein? Ich gehe aktuell davon aus, dass es sich um einen Fehler seitens CCU handelt.

**Comment by krobipd** [comment]
laut meinen Aufzeichnung ist da immer nur 0 drin. ich wüsste auch nicht wie man das mit der ccu beschreibt.

laut developer doku soll das ein integer wert zwischen 0 und 15 sein.
der adapter hat auch einen number wert angelegt.
das Problem ist ja auch das es ein read-only datenpunkt ist.

frage ist nur warum er jammert. aber vl weiß ja jemand wie man diesen datenpunkt seitens der ccu beschreibt, soweit ich das sehe ich das nur eine Status info, die zumindest bei meinen über 60 geräten nie was drin stehen hat (oder laut Aufzeichnung eben 0)

**Comment by innriver** [comment]
Für was steht der Datenpunkt section überhaupt. Es gibt auch noch den state section_status. Hier steht unknown (1) drin.
Der Fehler tritt bei mir auch nur bei den Rollladenaktoren IP-FROLL im Kanal 3, der die Höhe des Rollladens anzeigt, auf. In den anderen Kanälen werden hier Werte eingetragen. Bei allen anderen Geräten scheint es auch zu funktionieren z.B. bei den Messsteckdosen. Ich habe extra mal eine gelöscht und neu eingelesen - alles wieder da.

Noch einen schönen Ostermontag

**Comment by DrBakterius** [comment]
Ich erhalte nach dem CCU-Update auch die Info bei meinen beiden HmIP-BROLL:

`info: hm-rpc.0 (357822) State value to set for "hm-rpc.0.****.3.SECTION" has to be type "number" but received type "string"`

Wenn ich den Datenpunkt manuell auf Text ändere, kommt danach folgende Warnung:

`warn: admin.0 (303) Object hm-rpc.0.****.3.SECTION is invalid: Default value has to be type "string" but received type "number"`

Also was kommt jetzt an? Eine Zahl oder Text?

**Comment by isi07** [comment]
ich habe für einen HmIP-BROLL den Wert im Addon XML-APi nachgeschaut.

im Kanal 3 ist der Wert für SECTION leer / value="". Dieser gibt einen Fehler im hm-rpc Adapter
`<datapoint name="HmIP-RF.XXXXXXXXXXXXXX:3.SECTION" type="SECTION" ise_id="7096" value="" valuetype="16" valueunit="" timestamp="1681404516" operations="5"/>
`


im Kanal 4 desselben Geräts ist der Wert für SECTION value="0". Dieser gibt keinen Fehler
`<datapoint name="HmIP-RF.XXXXXXXXXXXXXX:4.SECTION" type="SECTION" ise_id="7105" value="4" valuetype="16" valueunit="" timestamp="1681404516" operations="5"/>
`

Ich vermute mal, dass das leere Feld dann wie ein String gewertet wird und nicht als number. Daher dann wohl die Meldung im hm-rpc Adapter.

**Comment by intruder7777** [comment]
Bei  mir sind es alle Dimmaktoren. HmIP-FDT und HmIP-BDT. Hier auch der Section Kanal

**Comment by MichaelSchaaf999** [comment]
Da es anscheinend bislang für den Adapter kein Update gibt, habe ich mittlerweile die Loglevel der beiden rpc-Instanzen von info auf warn umgestellt. Damit kommen dann keine ständigen Info-Meldungen mehr in die Logdatei.
Allerdings ist das ja keine Lösung, höchstens ein Workaround.

**Comment by Siggi0904** [comment]
same here since update to version 3.69.7
my device is a switch HmIP-BDT
deletion of datapoint and reindex/reimport devices didn't work.

**Comment by MichaelSchaaf999** [comment]
Leider kümmert sich hier niemand drum: Dies issue ist weder zugewiesen noch in Bearbeitung.

**Comment by mailman1de** [comment]
Es gab für diverse HmIP Geräte Firmwareupdates. Scheinbar betrifft es all diese Geräte. Selbst in den Heizgruppen kommen diese Meldungen jetzt. Bei intxxxxxxxx.1.Level ist der Wert jetzt auch falsch (zB in CCU 24% in ioBroker 0,24%). Evtl gibts ja eine neue Doku von eQ3 zur Schnittstelle.

**Comment by Apollon77** [comment]
> Leider kümmert sich hier niemand drum: Dies issue ist weder zugewiesen noch in Bearbeitung.

Ich denke @foxriver76 schaut sich das an sobald er neben den anderen iobroker Themen an denen er arbeitet (js-controller 5, die neue Vis App u.ä.) Zeit hat. Wen Info Messages nerven kann das Loglevel auf Warn ändern.

**Comment by MichaelSchaaf999** [comment]
Mal anschauen, aber schonmal vielen Dank!

**Comment by MichaelSchaaf999** [comment]
Nach Einspielen des empfohlenen Updates:
Fehler und die hm-rpc-Instanzen laufen nicht mehr (rot, nicht verbunden).



Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
host.iobroker | 2023-05-08 08:51:08.853 | error | instance system.adapter.hm-rpc.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: }
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js' ]
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:819:12)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:979:32)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1114:14)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js:31:20)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:107:18)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1003:19)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:774:27)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-05-08 08:51:08.853 | error | Caught by controller[0]: Error: Cannot find module 'timers/promises'
host.iobroker | 2023-05-08 08:51:08.852 | error | Caught by controller[0]: ^
host.iobroker | 2023-05-08 08:51:08.852 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-05-08 08:51:08.852 | error | Caught by controller[0]: internal/modules/cjs/loader.js:934
host.iobroker | 2023-05-08 08:51:08.793 | error | instance system.adapter.hm-rpc.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: }
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js' ]
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:819:12)
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:979:32)
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1114:14)
host.iobroker | 2023-05-08 08:51:08.793 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js:31:20)
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:107:18)
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1003:19)
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:774:27)
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: Error: Cannot find module 'timers/promises'
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: ^
host.iobroker | 2023-05-08 08:51:08.792 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-05-08 08:51:08.790 | error | Caught by controller[0]: internal/modules/cjs/loader.js:934

 usw usw

**Comment by MichaelSchaaf999** [comment]
Guten Morgen Max,

nach empfohlen Update der Adapter laufen die hm-rpc-Instanzen nicht mehr, Fehler, rot = keine Verbindung. Nix geht mehr.

Danke im Voraus & liebe Grüße
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Max Hauser ***@***.***>
Antworten an: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Datum: Samstag, 6. Mai 2023 um 21:25
An: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device (Issue #872)


Closed #872<https://github.com/ioBroker/ioBroker.hm-rpc/issues/872> as completed via c4da7d3<https://github.com/ioBroker/ioBroker.hm-rpc/commit/c4da7d35573612142772f8ef75a074673a22b3f3>.

**Comment by foxriver76** [comment]
Mist, habe ich übersehen. Das Update braucht derzeit Node.JS 16, grundsätzlich ist Node.JS 14 auch End-of-Life daher sowieso die Empfehlung auf 16 hoch zu gehen.

**Comment by MichaelSchaaf999** [comment]
Moin Max,

was ist „node.js“, eine Bibliothek?
Im iOBroker steht sogar: Node.js.  v14.21.3 (Empfohlene Version v18.16.0)
Was tun?

Danke im Voraus & liebe Grüße
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Max Hauser ***@***.***>
Antworten an: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Datum: Montag, 8. Mai 2023 um 09:01
An: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device (Issue #872)


Mist, habe ich übersehen. Das Update braucht derzeit Node.JS 16, grundsätzlich ist Node.JS 14 auch End-of-Life daher sowieso die Empfehlung auf 16 hoch zu gehen.

**Comment by foxriver76** [comment]
Hier findest du die Antworten auf deine Fragen und in Schritt 4 die Anleitung zum Update. 

https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten

In Schritt 4 in der URL entsprechend die 10 durch 16 oder 18 ersetzen.

**Comment by MichaelSchaaf999** [comment]
Nun, die Frage, ob nun 16 oder 18 wird nicht beantwortet.

Danke im Voraus & liebe Grüße
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Max Hauser ***@***.***>
Antworten an: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Datum: Montag, 8. Mai 2023 um 09:16
An: "ioBroker/ioBroker.hm-rpc" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.hm-rpc] Since CCU firmware update to 3.69.6 we see info messages for nearly every HmIP device (Issue #872)


Hier findest du die Antworten auf deine Fragen und in Schritt 4 die Anleitung zum Update.

https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten

In Schritt 4 in der URL entsprechend die 10 durch 16 oder 18 ersetzen.

**Comment by foxriver76** [comment]
Es sind keine Probleme mit 18 bekannt und wenn du auf 18 gehst hast du länger deine Ruhe bis zum nächsten Update ;-)
Im Endeffekt deine Entscheidung und für jetzt beides okay.

**Comment by Apollon77** [comment]
Also wenn hier Grafiken drin sein sollten bitte direkt auf GitHub adden und nicht per E-Mail

**Comment by MichaelSchaaf999** [comment]
Mittlerweile...
- influxd beendet, neu gestartet
- ein Graph bzw. ein bestimmtes Measurement meldete ständig Fehler, welches das war konnte man in der Fehlermeldung erkennen
- dieses hab ich dann mal im iOBroker deaktiviert (also im betreffenden Objekt dann die Auswahl "influxdb" deaktiviert und später dann wieder aktiviert)
- seitdem kommen keine Fehler mehr und es wird auch kein Speicherproblem mehr gemeldet

- Schlussfolgerung:
- diese Tabelle / dies Measurement muss in influxdb wohl defekt gewesen sein (zufälligerweise nach dem Node-Update), ließ sich weder weiter schreiben noch lesen
- die o.a. Maßnahme hat dann (natürlich unter Datenverlust der bis dahin gesammelten Daten) diese Probleme behoben - jetzt seit 25 min keine Fehlermeldungen mehr.
-

**Comment by MichaelSchaaf999** [comment]
Danke für die Mühe und schnellen Antworten!
Eine schöne Woche noch
wünscht M
