### ISSUE TITLE
Send this info to developer

### ISSUE THREAD

**Issue by grogo08** [ioBroker/ioBroker.hm-rpc#88]
hm-rpc.1 | 2018-08-15 17:49:59.662 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"PRESS_LONG":{"CONTROL":"BUTTON.LONG","DEFAULT":false,"FLAGS":1,"ID":"PRESS_L
-- | -- | -- | --
hm-rpc.1 | 2018-08-15 17:49:59.661 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HBW-TER-MOD1616.KEY.1"
hm-rpc.1 | 2018-08-15 17:49:59.640 | info | binrpc -> getParamsetDescription ["HBW1616001:17","VALUES"]
hm-rpc.1 | 2018-08-15 17:49:59.475 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"STATE":{"CONTROL":"SWITCH.STATE","DEFAULT":false,"FLAGS":1,"ID":"STATE","MAX
hm-rpc.1 | 2018-08-15 17:49:59.474 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HBW-TER-MOD1616.SWITCH.1"
hm-rpc.1 | 2018-08-15 17:49:59.461 | info | binrpc -> getParamsetDescription ["HBW1616001:1","VALUES"]
hm-rpc.1 | 2018-08-15 17:49:59.431 | warn | Send this info to developer: {"type":"meta","meta":{"adapter":"hm-rpc","type":"paramsetDescription"},"common":{},"native":{"faultCode":-3,"faultString":"Unknown paramset"}}
hm-rpc.1 | 2018-08-15 17:49:59.431 | warn | Send this info to developer: _id: "hm-rpc.meta.VALUES.HBW-TER-MOD1616.MAINTENANCE.1"

**Comment by grogo08** [comment]
Hi,

könnt ihr mir vielleicht das Modul HBW-TER-MOD1616 anlegen?

Besten dank!

Gruß,

Stephan

**Comment by charly9898** [comment]
Hallo
Frage zum Thema Sicherheit : Gibt es bei Anderen Probleme das der Adapter auf 'gelb' geht, d.h. er hängt?
Nach Neustart des Adapters funktioniert wieder alles.
Ich benutze einen Raspi für ioBroker und gleichzeitig als homeMatic-Zentrale

**Comment by Apollon77** [comment]
Letzte Frage gehört hier nicht her weil hat mit dem Issue hier nichts zu tun, oder !?

**Comment by charly9898** [comment]
Wo sollte ich Sie dann stellen?

Am 16. August 2018 16:11:12 MESZ schrieb Ingo Fischer <notifications@github.com>:
>Letzte Frage gehört hier nicht her weil hat mit dem Issue hier nichts
>zu tun, oder !?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ioBroker/ioBroker.hm-rpc/issues/88#issuecomment-413558840

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by BuZZy1337** [comment]
Diese Logeinträge sind leider nicht komplett @grogo08 
Hast du noch eine Chance diese direkt aus dem Logfile zu kopieren?

**Comment by charly9898** [comment]
Hi.
The old Logfiles are not stored. 
In the moment my system works stable.
I'm  sorry
