### ISSUE TITLE
No Error when when rpc connection (CCU -> IOB) will not work

### ISSUE THREAD

**Issue by MarkusSR1984** [ioBroker/ioBroker.hm-rpc#883]
**Describe the bug**
If CCU is not able to connect to HM-RPC the adapter does not show an error

I searched why my HM States does not get updates and found in logs on the CCU that the IOB host is not reachable for it.
my both HM-RPC instances (HMIP/rfd) didn´t show an error and stayed "green"

**Versions:**
 - hm-rpc version: 1.15.16
 - hm-rega version: 3.0.46
 - JS-Controller version: 4.0.24
 - Node version: 18.15.0
 - Operating system: debian (lxc) disabaled firewall
 - CCU model: debmatic
 - CCU firmware:  3.69.7.104

**Comment by foxriver76** [comment]
IF you e.g. set a wrong callback address, the adapter itself won't be able to detect this.
