### ISSUE TITLE
Update-Meldungen von Geräten wird nicht angezeigt

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.hm-rpc#894]
**Describe the bug**
Die CCU (RaspberryMatic) zeigt aktuell für 12 Geräte ein Firmwareupdate an. 
<img width="433" alt="Bildschirmfoto 2023-04-29 um 11 19 54" src="https://user-images.githubusercontent.com/8029204/235295239-712cc9a1-ee80-47cf-a7e7-1ed1356fc185.png">

Die Updates habe ich bereits heruntergeladen, in die CCU eingespielt und sie wurde bereits an 10 Geräte übertragen. Dennoch steht bei allen Geräten der Datenpunkt `UPDATE_PENDING` auf `False`.

**Expected behavior**
Meine Erwartungshaltung an diesen Datenpunkt wäre gewesen, dass er sich auf `True` ändert, sobald die die CCU erkennt, dass Updates vorliegen, spätestens jedoch, wenn die Updates an die Geräte übertragen wurden.

**Versions:**
 - hm-rpc version: v1.15.16
 - hm-rega version: v3.0.46
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: Ubuntu 22.04 LTS
 - CCU model: RaspberryMatic
 - CCU firmware: 3.67.10.20230225

**Comment by Apollon77** [comment]
Passt es denn nach einem neustart des adapter und hm-rega?
Die Erwartung kann nur sein wenn die CCU Änderungen dieses States auch "pusht" - was bei solchen States nicht unbedingt üblich ist ....Es kann also sein das der Adapter keine chance hat.

**Comment by Standarduser** [comment]
Nach einem Neustart von HM-RPC und HM-REGA ändert sich das Verhalten nicht.
Die Update-Meldung bleibt bei `False`

**Comment by foxriver76** [comment]
https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rega/master/regascripts/datapoints.fn Das wird bei Rega start ausgeführt, um die DPs abzuholen, checke gerne gegen ob es da nicht schon so drin steht, dann ist es das was die CCU liefert und Adapter kann nix machen.

**Comment by foxriver76** [comment]
Soweit ich das verstehe ist der DP auch eher,. wenn die FW erfolgreich zum Gerät übertragen wurde. Spriuch man in der CCU den Update Knopf drücken kann und nicht wenn neue FW downloadbar ist.
