### ISSUE TITLE
"totes" Gerät in ioBroker

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.hm-rpc#91]
Ich hatte zum Testen ein Gerät (Taster) an der CCU angelernt, welches auch sauber in ioBroker synchronisiert wird.
Nach den Test habe ich das Gerät am Bestimmungsort installiert und an einer anderen CCU angelernt, Beim kontrollieren des ioBroker-Logs ist mir dann folgende Meldung aufgefallen:
`javascript.1 getState "hm-rpc.0.OEQ0901505.0.CONFIG_PENDING" not found (3) states[id]=null                       
 javascript.1     at script.js.HomeMatic.ServiceAnnouncement:123:26                                              
 javascript.1     at Object.result.each (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:542:29)   
 javascript.1     at Object.countDevs (script.js.HomeMatic.ServiceAnnouncement:122:18)                           
 javascript.1     at Job.job (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:888:34)              
 javascript.1     at Job.invoke (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:173:10)                
 javascript.1     at /opt/iobroker/node_modules/node-schedule/lib/schedule.js:543:11                             
 javascript.1     at Timeout._onTimeout (/opt/iobroker/node_modules/node-schedule/lib/schedule.js:501:7)         
 javascript.1     at ontimeout (timers.js:386:11)                                                                
 javascript.1     at tryOnTimeout (timers.js:250:5)                                                              
 javascript.1     at Timer.listOnTimeout (timers.js:214:5)     `                                                  

Diese Meldung kommt bei der Abfrage für alle synchronisierten Eigenschaften des Gerätes und rühren daher, dass keine zu synchronisierenden Werte vorhanden sind. Ein löschen der Objekt-Struktur im ioBroker war nur von kurzer Freude, da es von der CCU wieder synchronisiert wurde.
Das Gerät selbst wird in der Admin-Oberfläche der CCU nicht angezeigt und kann ich daher auch nicht regulär gelöscht werden. Im Dateisystem finde ich die entsprechende Konfigurationsdatei:
`/usr/local/etc/config/rfd/OEQ0901505.dev`

Da das Gerät in der CCU nicht angezeigt wird, muss es ja eine Eigenschaft geben, an der die "Abwesenheit" des Gerätes erkannt wird. Kann das nicht im hm-rpc-Adapter berücksichtigt werden?

Nach dem Löschen der Konfigurationsdatei auf der CCU und deren Neustart (notwendig?) verschwand dann die Objekte auch im ioBroker. Schöner wäre natürlich wenn hm-rpc analog zum Admin der CCU inaktive Geräte erkennen und ignorieren würde.

**Comment by truegreyhound** [comment]
Nein, habe ich bewusst nicht, weil ich annehme, dass dann alle Objekte/Werte neu gesetzt und in ioBroker entsprechende Statusänderungen auslösen.
Aus meiner Sicht, wäre es wünschenswert, wenn in ioBroker solche Zombies gelöscht bzw. wenn nicht vorhanden, nicht synchronisiert werden, ggf. als Option der Schnittstelle.
Ich kann mir vorstellen, dass sich nicht jeder zu helfen weiß oder traut, dass entsprechende Objekt auf der CCU zu finden und zu löschen.
Ggf. wäre analog zu "updated" auch eine Liste von Zombie-Geräten hilfreich.

**Comment by foxriver76** [comment]
Ich werde mal probieren das nachzustellen, allerdings ist mir was nicht ganz klar: 

Du hast ein Gerät an der CCU abgelernt und ioBroker bekommt es nicht mit. Allerdings hast du einen Logauschnitt aus einer javascript Instanz oben wo du vermutlich (?) versuchst ein getState auf eines der Attribute des abgelernten Gerätes zu machen und der State existiert nicht mehr? Was dafür spricht, dass ioB es schon mitbekommen hat und die States gelöscht hat.

Also der Fehler ist aktuell:

1. Gerät wird an der CCU abgelernt
2. ioBroker entfernt die Objekte des Gerätes nicht selbstständig 

Muss leider etwas nachhaken, steige in der Issue-Beschreibung nicht ganz durch.

**Comment by foxriver76** [comment]
Habe es probiert nachzustellen:

- Gerät ablernen, während Instanz aktiv --> Gerät wird sofort gelöscht
- Instanz stoppen --> Gerät ablernen --> Instanz starten --> Gerät wird gelöscht, außer Geräte nicht löschen wurde in der Instanzkonfig angehakt

Falls das Problem noch existiert, bitte Issue erneut öffnen und meine Fragen aus dem vorherigen Kommentar beantworten. Bzw. Berhalten näher spezifizieren.
