### ISSUE TITLE
It would be nice if this adapter could connect to Groups XML-RPC

### ISSUE THREAD

**Issue by Holuba** [ioBroker/ioBroker.hm-rpc#93]
I use Homematic Heating groups (groups multiple thermostats into one Virtual Device). It woud be nice if i can control them over iobroker. But i found no way to enter the Endpoint "/groups" in the iobroker User-Interface. 

XML-RPC Interface for Groups:
<homematic ccu2 ip>:9292/groups

**Comment by Apollon77** [comment]
What exactly is missing? The groups should be available. Do you did a new sync of the devices?

**Comment by Holuba** [comment]
i connected one hm-rpc to the ccu2 on port 2001 (rdf - bin-rpc) and one hm-rpc to the ccu2 on port 2010 (HomeMaticIP - XML-RPC). 
I did a new sync of devices on both instances. But the Virtual Devices (Type: HM-CC-VG-1; s/n: INT0000001,INT0000002 and so on; in the ccu2 they named "Gruppe Heizungssteuerung").

I found out, that there is an extra xml-rpc endpoint for these type of devices:
homematic-ccu2-ip:9292/groups

i tryed to ad a new hm-rpc to this endpoint, but i can only change the port and can not add the /groups "folder".

**Comment by foxriver76** [comment]
I dont use virtual devices but I think you need a separate instance and set the daemon to `virtual devices`. 
![bildschirmfoto von 2018-11-28 02-12-01](https://user-images.githubusercontent.com/25484431/49122055-20504780-f2b3-11e8-9fc9-84770088b3a5.png)

Can you confirm that this works?

**Comment by Holuba** [comment]
Yes it works wonderfully on my installation. And yes, a separate instance is needed.

**Comment by foxriver76** [comment]
Of course, it was implemented by you. I missed that. Ticket was just not closed, thanks for your feedback :)

**Comment by Holuba** [comment]
oh .. yes ;)
