### ISSUE TITLE
HTTP(S)/Basic Authentication

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.hm-rpc#94]
Hallo zusammen,

ich würde den Lighttpd des RaspberryMatic gerne per HTTP Authentication richtig absichern, da bei normalen Passwortschutz immer noch die API ungeschützt erreichbar ist.
Gibt es eine Möglichkeit bei Umsetzung (vgl. https://github.com/fl0wde/RaspberryMatic_Authentification) die notwendigen Login-Daten innerhalb des iobrokers im rpc-Adapter zu hinterlegen?

Danke und viele Grüße
Zefau

**Comment by GermanBluefox** [comment]
Nein. Gibt es nicht.

вс, 9 сент. 2018 г., 20:45 Zefau <notifications@github.com>:

**Comment by Zefau** [comment]
Vielen Dank für die schnelle Antwort. Wäre eine Implementierung denn für euch ok?
Wenn ich das richtig sehe, unterstützt die Schnittstelle (homematic-xmlrpc) eine Basis Authentication (vgl. https://github.com/hobbyquaker/homematic-xmlrpc/blob/master/lib/client.js#L56).

Ich habe das bei mir lokal mal angepasst und die hm-rpc.js nach Zeile 1426 um `basic_auth: {user: "test", pass: "test"}` erweitert und diesen Zugang auch im HomeMatic lighttpd hinterlegt.

Funktioniert.

**Comment by GermanBluefox** [comment]
PRs are welcome..

ср, 12 сент. 2018 г. в 20:13, Zefau <notifications@github.com>:

**Comment by Apollon77** [comment]
Info von Jens Maus HM-Forum: https://homematic-forum.de/forum/viewtopic.php?f=69&t=46455#p465022 ... Also "the way to go" ist HTTPS und Authentifizierung (speziell FW 3.41.x+)

**Comment by foxriver76** [comment]
@Zefau have you tried it with the information given in https://homematic-forum.de/forum/viewtopic.php?f=69&t=46455#p465022 ? Seems like the ports were not adjusted in your setup?

**Comment by Zefau** [comment]
I developed the solution based on the old firmware. New ports where newly introduced with the latest release and thus are not reflected in my implementation.

**Comment by foxriver76** [comment]
Bei aktivierter Authentifizierung scheint über den normalen Port 2001 nichts zu gehen, mit einem https-Client bekomme ich keine Antwort. Selbes Setup 42001:
` init error: Error: self signed certificate` habe leider auf die schnelle nichts gefunden um das Problem zu adressieren.

**Comment by Zefau** [comment]
Dein Zertifikat ist selbst signiert und nicht von einer offiziellen CA, daher der Fehler. Daher muss dort irgendwo {rejectUnauthorized: false} im API request rein.

**Comment by foxriver76** [comment]
Danke, das ist schon erledigt im PR.
Bin gerade nur etwas verwundert: über rfd läuft es mit Auth genauso 'smooth' wie sonst auch, während ich beim HM-IP bei jedem zweiten Kommando ein Timeout bekomme.
