### ISSUE TITLE
HmIP-DRBL => LEVEL states are read-only and COMBINED_PARAMETER is missing.

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.hm-rpc#963]
HmIP-DRBL => LEVEL states are read-only and COMBINED_PARAMETER is missing.
I deleted the hole object structure and restart the Adapter, but no changes.

![Xnip2023-07-29_14-01-13](https://github.com/ioBroker/ioBroker.hm-rpc/assets/8231359/43d919c7-7f31-4b61-97ce-04df17823926)

![Xnip2023-07-29_08-53-10](https://github.com/ioBroker/ioBroker.hm-rpc/assets/8231359/23d1bd34-d96e-48e2-9050-b1976cdc80fe)

**Versions:**
 - hm-rpc version: 1.15.16
 - hm-rega version: 3.0.46
 - JS-Controller version: 4.0.23 / 4.0.24
 - Node version: 16.19.1
 - Operating system: Debian bullseye
 - CCU model: CCU3
 - CCU firmware: <ccu-version>
 - DRBL Firmware: 1.8.4 / 1.8.2

**Additional context**

**Comment by foxriver76** [comment]
Have you checked the other channels? normally there are separate channel for the target and the current level.

**Comment by Schmakus** [comment]
> Have you checked the other channels? normally there are separate channel for the target and the current level.

Oh man.......... Clap lefthand and righthand....... 
I had a Problem and I looked in the wrong channels.........
