### ISSUE TITLE
Neustart und Restart von Yakha bewirkt Fehlfunktion auf Apple Watch

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.hm-rpc#972]
Jedes Mal, wenn ich den Yakha Adapter neu starte, funktioniert HomeKit auf der Apple Watch nicht mehr.
Die Watch zeigt an, dass es keine Verbindung mehr gibt zu allen Geräten. Auf dem iPhone und Mac funktioniert HomeKit ohne Probleme.

Workaround: ein neues, weiteres Zuhause anlegen. Dann scheint die Apple Watch wieder zu synchronisieren. Was auch funktioniert, ist, ein schon neu, angelegtes Zuhause wieder zu löschen.

**Comment by foxriver76** [comment]
Falsches Repo oder?

**Comment by Marty56** [comment]
Kann sein. Es passiert aber nur im Zusammenspiel mit yakha.

**Comment by foxriver76** [comment]
Ok das hier ist nicht yahka
