### ISSUE TITLE
HmIPW-DRBL4 and HmIP-FBL using Slat (LEVEL_2)

### ISSUE THREAD

**Issue by Eulili** [ioBroker/ioBroker.hm-rpc#982]
I'm not able to write to the LEVEL_2 Object, so i can not change the Percents of Slat-Opening. The field is not writeable.

Im Using Version 1.15.18

`{
  "type": "state",
  "common": {
    "name": "LEVEL_2",
    "role": "",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 100,
    "unit": "%"
  },
  "native": {
    "MIN": 0,
    "UNIT": "100%",
    "OPERATIONS": 5,
    "MAX": 1.01,
    "FLAGS": 1,
    "ID": "LEVEL_2",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "BLIND_TRANSMITTER.LEVEL_2"
  },
  "from": "system.adapter.hm-rpc.0",
  "user": "system.user.admin",
  "ts": 1690712044072,
  "_id": "hm-rpc.0.00165F299C641C.1.LEVEL_2"
}`

**Comment by foxriver76** [comment]
probably you have another channel for write

**Comment by Eulili** [comment]
I tried several channels (1 to 4) to solve this, but i got no solution for this. Writing the channals from "FHEM" or "RaspberryMatic" works, but i tried to change unsing only "iobroker" for this.

**Comment by Eulili** [comment]
Here you can see the channels for the first of 4 Parts of the HmIPW-DRBL4
The yellow ones affect the blind settings the blue ones do not.

![RaspberryMatic HmIPW-DRBL4 PNG](https://github.com/ioBroker/ioBroker.hm-rpc/assets/6323389/02f39853-4ea6-4bb3-8d01-fd5eba15355e)

**Comment by foxriver76** [comment]
From what I remember, some people said, that you have to change `LEVEL_2` and then `LEVEL` to actually apply the positions. Forum can help you better here, hm-rpc currently has no special logic for this.

**Comment by Eulili** [comment]
As you see in my first part here:

` "read": true, "write": false,`

The values are only readable, so i cannot change them in the channel 2.
I will use another solution without iobroker for this. Thanks!

**Comment by Eulili** [comment]
THANKS! That was the solution for this! Great!

**Comment by foxriver76** [comment]
we also reported this to eq3 once, but no feedback here how API should behave https://github.com/eq-3/occu/issues/104
